ministryofjustice/hmpps-book-secure-move-frontend

- docker-compose.yml
This allows us to test the service running locally under Docker with a working Redis connection. Note you need to set the secrets in the file before it will run properly.
> Add docker-compose file for local Docker environment testing

- README.md
- app/moves/controllers/form.js
- app/moves/controllers/form.test.js
- app/moves/controllers/move-details.js
- app/moves/controllers/move-details.test.js
- app/moves/index.js
- app/moves/middleware.js
- app/moves/middleware.test.js
- app/moves/views/create/move-details.njk
- common/middleware/current-location.js
- common/middleware/current-location.test.js
- common/middleware/locals/index.js
- common/services/move.js
- common/services/move.test.js
- common/services/reference-data.js
- common/services/reference-data.test.js
- config/index.js
- server.js
- test/fixtures/api-client/reference.location.deserialized.json
- test/fixtures/api-client/reference.location.serialized.json
This change uses an environment variable to set the UUID of the current location.
This current location is then used in other parts of the application, for example listing moves for only that location or creating moves for only that location.
> [P4-473] Fix the current location for a user

- app/moves/fields.js
- app/moves/steps.js
- common/services/person.js
- common/services/person.test.js
- locales/en/fields.json
This change sets the current reference field to the specific
custody suite being used for the pilot.
It also adds support to the Person service formatter to correctly
handle any identifiers that are passed to it.
> [P4-411] Store the person's reference number

- app/moves/fields.js
- app/moves/steps.js
The keys for these properties have been changed in the API so this
change reflects that so the values are stored correctly.
Relates to this API change: ministryofjustice/hmpps-book-secure-move-api/pull/75
> Update assessment "other" field keys

- app/moves/steps.js
- common/templates/form-wizard.njk
- locales/en/actions.json
This change allows custom text to be passed to the form wizard
on any step by adding a `buttonText` property to the step
options.
It also includes updating the final step of the creation journey
to change the text to reflect the action that will happen after
clicking it.
> [P4-475] Update button text for final create step

- app/moves/fields.js
- common/templates/form-wizard.njk
Previously the form wizard would not output a field if
the `isConditional` property returned truthy.
This change renames that property to be something more generic (`skip`)
as we might want to skip a field for other reasons. It unties
the property from a specific scenario and offers more flexibility.
> Rename skip flag in form wizard

- README.md
- config/index.js
This adds support for specifying `REDIS_HOST` instead of `REDIS_URL`
which is what is used to deploy the app on cloud platform.
> Add Redis env vars to support Cloud platform

- server.js
Currently in production grant will attempt to redirect to http
protocol.
Although this isn't the best way to determine protocol currently
we can say that if the app is in production the protocol is `https`.
**Note:** I'm not sure I really like this but it will allow us to have staging working
to start with.
> Set grant return protocol based on environment

- app/auth/controllers.js
- app/auth/controllers.test.js
- app/auth/index.js
- common/components/internal-header/_internal-header.scss
- common/helpers/index.js
- common/helpers/url.js
- common/helpers/url.test.js
- common/templates/layouts/govuk.njk
- config/index.js
- locales/en/actions.json
The order of events is:
* We destroy the session on our service
* We redirect the user to the HMPPS SSO logout URL, which logs them out of that session as well
* HMPPS SSO redirects back to our service at the URL we specify, or failing that, back to its own login screen
> Add sign out link in header

- common/templates/layouts/govuk.njk
The sign out link in the header was missing the auth path after
a refactor to move the controler into the auth feature.
> Fix URL for sign out link

- package-lock.json
- package.json
- server.js
Slashify redirects any routes containing a trailing slash to
a URL without a slash.
This keeps our URLs more consistent for things like analytics and
avoids any duplicates.
> Add slashify to standardise URLs

- app/moves/fields.js
- locales/en/fields.json
This adds validation to the form wizard to validate each of the
move creation steps.
> [P4-439] Validate creation journey

- app/move/views/_includes/assessment.njk
- common/components/_panel/_panel.scss
- common/lib/api-client/models.js
This change updates the assessment answers to use the new `created_at`
property the API now supports.
> Include the created date in assessment answers

- app/moves/controllers/list.js
- app/moves/index.js
- app/moves/middleware.js
- app/moves/middleware.test.js
- app/moves/views/list.njk
- common/middleware/locals/index.js
This creates a new route to view moves from a specific location and
now displays all moves when visiting the route moves path.
Routes are now:
`/moves` - display all moves
`/moves/download.(csv|json)` - download all moves
`/moves/:locationId` - display moves from location
`/moves/:locationId/download.(csv|json)` - download moves from location
> [P4-266] Separate all moves from location based moves

- .env.example
- README.md
- common/middleware/development.js
- common/middleware/development.test.js
- common/middleware/ensure-authenticated.js
- common/middleware/ensure-authenticated.test.js
- config/index.js
- server.js
This change moves setting of certain conditions for development
only purposes into its own middleware.
The main functions are to bypass authentication and to set user
permissions for development purposes.
This will be used to improve how we bypass routes in #131
> Extract development specific middleware out

- app/move/controllers/cancel.js
- app/move/controllers/cancel.test.js
- app/move/views/view.njk
- app/moves/controllers/list.js
- app/moves/controllers/list.test.js
- app/moves/views/_layout.njk
- app/moves/views/download.njk
- app/moves/views/list.njk
- locales/en/actions.json
This change accomdates the supplier role where they cannot view
individual moves. If that permission is missing it renders an
alternative template without the list of moves.
> Display a different list template based on permissions

- common/lib/user.js
- common/lib/user.test.js
When an auth token is returned from the current auth provider (HMPPS SSO)
and that user doesn't have a role assocaited with it, there will be
no `authorities` property on the token.
When the user is missing this property the User class would throw an
error as it expected it to exist.
This fix will set a default value if that property doesn't exist and
return an empty permissions array.
> Catch missing authorities property on auth token

- app/home/controllers.js
- app/home/controllers.test.js
- app/move/controllers/cancel.js
- app/move/controllers/cancel.test.js
- app/move/controllers/new.save.js
- app/move/controllers/new.save.test.js
- app/move/views/view.njk
- app/moves/index.js
- app/moves/middleware.js
- app/moves/middleware.test.js
This change moves the logic that determines where to redirect a
user based on their permissions to the moves feature folder rather
than the route.
The current logic meant that a user could sign in with no permissions
and would see a `404` at the route so wouldn't necessarily know its
a permission issue.
Moving to the moves feature folder will have a user fallback to the
protectRoute middleware if they have no permissions to do anything
within the moves feature.
>  Move permissions redirect to moves feature

- common/middleware/errors.js
- common/middleware/errors.test.js
- common/templates/error.njk
- locales/en/errors.json
This change moves the logic for setting content on the error page
to the middleware rather than the template.
It also ensures there is specific content for the forbidden
handler.
> Update content on error handler

- app/auth/index.js
- app/auth/middleware.js
- app/auth/middleware.test.js
- common/lib/user.js
- common/lib/user.test.js
- common/services/reference-data.js
- common/services/reference-data.test.js
This change extends the user class to set the locations available
to that user on the user session object.
This PR is a precursor to some future changes:
- ensure user can access location being viewed
- if user only has access to only one location, default to that location
- if user has access to multiple locations, allow them to choose
> [P4-353] Add locations to the user object

- app/moves/controllers/list.js
- app/moves/controllers/list.test.js
- app/moves/views/_layout.njk
- common/components/pagination/pagination.yaml
- common/components/pagination/template.njk
- common/components/pagination/template.test.js
- locales/en/actions.json
This PR extends the pagination component to support list items in the middle and then adds the today shortcut to the moves listing template.
> [P4-273] Add "today" shortcut to pagination

- locales/en/actions.json
Schedule move text should be future, not past.
> [P4-518] Fix typo in scheduled move button

- app/move/controllers/new.assessment.js
- app/move/controllers/new.assessment.test.js
- app/move/controllers/new.move-details.js
- app/move/controllers/new.move-details.test.js
- app/move/controllers/new.personal-details.js
- app/move/controllers/new.personal-details.test.js
- common/helpers/reference-data.js
- common/helpers/reference-data.test.js
- common/lib/api-client/models.js
- test/fixtures/api-client/move.get.deserialized.json
- test/fixtures/api-client/move.get.serialized.json
- test/fixtures/api-client/moves.get.deserialized.json
- test/fixtures/api-client/moves.get.serialized.json
- test/fixtures/api-client/reference.assessment.deserialized.json
- test/fixtures/api-client/reference.assessment.serialized.json
- test/fixtures/api-client/reference.ethnicities.deserialized.json
- test/fixtures/api-client/reference.ethnicities.serialized.json
- test/fixtures/api-client/reference.genders.deserialized.json
- test/fixtures/api-client/reference.genders.serialized.json
- test/fixtures/api-client/reference.location.deserialized.json
- test/fixtures/api-client/reference.location.serialized.json
- test/fixtures/api-client/reference.locations.deserialized.json
- test/fixtures/api-client/reference.locations.page-1.serialized.json
- test/fixtures/api-client/reference.locations.page-2.serialized.json
This removes items that we don't want displayed when creating new moves from the reference data set.
It uses the `disabled_at` property to determine whether these options should be shown or not.
> [P4-515] Filter disabled options

- common/services/person.js
- common/services/person.test.js
This fixes a bug where the identifiers property on a person was
being replaced with an empty array if there was already an existing
one.
This adds a couple of extra tests to ensure this doesn't regress
in the future.
> [P4-502] Fix replacing of identifiers

- common/templates/layouts/govuk.njk
The service is moving in private beta so this change updates the
phase banner to match.
> [P4-539] Update phase banner to "Beta"

- common/assets/javascripts/application.js
- common/components/internal-header/_internal-header.scss
- common/components/internal-header/internal-header.js
This PR includes:
- an update to the style of the header to fix the missing padding on mobile layout
- fix for showing/hiding the menu on mobile (JS needed was taken from [header component](https://github.com/alphagov/govuk-frontend/tree/master/src/govuk/components/header) in GOV.UK Design System)
> [P4-495] [P4-496] Header tweaks

- .circleci/config.yml
Kick off a production build and deploy after a successful test on `master` subject to an Approval step. Mirrors https://github.com/ministryofjustice/hmpps-book-secure-move-api/pull/85
I've already added the 4 `KUBE_ENV_PRODUCTION_*` environment variables to the CircleCI config, (https://user-guide.cloud-platform.service.justice.gov.uk/tasks.html#add-variables-to-circleci)
> [P4-552] CircleCI production build/deploy steps

- common/helpers/reference-data.js
- common/helpers/reference-data.test.js
The reference data disabled filter was using the wrong property name.
This change updates it to use the correct one.
> Use correct property name for disabled filter

- app/move/index.js
- app/move/steps.js
- common/templates/form-wizard.njk
This change sets the page title for form wizard steps. At the moment
the form wizard falls back to the default page title.
This change adds a new property to the wizard settings to use as
the page title. It also renames the `heading` property for each step
to be more consistent.
> Add page title to form wizard

- app/move/views/view.njk
- common/components/card/_card.scss
- common/presenters/move-to-card-component.js
- common/presenters/move-to-card-component.test.js
- locales/en/moves.json
This change updates how the move reference is displayed on the
move listing and move detail pages.
> Update move reference style

- README.md
- app/move/views/cancel.njk
- app/move/views/view.njk
- app/moves/views/_layout.njk
- app/moves/views/download.njk
- app/moves/views/list.njk
- common/middleware/locals.js
- common/templates/layouts/govuk.njk
- config/index.js
- config/nunjucks/globals.js
- config/nunjucks/globals.test.js
This change adds support for Google Analytics tracking if there is an environment variable set.
It includes some code to filter out any Personal Identifiable Information (PII) that could be sent within page titles.
We will need to ensure that any future changes don't start sending any PII to google as we add them.
> [P4-299] Add google analytics

- app/move/views/_includes/assessment.njk
- app/move/views/view.njk
- app/moves/views/list.njk
- common/components/message/_message.scss
- common/components/message/message.yaml
- common/components/message/template.njk
- common/components/message/template.test.js
- locales/en/moves.json
This change covers 2 tickets which relate to how empty results are displayed both on the move detail page and the move listing page. 
It extends the message component so that it can be used to display the empty results text in the desired way.
> [P4-476] [P4-546] No results panel

- app/move/controllers/new.save.js
- app/move/controllers/new.save.test.js
This change redirects the user back to the date they created the move
for on the dashboard.
This makes more sense than always redirecting the user back to the
default day (today) where they won't see the move they just created.
> Redirect user back to that day after save

- app/move/views/view.njk
- app/moves/index.js
- app/moves/middleware.js
- app/moves/middleware.test.js
- common/middleware/locals.js
Currently the link back to the dashboard will go back to a non-filtered view.
If a user changes the date and navigates to a move the current date will be lost and they will return to the default dashboard view for "today" on clicking the back to dashboard link.
This change will persist the current filter so that it can be used to go back to the correctly filtered version of the dashboard.
> [P4-317] Store listing state

- common/assets/scss/overrides/_font-corrections.scss
- common/components/card/_card.scss
- common/components/tag/_tag.scss
When multiple tag components are aligned inline there is no vertical
spacing when they wrap onto multiple lines.
This change addresses this visual bug.
It also includes a small tweak to the spacing of the GOV.UK Design System tag component.
> [P4-591] Risk flag spacing

- common/components/pagination/_pagination.scss
The inline variation of the pagination component wasn't being
displayed correctly on certain browser (Safari) due to the position
the inner elements were being given.
The text element was being `display: inline-block` which caused the
text deocration not to be inherited which concealed the alignment
issue.
This change displays the elements as inline and sets the text decoration
styles on the correct element (the parent anchor).
> [P4-538] Fix pagination alignment

- app/move/controllers/new.personal-details.js
- app/move/controllers/new.personal-details.test.js
- app/move/fields.js
- app/move/steps.js
- common/helpers/field.js
- common/helpers/field.test.js
- common/lib/api-client/models.js
- common/presenters/person-to-summary-list-component.js
- common/presenters/person-to-summary-list-component.test.js
- common/templates/form-wizard.njk
- locales/en/fields.json
- test/fixtures/api-client/move.get.deserialized.json
- test/fixtures/api-client/move.get.serialized.json
This adds a new field to capture any extra gender information necessary
to transport a detainee/prisoner.
> [P4-537] Extra gender information

- app/move/controllers/new.form.js
- app/move/controllers/new.form.test.js
- common/assets/scss/overrides/_all.scss
- common/assets/scss/overrides/_buttons.scss
- common/templates/form-wizard.njk
This adds a cancel button that can be used by the user to cancel the current create journey.
> [P4-503] Create cancel option

- app/move/controllers/new.move-details.js
- app/move/controllers/new.move-details.test.js
- common/services/reference-data.js
- common/services/reference-data.test.js
This allows the reference data service to look up locations by both type as currently, and also NOMIS agency ID, as implemented in https://github.com/ministryofjustice/hmpps-book-secure-move-api/pull/95.
This is a pre-requisite to look up locations by agency ID, as supplied by HMPPS SSO.
> Allow reference data service to search for locations by NOMIS agency ID

- .circleci/config.yml
This Coveralls service has been down for sometime and is causing
the unit test build to fail.
This change removes that from the unit_test job on CI so that
it doesn't prevent successful builds until Coveralls fix the issue.
> Disable coveralls coverage upload

- common/lib/api-client/middleware/auth.js
- common/lib/api-client/middleware/auth.test.js
A timeout was added to all regular API client calls but the
separate auth call was missed.
This change adds the setting to the auth middleware to ensure it
receives the same timeout. This is an initial fix to prevent
the frontend from hanging.
In future it might also be better to make use of the axios instance
on the jsonApi object. But that can come as part of a refactor to the
way [the API client is currently tested and used within the app](https://github.com/ministryofjustice/hmpps-book-secure-move-frontend/issues/82).
Fixes #189
> Ensure API auth call includes timeout

- .env.example
- README.md
- app/auth/index.js
- app/auth/middleware.js
- app/auth/middleware.test.js
- app/healthcheck/dependencies.js
- common/lib/access-token.js
- common/lib/access-token.test.js
- common/lib/user.js
- common/lib/user.test.js
- common/services/reference-data.js
- common/services/reference-data.test.js
- common/services/user-locations.js
- common/services/user-locations.test.js
- config/index.js
- config/index.test.js
- test/fixtures/api-client/reference.locations.serialized.json
This allows the frontend to look up the user's locations either on HMPPS SSO or NOMIS depending on the type of user, and resolves those to the IDs represented in the API. This will allow us to implement location switching.
> Locations lookup

- common/assets/scss/application.scss
- common/assets/scss/overrides/_font-corrections.scss
- common/templates/layouts/base.njk
- config/nunjucks/index.js
- package-lock.json
- package.json
- server.js
This shows the user's current location on the page header, using the [MoJ organisation switcher](https://moj-design-system.herokuapp.com/components/organisation-switcher) component. This can then be extended in a subsequent PR to allow the user to switch their location.
> Show user's location in header

- common/components/internal-header/template.njk
- common/components/internal-header/template.test.js
- common/templates/layouts/base.njk
Add user name into the internal header.
The `user.username` is currently only available via the `access_token` further work needs to be created to query the api to get the `user.name` which is easier on the eye. This was felt out of scope for this work.
> [P4-505] Display username in header

- common/services/move.js
- common/services/move.test.js
- test/fixtures/api-client/moves.get.deserialized.json
- test/fixtures/api-client/moves.get.page-1.serialized.json
- test/fixtures/api-client/moves.get.page-2.serialized.json
This change ensures that we return the maximum number of moves
to the dashboard. At the moment there is no pagination so this
will ensure that no moves are not displayed on the dashboard.
There will be a performance issue with this initially but this
has been accepted for this initial pilot where only small number of
moves are being put through a day.
> [P4-260] Increase page limit on moves request

- app/move/middleware.js
- app/move/middleware.test.js
- common/services/move.js
- common/services/move.test.js
Previously the call would return the response from the JSON API
client library which would include unnecessary properties.
This change replicates the other methods in the service and extracts
the deserialized data from the response and returns that rather
than the full response object.
> Update move service calls to always return data

- package.json
The repository was recently renamed by the package manifest wasn't
updated to match.
This change updates the references to the old repo path.
It also includes an addition to the contributors property.
> Update manifest file

- common/templates/form-wizard.njk
- locales/en/actions.json
- locales/en/validation.json
This amends the form wizard template to make sure it is making
use of the i18n library to translate any content.
> Ensure form wizard template is using translations

- common/middleware/ensure-current-location.js
- common/middleware/ensure-current-location.test.js
If a user has permission to view all moves, regardless of location,
they should be able to view moves even if their user does not currently
have any available locations.
This is currently the case for suppliers. Without this change a
supplier user is only greeted with the no locations message and cannot
view any other parts of the app.
> [P4-638] Fix moves permissions with no locations case

- app/move/controllers/new.form.js
- app/move/controllers/new.form.test.js
The current location is no longer set via environment variable.
This change updates the error message that is thrown when the
create journey is started without a current location.
> Update the error message for checking current location

- app/move/controllers/new.form.test.js
- common/components/message/template.test.js
- common/lib/api-client/middleware/errors.test.js
- common/lib/user.test.js
- common/middleware/errors.test.js
- config/nunjucks/filters.test.js
- config/nunjucks/globals.test.js
A number of tests were using `to.equal(undefined)`. This is the same
as `to.be.undefined` in chai and the latter reads better.
This change makes the change across the test codebase after it was
spotted in another change (#202).
> Update test undefined syntax

- app/move/views/view.njk
- common/assets/javascripts/application.js
- common/assets/scss/components/_all.scss
- common/assets/scss/components/_sticky-sidebar.scss
- package-lock.json
- package.json
This adds some client side JS to pin the right hand panel
on the move detail page to the top of the window on scroll.
This allows the user to keep the context of the person they
are moving and where they are moving as they scroll the page.
> [P4-504] Add sticky sidebar to move detail page

- app/move/controllers/cancel.js
- app/move/controllers/cancel.test.js
- app/move/controllers/create/save.js
- app/move/controllers/create/save.test.js
- app/move/controllers/view.js
- app/move/controllers/view.test.js
- app/move/views/cancel.njk
- app/move/views/view.njk
- common/presenters/move-to-card-component.js
- common/presenters/move-to-card-component.test.js
- common/services/move.js
- common/services/move.test.js
- common/services/person.js
- common/services/person.test.js
This extracts the logic for setting the persons fullname into the
shared middleware so that it can be used by all views that deal
with a person on a move model.
> [P4-629] Set persons fullname in shared middleware

- common/lib/api-client/json-api.js
- common/lib/api-client/models.js
This change exports the model objects rather than a function that
defines each model on the API client.
This will allow the model and its attributes to be used in other
parts of the app like services to ensure when formatting they follow
the same property structure as the API model.
> Refactor API model definitions

- app/auth/controllers.js
- app/auth/controllers.test.js
The session destroy method as asynchronous, especially when using
a session store like Redis.
Currently the user is being redirect before the session is actually
destroyed which has led to some inconsistencies when signing out
and back in again in quick succession.
This change calls the redirect in the destroy callback to ensure
it has been destroyed properly.
> Ensure session is destroyed before redirecting

- app/move/controllers/confirmation.js
- app/move/controllers/confirmation.test.js
- app/move/controllers/create/save.js
- app/move/controllers/create/save.test.js
- app/move/controllers/index.js
- app/move/index.js
- app/move/steps/create.js
- app/move/views/confirmation.njk
- common/assets/scss/application.scss
- common/templates/layouts/base.njk
- locales/en/moves.json
Add a Move completed page to the create journey
- If a user uses the browser back button whilst on the confirmation page it will redirect them to `/moves`
- Users can go to `move/<move_id>/confirmation` to see individual confirmations
> [P4-627] Add completed page create journey

- common/controllers/form-wizard.js
- common/controllers/form-wizard.test.js
- common/templates/form-wizard-error.njk
- locales/en/errors.json
If a journeys session model has been reset or destroyed then
an error with the code `MISSING_PREREQ` is thrown. This work handles
this error and displays a page with a user-friendly message
@lmoney-moj is sending final copy over at present this is just placeholder copy
`SESSION_TIMEOUT`
`MISSING_PREREQ`
> Handle journey prereq error

- app/move/controllers/cancel.js
- app/move/controllers/cancel.test.js
- app/move/controllers/index.js
- app/move/fields/cancel.js
- app/move/fields/index.js
- app/move/index.js
- app/move/steps/cancel.js
- app/move/steps/index.js
- app/move/views/cancel.njk
- common/assets/scss/application.scss
- common/lib/api-client/models.js
- common/services/move.js
- common/services/move.test.js
- common/templates/form-wizard.njk
- common/templates/layouts/base.njk
- locales/en/fields.json
- locales/en/messages.json
- locales/en/moves.json
- test/fixtures/api-client/move.find.json
- test/fixtures/api-client/move.findAll.json
This change adds the initial journey to capture reasons for cancelling a move request.
It makes use of the existing form wizard library to capture form inputs and handle
validation of particular fields.
> [P4-629] Capture cancellation reason

- app/move/views/confirmation.njk
- locales/en/moves.json
This adds two small fixes to the confirmation page:
- add missing full stop to end of success sentence
- wrap dashboard link in paragraph so text size matches (the GOV.UK
design system doesn't provide the same font size style for elements
not wrapped in p, ul, etc.)
> Fix confirmation page copy

- app/move/controllers/create/move-details.js
- app/move/controllers/create/move-details.test.js
- common/services/reference-data.js
- common/services/reference-data.test.js
Previously the call to `referenceDataService.getLocations` was bringing back all `location_type` rather than a specific type. This work fixes that.
This work also removes the call to get `prison` locations as the form on this page no longer requires them
> Fix for locations

- app/move/controllers/cancel.js
- app/move/controllers/cancel.test.js
- app/move/controllers/view.js
- app/move/controllers/view.test.js
- app/move/views/view.njk
- common/components/message/_message.scss
- locales/en/messages.json
- locales/en/moves.json
If a move has been cancelled it will display a banner to signify
that this move is in a cancelled state.
The banner can be used in the future to show the status of a move and any further
information like reason for cancellation.
🚀 **[DEMO](https://book-a-secure-move.herokuapp.com/)** 🚀
> [P4-636] Display cancellation banner on move detail page

- app/move/controllers/create/move-details.test.js
- app/move/fields/create.js
- app/move/steps/create.js
- locales/en/fields.json
The move details form errors out because it is looking for a value that was being set by the recently removed prison recall select.
This work removes the need for a value from the prison recall select and
update tests where required.
> Fix for prison recall selection

- common/services/person.js
- common/services/person.test.js
The transformation of the person model response was moved to a
shared place so that we can do common things with each Person.
This was added to the Move service where a person exists on a move
but it wasn't added to the Person service.
This change ensure that all responses from the API regarding creating
or updating a person transform the response in the same way.
This relates to #211
> Ensure person service transforms the response

- app/move/middleware.js
- app/move/middleware.test.js
- app/moves/controllers/download.js
- app/moves/controllers/download.test.js
- app/moves/controllers/list.js
- app/moves/controllers/list.test.js
- app/moves/middleware.js
- app/moves/middleware.test.js
- app/moves/views/list.njk
- common/assets/scss/application.scss
- common/presenters/move-to-card-component.js
- common/presenters/move-to-card-component.test.js
- common/presenters/moves-by-to-location.js
- common/presenters/moves-by-to-location.test.js
- common/services/move.js
- common/services/move.test.js
- common/services/reference-data.test.js
- common/templates/layouts/base.njk
- locales/en/default.json
- locales/en/moves.json
This set of changes includes cancelled moves on the dashboard so that a user can still see and view the details of cancelled moves.
> [P4-634] Show cancelled moves on the dashboard

- app/moves/controllers/list.js
- app/moves/controllers/list.test.js
- app/moves/index.js
- app/moves/middleware.js
- app/moves/middleware.test.js
This change amends the location middleware to check that the user
can see this location before displaying the view.
Previously if a user knew the UUID of a location that they didn't have
access to they would've still been able to see that location's moves.
Now if a user accesses a UUID that is not found in their list of
permitted locations it will return a `404`.
**Note:** This change also includes a small refactor to the list controller.
> [P4-650] Ensure a user can only see locations they have access to

- app/moves/controllers/list.js
- app/moves/controllers/list.test.js
- app/moves/middleware.js
- app/moves/middleware.test.js
- app/moves/views/list.njk
This ensures a move date is valid before doing anything else with it.
In the instance that a move date is not valid it will redirect back
to the base URL of the moves app so that the user is redirected to
the default dashboard.
> [P4-661] Handle invalid move date

- common/templates/form-wizard.njk
- locales/en/validation.json
The GOV.UK Design System suggests using a prefix in the page title
so that screen readers will read out that there is an error straight
away:
https://design-system.service.gov.uk/components/error-summary/#how-it-works
This also allows us to track error pages separately in analytics
by using the page title as a secondary dimension.
> Add "Error:" page title prefix to form error pages

- app/move/views/_includes/assessment.njk
- common/components/meta-list/_meta-list.scss
- common/presenters/assessment-answer-to-tag.js
- common/presenters/assessment-answer-to-tag.test.js
- common/presenters/assessment-by-category.js
- common/presenters/assessment-by-category.test.js
- common/presenters/assessment-to-tag-list.js
- common/presenters/assessment-to-tag-list.test.js
- common/presenters/move-to-card-component.test.js
- config/nunjucks/filters.js
This change groups the flags to avoid duplicates being shown in the summaries.
This is particularly necessary for the way alerts are being pulled in from NOMIS.
> [P4-670] Alert groupings

- common/helpers/reference-data.js
- common/helpers/reference-data.test.js
- common/presenters/assessment-by-category.js
- common/presenters/assessment-by-category.test.js
- common/presenters/assessment-to-tag-list.js
- common/presenters/assessment-to-tag-list.test.js
- common/presenters/moves-to-csv.js
- common/presenters/moves-to-csv.test.js
- test/fixtures/moves.json
This change applies an expired filter to ensure expired alerts or flags are not displayed on the move detail page or the dashboard.
This is so that any flags that are no longer relevant are not displayed.
> [P4-685] Filter expired alerts

- common/assets/javascripts/analytics.js
- common/assets/javascripts/application.js
- common/templates/layouts/base.njk
This change adds a few improvement to how we are capturing things using analytics:
- ensure we are capturing basic metrics even when JS is not available
- capture error fields as events
> Analytics improvements

- app/move/controllers/create/assessment.js
- common/helpers/field.js
- common/helpers/field.test.js
If translations are available in our locales file then use these in the application. This means we can provide:
- form options `hint`locale translations
- override `title` text sent from the `BE` `API` with `label` locale translations
> [P4-437] - Use translations for assessment questions

- common/lib/api-client/auth.js
- common/lib/api-client/auth.test.js
- common/lib/api-client/index.js
- common/lib/api-client/index.test.js
- common/lib/api-client/middleware/auth.js
- common/lib/api-client/middleware/auth.test.js
- common/lib/api-client/models.test.js
This change refactors the way the  auth token is retrieved and set to connect to the backend API.
It refactors most of the logic from the middleware into a self-contained library that handles getting the token which makes the middleware a lot simpler and easier to test/mock elsewhere.
> Extract API client auth

- common/presenters/person-to-summary-list-component.js
- common/presenters/person-to-summary-list-component.test.js
- locales/en/fields.json
This maps over the identifiers on the person model and displays them
in the personal details section of the move detail page.
> Display other identifiers in person details

- common/assets/scss/components/_sticky-sidebar.scss
The summary panel appears over the content on mobile
Add an override class to stop this happening
> Mobile sticky sidebar fix

- config/nunjucks/filters.js
- config/nunjucks/filters.test.js
FormateDate also excepts a date object. This work ensures that a date
and a string are formatted to the correct date
> Fix for date being passed into formatDate

- app/move/controllers/create/personal-details.js
- app/move/controllers/create/personal-details.test.js
The current create journey creates a new person in the API each time the personal details step is saved. 
So if a user does:
- User completes personal details step
- Hits continue
- Hits "Back" on move details steps
- Hits continue
Then duplicate people will be created in the API
If a person already exists in the session then update their details via the personService rather than creating a duplicate. This avoids duplicate people being saved to the API and stops duplicates being created when a user goes back in the browser to update a person details.
> [P4-690] Update a person if they already exist

- common/lib/api-client/index.js
- common/lib/api-client/index.test.js
- common/lib/api-client/middleware/index.js
- common/lib/api-client/middleware/request.js
- common/lib/api-client/middleware/request.test.js
- common/lib/api-client/models.js
- common/lib/api-client/models.test.js
- config/index.js
- config/redis-store.js
- config/redis-store.test.js
- package-lock.json
- package.json
- server.js
This change allows API models to be cached rather than serving from the API each time.
This is useful for reference data that doesn't change very often.
- Is this the best place to cache this data? 
- Could we use a caching layer in between rather than using the frontend Redis instance?
- What's a reasonable time to cache this data? 
- 24 hours?
- 7 days?
> [P4-367] Cache reference data from API

- .env.example
- README.md
- config/index.js
This change amends the way the API is set in the environment variables.
Currently it requires the host to be defined 3 times for `API_BASE_URL`,
`API_HEALTHCHECK_URL` and `API_AUTH_URL`. If the host needs to be
changed, for example switching between environments when testing this
requires changing 3 variables.
This change just neatens that up so that it only needs to be defined once.
It introduces some temporary logic to make sure the change is backwards
compatible with current releases. Once all envionrments have been
updated this logic can be removed.
> Update API environment variable configuration

- package-lock.json
- package.json
- server.js
From Express v4.16.0 onwards `express.urlencoded` does what the Body Parser dependency does so no need to have both.
Details can be seen here:
http://expressjs.com/en/api.html#express.urlencoded
- `json` parsing and from submission both continue to work with these changes
- `npm t` passes
- Application works as in you can login and view the dashboard
> Remove Body Parser dependency

- server.js
This work omits any request data that is being sent to Sentry. This data could potentially hold form information such as `first` and `last` name.
This change means that if `request.data` exists in the Sentry `event` it is removed.
Information around sensitive data can be seen https://docs.sentry.io/data-management/sensitive-data/
> [P4-530] Remove PII information from Sentry data

- common/assets/scss/components/_icons.scss
- package-lock.json
- package.json
- server.js
- webpack.config.production.js
This work: 
- Revision images when `webpack` is ran in `production` mode
- Minify images when `webpack` is ran in `production` mode
- Tidy up of `webpack` `env` config files
- This work does not revision `GOVUK` or `MOJ` `dependency` assets. This will come in a separate PR if needed?
- The image size options could be tweaked a little more at the moment this just uses the default
> [P4-550] Revision images

- app/move/views/cancel.njk
- common/templates/form-wizard.njk
The Error page when you try and cancel a move and it the form validation errors does not have the `'Error:'` prefix in the page title element.
This work adds the `'Error:'` prefix in to the page title element.
> [P4-709] Add the 'Error:' prefix to cancel error page title

- package-lock.json
- package.json
- server.js
The cookie parser middleware is no longer needed for express session as
per the note found https://github.com/expressjs/session#sessionoptions
This work removes the cookie parser middleware.
Note: we are not using `req.cookies` anywhere in the app so this middleware has been added because it used to be required for `express-session` to work.
> Remove cookie parser middleware

- server.js
Force a session identifier cookie to be set on every response by adding
the 'rolling: true' property to express-session. Information can be
found https://github.com/expressjs/session#rolling
I suspect this will stop the timeout we see when a move is left for an amount of time even through the user is refreshing the page
> Extend session expiry on page loads

- package-lock.json
- package.json
- server.js
It turns out that hmpo-form-wizard requires the use of cookie-parser.
This work reverts the previous removal of cookie-parser in #267
> Reverting the removal of cookie-parser dep

- app/move/controllers/create/assessment.js
- app/move/controllers/create/assessment.test.js
- app/move/fields/create.js
- common/helpers/field.js
- common/helpers/field.test.js
- locales/en/fields.json
This work makes the "other" comment boxes in the assessment section of the move journey mandatory.
> [P4-545] Mandatory other free text

- app/move/controllers/create/base.js
- app/move/controllers/create/base.test.js
- common/controllers/form-wizard.js
- common/controllers/form-wizard.test.js
- common/templates/form-wizard-error.njk
- locales/en/errors.json
This change updates how the app handles a missing location.
If a location is missing it will be treated as an expected error
page.
It will display a message to go to the locations page to set one
before creating a move.
> Update missing location error handling

- common/lib/user.js
- common/lib/user.test.js
- common/services/reference-data.js
- common/services/reference-data.test.js
- common/services/user.js
- common/services/user.test.js
This change refactors the way locations are retrieved for supplier users.
When a user has a supplier role it will lookup the list of locations using a different filter from the API.
This then allows the user to be treated the same way as other users and to see a list of locations they can access.
This is the first step in filtering moves for suppliers.
> Refactor locations to cater for suppliers

- app/locations/controllers.js
- app/locations/controllers.test.js
- app/locations/index.js
- app/locations/views/locations.njk
- common/middleware/ensure-current-location.js
- common/middleware/ensure-current-location.test.js
- common/templates/layouts/base.njk
- locales/en/locations.json
This change updates how a location is checked and set.
This allows users with a role of `moves:view:all` to be able to select all moves available to them.
> Allow users to view all locations at once

- app/locations/views/locations.njk
- common/lib/api-client/models.js
- common/lib/api-client/models.test.js
- common/services/reference-data.js
- common/services/reference-data.test.js
- common/services/user.js
- common/services/user.test.js
- test/fixtures/api-client/supplier.find.json
- test/fixtures/api-client/supplier.findAll.json
This change uses the key retrieved from a supplier's auth group to get the list of available locations for that supplier.
> Use supplier auth group to retrieve locations

- common/lib/api-client/models.js
- test/fixtures/api-client/location.find.json
- test/fixtures/api-client/location.findAll.json
The location model in the API was missing the supplier attribute
that was added.
This change also removes the missing attribute warning that appeared.
> Add suppliers attribute to location model

- app/moves/middleware.js
- app/moves/middleware.test.js
Currently the root moves URL with date will allow a user to see all
moves in the system.
This change ensures they can view a collection of moves but only for
locations that they have access to.
This change is to allow suppliers to download a list of their moves
for all locations they have access to.
> Only allow user's to see their locations

- config/index.js
This logic was to allow the app to be released without affecting
previous builds. Now all environments have been updated this logic
can be removed.
> Remove temporary config logic

- package-lock.json
- package.json
Instead of linting all files on each commit we should lint just the staged (changed)
files since the rest of the files have already been linted in CI.
https://dsdmoj.atlassian.net/browse/P4-755
> Lint only staged files

- common/controllers/form-wizard.js
- common/controllers/form-wizard.test.js
- common/helpers/field.js
- common/helpers/field.test.js
The `abbr` html tag has been brought in previously for labels. This fix
changes the error messages to be html rather than text so that html can
be rendered in an error message.
> Fix for html in error messages

- app/moves/controllers/download.js
- app/moves/controllers/download.test.js
This fixes the download file name issue in Firefox.
> Wrap download file name in quotes

- .circleci/config.yml
Should fix the failing CP deployments
> Use book-a-secure-move GitHub group for Cloud Platform deployment through Circle

- README.md
This aligns the commands with the rest of the examples shown in the
README
> Prepend npm to the e2e example commands

- app/move/controllers/create/pnc-search-results.test.js
- app/move/steps/create.js
- app/move/views/create/pnc-search-results.njk
- common/helpers/field.js
- common/helpers/field.test.js
- test/e2e/moves.test.js
Bug fixes for the PNC search journey
- Upper case the detainees name
- Provide a `back` link on the PNC search results page
- Pre-populate the  PNC number when a user clicks the `Create a move for a different person` link
> [P4-776] - Bug fixes PNC search

- locales/en/moves.json
This fix means the search query is not escaped when it is passed to be displayed in the matches header. This is because PNC numbers generally contain a forward slash.
> Fix for the matches header containing html

- app/move/controllers/confirmation.js
- app/move/controllers/confirmation.test.js
- app/move/controllers/create/base.js
- app/move/controllers/create/base.test.js
- common/lib/analytics.js
- common/lib/analytics.test.js
- common/lib/user.js
- common/lib/user.test.js
- package.json
This work sends the Create a Move Journey duration to Google analytics.
It can be found in 
`behaviour` 
`-> site speed` 
`-> user timings`
This is GA from the demo site:
> [P4-788] - Send create a move journey time to GA

- app/move/controllers/confirmation.js
- app/move/controllers/confirmation.test.js
- app/move/controllers/create/base.js
- app/move/controllers/create/base.test.js
- common/lib/analytics.js
- common/lib/analytics.test.js
It was discovered by @spikeheap that `process.hrtime()` doesn't work across PODS on K8's. This work reverts the code to use the original implementation of `Date` rather than `process.hrtime()`
Of note - this has been tested on `heroku` and appears to be working correctly.
> [P4-788] - Switch to use Date for timing Create a move Journey - Analytics

- .circleci/config.yml
This PR adds preprod to the CircleCI pipeline. It doesn't depend on staging, and doesn't become a dependency on production.
We may want to revisit the workflow later on (e.g. to promote builds), this PR just adds the environment following the current approach.
> Add preprod to circleci pipeline

- app/locations/views/locations.njk
- config/nunjucks/filters.js
Formatting of locations was inconsistent in the UI layer
Align formatting of all location title in the UI layer to [titleCase/startCase](https://en.wikipedia.org/wiki/Letter_case#Title_case)
> This simplified variant of title case is also known as start case or initial caps.
> Format locations text

- common/components/card/template.test.js
- common/components/data/template.test.js
- common/components/internal-header/template.test.js
- common/components/link/template.test.js
- common/components/message/template.test.js
- common/components/meta-list/template.test.js
- common/components/multi-file-upload/template.test.js
- common/components/pagination/template.test.js
- common/components/panel/template.test.js
- common/components/results/template.test.js
- common/components/tag/template.test.js
- common/components/time/template.test.js
- common/controllers/form-wizard.test.js
- common/lib/component/helpers.js
- test/unit/component-helpers.js
- With the rendering of components via JavaScript now available in the app I wanted to dry up the use of the methods being shared between the app and tests.
- I also wanted to be more explicit with the naming of the render method used within tests so that it isn't used in the app
- Also a little bit of tidy up and removing of work that isnt being used
> Refactor component helpers

- common/lib/api-client/auth-request.js
- common/lib/api-client/auth-request.test.js
This argument is no longer needed as you can send the headers via config
in the `.post` method
> Remove headers argument

- test/e2e/helpers.js
- test/e2e/moves.test.js
This work improves the CSV waiting for downloads methods. 
Basically it now waits until the `glob.sync` looking for CSV downloads returns a result. When the glob returns a result it means the files have downloaded and exist. 
This also simplifies the work that was there previously and removes the hard wait of 5 seconds
which at some point would more than likely fail.
> Improve waiting for CSV downloads helpers

- app/move/controllers/create/base.test.js
- app/moves/controllers/download.test.js
- common/presenters/move-to-meta-list-component.test.js
- config/nunjucks/filters.test.js
Currently when the tests are run from a different timezone they fail
as they are expecting text based on a UTC timezone.
This updates the tests to mock run tests in UTC where possible so that
time related tests will always pass as expected no matter the timezone.
> Update tests to have expected timezone

- app/move/controllers/view.js
- app/move/controllers/view.test.js
- app/move/views/view.njk
- common/assets/scss/application.scss
- common/components/card/_card.scss
- common/components/card/card.yaml
- common/components/card/template.njk
- common/components/card/template.test.js
- common/presenters/move-to-card-component.js
- common/presenters/move-to-card-component.test.js
- config/i18n.js
- locales/en/moves.json
- locales/en/statuses.json
- test/unit/component-helpers.js
The layout in app-card might be seen as a bit cheeky -- happy to look into alternatives.
**Questions:**
- are the banners displayed for every possible status?
- will the statuses be translated?
- the explanation at the bottom of the big banner: which property of the move does it correspond to? (for example, is it additional_information?
> P4 558 display status

- locales/en/statuses.json
This adds content for the completed status to the locales file so that
if moves with a completed status come through they are displayed
correctly.
> Add completed status to locales

- common/components/meta-list/_meta-list.scss
> P4-909-wrap-text-in-details

- app/moves/index.js
The download all moves route was using the middleware for
a single location rather than all locations and was there not
filtering the moves.
This fix ensures the routes use the correct controller.
> Ensure download users correct middleware

- app/moves/controllers/download.js
- app/moves/controllers/download.test.js
- app/moves/controllers/list.js
- app/moves/controllers/list.test.js
- app/moves/middleware.js
- app/moves/middleware.test.js
- common/services/move.js
- common/services/move.test.js
This change extends the move service to include a method to get all
active move statuses. Currently that includes `requested`, `accepted` and `completed`
that we know of.
This will extend as more statuses are known.
> [P4-900] Add completed moves to move requests

- app/move/controllers/create/document.js
- app/move/controllers/create/document.test.js
- app/move/fields/create.js
- app/move/steps/create.js
- common/components/multi-file-upload/multi-file-upload.js
- common/components/multi-file-upload/multi-file-upload.yaml
- common/components/multi-file-upload/template.njk
- common/components/multi-file-upload/template.test.js
- common/helpers/field.js
- common/helpers/field.test.js
- locales/en/fields.json
This change is linked to P4-935 which will allow documents to be uploaded without the need for a move ID.
As part of this work some updates to the multi file upload component were required so this work is being split out to make it easier to review.
See breakdown of commits for reasoning behind changes.
> [P4-935] Update multi field component

- app/auth/middleware.js
- app/auth/middleware.test.js
Currently there is a bug where if the session expires on the frontend,
it will attempted to redirect to the auth service which will make a
call to see if the user is still authenticated.
If they are, it will regenerate the session, persisting some values.
However, the `currentLocation` value is not persisted across this
regeneration which means that the check locations middleware then
redirects the user back to the locations mountpath to choose their
location again even though, in their eyes, they were never logged
out.
To fix this, `req.session.currentLocation` is now persisted across
this session regeneration so that the user remains on the page they
were before the re-authentication.
> [P4-978] Ensure current location is persisted on session regeneration

- app/move/controllers/create/base.js
- app/move/controllers/create/base.test.js
- app/move/steps/create.js
This change moves the logic to set the correct button text for the
create journey, whether to display continue or schedule move, to
the controller so that this logic doesn't need to live in each step.
It also makes it easier when using the forking via next as the button
text will be dynamically set based on the next step of each current
step.
> [P4-742] Move button logic to controller

- app/move/controllers/create/document.js
- app/move/controllers/create/document.test.js
- common/services/document.js
As the delete method on the API doesn't actually delete a document
we don't need to call this method during the delete process in the
create journey.
Instead we can just remove that document from the session so that it
isn't sent to the API to associate to the move.
> [P4-933] Remove destroy method from document service

- common/helpers/field.js
- common/helpers/field.test.js
The field helper that builds the search results for the person search
will currently error if certain properties don't exist.
This ensures there are relevant defaults and adds test coverage for
these scenarios.
> Prevent field helper failing with no input

- common/lib/user.js
- common/lib/user.test.js
This change adds the relevant app level permissions for
Secure Training Centres (STC), Secure Children's Homes (SCH) and
Youth Offending Institutes (YOI).
> [P4-1029] Add permissions for STC/SCH/YOI

- .circleci/config.yml
This change updates the CircleCI workflow to be more specific based on branch and Git tag.
We use git tags when creating a new release to deploy to production so the workflow will now only run production jobs for git tags, including the manual approval. This means that all workflows on master will not remain "On hold" and therefore return a `pending` state.
It will allow us to see builds as success or failure on master rather than always in a pending state.
- build and tests (linting and unit testing)
- build and tests (linting and unit testing)
- build staging
- build preproduction
- deploy staging
- end to end tests
- deploy preproduction
This is for deployment to production only.
- build and tests (linting and unit testing)
- build staging
- build preproduction
- build production
- …
> Only run production build/deploy jobs on Git tags

- .circleci/config.yml
This uses the slack Orb in CircleCI config to only alert the channel
on master failures, not branches.
> Only notify slack on CircleCI failures

- app/move/fields/create.js
- app/move/steps/create.js
- locales/en/fields.json
- locales/en/moves.json
> [P4-1060] Step for the move agreed

- app/move/fields/create.js
- app/move/steps/create.js
- locales/en/fields.json
- locales/en/moves.json
Step for the move range input. Will appear only on journeys whose origin is a prison.
> [P4 1063] - Step for the move range input. Will appear only on journeys whose origin is a prison.

- app/move/controllers/create/assessment.js
- app/move/controllers/create/assessment.test.js
- app/move/fields/create.js
- app/move/steps/create.js
- common/helpers/field.test.js
- locales/en/fields.json
- locales/en/moves.json
This creates logic to split how different journeys will see the release status question.
Users sending some from Police/STC/SCH will see it asked as part of the risk step.
Prison users will see it asked as a separate step.
> [P4-968] Prison risk logic

- app/move/steps/create.js
- locales/en/fields.json
- locales/en/moves.json
This change creates a separate step just for capturing the special
vehicle assessment question for journeys where someone is being sent
from Prison.
It uses the same logic for the risk/release status steps.
@Andy-Millar I tweaked the label very slightly to match the rest of the page headings/field labels:
I swapped "they" for "this person".
> [P4-961] Add separate special vehicle step

- test/e2e/moves.test.js
A recent change to the special vehicle step broke the e2e tests as they
look for specific text.
In the future we will need to update them so they're not as dependent
on content but for now this will fix the breaking build.
> fix(createmove): Update e2e tests for special vehicle

- app/move/steps/create.js
- app/move/views/create/person-search-results.njk
- app/move/views/create/person-search.njk
- common/assets/scss/application.scss
- common/assets/scss/overrides/_buttons.scss
- common/templates/form-wizard.njk
- common/templates/layouts/base.njk
- config/nunjucks/filters.js
- locales/en/moves.json
When a user searches for someone with a prison number and there are no
results we need to ensure that they can't create a new person in our
system.
This adds logic to not allow a user to progress to the personal
details step.
It also includes some changes to the display logic of the messages
depending on if there are results or not.
> [P4-1086] Prevent prison person creation

- app/move/steps/create.js
This adds the logic needed to direct a user to the correct risk
page based on the from location. Previously it would use the
prison variation if a user selected "Prison" from the move type.
> fix: Set correct journey for prison to prison moves

- app/moves/controllers/index.js
- app/moves/controllers/list-proposed.js
- app/moves/index.js
- app/moves/views/_layout.njk
- app/moves/views/list-proposed.njk
- common/lib/permissions.js
- common/lib/user.js
- common/services/move.js
- common/services/move.test.js
- locales/en/moves.json
To note:
- this covers the story for the dashboard route only
- displays active moves instead of proposed moves
- displays moves by day instead of by week (will be tackled in P4-1065)
- has no download button
> [P4 1064] Skeleton of the dashboard that will be displaying proposed moves

- common/lib/user.js
- common/lib/user.test.js
My previous PR causes login to fail if the role is not in the list of the permissions.
> [NOJIRA] fix: Add fallback if role has no permissions

- app/move/controllers/confirmation.js
- app/move/controllers/confirmation.test.js
- app/move/controllers/create/base.js
- app/move/controllers/create/base.test.js
- app/move/controllers/create/save.js
- app/move/controllers/create/save.test.js
- app/move/index.js
- common/lib/analytics.js
- common/lib/analytics.test.js
- common/lib/user.js
- common/lib/user.test.js
This refactor removes the only current use of a user's role within
the codebase - sending journey times to analytics.
This logic is also no longer what we use to determine different journeys.
It also includes reworking the location of it to be confined to the
actual create journey and its session so we don't need to manipulate
the session within an analytics library and avoids us neeeding to pass
in the request object.
> Remove the need for user roles

- app/auth/middleware.js
- app/auth/middleware.test.js
- common/lib/access-token.js
- common/lib/access-token.test.js
This fixes a few errors we've been seeing in Sentry.
It also handles the case of a failed token better by returning a `403` to the user.
> Tidy up some sentry errors

- app/move/fields/create.js
- locales/en/fields.json
- test/e2e/page-model.js
The date refactor change the formatter to use a string rather than
the function that it needed to. This meant that certain date strings
that were previously supported no longer were supported.
This ensures the formatter is called correctly and uses the shared
date field object with other date fields, like date of birth.
It also includes an update to the e2e tests to catch if this changes
again in the future.
> fix: Ensure date field runs formatter

- common/lib/api-client/models.js
- test/fixtures/api-client/move.find.json
- test/fixtures/api-client/move.findAll.json
This adds the new attributes on the move model for prison transfer
moves.
It adds:
- `move_agreed` - whether a user has agreed the move with receiving prison
- `move_agreed_by` - if so, who it was agreed with
> feat: Add support for new move agreed attributes

- app/move/controllers/create/assessment.js
- app/move/controllers/create/assessment.test.js
- app/move/fields/create.js
- app/move/fields/create.test.js
- common/helpers/field.js
- common/helpers/field.test.js
- locales/en/fields.json
This refactors the way the assessment questions are populated. The main thing is to move the logic out of the controller and into one central place.
It also means we don't have to know about the suffix in too many different places. Only the locales files now.
> [P4-1106] Update assessment question helpers

- app/move/fields/create.js
- app/move/steps/create.js
- locales/en/fields.json
Previously we were using a different filter for the prison number
identifier. Trying to alias `nomis_offender_no` to `prison_number`
on the API caused issues so we're rolling the change back to only
consistently use `prison_number` for now.
This change updates the filter on the frontend to use the new API
filter.
> fix: Update prison number key

- .circleci/config.yml
The GitHub release command was being run without the code being checked
out for that job.
This should fix that the next time that workflow is released.
> fix: Ensure the code is checked out before running the GitHub release

- app/moves/middleware.js
- app/moves/middleware.test.js
Fixed a logical error in pagination, related to today's date.
> [NOJIRA] fix: Today date in pagination is to be current date, not the base date

- app/move/controllers/create/assessment.js
- app/move/controllers/create/assessment.test.js
- app/move/controllers/create/save.js
- app/move/controllers/create/save.test.js
- app/move/index.js
- app/move/steps/create.js
- app/move/views/create/assessment.njk
- locales/en/moves.json
This change includes a way to replay answers that we have for a user in NOMIS around their release status and their need for a special vehicle.
It uses the same pattern for displaying the flags as on the profile page.
> [P4-1106] Display NOMIS alerts on assessment pages

- app/move/index.js
A change made in `a556d2b` updated the create form wizard config to use
a shared template path. However, this meant that the default
`form-wizard` template was no longer found in that folder.
This change updates the path to the default template for the create
wizard.
> fix: Update default template for create wizard

- app/move/controllers/create/move-details.js
- app/move/controllers/create/move-details.test.js
- app/move/fields/create.js
- app/move/steps/create.js
- locales/en/fields.json
This change moves how the different fields are set within the move
details step.
We were doing a lot of logic in the initial configure method of the
controller. This adjusts some of that and makes use of the middleware
hooks within the form wizard to reduce the complexity of the methods,
also making them easier to test.
> Remove prison option for prison moves

- locales/en/moves.json
The search term was being passed to the i18n library which would escape
the value. Some PNC reference numbers contains characters like `/` so
we need to make sure they're not escaped.
> fix: Unescape search term in person search results

- locales/en/moves.json
As part of a previous update a translation key was removed.
This meant the content wasn't being displayed in the view anymore. This
change adds it back in.
> fix: Add back missing translation

- app/move/controllers/create/assessment.js
- app/move/controllers/create/assessment.test.js
- app/move/steps/create.js
This change allows a step to define what assessment answer keys should
be played back to the user for that step.
Before it relied on showing only fields that were in the step, but in
one case we also wanted to include pregnancy in the list of answers
we show.
> Add support to define keys to show for previous assessment

- README.md
- app/person/controllers.js
- app/person/controllers.test.js
- app/person/index.js
- config/index.js
This change reworks how images are retrieved from NOMIS. It introduces
a new environment variable that will allow us to turn the image sync
to NOMIS on or off by an environment variable (`FEATURE_FLAG_IMAGES`).
Once we decide we always want these on again we can revert this commit.
> refactor: Allow images to be controlled by env var

- common/lib/api-client/index.js
- common/lib/api-client/index.test.js
- common/lib/api-client/middleware/post.js
- common/lib/api-client/middleware/post.test.js
- common/lib/multer.api-document.storage.js
- common/lib/multer.api-document.storage.test.js
- locales/en/validation.json
Files that passed Multer's vaildation but failed to be successfully uploaded to the document store resulted in an error message like this:
Post fix:
> [P4 1082] fix: Prevent garbled message on failed attempt to upload file on STC/SCH move

- app/moves/controllers/index.js
- app/moves/controllers/list-by-status.js
- app/moves/index.js
- app/moves/middleware.js
- app/moves/middleware.test.js
- app/moves/views/_layout.njk
- app/moves/views/list-by-status.njk
- common/assets/scss/components/_all.scss
- common/components/filter/_filter.scss
- common/components/filter/filter.yaml
- common/components/filter/macro.njk
- common/components/filter/template.njk
- common/components/filter/template.test.js
- common/presenters/index.js
- common/presenters/move-type-for-filter.js
- common/services/move.js
- common/services/move.test.js
- common/templates/layouts/base.njk
- locales/en/moves.json
This pr contains the routes and the links for the various types of moves displayed in the dashboard in the OCA workflow. 
Small viewport:
Very small viewport:
> [P4-1139] feat: Navigation for multiple types of moves

- app/move/controllers/create/base.test.js
- app/move/formatters.js
- app/move/formatters.test.js
- app/move/validators.js
- app/move/validators.test.js
- common/helpers/field.js
- common/helpers/field.test.js
- config/nunjucks/filters.js
- config/nunjucks/filters.test.js
- locales/en/validation.json
This PR contains a number of changes related to capturing hearing time for Prison to Court moves.
That change required some extension to existing libraries like formatters, validators and filters.
The major change is currently blocked by some API changes that it requires first so these changes are being split into a separate PR so that they can be merged now.
See #398 for the changes related to the create move journey.
> [P4-1154] Capture hearing time and court case setup

- app/moves/middleware.js
- app/moves/middleware.test.js
- common/assets/scss/application.scss
- common/templates/layouts/base.njk
- locales/en/default.json
This pr removes the beta banner and adds a primary navigation in every page.
N.B. This change affects the whole site! Do not merge unless approved on every level :-)
> [P4-1149] feat: Primary navigation with link to the dashboard

- common/presenters/person-to-card-component.js
- common/presenters/person-to-card-component.test.js
- common/services/person.js
- common/services/person.test.js
- config/index.js
- test/e2e/helpers.js
- test/e2e/move.new.police.test.js
- test/e2e/move.new.prison.test.js
- test/e2e/move.new.stc.test.js
- test/e2e/pages/create-move.js
- test/e2e/pages/move-detail.js
- test/e2e/roles.js
- test/e2e/smoke.test.js
This change includes a further refactor of the end-to-end test suite to allow us to create fixtures more easily and re-use more of the code across different journeys.
It also fixes a few bugs that were spotted within existing libraries whilst running these new scenarios.
If it's easier these can be split out into a separate PR...
> [P4-1112] Prison to Court end-to-end tests

- app/locations/views/locations.njk
- common/templates/layouts/base.njk
This PR:
- fixes the wrong label in the primary navigation, as it was determined by location only and not permissions
- removes the primary navigation in the location template, as it's too early to determine its link
> [NOJIRA] fix: Navigation displays wrong label

- app/move/steps/create.js
- test/e2e/move.new.prison.test.js
- test/e2e/move.new.stc.test.js
This fixes 2 issues that are causing the end-to-end tests to fail:
- Date range step is shown to all prison journeys
- End-to-end tests for STC and Prison don't cater for separate move date step
> Fix end-to-end tests

- README.md
- app/auth/middleware.js
- app/auth/middleware.test.js
- app/moves/middleware.test.js
- common/components/multi-file-upload/multi-file-upload.js
- common/components/multi-file-upload/template.njk
- common/middleware/ensure-authenticated.js
- common/middleware/ensure-authenticated.test.js
- common/middleware/ensure-body-processed.js
- common/middleware/errors.js
- common/middleware/errors.test.js
- common/middleware/process-original-request-body.js
- common/middleware/process-original-request-body.test.js
- config/index.js
- locales/en/errors.json
- locales/en/validation.json
- server.js
Problem
-------
After successfully reauthenticating a user, the user's session is regenerated. Unfortunately this had the side-effect of losing all the info that HMPO form wizard has stored resulting in the user seeing a session timeout message (or for xhr requests, the cryptic 'Server returned code 0')
Even if the HMPO form wizard was not being lost, the reauthentication redirect would have the effect of causing any posted information to be dropped.
Ideally a new token could just be requested using the refresh token rather than redirecting the user, but the HMPPS OAuth server does not support refresh tokens for the type of grant we require.
Fix
---
- Copy properties from previous session to new one
- Stash POST body (if any) in `req.session.originalRequestBody` when redirecting to …
> fix: [P4-1041] Extend service timeout

- app/move/controllers/confirmation.js
- app/move/controllers/confirmation.test.js
- app/move/views/confirmation.njk
- locales/en/default.json
- locales/en/moves.json
This adds the ability to display the supplier that serves that location
on the confirmation page.
If there are no suppliers mapped it uses a fallback.
This change is linked to #404 but has been separated so that it can be merged to avoid conflicts.
> [P4-1108] feat: Use supplier name in confirmation message

- app/moves/middleware.test.js
Fixed unit test which attempted to destructuring an inexistent object.
> fix: Fix broken unit test

- common/templates/layouts/base.njk
There are some more changes that need to be made to the navigation for
it to be in a fully releasable state but we would like to release
some other changes from master so this change temporarily removes
it from the template.
> chore: Temporarily hide the primary navigation

- common/middleware/errors.js
- common/middleware/errors.test.js
- common/templates/error.njk
- locales/en/errors.json
This change adds a message to the error page for prison locations to communicate that the problem may be with NOMIS.
This is an MVP solution for now. We didn't want to go down the route of monitoring live uptime of NOMIS as our reliance is still quite minimal.
> [P4-1111] Show status of NOMIS

- common/services/person.js
- common/services/person.test.js
Previously, if no identifiers existed the formatter would set the
value to an empty array. This meant it would delete any that already
existed on that person if only another attribute was being updated.
This change ensures that with no existing identifiers it would not
override that value.
> fix: Ensure person formatter doesn't send empty identifiers

- app/moves/controllers/dashboard.js
- app/moves/controllers/index.js
- app/moves/index.js
- app/moves/middleware.js
- app/moves/middleware.test.js
- app/moves/views/dashboard.njk
- common/components/filter/_filter.scss
- common/components/filter/filter.yaml
- common/components/filter/template.njk
- common/components/filter/template.test.js
- common/presenters/move-type-for-filter.js
- common/presenters/move-type-for-filter.test.js
- config/nunjucks/filters.js
- config/nunjucks/filters.test.js
- locales/en/moves.json
This is the dashboard for the OCA journey. For now allowances are not included, as agreed with Andrew.
The existing URLs for the moves now acquire the suffix `/outgoing`, in preparation from when we will have `/incoming` as well. The current "default" view per location url is now taken by the dashboard.
Each box in the filter of the dashboard links to the corresponding filtered view; however, `total` links to `proposed`.
Please note before merging this that this changes the behaviour of the existing public website.
No e-2-e tests were harmed in the making of this change.
> [P4-1212]: feat: Dashboard for the OCA journey

- app/move/fields/create.js
This change ensures the step now behaves more consistently with other
steps that only have one question. It's also the pattern suggested
on the GOV.UK Design System when asking only one question on a page.
> fix: Visually hide date fieldset legend

- app/move/fields/create.js
- common/helpers/field.js
- common/helpers/field.test.js
This helper method was mutating the original field and assigning
the dependent property. This meant in the case where lots of fields
existed, each field got the value of the last item.
This change creates a copy and re-assigns the field rather than
adding a property to the original field object.
> [P4-1224] fix: Prevent field helper mutating properties

- app/move/views/_includes/assessment.njk
- test/e2e/move.new.police.test.js
- test/e2e/pages/move-detail.js
This change ensures that the court information section is only displayed on the move detail page when the move is to a court location.
Previously we would show the court section for all types of moves, but for Police to Prison or Prison to Prison moves for example, we will no longer need to display this information.
<kbd><img src="https://user-images.githubusercontent.com/3327997/78652995-657a8580-78ba-11ea-8a0e-e8bc1b988e79.png"></kbd>
<kbd><img src="https://user-images.githubusercontent.com/3327997/78652957-5693d300-78ba-11ea-8acb-e38eac1063cc.png"></kbd>
> [P4-1237] Ensure court information is only displayed when appropriate

- app/move/views/confirmation.njk
- locales/en/moves.json
- test/e2e/pages/create-move.js
The text on the confirmation page is different between scheduled and proposed moves.
Also: fixed broken e2e test.
> [NOJIRA] Fix end to end test and confirmation page for proposed moves

- app/move/controllers/confirmation.js
- app/move/controllers/confirmation.test.js
- app/move/views/confirmation.njk
- config/nunjucks/filters.js
- config/nunjucks/filters.test.js
- locales/en/moves.json
This change involves adding messages to the confirmation page of creating a new move to display whether the relevant information has been added to NOMIS or not.
The two scenarios use distinctly different components to draw more attention to the case where something needs to be done.
It also has basic handling for when multiple hearings are supported when creating a move - it will join case numbers using commas and the word "and".
**Note:** This only applies to moves from a Prison to a Court
- Message to user to say has been added successfully (includes date and case number)
- Includes content to add further hearings to NOMIS
<kbd><img src="https://user-images.githubusercontent.com/3327997/78820274-69e49280-79cf-11ea-945d-5b7814e2a55d.png"></kbd>
<kbd><img …
> [P4-1108] Add message to confirmation page with sync status

- app/move/controllers/view.js
- app/move/controllers/view.test.js
- app/move/views/_includes/assessment.njk
- common/presenters/court-hearing-to-summary-list-component.js
- common/presenters/court-hearing-to-summary-list-component.test.js
- common/presenters/index.js
- locales/en/moves.json
This change adds hearings to the display of hearings on the move detail page. It uses the GOV.UK Summary List component to display the information for a hearing and will not display any rows that don't have a value.
It also changes the display slightly based on the number of hearings. If there is only one hearing it condenses the display of numbers and uses a singular heading.
If a court date was not created in NOMIS during the creation of the move it will display a warning message to check manually that the court date has been created.
<kbd><img src="https://user-images.githubusercontent.com/3327997/78900431-bfbc4780-7a6e-11ea-9899-f8b383782f32.png"></kbd>
<kbd><img src="https://user-images.githubusercontent.com/3327997/78900104-46245980-7a6e-11ea-8dc7-d52cb6e7d7c2.png"></kbd>
<kbd><img …
> [P4-1236] Display hearings on move detail page

- .mocharc.js
- package.json
- test/unit/mocha.opts
As of v6.0.0 mocha now supports [configuration files](https://mochajs.org/#configuring-mocha-nodejs) and will likely
deprecate the use of [mocha.opts](https://mochajs.org/#mochaopts) in future releases.
This change updates the way we configure mocha to be ready for any
future deprecations.
> Update mocha configuration method

- common/lib/analytics.js
- common/lib/analytics.test.js
This change updates the way uuid v4 is imported as since v7 in
the uuid package the method we use is no longer supported.
> Update deprecated uuid/v4 import

- app/move/views/cancel.njk
Used the `html` property to output the cancellation step message instead of `text`.
In the cancellation step names that contain special characters are
currently being escaped.
This change ensures that names are displayed correctly if they contain
apostrophes or hyphens.
<kbd><img src="https://user-images.githubusercontent.com/3327997/79128771-f9a58a80-7d9b-11ea-9cbb-07f2bca0cdc9.png"></kbd>
<kbd><img src="https://user-images.githubusercontent.com/3327997/79128724-ebf00500-7d9b-11ea-8dda-668f73f0cc16.png"></kbd>
> Ensure names that contain special characters don't escape

- app/move/controllers/create/court-hearings.js
- app/move/controllers/create/court-hearings.test.js
- app/move/controllers/create/save.js
- app/move/controllers/create/save.test.js
- common/services/court-hearing.js
- common/services/court-hearing.test.js
Court hearings were previously being saved after the court hearings
step. But this meant they were being sent without a move ID, which is
required to be able to save that hearing to NOMIS.
This change moves that logic until after the creation of a move so that the move ID can
be sent as part of the court hearing. This allows it to be created in NOMIS and associates
that court hearing with the move.
> Move saving of court hearings to end of create journey

- app/move/controllers/create/save.js
- app/move/controllers/create/save.test.js
Currently when a move is created without the court hearings step
the property that is mapped doesn't exist which meant the map would
fail.
This change ensures that if the property doesn't exist is creates a
fallback array.
> Handle moves with no court hearings

- common/lib/api-client/middleware/request.js
- config/redis-store.js
- config/redis-store.test.js
- server.js
This fix moves the config into the redis store library so that if
it is created without config, it will use the settings from the config
file.
This means the load order is less important when creating the client.
It also means that it can be used elsewhere without needing to pass in
the configuration, for example, without end-to-end tests.
> fix: Use fallback config when creating Redis store

- README.md
- common/lib/api-client/index.js
- common/lib/api-client/middleware/request.js
- common/lib/api-client/middleware/request.test.js
- config/index.js
This change introduces environment variable support for API cache.
It adds support for:
- cache to be completely disabled, which can be useful during
development or debugging
- the expiry time to be changed per environment, can be useful to have
shorter expiry on staging/development environments
> feat: Allow API cache to be controlled by environment variables

- README.md
- app/person/controllers.js
- app/person/controllers.test.js
- app/person/index.js
- config/index.js
This change undoes the introduction of a feature flag to toggle the loading of images.
It was done whilst there was a bug in the API so that we could quickly switch it on or off in
production whilst it was being debugged. It's not working fully. We'd rather not have lots of
feature flag toggles all around the app so this code is being removed to tidy up some of that
tech debt.
This reverts commit 8141bb2babcba3cf86a95b345bbd9cbf7a1e36a2.
> Revert "refactor: Allow images to be controlled by env var"

- common/components/message/_message.scss
- common/components/message/message.js
- common/components/message/message.yaml
- common/components/message/template.njk
- common/components/message/template.test.js
This introduces the ability to focus the message component using
a configuration item. If this is enabled the element will be focused on page
load. This will help improve accessibility as assistive technologies like
screenreaders will read this content first.
It also includes an update to the style to show the focused state when the element
is focused.
> [P4-1306] Allow message component to be focusable

- app/move/controllers/create/base.js
- app/move/controllers/create/base.test.js
- app/move/views/confirmation.njk
- locales/en/actions.json
- locales/en/errors.json
- locales/en/messages.json
- locales/en/moves.json
The statuses for a move were recently updated. We used to refer to a
move as "Scheduled" when it was created, but with the introduction of
different states for a supplier this term was changed to "Requested".
Currently we use a mix of the two terms which could be confusing to users.
This change ensures we have consistency in terminology and updates
any existing references to "Scheduled" to be "Requested".
Notice the inconsistency between "Scheduled" and "Requested" in the submit button, the confirmation banner and the status indicators on the move detail and dashboard.
There was also inconsistency with "Reference number" and "Move reference" between the confirmation banner and the dashboard and move detail pages.
<kbd><img src="https://user-images.githubusercontent.com/3327997/79864038-ab6 …
> Update consistency of "requested" language

- app/move/controllers/create/move-details.js
- app/move/controllers/create/move-details.test.js
- app/move/fields/create.js
- app/move/steps/create.js
- common/lib/permissions.js
- common/lib/user.test.js
- locales/en/fields.json
This refactor moves some of the existing logic from the steps object
to one of the controllers.
It moves the logic for determining which destinations a user can send
a person to. That logic has had to be based on permissions to some extent
which meant creating various different "steps" and using the [Form Wizard
forking logic](https://github.com/UKHomeOffice/passports-form-wizard#next-steps) to handle that.
This caused a problem when trying to introduce the ability to go back
and make a change to the move details when there is a conflict as there
isn't one step to direct a user to.
The existing logic also meant transforming the name of one of the fields
to not break the logic within the process method of the lifecycle.
This change uses permissions to determine which types of move a user …
> [P4-1306] Extend permissions to determine permitted destinations

- test/e2e/pages/create-move.js
The way move details is constructed changed and this test wasn't
updated at the same time.
This updates the selector so they will now pass.
> fix(e2e): Update selector used in end-to-end tests

- common/components/read-only-field/macro.njk
- common/components/read-only-field/read-only-field.yaml
- common/components/read-only-field/template.njk
- common/components/read-only-field/template.test.js
- common/templates/layouts/base.njk
- test/unit/component-helpers.js
Display the value of a field rather than allow the user to edit it.
Optionally output further additional components (just details for now).
Read-only
> Add read-only field component

- app/move/controllers/create/save.js
- app/move/controllers/create/save.test.js
- app/move/steps/create.js
- app/move/views/create/save-conflict.njk
- locales/en/validation.json
This fix handles `422` errors during move creation where the reason code
is `taken`.
This means that the user is trying to create a duplicate
move (same to and from location, date and person) which the service
doesn't currently allow.
We now provide the user with better feedback that this is what has
happened and a link to the existing move, as well as options to change
the date or location if they still want to create a move for that person.
**Note:** Depends on #442 
<kbd><img src="https://user-images.githubusercontent.com/3327997/79869820-e4eb7700-83d9-11ea-90ee-9465ffa9d0d9.gif"></kbd>
<kbd><img src="https://user-images.githubusercontent.com/3327997/79870188-82df4180-83da-11ea-8942-5b92ec86d079.gif"></kbd>
<kbd><img src="https://user-images.githubusercontent.com/3327997/79868844-719535 …
> [P4-1306] Provide better user feedback when a move conflict occurs

- app/allocations/middleware.js
- app/allocations/middleware.test.js
- app/moves/controllers/list-by-status.js
- app/moves/views/list-by-status.njk
- common/assets/scss/application.scss
- common/lib/api-client/models.js
- common/lib/api-client/models.test.js
- common/presenters/index.js
- common/presenters/moves-to-table.js
- common/presenters/moves-to-table.test.js
- common/presenters/object-to-table-head.js
- common/presenters/object-to-table-head.test.js
- common/presenters/object-to-table-row.js
- common/presenters/object-to-table-row.test.js
- common/templates/layouts/base.njk
- config/nunjucks/filters.js
- config/nunjucks/filters.test.js
- locales/en/allocations.json
- locales/en/default.json
- locales/en/moves.json
- test/fixtures/api-client/allocation.findAll.json
- test/fixtures/api-client/move.find.json
- test/fixtures/api-client/move.findAll.json
This PR represents a first iteration of the table component, with no pagination nor sorting. I have used the OCA journey to mount it since the PMU dashboard is not ready yet.
A couple of things:
- this PR has unearthed a previously unnoticed bug: the reason for move is not saved correctly. I will investigate the reason
- The default output of the date range filter when passed only one date is different from the format of the single date formatter (you can notice the difference in the second row of the screenshot). This may need to be addressed separately.
- I have kept the table presenter very generic for it to work for both moves and allocations, and I am sure this will cause discussion, since therefore most of the presentational behaviour is handled by the config attached in the …
> [P4 1309] Generic table for allocations and moves

- app/move/views/view.njk
- common/assets/scss/core/_elements.scss
- common/templates/form-wizard.njk
- common/templates/layouts/two-column.njk
This change adds the person's image to the right hand summary panel
displayed on both the move creation journey and the move detail
page.
<kbd><img src="https://user-images.githubusercontent.com/3327997/80319423-05fffd80-8808-11ea-89ba-4cddc9ef0bf5.png"></kbd>
<kbd><img src="https://user-images.githubusercontent.com/3327997/80319437-1adc9100-8808-11ea-93ba-782bd0363ce7.png"></kbd>
> [P4-1307] Add image to move detail and create summary

- test/e2e/_helpers.js
When selector is a label with a `for` attribute targeting a radio or checkbox input, `t.click(selector)` focuses the input but does not always select it.
This ensures that the actual input (if one is present) is clicked instead which appears to be rock solid.
> fix: Ensure that radios and checkboxes are selected when clicked

- common/templates/form-wizard.njk
The person image in the form wizard journey is using the wrong
variable.
Copy + paste error when making a tweak to the two different
places it was being used...
> fix: Use correct variable for person image during creation journey

- common/lib/api-client/middleware/request.js
This adds the key that is used to cache requests from the API in
the devour middleware debugging lines. This then allows you to see
what URLs are being called on the API.
> build: Output cache key when debugging API client

- app/move/controllers/create/court-hearings.js
- app/move/controllers/create/court-hearings.test.js
- common/services/person.js
- common/services/person.test.js
The API endpoint has been updated to include a filter to show active
court cases rather. This is the corresponding change on the frontend
to support that update.
cc/ @alexdesi
> fix: Update court cases endpoint to only return active cases

- app/move/controllers/view.js
- app/move/controllers/view.test.js
- app/move/views/cancel.njk
- app/move/views/confirmation.njk
- app/move/views/create/save-conflict.njk
- app/move/views/view.njk
- common/templates/form-wizard.njk
- common/templates/includes/messages.njk
- common/templates/layouts/base.njk
- locales/en/statuses.json
This updates the header section of the move detail page to use banners
less frequently and only for particular states. It reverts some changes
to introduce the banner for all statuses.
Now it uses the same style as on the dashboard to provide more continuity
across pages.
Particular states which need to draw more attention, like a cancelled
state, now use the temporary notice banner so that they are more obvious
that the move is in a unique state.
This change will also now better support the addition of "flash" banners that will appear after successfully saving updates.
| <kbd><img src="https://user-images.githubusercontent.com/3327997/80415379-5fc8fc00-88ca-11ea-9634-7a2ade3e78e7.png"></kbd> | <kbd><img …
> Update move detail banners

- app/allocations/controllers/index.js
- app/allocations/controllers/list.js
- app/allocations/controllers/list.test.js
- app/allocations/index.js
- app/allocations/middleware.js
- app/allocations/middleware.test.js
- app/allocations/views/list.njk
- common/presenters/allocations-to-table.js
- common/presenters/allocations-to-table.test.js
- common/presenters/index.js
- common/services/allocation.js
- common/services/allocation.test.js
- locales/en/allocations.json
This is a partial version of the dashboard for allocations. It doesn't contain yet the progress status, nor the sorting. There's no BE support for either yet, nor there is proper filtering: every allocation is always returned.
One notable awkwardness is that some of our filters are boolean, and when they are in the url, `req.query` returns them as strings. This is due by express depending on qs, where `parseBool` is apparently an hotly debated issue and has never been included.
This has led to reverting the elimination of query-string, and using said module to parse the original query string instead of using `req.query`. It's not that great and we might just decide we don't want boolean filters, although this can be seen as a serious limitation.
> [P4 1280] List view for allocations

- common/presenters/move-to-card-component.js
- common/presenters/move-to-card-component.test.js
- test/e2e/pages/move-detail.js
The banners were recently updated and the identifier used has also
changed.
This caused some of the end-to-end tests to fail.
This fix updates the identifier for that element to the new one.
This PR also contains an update to ensure the status badge is only shown for
cards that require them to be distinguished - cancelled moves are already separated
on the page.
> [Fix] End-to-end tests for cancelled banner

- common/middleware/permissions.js
- common/middleware/permissions.test.js
Update middleware check method (and all methods that piggyback on it) to accept a string or an array.
```
app.use(protectRoute(['foo', 'bar']))
equivalent to: app.use(protectRoute('foo'), protectRoute('bar'))
```
```
canAccess(['foo', 'bar'])
equivalent to: canAccess('foo') && canAccess('bar')
```
> refactor: Allow permission check to use string or array

- app/move/controllers/update/base.js
- app/move/controllers/update/base.test.js
- app/move/controllers/view.js
- app/move/controllers/view.test.js
- app/move/controllers/view/view.update.links.js
- app/move/controllers/view/view.update.links.test.js
- app/move/controllers/view/view.update.urls.js
- app/move/controllers/view/view.update.urls.test.js
- app/move/index.js
- app/move/steps/update.js
- app/move/views/_includes/assessment.njk
- app/move/views/view.njk
- common/components/meta-list/_meta-list.scss
- common/components/meta-list/meta-list.yaml
- common/components/meta-list/template.njk
- common/components/meta-list/template.test.js
- common/presenters/move-to-meta-list-component.js
- common/presenters/move-to-meta-list-component.test.js
- locales/en/moves.json
- test/e2e/_move.js
- test/e2e/_routes.js
- test/e2e/move.update.police.test.js
- test/e2e/pages/create-move.js
- Enable multiple steps to be loaded per journey
- Enable different role per journey
- Use key for urls and locales lookup rather than brittle url munging
- Process all update link data up front in move view
- Add ability to moveSummaryList component to output action links
- Enable link to update move date
- Suppress updating of to location route until redirect endpoint in place
- Ensure e2e tests actually change gender
> Improve loading of update steps

- common/templates/layouts/list-view.njk
- config/nunjucks/filters.js
- config/nunjucks/filters.test.js
This set of changes improves the way date ranges are handled around the single request journeys.
It caters for when there is only date, ensuring it uses the same default format as elsewhere in the application as well as allowing relative dates to be explicitly used to avoid date ranges in a table being shown as "This week".
| <kbd><img src="https://user-images.githubusercontent.com/3327997/80604572-ca447e00-8a29-11ea-9f13-7c13d8e63d02.png"></kbd> | <kbd><img src="https://user-images.githubusercontent.com/3327997/80604682-f06a1e00-8a29-11ea-910d-e586aa30d4aa.png"></kbd> |
> [Fix] Date range filters

- common/presenters/move-to-meta-list-component.js
- common/presenters/move-to-meta-list-component.test.js
Previously we were combining the from and to date into the one date
row on the right hand move summary panel.
We've decided to split this into separate rows to give a clearer picture
of the situation.
This also fixes a bug where the mock date happened to be tomorrow and
we weren't mocking the date formatters which caused the text to be
different and the tests to start failing.
*No changes - posting for visual reference to other states*
| <kbd><img src="https://user-images.githubusercontent.com/3327997/80694473-78086900-8acc-11ea-805f-39a90f228511.png"></kbd> | <kbd><img src="https://user-images.githubusercontent.com/3327997/80694473-78086900-8acc-11ea-805f-39a90f228511.png"></kbd> |
| <kbd><img …
> fix: Update how from and to dates are handled in the summary panel

- common/services/move.js
- common/services/move.test.js
The prison transfer reason is currently a relationship in the API, so
when we are sending that data from something like the formwizard to the
service we need to make sure the value is structured correctly as an
object.
Otherwise the devour serializer will not send it correctly to the API
and will not store the value correctly.
**Note:** I'd like to fix this properly ideally so it maybe happens as part of the serializer. It could use the models config to see if the attribute is a relationship and if the string is a UUID format, transform to a correctly formatted object.
This could also be used for the person formatter.
> fix: Format prison transfer relationships

- app/moves/controllers/dashboard.js
- app/moves/views/dashboard.njk
- app/moves/views/list-by-status.njk
- app/moves/views/list.njk
- common/templates/layouts/list-view.njk
- locales/en/moves.json
- locales/en/statuses.json
This set of changes includes adding back in the download (if a user has permission to download) and print links that appear on the other dashboards for the single requests page.
It also includes some updates to the content to make things more consistency across the different screens.
*Click screenshots to enlarge*
| <kbd><img src="https://user-images.githubusercontent.com/3327997/80610102-d7b13680-8a30-11ea-960a-63179280a917.png"></kbd> | <kbd><img src="https://user-images.githubusercontent.com/3327997/80609493-0b3f9100-8a30-11ea-9322-ce580cf075e2.png"></kbd> |
| <kbd><img src="https://user-images.githubusercontent.com/3327997/80610027-bfd9b280-8a30-11ea-9fc9-62f509561e01.png"></kbd> | <kbd><img …
> Add download and print links to single requests dashboard

- app/moves/controllers/list.js
- app/moves/controllers/list.test.js
- common/components/card/_card.scss
- common/presenters/move-to-card-component.js
- common/presenters/move-to-card-component.test.js
- common/presenters/moves-to-table.js
- common/presenters/moves-to-table.test.js
- common/presenters/person-to-card-component.js
- common/presenters/person-to-card-component.test.js
- common/services/move.js
- common/services/move.test.js
- locales/en/moves.json
This change make use of re-using the card component when displaying
moves within a table layout. This means we can have more consistency between different layouts
when displaying a person's information.
The word "Move" was also removed from the reference label so it could be displayed better in the table layout. This update occurs across existing dashboards and layouts too.
This change also includes an update to the ordering so that they are ordered by the latest created move.
*Click image to enlarge*
| <kbd><img src="https://user-images.githubusercontent.com/3327997/80633008-fffc5d80-8a4f-11ea-981d-f0db8ac35cbf.png"></kbd> | <kbd><img src="https://user-images.githubusercontent.com/3327997/80632584-63d25680-8a4f-11ea-9088-7d57efd20e7e.png"></kbd> |
| …
> Use card component within table layout

- test/e2e/pages/create-move.js
Some form field names recently changed but the updates were missed
in the end-to-end tests.
This fixes the relevant selectors.
> fix: Update selectors in end-to-end tests

- app/move/controllers/update/assessment.js
- app/move/controllers/update/assessment.test.js
- app/move/controllers/update/base.js
- app/move/controllers/update/base.test.js
- app/move/controllers/update/move-date.js
- app/move/controllers/update/move-date.test.js
- app/move/controllers/update/move-details.js
- app/move/controllers/update/move-details.test.js
- app/move/controllers/update/personal-details.js
- app/move/controllers/update/personal-details.test.js
- app/move/index.js
- app/move/steps/update.js
- locales/en/moves.json
If any values on a move are changed, we now display a confirmation message that they have been saved on the move view page.
> Show confirmation message after updating move [P4 1353]

- common/lib/api-client/models.js
This adds the `disabled_at` attribute to the prison transfer model.
This removes the warnings that devour issues when the model doesn't
contain an attribute that is returned.
> chore: Add missing attributes to prison transfer reason model

- test/e2e/pages/dashboard.js
- test/e2e/pages/index.js
- test/e2e/smoke.test.js
The root dashboard was changed to remove the pagination and to act
more like a springboard into other parts of the service. This broke the
existing smoke tests.
This change adapts the smoke tests to cater for a different style of
dashboard and introduces a new page object to deal with them.
> fix: Update end-to-end tests to support new "home" dashboard

- README.md
- app/move/controllers/create/court-hearings.js
- app/move/controllers/create/court-hearings.test.js
- app/move/controllers/create/save.js
- app/move/controllers/create/save.test.js
- app/move/fields/court-hearing-start-time.js
- app/move/fields/has-court-case.js
- app/move/steps/create.js
- app/move/validators.js
- app/move/validators.test.js
- common/lib/api-client/models.js
- common/lib/api-client/models.test.js
- common/presenters/timetable-to-table-component.js
- common/presenters/timetable-to-table-component.test.js
- common/services/court-hearing.js
- common/services/court-hearing.test.js
- common/services/person.js
- common/services/person.test.js
- config/index.js
- config/nunjucks/filters.js
- config/nunjucks/filters.test.js
- locales/en/fields.json
- locales/en/moves.json
- locales/en/validation.json
- test/e2e/pages/create-move.js
- test/e2e/smoke.test.js
- test/fixtures/api-client/timetable_entry.findAll.json
This adds the timetable step to the existing journey that was built in #459.
It now also includes some updates to the way the frontend talks to the API and some extra validation to ensure the start time of the court hearing is in the future.
This work also adds a feature flag so this can be merged and deployed without being immediately released.
> [P4-1155] Link timetable journey together

- common/controllers/form-wizard.js
- common/controllers/form-wizard.test.js
- locales/en/errors.json
This change improves how CSRF errors are dealt with. At the moment,
they fallback to the default error handler which causes a user to see
a "Page unavailable" page and trigger a sentry error.
This error case is expected and we can provide a better route to handling
it. This change catches the error as part of the form wizard and displays
the form wizard error page. This will also prevent us from seeing this
error in sentry which should be reserved for unexpected errors.
<kbd><img src="https://user-images.githubusercontent.com/3327997/81070743-952da500-8edb-11ea-8b79-8d5638274460.png"></kbd>
<kbd><img src="https://user-images.githubusercontent.com/3327997/81070784-a4145780-8edb-11ea-882d-d69661faf517.png"></kbd>
> fix: Handle how CSRF errors are dealt with

- app/move/controllers/create/move-date.js
- app/move/controllers/create/move-date.test.js
This fixes an error where date-fns returns an error if an invalid
date is passed to `format()`.
This caused the move details step to through an error when trying to
format the move date to be of the type expected by the API.
This fixes sentry error #BOOK-A-SECURE-MOVE-FRONTEND-1H
> fix: Ensure move date is valid before processing

- app/moves/index.js
- app/moves/middleware/set-dashboard-move-summary.js
- app/moves/middleware/set-dashboard-move-summary.test.js
- app/moves/middleware/set-move-type-navigation.js
- app/moves/middleware/set-move-type-navigation.test.js
- app/moves/middleware/set-moves-by-date-range-and-status.js
- app/moves/middleware/set-moves-by-date-range-and-status.test.js
- common/middleware/set-primary-navigation.js
- common/middleware/set-primary-navigation.test.js
- common/presenters/move-type-for-filter.js
- common/services/index.js
- common/services/move.js
- common/services/move.test.js
- common/services/single-request.js
- common/services/single-request.test.js
- locales/en/statuses.json
Single requests were previously making use of existing moves services and URLs and passing a list of statuses directly from the URL to the API.
The problem with this is that to correctly filter down the moves to only display single requests we actually need to pass other filters to the API, like `move_type`. It also wasn't using the correct statuses within the existing URLs.
This work abstracts that work to a single requests service so that if statuses/filters change within the API they are contained within one place in this app.
That allows us to display moves based on filters in the UI and keep that abstraction away from URLs/controllers/middleware.
There should be no major difference in the screens for this change apart from the URL changes.
This is also a start to try and split the …
> [P4-1467] Filter single requests correctly

- README.md
- common/middleware/development.js
- common/middleware/development.test.js
- config/index.js
- server.js
This allows the locations to be set using an environment variable
populated with NOMIS Agency IDs.
This is useful during development when working offline or when the auth
service is not working.
> chore: Allow locations to be set by env var during development

- test/e2e/_helpers.js
The autocomplete filters the options based on what is in the input. The presence of any previous input meant that only one matching option was returned from focusing the field - the very same currently selected option!
The fix is to zap the input first.
> fix: Ensure fillinAutocomplete e2e helper can change its value

- app/auth/middleware.js
- app/auth/middleware.test.js
- app/move/controllers/create/base.js
- app/move/controllers/create/base.test.js
- app/move/controllers/create/document.test.js
- app/move/controllers/update/move-details.js
- app/move/controllers/update/move-details.test.js
- app/move/steps/update.js
- common/lib/api-client/middleware/post.js
- common/lib/api-client/middleware/request.js
- common/lib/api-client/middleware/request.test.js
- common/lib/api-client/models.js
- common/lib/api-client/models.test.js
- common/lib/user.js
- common/lib/user.test.js
- common/services/move.js
- common/services/move.test.js
- locales/en/moves.json
- test/e2e/_helpers.js
- test/e2e/_move.js
- test/e2e/move.update.police.test.js
- test/e2e/pages/move-detail.js
- test/fixtures/api-client/README.md
- test/fixtures/api-client/event.create.json
- test/fixtures/api-client/move.find.json
- test/fixtures/api-client/move.findAll.json
Adds ability to change where a move is going to or, if a prison recall, amend the move’s additional information.
Adds link to edit move details from move view page.
Prison recall move
Other move types
> [P4 1440] Provide ability to update to location frontend

- common/services/single-request.js
- common/services/single-request.test.js
When refactoring into a separate service, the default sort was lost.
This change ensures we are still sorting single requests by the
created at date.
> fix(single requests): Fix default sort direction of single requests

- .circleci/config.yml
- .circleci/get-review-app-url.sh
This set of changes updates the continuous deployment workflow we use. It adds:
- further slack notifications to notify team channels of deployments and users who need to approve those deployments
- end-to-end testing on Pull Requests
This comes with some updates to the existing continuous deployment workflows, see the screenshots for exact differences.
In summary:
- pull requests run end-to-end tests against Heroku review apps
- master deploys to staging and runs end-to-end tests against staging
- pre-production is now **only** deployed as part of the release workflow and end-to-end tests are run against pre-production for releases
Closes #434
*Click images to enlarge them*
| <kbd><img src="https://user-images.githubusercontent.com/3327997/81559099-bf …
> Update CI workflows

- app/move/controllers/update/court.js
- app/move/controllers/update/court.test.js
- app/move/controllers/update/index.js
- app/move/steps/update.js
- app/move/views/_includes/assessment.njk
> fix: Prevent update court link when move not to court

- app/move/fields/move-agreed-by.js
- app/move/fields/move-agreed.js
- common/presenters/move-to-meta-list-component.js
- common/presenters/move-to-meta-list-component.test.js
- common/services/move.js
- common/services/move.test.js
- locales/en/fields.json
- locales/en/moves.json
This adds a new item to the summary panel to show the status of
the prison transfer with the receiving prison.
It will show the person's name if it has been entered when creating
the transfer request.
| <kbd><img src="https://user-images.githubusercontent.com/3327997/81589324-425b5e00-93b1-11ea-848f-b2b4441b7251.png"></kbd> | <kbd><img src="https://user-images.githubusercontent.com/3327997/81589193-222b9f00-93b1-11ea-90b5-5637ae20b02d.png"></kbd> |
| <kbd><img src="https://user-images.githubusercontent.com/3327997/81589324-425b5e00-93b1-11ea-848f-b2b4441b7251.png"></kbd> | <kbd><img src="https://user-images.githubusercontent.com/3327997/81589448-5901b500-93b1-11ea-8e1f-e9dedc577e07.png"></kbd> |
> fix(single requests): Show agreement status with receiving prison

- app/move/controllers/index.js
- app/move/controllers/review.js
- app/move/controllers/review.test.js
- app/move/controllers/view.js
- app/move/controllers/view.test.js
- app/move/fields/index.js
- app/move/fields/review/index.js
- app/move/fields/review/move-date.js
- app/move/fields/review/rejection-reason-comment.js
- app/move/fields/review/review-decision.js
- app/move/index.js
- app/move/steps/index.js
- app/move/steps/review.js
- app/move/views/review.njk
- app/move/views/view.njk
- common/components/message/_message.scss
- common/lib/permissions.js
- common/lib/user.test.js
- common/presenters/move-to-meta-list-component.js
- common/services/single-request.js
- common/services/single-request.test.js
- common/templates/form-wizard.njk
- config/nunjucks/filters.js
- config/nunjucks/filters.test.js
- locales/en/actions.json
- locales/en/errors.json
- locales/en/fields.json
- locales/en/messages.json
- locales/en/moves.json
- locales/en/statuses.json
This introduces the ability for a user to approve or reject a single request (a `proposed` move). It uses the form wizard to create a simple one step journey and creates extra service methods to interact with the API.
**NOTE**: This requires two changes to the API to be fully supported. One to extend the cancellation reasons to include `rejected` and another to remove date validation when sending a `PATCH` with `proposed` moves.
<kbd><img src="https://user-images.githubusercontent.com/3327997/81576794-9873d580-93a0-11ea-8c85-a524c911e9c8.png"></kbd>
<kbd><img src="https://user-images.githubusercontent.com/3327997/81576822-a590c480-93a0-11ea-86b7-c8ac00ad040f.png"></kbd>
<kbd><img src="https://user-images.githubusercontent.com/3327997/81571300-a70abe80-9399-11ea-9449-1a969dae4363.png"></kbd …
> [P4-1364] [P4-1362] Review a single request (approve/reject)

- app/move/fields/index.js
In a change made to update the names of the field objects a reference
to the create fields was broken in the update fields object.
This fixes that reference and ensures edit works correctly.
> fix(edit): Correct the reference to update fields

- common/presenters/move-to-meta-list-component.js
- common/presenters/move-to-meta-list-component.test.js
The logic for displaying this label and value in the summary panel
was checking if it was not undefined. However, the API currently returns
a value of `false` and does not support `null`.
This meant that for all existing court moves this label was being displayed
as "Not agreed". This information is not relevant for these types of moves
so the logic has been updated to only display for prison transfers.
> fix: Only display move agreed status for single requests

- app/move/controllers/create/base.js
- app/move/controllers/create/base.test.js
- locales/en/actions.json
This updates the text used for the final step for single requests. Previously the text suggested the move was going to be requested with a supplier. This updates the text to be clearer about what is happening after submission.
| <kbd><img src="https://user-images.githubusercontent.com/3327997/81693909-8fded600-9458-11ea-83ab-c5f32ea248a0.png"></kbd> | <kbd><img src="https://user-images.githubusercontent.com/3327997/81694015-b3098580-9458-11ea-98ec-ffee0f5e1fba.png"></kbd> |
> Update button text for single requests

- app/moves/index.js
- app/moves/middleware/index.js
- app/moves/middleware/set-body.single-requests.js
- app/moves/middleware/set-body.single-requests.test.js
- app/moves/middleware/set-filter.single-requests.js
- app/moves/middleware/set-filter.single-requests.test.js
- app/moves/middleware/set-results.single-requests.js
- app/moves/middleware/set-results.single-requests.test.js
- common/middleware/set-primary-navigation.js
- common/middleware/set-primary-navigation.test.js
- common/services/single-request.js
- common/services/single-request.test.js
This refactor moves the shared body of filtering a set of results
and displaying the filter to a common middleware that precedes both
middleware responsible for setting the filter and the results.
This means that we reduce the places we need to have this code and
can move in a direction to share the setting of filters and results
going forward.
This change also amends how single requests are "filtered". Previously
this was done as part of the URL path which meant a bit more heavy
lifting around middleware. This moves to a query based approach
which means we can share the code across other parts of the application
to handle filtering and sorting.
**Note:** This work is the start to move the dashboard summary panels to the 
root of the application and to support single requests by a single …
> refactor: Use common body for filters and results

- test/e2e/_move.js
- test/e2e/move.update.police.test.js
- test/e2e/pages/create-move.js
Adds e2e tests for checking that move date can be updated.
Extends create-move's `fillInDate` method to allow an optional date type or value to be passed to it.
> chore: Add e2e tests for updating move date

- .circleci/config.yml
This change uses separate environment variables for testing against
different environments.
Previously we were overriding variables which led to some unexpected
issues in some cases when a variable wasn't being correctly overriden.
It would fall back to the default and fail in different ways, or worse
cause false positives.
> build: Use separate env vars for end-to-end tests

- app/move/controllers/update/document.js
- app/move/controllers/update/document.test.js
- app/move/controllers/update/index.js
- app/move/steps/update.js
- app/move/views/view.njk
- common/lib/permissions.js
- common/lib/user.test.js
- locales/en/moves.json
- test/e2e/_helpers.js
- test/e2e/_move.js
- test/e2e/_routes.js
- test/e2e/move.update.forbidden.test.js
- test/e2e/move.update.police.test.js
- test/e2e/move.update.stc.test.js
- test/e2e/pages/move-detail.js
Users with `move:update` permission can now update documents for moves when the current location allows documents.
Adds link to move view
Adds update document view
(Looks and functions identically to create's document view)
> [P4 1196] Provide ability for STC user to update move documents

- app/allocations/middleware.js
- app/allocations/middleware.test.js
- app/moves/controllers/download.js
- app/moves/controllers/download.test.js
- app/moves/index.js
- app/moves/middleware/set-body.single-requests.js
- app/moves/middleware/set-body.single-requests.test.js
- app/moves/middleware/set-pagination.js
- app/moves/middleware/set-pagination.test.js
- app/moves/middleware/set-results.outgoing.js
- app/moves/middleware/set-results.outgoing.test.js
- common/helpers/date-utils.js
- common/helpers/date-utils.test.js
- common/middleware/set-date-range.js
- common/middleware/set-date-range.test.js
- config/index.js
- package-lock.json
- package.json
This is part of a wider piece of work to stop using `res.locals`
through middleware. This technique makes it harder to see where something
in a view is coming from.
This also refactors some of the date utils to make use of app wide
configuration and improve how dates are handled.
Helps to address #451
> refactor: Stop using res.locals for date range

- app/moves/constants.js
- app/moves/index.js
- app/moves/middleware/index.js
- app/moves/middleware/redirect-default-query.js
- app/moves/middleware/redirect-default-query.test.js
- app/moves/middleware/redirect-view.js
- app/moves/middleware/redirect-view.test.js
- common/middleware/set-primary-navigation.js
- common/middleware/set-primary-navigation.test.js
This changes the way default URLs are handled within the moves app. Now each "view" has a default time period which is handled at the base router level.
This simplifies the main navigation and any other areas where we will need to link to the default
view for a particular list of moves.
> refactor: Handle redirecting of different move types

- app/moves/middleware/redirect-base-url.js
- app/moves/middleware/redirect-base-url.test.js
- test/e2e/pages/dashboard.js
- test/e2e/smoke.test.js
This fixes the issue with failing tests around users who have a
dashboard.
Previously the dashboard was nested within moves and expected some
redirects to take place. This udpates the tests to match the new
behaviour.
> fix(e2e): Update the tests for dashboards

- app/allocation/controllers/view.js
- app/allocation/controllers/view.test.js
- app/allocation/fields/sentence-length.js
- app/allocation/index.js
- app/allocation/views/view.njk
- common/lib/api-client/models.js
- common/presenters/allocation-to-meta-list-component.js
- common/presenters/allocation-to-meta-list-component.test.js
- common/presenters/allocation-to-summary-list-component.js
- common/presenters/allocation-to-summary-list-component.test.js
- common/presenters/allocations-to-table.js
- common/presenters/allocations-to-table.test.js
- common/presenters/index.js
- locales/en/actions.json
- locales/en/allocations.json
- locales/en/default.json
- locales/en/fields.json
- test/fixtures/api-client/allocation.findAll.json
The links cancel and remove from allocations are dummies; so is the allocation history tab.
It has been tried only with fake data, which may explain why there is no picture and no meta data returned from the backend.
With empty slots:
With filled slots:
> [P4 1287] Single allocation view

- app/allocations/middleware.js
- app/locations/middleware.js
- app/locations/middleware.test.js
- app/locations/views/locations.njk
- app/move/index.js
- app/moves/constants.js
- app/moves/controllers/list-as-cards.js
- app/moves/controllers/list-as-cards.test.js
- app/moves/controllers/list-as-table.js
- app/moves/index.js
- app/moves/middleware/set-pagination.js
- app/moves/middleware/set-pagination.test.js
- common/helpers/date-utils.js
- common/helpers/date-utils.test.js
- common/helpers/index.js
- common/helpers/url.js
- common/helpers/url.test.js
- common/lib/permissions.js
- common/lib/user.test.js
- common/middleware/permissions.js
- common/middleware/permissions.test.js
- common/templates/layouts/base.njk
- package-lock.json
- package.json
- test/e2e/_move.js
- test/e2e/pages/page.js
This set of changes refactors and updates the permissions and routing for moves.
It allows OCA users to see single requests and makes the middleware more re-usable by other
parts of the application but using a configuration approach.
It also adds the correct permissions for Population Management Unit (PMU) users to see all
single requests for this MVP release.
> Allow PMU users to view all single requests

- common/services/move.js
- common/services/move.test.js
Currently, for every move listed, we format the person associated to it. However, we are moving towards supporting moves without people associated, for the allocations.
This causes in some cases the app to fail, as it's looking to extract properties from a null object.
> fix(allocations): Avoid formatting a person if  move has none associated

- app/allocation/controllers/cancel.js
- app/allocation/controllers/cancel.test.js
- app/allocation/controllers/index.js
- app/allocation/controllers/view.js
- app/allocation/controllers/view.test.js
- app/allocation/index.js
- app/allocation/steps/cancel.js
- app/allocation/steps/index.js
- app/allocation/views/view.njk
- app/allocations/middleware.js
- app/allocations/middleware.test.js
- common/lib/api-client/models.js
- common/lib/permissions.js
- common/lib/user.test.js
- common/presenters/allocations-to-table.js
- common/presenters/allocations-to-table.test.js
- common/services/allocation.js
- common/services/allocation.test.js
- locales/en/allocations.json
- locales/en/fields.json
- test/fixtures/api-client/allocation.findAll.json
- test/fixtures/api-client/event.create.json
- test/fixtures/api-client/move.find.json
- test/fixtures/api-client/move.findAll.json
This PR contains the redirection of the PMU users to a (temporary?) dashboard, and add the cancellation journey to the allocation view, without specifying a reason yet.
Upon logging in, the PMU user is presented with this dashboard:
Clicking on "Allocations" (the single request links does not go anywhere for now):
The single view has now the cancel link:
Intermediate page that will contain the reason, when it's supported by the BE:
Confirmation:
> [P4 1276] cancel allocation without specifying a reason

- app/allocation/views/confirmation.njk
- locales/en/allocations.json
As mentioned by @Andy-Millar :
- removed the link to the dashboard by region, since we don't have it yet
- fixed the link to the dashboard (might possibly need to be revisited after https://github.com/ministryofjustice/hmpps-book-secure-move-frontend/pull/523 is merged)
- added the link to the single allocation
- as for the locations, there is no link because we don't have that view yet
> fix(allocations): Display correct links in the confirmation page

- test/e2e/_roles.js
- test/e2e/pages/create-move.js
- test/e2e/pages/page.js
The current suite of end-to-end tests can sometimes fail unexpectedly.
This change attempts to wrap the logic around signing in and choosing
a location with more assertions to see where things are consistently
going wrong.
Code suggestion from @solidgoldpig
> test(e2e): Add additional assertions to aid end-to-end tests

- common/presenters/single-requests-to-table-component.js
- common/presenters/single-requests-to-table-component.test.js
- locales/en/moves.json
Currently some users so a table with all locations. In the table view, it's hard to see where the different moves are coming from.
This change adds a column to display the location of the sending location.
> chore(single requests): Add from location to table

- app/allocation/steps/cancel.js
- app/allocation/views/cancel/cancel-reason.njk
- locales/en/actions.json
This change adds the red colour to the button and the "back to allocation" link to the cancel reasons page.
> fix(allocations): Allow the user to call off the cancellation

- app/allocation/index.js
- app/allocation/views/view.njk
- common/lib/permissions.js
- common/lib/user.test.js
This updates the permissions to allow Operational Capacity Allocation (OCA) users to see allocations and to restrict cancelling an allocation to only Population Management Unit (PMU) users.
> chore(permissions): Update permission for OCA and PMU users

- common/services/single-request.js
- common/services/single-request.test.js
Single requests are being filtered on a `move_type` of `prison_transfer`
which was enough to distinguish them previously. However, we have added
support for allocation moves which are also classed as a `prison_transfer`.
This means we needed a further way to remove results related to an
allocation move from single requests.
This change adds the new filter within the API to exclude allocation
moves.
> fix(single requests): Remove allocations from single requests results

- app/allocation/controllers/view.js
- app/allocation/controllers/view.test.js
- app/move/controllers/view.js
- app/move/controllers/view.test.js
- app/move/views/view.njk
- common/assets/scss/overrides/_all.scss
- common/assets/scss/overrides/_moj-frontend.scss
- common/components/card/_card.scss
- common/presenters/assessment-answers-by-category.js
- common/presenters/assessment-answers-by-category.test.js
- common/presenters/assessment-to-summary-list-component.js
- common/presenters/assessment-to-summary-list-component.test.js
- common/presenters/move-to-card-component.js
- common/presenters/move-to-card-component.test.js
- common/presenters/moves-to-csv.js
- common/presenters/person-to-card-component.js
- common/presenters/person-to-card-component.test.js
- common/presenters/person-to-summary-list-component.js
- common/presenters/person-to-summary-list-component.test.js
- common/services/allocation.js
- common/services/allocation.test.js
- common/services/person.js
- common/services/person.test.js
- locales/en/default.json
This set of changes address handling moves that do not yet have a person attached to them.
These types of moves are ones that have been created as a placeholder as part of an "allocation" (or a collection of moves). The journey is for another user to come back and add a person to each of these moves.
Previously the application had an expectation that all moves always had a person associated with them so a lot of display and logic relied on that concept. This concept now needs to be adapted with these extra journeys and that's what this PR attempts to address.
It fixes the logic within the person transform method as well as other parts of the application that display a person.
| <kbd><img src="https://user-images.githubusercontent.com/3327997/82664924-a …
> Handle moves without a person

- app/allocations/middleware/set-results.allocations.js
- app/allocations/middleware/set-results.allocations.test.js
- common/assets/scss/utilities/_all.scss
- common/assets/scss/utilities/_typography.scss
- common/presenters/allocations-to-table.js
- common/presenters/allocations-to-table.test.js
- common/presenters/table/object-to-table-head.js
- common/presenters/table/object-to-table-head.test.js
- common/services/allocation.js
- common/services/allocation.test.js
- common/templates/collection-as-table.njk
This change aims to display the cancelled allocations in the dashboard. Currently not supported by the api service -- the implementation should be merged soon.
> [P4 1310] Display cancelled allocations

- app/allocation/views/view.njk
Currently the heading of the allocation view is not unescaped, which means that strange characters appears on the screen:
Adding `safe` to the template allows the characters to be correctly displayed.
> fix(allocations): Unescape the heading of allocation view

- app/move/controllers/cancel.js
- app/move/controllers/cancel.test.js
- app/move/views/view.njk
- locales/en/actions.json
- locales/en/default.json
- locales/en/messages.json
- locales/en/moves.json
This change improves the way a move that doesn't have a person is handled. Because the detail page relies heavily on the person details this page looked a little patchy, this change removes the details that we don't have and replaces them with a message.
It also includes the banner that shows there are actions awaiting on this item, with an action if the user has that permission level.
| <kbd><img src="https://user-images.githubusercontent.com/3327997/82954175-1c82ab80-9fa4-11ea-9649-40afc5900145.png"></kbd> | <kbd><img src="https://user-images.githubusercontent.com/3327997/82954079-e47b6880-9fa3-11ea-8cb2-46da9318bebb.png"></kbd> |
> Update move detail page with moves that don't have a person

- common/components/card/_card.scss
- common/components/card/template.njk
A previous update to the card component fixed the float issue with
images. This meant introducing a fixed width margin on the left.
However, this caused a problem when a card didn't include an image
as the margin was still being applied.
This fix uses a modifier class on the card for when an image is present
to handle applying the extra style required for the image.
| <kbd><img src="https://user-images.githubusercontent.com/3327997/83125554-9a8fa100-a0cf-11ea-837a-1271213eedc9.png"></kbd> | <kbd><img src="https://user-images.githubusercontent.com/3327997/83125497-83e94a00-a0cf-11ea-94ab-1fe5d2f9eee7.png"></kbd> |
> fix: Ensure card without image doesn't have left margin

- app/allocations/middleware/set-filter.allocations.js
- app/allocations/middleware/set-filter.allocations.test.js
- common/services/allocation.js
- common/services/allocation.test.js
This update ensures that the correct filter to show non-cancelled
moves is sent to the API.
It also ensures that the correct method is called in the filter so that
the numbers reflect the correct results.
**Depends on** [#494](https://github.com/ministryofjustice/hmpps-book-secure-move-api/pull/494) in API project
> fix(allocations): Ensure cancelled moves are returned correctly

- app/allocation/controllers/index.js
- app/allocation/controllers/view.js
- app/allocation/controllers/view.test.js
- app/allocation/views/view.njk
- app/move/controllers/index.js
- app/move/controllers/unassign.js
- app/move/controllers/unassign.test.js
- app/move/index.js
- app/move/steps/index.js
- app/move/steps/unassign.js
- app/move/views/unassign.njk
- common/presenters/move-to-card-component.js
- common/presenters/move-to-card-component.test.js
- common/services/move.js
- common/services/move.test.js
- locales/en/actions.json
- locales/en/allocation.json
- locales/en/allocations.json
Adds unassign route to move
Adds unassign link to allocation view and suppresses status badge
|![View_allocation](https://user-images.githubusercontent.com/4856/83120580-23efa500-a0c9-11ea-9a18-8bbc0190fb95.png)|![View_allocation](https://user-images.githubusercontent.com/4856/83120478-07536d00-a0c9-11ea-80c5-4add92bd142b.png)|
> P4 1349 remove person from allocation

- app/move/controllers/assign/confirmation.js
- app/move/controllers/assign/confirmation.test.js
- app/move/controllers/assign/index.js
- app/move/steps/assign.js
- app/move/views/assign/confirmation.njk
- locales/en/allocation.json
Adds a warning to confirmation page that user should add the move to NOMIS
Also reinstates the link to assign another person if allocation still has unfilled moves
> P4 1336 confirm person added to allocation

- app/move/controllers/assign/base.js
- app/move/controllers/assign/base.test.js
- app/move/fields/index.js
- app/move/fields/move-agreed-assign.js
- app/move/fields/move-not-agreed-instruction.js
- app/move/steps/assign.js
- common/components/raw/macro.njk
- common/components/raw/raw.yaml
- common/components/raw/template.njk
- common/components/raw/template.test.js
- common/templates/layouts/base.njk
- test/unit/component-helpers.js
Updates `agreement` step of move `assign` journey to use an extended version of the `move_agreed` field. Adds `move_not_agreed_instruction` as conditional field when `move_agreed` answer is`false`.
Adds text with instructions of how to proceed if the move of a person to be assigned to an allocation has not yet been agreed.
- [P4-1445](https://dsdmoj.atlassian.net/browse/P4-1445)
|![Has_this_move_been_agreed_with_receiving_prison__-_person_assign](https://user-images.githubusercontent.com/4856/83184458-6775fd80-a121-11ea-8a39-7e6bfc5882d3.png)|![Has_this_move_been_agreed_with_receiving_prison__-_person_assign](https://user-images.githubusercontent.com/4856/83184230-10702880-a121-11ea-849c-80f0fb31d233.png) |
> [P4 1445] Display additional info when no allocation move agreement

- test/e2e/_move.js
- test/e2e/move.update.forbidden.test.js
- test/e2e/move.update.police.test.js
- test/e2e/move.update.stc.test.js
- test/e2e/pages/update-move.js
This tries to reduce the need to create a new move for each editability
test in order to speed them up.
It also moves away from moves being created based on a user and their role
as this is a concept we have tried to stay away from. We can keep some
checks linked to roles based around permissions but when creating those
fixtures they shouldn't be tied to a person's role.
> test: Increase the speed of the editability tests

- config/index.js
- locales/en/fields.json
- package.json
- test/e2e/_roles.js
- test/e2e/_routes.js
- test/e2e/allocation.cancel.test.js
- test/e2e/allocation.new.test.js
- test/e2e/pages/allocation-cancel.js
- test/e2e/pages/allocation-criteria.js
- test/e2e/pages/allocation-details.js
- test/e2e/pages/allocation-journey.js
- test/e2e/pages/allocation-view.js
- test/e2e/pages/index.js
- test/e2e/pages/page.js
These are the tests for cancel and create allocation. They pass locally (most of the time), but need a test user to be added to this PR for it to run.
> [P4 1276] e2e tests for cancel and create allocation

- app/allocations/constants.js
- app/allocations/middleware/set-body.allocations.js
- app/allocations/middleware/set-body.allocations.test.js
- app/allocations/middleware/set-results.allocations.js
- app/allocations/middleware/set-results.allocations.test.js
- common/assets/scss/components/_all.scss
- common/assets/scss/components/_sortable-table.scss
- common/presenters/allocations-to-table-component.js
- common/presenters/allocations-to-table-component.test.js
- common/presenters/table/object-to-table-head.js
- common/presenters/table/object-to-table-head.test.js
- common/services/allocation.js
- locales/en/default.json
This PR adds the ability to sort (server-side) to the allocation table (only the active allocations one. The cancelled one currently inherits the same filters but has no sorting capabilities of its own).
Headers of the columns were changed to accomodate links that refresh the page with the various sorting options. If a column is sortable, the first click triggers a sort ascending. Further clicks will toggle the order. Clicking on another column triggers a sort ascending on that one, and so on.
We want the users to be able to find allocations quickly.
- [P4-1447]()
Detail of active current sort:
Commit messages with a `fix` or `feat` type are automatically used to generate the [changelog](ministryofjustice/hmpps-book-secure-move-frontend/blob/maste …
> [P4-1447] feat(allocations): Added sorting to allocation tables

- package-lock.json
In a previous PR, I had bumped up the version of testcafe, but omitted to reflect the change by committing package-lock.json. This PR aims to remedy that.
Just package-lock.json.
To avoid discrepancies between package and lockfiles.
> chore: Updated package-lock.json

- common/lib/api-client/middleware/request.js
- common/lib/api-client/middleware/request.test.js
- common/services/allocation.js
- common/services/allocation.test.js
- common/services/move.js
- common/services/move.test.js
- common/services/person.js
- common/services/person.test.js
- common/services/reference-data.js
- common/services/reference-data.test.js
Updates api-client calls to explicitly use `include` parameter to have the backend return requested relationship types in returned `included` object.
1. We were not following the JSON-API specs
2. This will allow us to fine-tune requests to only ask for the requests we actually need.
- [P4-1510 - Support query include in moves endpoint](https://dsdmoj.atlassian.net/browse/P4-1510)
- [P4-1507 - Support query include in allocations endpoint](https://dsdmoj.atlassian.net/browse/P4-1507)
- [P4-1513 - Support query include in people endpoint](https://dsdmoj.atlassian.net/browse/P4-1513)
- [P4-1611 - Support query include in locations endpoints](https://dsdmoj.atlassian.net/browse/P4-1611)
> P4 1510 support query include in moves endpoint

- test/e2e/allocation.new.test.js
Update to e2e test assertion.
It also includes a small tweak to the variable names to make them a little
more readable.
This method was assigning the result of a promise to a variable and not
using `await` to wait for the result. This fix ensures that the promise
will be waited for by passing it into TestCafe's `assert` method directly. …
> fix: Ensure end-to-end test assertions are called with a promise

- test/e2e/_helpers.js
Ethnicities and genders have disabled values removed.
Test fixtures could occasionally generate data with a value that was disabled which led to the test failing.
This brings the fixtures in line with what the frontend expects.
n/a
> Prevent e2e fixtures using disabled reference data

- app/allocation/fields/moves-count.js
- locales/en/allocations.json
- locales/en/fields.json
Changed the label of the sentence length field to match the prototype: from "Sentence length" to "Time left to serve".
Also fixed a minor issue with another label, and the validation of prisoners number.
Adherence to the prototype
- [P4-1461]()
> [P4 1461] Change "Sentence length" to "Time left to serve"

- test/e2e/allocation.new.test.js
This fixes the use of an `await` within a `forEach` loop. 
The forEach
loop doesn't wait for a promise called within `await` to be resolved or
rejected before it continues its loop.
This caused some issues with this test intermittently failing which
using a for...of loop should resolve.
> test: Remove use of await in foreach loop

- app/move/controllers/assign/base.js
- app/move/controllers/assign/base.test.js
- common/presenters/move-to-meta-list-component.js
- common/presenters/move-to-meta-list-component.test.js
- common/services/move.js
- common/services/move.test.js
This fix removes the checks from when to display the `move_agreed`
and `move_agreed_by` fields for a move.
This means that when assigning a person to an allocation you will now see the response
to the "Has this move been agreed with the receiving prison?" question in the summary
panel on the right hand side.
Previously the API didn't support `null` values for these fields
which meant that on creation of new moves, it defaulted the value
to false. However, `false` actually means that the person has
answered that the move was not agreed with the receiving prison.
This broke in the case of moves within an allocation because this
question had never been asked as part of creating the move at any
point.
This supports the [change in the …
> [P4-1608] Update move agreed field logic

- common/lib/permissions.js
- common/lib/user.test.js
OCA users lose the permission to create court transfer moves.
Such users can only create prison transfer moves
- [P4-1416]()
| <kbd><img width="667" alt="Screenshot 2020-06-08 at 15 15 39" src="https://user-images.githubusercontent.com/853989/84041301-9307ac00-a99b-11ea-86a6-181516d57d9a.png"></kbd> | <kbd><img width="620" alt="Screenshot 2020-06-08 at 15 16 56" src="https://user-images.githubusercontent.com/853989/84041335-9e5ad780-a99b-11ea-9d6d-cafae34ecdce.png"></kbd> |
> [P4-1416] fix(moves): Remove ability of OCA users to create court transfer moves

- common/services/allocation.js
- common/services/allocation.test.js
Added `moves.person`, `moves.person.ethnicity` and `moves.person.gender` to default allocation `include` parameter
Missed in previous api improvements - filled values fail to show correctly without them.
n/a
> chore: Add missing include values to allocations

- common/lib/api-client/index.js
- common/lib/api-client/index.test.js
- common/lib/api-client/middleware/index.js
- common/lib/api-client/middleware/request-include.js
- common/lib/api-client/middleware/request-include.test.js
- common/lib/api-client/middleware/request.js
- common/lib/api-client/middleware/request.test.js
- common/lib/api-client/models.js
- common/lib/api-client/models.test.js
- common/services/allocation.js
- common/services/allocation.test.js
- common/services/move.js
- common/services/move.test.js
- common/services/person.js
- common/services/person.test.js
- common/services/reference-data.js
- common/services/reference-data.test.js
This moves the default include used to call the API models to the
model options configuration and away from the service.
This should make maintaining the defaults required easier and keep
the concern within the same layer.
> Maintain default include for resources within the model defintion

- common/presenters/court-case-to-card-component.js
- common/presenters/move-to-card-component.js
- common/presenters/move-to-meta-list-component.js
- common/presenters/person-to-card-component.js
- common/presenters/person-to-card-component.test.js
- common/services/person.js
- common/services/person.test.js
Check relationship values explicitly since null values prevent defaults being assigned when destructruring function params.
Prevent person object being set to undefined when null returned (principle of least surprise).
To support https://github.com/ministryofjustice/hmpps-book-secure-move-api/pull/551
- [P4-1661](https://dsdmoj.atlassian.net/browse/P4-1661)
> P4 1661 Handle null relationships

- .circleci/get-review-app-url.sh
- .testcaferc.json
This increase the default timeout for the TestCafe suite.
In some instances, like waiting for the next page after clicking a
link TestCafe fails an assertion as page loads can take a little while.
This increase that timeout to see if it will help some of the inconsistent
test failures we have seen recently. …
> chore: Increase end-to-end test timeout

- app/allocation/controllers/index.js
- app/allocation/controllers/remove-move.js
- app/allocation/controllers/view.js
- app/allocation/controllers/view.test.js
- app/allocation/index.js
- app/allocation/steps/index.js
- app/allocation/steps/remove-move.js
- app/allocation/views/cancel/cancel-reason.njk
- app/allocation/views/view.njk
- common/assets/scss/utilities/_typography.scss
- common/presenters/move-to-card-component.js
- common/presenters/move-to-card-component.test.js
- common/templates/form-wizard.njk
- locales/en/moves.json
This PR adds the possibility of removing a single personless move from an allocation. This can be done only by PMU and only if there are at least two slots -- e.g. you cannot create a 0 slots allocation with it.
A small journey was added in allocations, that reused the move services.
It's a way of editing the unfilled allocations
- [P4-1662]()
The initial state of the allocation. Note the "Remove from allocation" links.
<kbd><img width="664" alt="Screenshot 2020-06-11 at 17 14 56" src="https://user-images.githubusercontent.com/853989/84414880-f139c680-ac09-11ea-9010-88234ed76cdc.png"></kbd>
After clicking on "Remove from allocation"
<kbd><img width="682" alt="Screenshot 2020-06-11 at 17 24 27" src="https://user-images.githubusercontent.com/853989/84414954-fc8cf200-ac09-11ea-9475-f2a3c9a890 …
> feat(allocations): Remove single move from allocation

- package.json
Adds an npm script that exits if it detects the current branch is master and runs that as the first step of the pre-commit hook.
Accidental commits and pushes to master have been know to happen.
#512
> chore: Prevent accidental commits to master #512

- common/services/allocation.js
- common/services/allocation.test.js
- common/services/move.js
- common/services/move.test.js
- common/services/reference-data.js
- common/services/reference-data.test.js
Double-check that data contains moves before attempting to use next link
This commit also closes the same out-of-bounds error for allocations and locations
> fix: Prevent infinite calls to moves endpoint

- common/templates/form-wizard.njk
Remove `move` from `move.person.fullname` when assigning sidebar heading value
The addition of move caused the name to not be displayed when creating a new move
n/a
> fix: Ensure selected person shown in sidebar when creating move

- app/move/controllers/cancel.js
- app/move/controllers/cancel.test.js
- app/move/controllers/view.js
- app/move/controllers/view.test.js
- app/move/index.js
- app/move/views/cancel.njk
- app/move/views/view.njk
- common/lib/permissions.js
- common/lib/user.test.js
This PR allows the OCA user to cancel proposed moves. To this purpose it introduces a new permission: `move:cancel:proposed`.
The cancel link is now displayed if the user has the right permissions and the move has a `proposed` status.
We want the OCA users to be able to retract single requests.
- [P4-1419]()
| <kbd><img width="547" alt="Screenshot 2020-06-17 at 12 07 12" src="https://user-images.githubusercontent.com/853989/84891310-9124a380-b093-11ea-95a1-961ef510330e.png"></kbd> |<kbd><img width="566" alt="Screenshot 2020-06-17 at 12 04 52" src="https://user-images.githubusercontent.com/853989/84891343-9eda2900-b093-11ea-8241-2ef0815497e5.png"></kbd> |
||<kbd><img width="555" alt="Screenshot 2020-06-17 at 12 06 12" …
> [P4-1419] - feat(moves): Give OCA users ability to cancel proposed moves

- app/move/controllers/create/save.js
- app/move/controllers/create/save.test.js
- common/lib/api-client/models.js
- common/lib/api-client/models.test.js
- common/presenters/assessment-answers-by-category.test.js
- common/presenters/assessment-to-summary-list-component.test.js
- common/services/profile.js
- common/services/profile.test.js
- test/fixtures/api-client/person.create.json
- test/fixtures/api-client/profile.create.json
Save controller of create move now creates a profile and uses the resulting profile when creating the move.
To support api-improvements
- [P4-1672 - Rework create move flow to use profile](https://dsdmoj.atlassian.net/browse/P4-1672)
> [P4-1672] Rework create move flow to use profile

- app/move/controllers/update/assessment.js
- app/move/controllers/update/assessment.test.js
- common/services/profile.js
- common/services/profile.test.js
DEPENDS on https://github.com/ministryofjustice/hmpps-book-secure-move-frontend/pull/610
- Adds update profile method
- Updates update assessment controller to use profile rather than person
Support api improvements
- [P4-1674 - Rework update move flow to use profile](https://dsdmoj.atlassian.net/browse/P4-1674)
> [P4-1674] Rework update move flow to use profile

- app/move/controllers/assign/save.js
- app/move/controllers/assign/save.test.js
- common/services/move.js
- common/services/move.test.js
Depends on https://github.com/ministryofjustice/hmpps-book-secure-move-frontend/pull/611
- Updates assign controller to use profile rather than person
- Updates unassign controller to use profile rather than person
Support api improvements
- [P4 1673 - Rework assign person to allocation flow to use profile](https://dsdmoj.atlassian.net/browse/P4-1673)
> [P4 1673] Rework assign person to allocation flow to use profile

- test/e2e/_helpers.js
- test/e2e/_move.js
- Use profile rather than person when creating a move for use in e2e tests.
Api improvements
- [P4-1703 - Update e2e fixtures to use profile]()
> [P4 1703] Update e2e fixtures to use profile

- app/allocation/fields/cancellation_reason_comment.js
- app/allocation/fields/other-criteria.js
- app/move/controllers/create/base.test.js
- app/move/controllers/create/document.test.js
- app/move/fields/cancellation-reason-comment.js
- app/move/fields/court-hearing-comments.js
- app/move/fields/court-hearing-court-case.js
- app/move/fields/court-hearing-start-time.js
- app/move/fields/date-custom.js
- app/move/fields/date-to.js
- app/move/fields/move-agreed-by.js
- app/move/fields/move-not-agreed-instruction.js
- app/move/fields/review/cancellation-reason-comment.js
- app/move/fields/review/move-date.js
- app/move/fields/review/rebook.js
- app/move/fields/review/rejection-reason.js
- app/move/fields/to-location-court-appearance.js
- app/move/fields/to-location-prison-transfer.js
- common/controllers/form-wizard.js
- common/controllers/form-wizard.test.js
- common/helpers/field/index.js
- common/templates/form-wizard.njk
- locales/en/fields.json
This addition means that the form wizard will always set the correct
`dependent` property on a field if it is added as a conditional
field within another field's options.
This PR also includes a small change to an existing helper and the addition of
page caption support within a form wizard step.
Previously creating conditional fields was a two step process that
involved adding a field as a conditional option to a parent as well
as adding a dependent property to the child field to ensure validation
is only applied in the correct circumstances.
This change doesn't affect any previous implementations but makes this
process easier moving forward so that when dynamically creating fields,
like will be the case for the Person Escort Record framework, you
don't need to loop over the fields again …
> [P4-1734] Update form wizard to support ingesting YAML framework

- README.md
- package.json
- test/e2e/move.new.stc.test.js
- test/e2e/move.update.stc.test.js
- test/e2e/run-without-document-tests.js
- Add meta tag (`hasDocument=true`) to STC tests that involve uploading documents.
- Add script that runs all tests filtering out those with the `hasDocument` meta tag
This enables us to skip tests which upload documents - currently runinng against a local API triggers errors such as:
> ActionController::BadRequest (Invalid request parameters: invalid byte sequence in UTF-8)
The documents with the tag can be skipped bu running the following script
`node test/e2e/run-without-document-tests.js`
n/a
n/a
n/a
> Add hasDocument meta tag to e2e tests

- common/lib/api-client/models.js
- common/services/person.js
- common/services/person.test.js
- common/services/person/person.unformat.js
- common/services/person/person.unformat.test.js
- Removes person from move model
- Removes formatting and unformatting of assessment_answers in person service
- Removes assesment_answers from person model
Api improvements
- [P4-1678 - Remove assessment answers from person service](https://dsdmoj.atlassian.net/browse/P4-1678)
> [P4-1678] Remove assessment answers from person service

- .eslintrc.js
- common/services/frameworks.js
- common/services/frameworks.test.js
- common/services/index.js
- config/paths.js
- nodemon.json
- package-lock.json
- package.json
- webpack.config.js
This change includes a new service to import and transform the YAML
files from the Book a secure move frameworks repo.
It transforms these files into the appropriate structure so that they
can be used by the form-wizard library within the frontend app.
- [P4-1734](https://dsdmoj.atlassian.net/browse/P4-1734)
> [P4-1734] feat: Add importer for Book a secure move frameworks

- Dockerfile
Updates `Dockerfile` to copy `common/services/frameworks.js` during build phase 
Build was broken without it
n/a
n/a
> build: Copy frameworks service during docker build phase

- common/lib/api-client/middleware/request-include.js
- common/lib/api-client/middleware/request-include.test.js
- common/lib/api-client/models.js
- common/services/person.js
- common/services/person.test.js
- Add `location` to personService's `getActiveCourtCases` and `getTimetableByDate` methods.
Default includes will be removed from all endpoint under v2.
See https://github.com/ministryofjustice/hmpps-book-secure-move-api/pull/633
`court_case` and 'timetable` had been missed and were still relying on the default rather than explicit behaviour.
- [P4-1618 - Remove default includes wherever they are defined
](https://dsdmoj.atlassian.net/browse/P4-1618)
Functionaly identical
> [P4 1618] Add explicit include to nested personService methods

- package-lock.json
- package.json
Upgrade `@ministryofjustice/frontend` to `0.19-alpha`
> chore: Bump moj-frontend to 0.19-alpha

- README.md
- start.js
Datetimes were being sent as UTC since container does not have zone info.
This brings the behaviour in line with the rails app for the API
> fix: Set app timezone to be Europe/London explicitly

- common/controllers/form-wizard.js
- common/controllers/form-wizard.test.js
- common/helpers/field/get-field-error-message.js
- common/helpers/field/get-field-error-message.test.js
- common/helpers/field/set-field-error.js
- common/helpers/field/set-field-error.test.js
- common/services/frameworks.js
- common/services/frameworks.test.js
This adds support to define a custom validation message within the
fields configuration that can be used to render the validation
message.
The form wizard currently uses the translation files to build form validation messages.
However, when importing the frameworks we want to keep the validation message tied to the field
configuration. The manifest defines that the message can be supplied as part of the validation object.
With this change we can pass this directly to the form wizard and then extract that message 
so that it can be used to render the message in the error summary and on the field.
- [P4-1736](https://dsdmoj.atlassian.net/browse/P4-1736)
| Validation message output | Manifest file defintion |
| <kbd><img …
> [P4-1736] Support custom validation messages in form wizard

- app/person-escort-record/controllers.js
- app/person-escort-record/controllers.test.js
- app/person-escort-record/router.js
- app/person-escort-record/router.test.js
- app/person-escort-record/views/form-step.njk
- locales/en/actions.json
This creates a new base controller for a frameworks step.
It introduces a custom success handler that checks for the presence
of the save and return button.
If a user has clicked this button instead of the standard submit
button they will be taken back to the section overview.
**Note:** It's not possible to partially save a step. All fields must pass validation to be able to save and return
to the overview. If a user navigates away they will lose the progress of the current step, but this behaviour is
consistent with other journeys within the service and with many other web forms.
Completing the Person Escort Record can be a lengthy process and users may need to save their progress
and return another time. This features allows them to save the current step and come back when they are …
> [P4-1741] Support save and return in Person Escort Record steps

- package-lock.json
Update the package-lock.json file
The package-lock.json file was pointing to a commit that was on a branch
that has since been removed. This updates the package lock file to
point to a valid commit within the frameworks repo.
> build: Fix reference to frameworks repo in package lockfile

- app/move/controllers/create/save.js
- app/move/controllers/create/save.test.js
- app/move/controllers/update/document.js
- app/move/controllers/update/document.test.js
- app/move/views/view.njk
- common/lib/api-client/models.js
- test/fixtures/api-client/profile.create.json
Store and fetch documents on/from profile rather than move
https://github.com/ministryofjustice/hmpps-book-secure-move-frontend/pull/636/commits/fc45e930eddf510aee34c046d7c6121b550a3a08 can be reverted when we update to v2 of the API
API improvements
n/a
> Migrate documents from move to profile

- server.js
Use `combined` log format in production-like environements
We were using `dev` before - which both has less info than we want plus colour-ctl sequences in the output
n/a
n/a
> build: Use combined log format when in production-like envs

- .npmrc
Add `engine-strict = true` to `.npmrc`
Ensure that users have the right version of node
n/a
n/a
n/a
> build: Ensure node version matches that specified in package.json

- common/services/frameworks.js
- common/services/frameworks.test.js
Set the `multiple` to `true` for checkbox questions from the framework when converting to the expected form wizard format.
The form wizard requires a multiple property to be set on fields that
can contain multiple items in the value, for example a checkbox
field.
This adds the property to the field in the framework transformer so
that the form wizard can support checkboxes as expected.
summary of …
> [P4-1767] fix(frameworks): Add multiple flag to checkbox fields from framework

- app/person-escort-record/controllers/framework-section.js
- app/person-escort-record/controllers/framework-section.test.js
- app/person-escort-record/controllers/frameworks.js
- app/person-escort-record/controllers/frameworks.test.js
- app/person-escort-record/controllers/index.js
- common/services/framework-response.js
- common/services/framework-response.test.js
- common/services/index.js
This extends the frameworks controller to support saving a response via the frameworks response service.
It uses the [form-wizard controller lifecycle](https://github.com/UKHomeOffice/passports-form-wizard#controller-lifecycle) to handle sending the values to the API at the appropriate point.
We need a way to send the data from the form back to the API. 
- [P4-1737](https://dsdmoj.atlassian.net/browse/P4-1737)
[GitHub release notes](https://github.com/ministryofjustice/hmpps-book-secure-move-frontend/releases) during the release task. Please make sure they will read well on …
> [P4-1737] Save responses for Person Escort Record

- common/lib/permissions.js
- common/lib/user.test.js
This adds support for a new role for court users that gives them
access to the dashboard and incoming and outgoing moves views.
It also allows them to downloads moves as a CSV.
The service is adding support for new roles, which this change will enable.
- [P4-1810](https://dsdmoj.atlassian.net/browse/P4-1810) …
> [P4-1810] feat: Add support for Court users to access the service

- README.md
- app/move/controllers/view.js
- app/move/controllers/view.test.js
- app/move/views/_includes/assessment.njk
- app/move/views/view.njk
- app/person-escort-record/controllers/frameworks.js
- app/person-escort-record/controllers/frameworks.test.js
- config/index.js
- locales/en/actions.json
- locales/en/messages.json
This creates a new banner on the move detail page which allows
a new Person Escort Record to be created given certain business rules
or continued if one is in progress.
It uses the consistent action banner and a consistent position for the link to either
start or continue the Person Escort Record (PER).
If a PER has **not been started** yet, it displayed a green button in the banner to go to the journey to start
a new PER.
If a PER is **in progress**, it displays a link to continue the PER in the action banner.
If a PER has been **completed**, it no longer displays the banner and displays a link at the bottom
of the page to view the completed PER.
The Person Escort Record is a new feature where users can fill in more detailed risk and health information. This
change creates a way for a …
> [P4-1759] Add start/progress banner for Person Escort Record to move detail

- app/move/controllers/create/assessment.js
- app/move/controllers/create/assessment.test.js
- app/move/controllers/create/base.js
- app/move/controllers/create/base.test.js
- app/move/controllers/create/save.js
- app/move/controllers/create/save.test.js
- app/move/controllers/update/assessment.js
- app/move/controllers/update/assessment.test.js
- app/move/controllers/update/base.js
- app/move/controllers/update/base.test.js
- common/services/profile.js
- common/services/profile.test.js
- common/services/profile/profile.unformat.js
- common/services/profile/profile.unformat.test.js
Amends create and update controllers to use profile rather than person for getting the previous assessment answers
Required to enable transition from v1 to v2 of the API
- [P4-1910](https://dsdmoj.atlassian.net/browse/P4-1910)
> [P4-1910] Use profile for assessment answers

- .testcaferc-with-video.json
- .testcaferc.json
- README.md
- package.json
- test/e2e/parallel-runner.js
Rather than creating a separate testcafe instance for each and every test,
this splits the tests into the number of buckets matching the max_processes
and spins up that number of Testcafes. NB. if max_processes is set to 1,
then the behaviour is exactly as if calling the original non-parallelised
script.
Additionally this has the side effect of making killing the process kill
all the child processes.
NB. If the process is killed before the browsers have connected to the
Testcafe runner server, those browsers will show as "Disconnected" and
have to be killed manually.
The experience of attempting to cancel a run locally was beyond dreadful
n/a
n/a
> build: Improve e2e parallelism

- app/person-escort-record/controllers/framework-overview.js
- app/person-escort-record/controllers/framework-overview.test.js
- app/person-escort-record/controllers/index.js
- app/person-escort-record/index.js
- app/person-escort-record/views/framework-overview.njk
- common/assets/scss/components/_all.scss
- common/components/task-list/_task-list.scss
- common/components/task-list/macro.njk
- common/components/task-list/task-list.yaml
- common/components/task-list/template.njk
- common/components/task-list/template.test.js
- common/presenters/framework-to-task-list-component.js
- common/presenters/framework-to-task-list-component.test.js
- common/presenters/index.js
- common/templates/layouts/base.njk
- locales/en/person-escort-record.json
This adds a controller and route handler for the top level of the person escort record route:
```
/person-escort-record/:recordId
```
It makes sense to show logical things at different stages of the URL. Currently we show the sections nested within
this URL structure so this adds a handler to show the status of the PER broken down by section. It uses a simplified
version of an existing [task list](https://govuk-prototype-kit.herokuapp.com/docs/templates/task-list) pattern used elsewhere in government.
- [P4-1726](https://dsdmoj.atlassian.net/browse/P4-1726)
<kbd><img src="https://user-images.githubusercontent.com/3327997/87340293-c3fd7280-c53f-11ea-8683-7187ca0366c4.png"></kbd>
Commit messages with a `fix` or `feat` type are automatically used to …
> [P4-1726] Show overview and progress of Person Escort Record

- README.md
- config/index.js
Add `API_TIMEOUT` env var
Enables us to customise the timeout of requests to the API
> build: Add API_TIMEOUT env var

- common/components/message/_message.scss
Update the link colour within the instructional banner so it passed
accessibility contrast standards.
This uses the shade mixin to inject a bit of black to the link colour
when links appear on the instructional banner that has the light blue
background.
The new colour is only marginally different but now passed with WCAG AA
on normal size text with a contrast of 4.55:1, from a previous value
of 3.99:1.
The previous contrast failed WCAG AA standards which is the minimum which should
be achieving where possible.
| <kbd><img src="https://user-images.githubusercontent.com/3327997/87769055-f5629080-c814-11ea-9949-eadff4a18e80.png"></kbd> | <kbd><img src="https://user-images.githubusercontent.com/3327997/87769029-e7ad0b00-c814-11ea-9feb-daa64a323795.png"></k …
> fix: Correct the contrast of links on light blue banner

- common/presenters/framework-to-task-list-component.js
- common/presenters/framework-to-task-list-component.test.js
- common/services/frameworks.js
- common/services/frameworks.test.js
This adds support to use an order property for a section to order
them when they are displayed in summaries or task lists.
The order in which users should complete steps has an order that has been established during
lots of user research so we need a way to be able to control that order from the framework.
- [P4-1726](https://dsdmoj.atlassian.net/browse/P4-1726) …
> [P4-1726] Support ordering of framework sections

- app/move/controllers/view.js
- app/move/controllers/view.test.js
- app/move/views/view.njk
- app/person-escort-record/app/confirm/config.js
- app/person-escort-record/app/confirm/controllers.js
- app/person-escort-record/app/confirm/controllers.test.js
- app/person-escort-record/app/confirm/fields.js
- app/person-escort-record/app/confirm/index.js
- app/person-escort-record/app/confirm/steps.js
- app/person-escort-record/app/confirm/views/provide-confirmation.njk
- app/person-escort-record/index.js
- common/services/person-escort-record.js
- common/services/person-escort-record.test.js
- common/templates/form-wizard.njk
- locales/en/actions.json
- locales/en/fields.json
- locales/en/messages.json
- locales/en/person-escort-record.json
Adds a new sub-app to handle the journey for "confirming" a Person Escort Record. 
Once a PER has been confirmed it should no longer be edited so that it can be printed in that final state.
- [P4-1710](https://dsdmoj.atlassian.net/browse/P4-1710)
<kbd><img src="https://user-images.githubusercontent.com/3327997/87724760-e992b200-c7b3-11ea-94dc-e9565d5576c5.png">
<kbd><img src="https://user-images.githubusercontent.com/3327997/87724832-05965380-c7b4-11ea-8f8e-c08c4472f72c.png">
<kbd><img src="https://user-images.githubusercontent.com/3327997/87725073-7dfd1480-c7b4-11ea-88fa-5f6ba79ac053.png"></kbd>
Commit messages with a `fix` or `feat` type are automatically used to generate the [changelog](ministryofjustice/hmpps-book-secure-move-frontend/blob/mas …
> [P4-1710] Add journey to "confirm" Person Escort Record

- .circleci/config.yml
Attempt at saving cost without increasing build time too much. Discussed with Alex Robinson.
Changed CircleCI config to reduce the build resource type from xlarge to large 
roughly 50 - 75% cost saving I think
N/A
N/A
N/A
> Update to use large rather than xlarge ci instance

- common/lib/api-client/models.js
- common/presenters/person-to-summary-list-component.js
- common/presenters/person-to-summary-list-component.test.js
- common/services/person.js
- common/services/person.v1.test.js
- config/index.js
- test/e2e/_helpers.js
- test/fixtures/api-client/person.create.json
Implemnents P4-1911
- Flatten identifier properties in model
- Update personService transform, format and unformat methods to match
- Update personToSummaryList presenter to use flattened props
Enables move from v1 -> v2 of API
- [P4-1911](https://dsdmoj.atlassian.net/browse/P4-1911)
> chore: Support v1 and v2 person differences

- app/person-escort-record/controllers/frameworks.js
- app/person-escort-record/controllers/frameworks.test.js
- common/helpers/field/index.js
- common/helpers/field/is-allowed-dependent.js
- common/helpers/field/is-allowed-dependent.test.js
- common/helpers/frameworks/index.js
- common/helpers/frameworks/responses-to-save-reducer.js
- common/helpers/frameworks/responses-to-save-reducer.test.js
This change ensures that any dependent responses are not sent to be
saved if the dependent field doesn't match the condition the field
depends on.
This also includes a fix to remove any falsy values from Array like
objects which prevents the API from returning an error when an
array with one empty string is sent when no checkboxes are selected.
Currently the API would return an error when the frontend would send values for responses that
aren't valid because the condition for a dependent question is not met.
This change ensures that we remove any dependent fields before sending to the API.
Commit messages with a `fix` or `feat` type are automatically used to generate the [changelog](ministryofjustice/hmpps-book-secure-move-frontend/blob/master/CHA …
> Ensure dependent framework responses are filtered correctly

- app/allocation/controllers/cancel.js
- app/allocation/controllers/cancel.test.js
- app/allocation/controllers/create/confirmation.js
- app/allocation/controllers/create/confirmation.test.js
- app/allocation/controllers/remove-move.js
- app/allocation/controllers/view.js
- app/allocation/controllers/view.test.js
- app/allocation/middleware.js
- app/move/controllers/assign/base.js
- app/move/controllers/assign/base.test.js
- app/move/controllers/cancel.js
- app/move/controllers/cancel.test.js
- app/move/controllers/confirmation.js
- app/move/controllers/confirmation.test.js
- app/move/controllers/review.js
- app/move/controllers/review.test.js
- app/move/controllers/unassign.js
- app/move/controllers/unassign.test.js
- app/move/controllers/update/assessment.js
- app/move/controllers/update/base.js
- app/move/controllers/update/base.test.js
- app/move/controllers/update/court.js
- app/move/controllers/update/court.test.js
- app/move/controllers/update/document.js
- app/move/controllers/update/move-details.js
- app/move/middleware.js
- app/move/middleware.test.js
- locales/en/allocations.json
Replaces the use of `res.locals[var]` with `req[var]`.
Part of cleaning out long-lived branches that have been kicked around a while...
Closes #451 
This helps to reduce the issue we have of things being set to `res.locals`
within middleware and making it a little harder to find where is it being
set.
This moves towards a pattern of setting things on the request object
within middleware if that value needs to be used later on in the request
chain.
Then if that value is required by a view, it is handled within the
controller that calls that template. …
> Set variables on req instead of res.locals

- .circleci/config.yml
- Dockerfile
- app/healthcheck/controllers.js
- app/healthcheck/controllers.test.js
- config/index.js
- test/e2e/parallel-runner.js
On CircleCI E2E tests run against master branch poll ping endpoint to check same commit has been deployed before running the tests
Update ping endpoint to return build details to enable checking of commit.
Tests against master on staging were kicked off the moment that the staging deployment task had finished.
This meant that:
a) tests early in the run may have been run against the old pods running the previous deployed commit of the app.
b) tests that ran against the wrong pods were in danger of having requests dropped if they had not been fulfilled by the time the pods were terminated which would cause the test to fail.
This should prevent tests being run against the wrong pods and having the pods switched out from under them.
n/a
n/a
> build: Wait for master to be deployed before running e2e tests

- common/lib/permissions.js
- common/lib/user.test.js
- config/index.js
- test/e2e/_roles.js
- test/e2e/move.update.allowed.test.js
Add `move:update` permission to `SCH` users
SCH users need to be able to update moves
- [P4-1927](https://dsdmoj.atlassian.net/browse/P4-1927)
n/a
> [P4 1927] Enable move updates for SCH users

- test/e2e/pages/allocation-criteria.js
The E2E tests selected dependent fields incorrectly in allocation criteria page.
This PR updates the text of the fields in the E2E tests.
> [E2E] Fixed estate type selection

- app/move/controllers/view.js
- app/move/controllers/view.test.js
- app/move/views/view.njk
- common/assets/scss/overrides/_govuk-frontend.scss
- common/components/card/_card.scss
- common/components/card/card.yaml
- common/components/card/template.njk
- common/components/card/template.test.js
- common/components/tag/_tag.scss
- common/lib/api-client/models.js
- common/presenters/framework-flags-to-tag-list.js
- common/presenters/framework-flags-to-tag-list.test.js
- common/presenters/index.js
- common/presenters/move-to-meta-list-component.test.js
- common/presenters/profile-to-card-component.js
- common/presenters/profile-to-card-component.test.js
- config/index.js
- locales/en/person-escort-record.json
- test/fixtures/api-client/person_escort_record.create.json
- test/fixtures/api-client/person_escort_record.find.json
This set of changes amend the behaviour for display tags for a move. Tags will now only be shown when
all sections of the Person Escort Record are completed.
If they have not been completed or a PER has not yet been started it will display a message in place of the
tags showing what needs to be done.
The Person Escort Record is a new feature that allows risk and health information to be collected in more
detail. With this new addition the previous behaviour for rendering flags no longer fits or is appropriate.
This new behaviour avoids the need for any complicated logic to combine the tags and instead will only
display if we know all the information we need.
- [P4-1784](https://dsdmoj.atlassian.net/browse/P4-1784)
This shows the two variations for a complete PER and an incomplete PER …
> [P4-1784] Render flags from the Person Escort Record instead of the move request

- app/move/controllers/view.js
- app/move/controllers/view.test.js
- common/services/move.js
- common/services/move.test.js
- common/services/single-request.js
- common/services/single-request.test.js
- locales/en/statuses.json
- test/e2e/move.new.police.test.js
Adds `booked` and `in_transit` to list of statuses to filter by when viewing active moves
There was no way of seeing such moves
- [P4-1861](https://dsdmoj.atlassian.net/browse/P4-1861)
> [P4-1861] Add booked and in transit moves to list of active moves

- app/person-escort-record/controllers/framework-overview.js
- app/person-escort-record/controllers/framework-overview.test.js
- app/person-escort-record/controllers/framework-section.js
- app/person-escort-record/controllers/framework-section.test.js
- app/person-escort-record/views/framework-overview.njk
- app/person-escort-record/views/framework-section.njk
Add a link to the overview page of a framework section so that a user
can get back to the move after viewing a section.
Currently the user would hit a bit of a dead-end when viewing the overview
of a framework section, this allows them to navigate back to the move
detail page.
- [P4-XXXX]()
| <kbd><img src="https://user-images.githubusercontent.com/3327997/88927132-45127480-d277-11ea-89e6-b63b17b31fb5.png"></kbd> | <kbd><img src="https://user-images.githubusercontent.com/3327997/88929317-45603f00-d27a-11ea-8eea-aa459e51a87e.png"></kbd> |
| <kbd><img src="https://user-images.githubusercontent.com/3327997/88927127-4479de00-d277-11ea-8ac3-0953f0b925a1.png"></kbd> | <kbd><img src="https://user-images.githubusercontent.com/3327997/88927125-4348b100-d277-11e …
> chore: Add link back to move on Person Escort Record overview page

- app/move/controllers/view.js
- app/move/controllers/view.test.js
- app/move/views/view.njk
- app/person-escort-record/app/confirm/index.js
- app/person-escort-record/app/new/index.js
- app/person-escort-record/controllers/framework-section.js
- app/person-escort-record/controllers/framework-section.test.js
- app/person-escort-record/controllers/framework-step.js
- app/person-escort-record/controllers/framework-step.test.js
- app/person-escort-record/controllers/index.js
- app/person-escort-record/index.js
- app/person-escort-record/router.js
- app/person-escort-record/router.test.js
- app/person-escort-record/views/framework-section.njk
- common/lib/permissions.js
- common/lib/user.test.js
This creates the necessary permissions needed to access various
journeys within a Person Escort Record.
It uses the existing permissions model approach to assign permissions
based on roles from the Auth Service.
It wraps some pieces of the UI in logic and uses the protectRoute
middleware to prevent access to particular routes if the user
does not have access to those permissions.
As we have done with other parts of the service, we want to protect certain actions to users
who have permission to do so.
Protecting this feature using permissions also allows us to roll this out incrementally to locations.
- [P4-1966](https://dsdmoj.atlassian.net/browse/P4-1966) …
> [P4-1966] Enable permissions for Person Escort Record

- test/e2e/pages/allocation-criteria.js
- test/e2e/pages/allocation-details.js
- Ensure allocation date is actually in future
- Ensure otherEstate value set when other selected for estate
E2E tests would "randomly" fail
n/a
n/a
> Fix failing allocation e2e test

- package-lock.json
- package.json
```
govuk-frontend 3.7.0 -> 3.8.0
```
n/a
n/a
NB. Checked for visual consistency
> feat: Upgrade govuk-frontend to v3.8.0

- app/move/controllers/view.js
- app/move/controllers/view.test.js
- app/move/views/_includes/assessment.njk
- app/move/views/_includes/court-information.njk
- app/move/views/_includes/person-escort-record-summary.njk
- app/move/views/view.njk
- common/assets/scss/overrides/_govuk-frontend.scss
- common/components/framework-response/template.njk
- common/components/framework-response/template.test.js
- common/components/meta-list/_meta-list.scss
- common/presenters/assessment-category-to-panel-component.js
- common/presenters/assessment-category-to-panel-component.test.js
- common/presenters/assessment-category-to-summary-list-component.js
- common/presenters/assessment-category-to-summary-list-component.test.js
- common/presenters/framework-field-summary-list-row.js
- common/presenters/framework-field-summary-list-row.test.js
- common/presenters/framework-flags-to-tag-list.js
- common/presenters/framework-flags-to-tag-list.test.js
- common/presenters/framework-responses-to-meta-list-component.js
- common/presenters/framework-section-to-panel-list.js
- common/presenters/index.js
- config/index.js
- locales/en/person-escort-record.json
This set of changes restructures the move detail page to show the warnings from the Person Escort Record
once it has been completed. Up until that point it will render a message that the warnings cannot be displayed
until all sections have been completed, similar to the summary section.
Once sections have been completed it will render a summary of the tags from the Person Escort Record
answers as well as showing the previous warnings that were collected during the original request.
The Person Escort Record is a more detailed version of the risk and health information and will soon be
enabled for all moves.
Once this exists we need to restructure the way this information is being displayed on the move detail.
Essentially this information will overrule the information provided during …
> [P4-1760] Render Person Escort Record framework flags on the move detail page

- app/move/controllers/view.js
Allow a PER to be started or edited in `booked` state.
Person Escort Records should still be editable or be able to be started
when a move is in the booked state.
Previously we were checking for the move being in the requested state.
> fix(per): Allow Person Escort Records starts/updates in booked state

- app/person-escort-record/controllers/framework-section.js
- app/person-escort-record/controllers/framework-section.test.js
- app/person-escort-record/controllers/framework-step.js
- app/person-escort-record/controllers/framework-step.test.js
- app/person-escort-record/index.js
- app/person-escort-record/views/framework-section.njk
This prevents a user from accessing the edit steps once a Person Escort Record has been confirmed.
If I user has the URL stored and tries to access it, they will be redirected back to the section overview.
The API already won't allow this so this just handles that journey
better on the frontend so that the user won't end up seeing API
error messages.
It also hides the actions from the overview if is has been completed.
- [P4-1800](https://dsdmoj.atlassian.net/browse/P4-1800)
| <kbd><img src="https://user-images.githubusercontent.com/3327997/89098842-5086ac80-d3eb-11ea-9b9e-aaa513377159.png"></kbd> | <kbd><img src="https://user-images.githubusercontent.com/3327997/89098831-3a78ec00-d3eb-11ea-83a1-5ecea2a2dfc9.png"></kbd> |
Has been tested in the …
> [P4-1800] Prevent access to framework steps once a Person Escort Record has been confirmed

- app/move/views/view.njk
This amends the condition for checking which flags to display to use the new controller variable to ensure
consistent display.
The logic for switching the display of the move detail page was
only being done on whether a Person Escort Record existed.
This was because this logic was introduced separately to the fix
to ensure user's without the correct permission don't see this feature.
- [P4-1795](https://dsdmoj.atlassian.net/browse/P4-1795)
[GitHub release notes](https://github.com/ministryofjustice/hmpps-book-secure-move-frontend/releases) during the release task. Please …
> [P4-1795] fix(per): Ensure move detail logic uses permissions too

- app/person-escort-record/controllers/framework-step.js
- app/person-escort-record/controllers/framework-step.test.js
Fixes the call to `super.middlewareLocals` in the framework step controller.
A git merge caused the wrong parent method to be called when setting
extra locals in this controller. That meant that the CSRF token wasn't
being set for the form and caused an error when trying to submit an
answer. …
> fix(framework): Call correct parent method when setting locals

- common/lib/api-client/models.js
Add `original_move` to `moves` model
Prevent devour client complaining about missing field
n/a
> chore: Add original_move relationship to move model

- app/moves/controllers/download.js
- app/moves/controllers/download.test.js
- app/moves/index.js
- app/moves/middleware/index.js
- app/moves/middleware/set-download-results.moves.js
- app/moves/middleware/set-download-results.moves.test.js
- app/moves/middleware/set-download-results.single-requests.js
- app/moves/middleware/set-download-results.single-requests.test.js
- app/moves/middleware/set-results.moves.js
- app/moves/middleware/set-results.moves.test.js
- app/moves/middleware/set-results.single-requests.js
- common/services/allocation.js
- common/services/allocation.test.js
- common/services/move.js
- common/services/move.test.js
- common/services/single-request.js
- common/services/single-request.test.js
This change tailors the current includes used to ask for a list of
resources to only require the minimum to build that view.
Currently we use a default include, specified on the model, that
asks for **every** include when making requests to the API for a
particular model.
This has started to make performance quite slow as certain requests,
like loading a list of moves or allocations, don't require the same
detail as when viewing a single resource.
The example for these benchmarks included 25 active moves and 30 cancelled moves.
| <kbd><img src="https://user-images.githubusercontent.com/3327997/89270064-1a3f6c00-d63b-11ea-960e-310294eda27f.png"></kbd> | <kbd><img src="https://user-images.githubusercontent.com/3327997/89270728-0e07de80-d63c-11ea-916d-84a …
> Customise what includes we need for API requests

- common/services/allocation.js
- common/services/allocation.test.js
The `moves.profile` include was missed when tailoring the requests
for allocations to be more specific.
This change adds that include back in to the call to get active and
cancelled allocations.
This was needed to be able to build the progress on the dashboard.
> hotfix(allocations): Add missing include to listing call

- app/move/controllers/view.js
- common/presenters/framework-responses-to-meta-list-component.js
- common/presenters/framework-responses-to-meta-list-component.test.js
- common/presenters/framework-section-to-panel-list.js
- common/presenters/framework-section-to-panel-list.test.js
This fix checks to see if the response already exists when it's a
collection and appends to that response instead of creating a duplicate question.
This mimics the behaviour used for the overview pages.
It also adds some more high level unit tests to the presenters that control
this behaviour.
Previously if the response type was `collection` and multiple values
were selected which correlate to a "tag" needing to be shown the
question text was being duplicated.
This was because the response values were being filtered and then
appending separately.
| <kbd><img src="https://user-images.githubusercontent.com/3327997/89412176-e8a3cf00-d726-11ea-8136-8bf3fd3857f0.png"></kbd> | <kbd><img src="https://user-images.githubusercontent.com/3327997/89412131-d6c22c00 …
> fix(per): Group responses correctly under flag summary

- app/router.js
This change ensures we only run the map to load routers for directories.
This will remove the warning that appears each time the app is started.
It also adds extra uses of the debug module to see which sub-apps are
loaded and in which order for debugging purposes.
The file that loads the routers for the sub-apps was trying to
load itself which was causing a circular dependency warning.
This fix will remove the following warning:
<kbd><img src="https://user-images.githubusercontent.com/3327997/89630045-114ed480-d89f-11ea-8dfc-d23ee8d3a532.png"></kbd> …
> fix: Remove circular dependency when loading routers

- app/move/controllers/view.js
- app/move/controllers/view.test.js
- app/move/index.js
- app/person-escort-record/index.js
- app/person-escort-record/middleware.js
- app/person-escort-record/middleware.test.js
- app/person-escort-record/router.js
- app/person-escort-record/router.test.js
- common/services/framework-response.test.js
- common/services/frameworks.js
- common/services/frameworks.test.js
This changes the way the Person Escort Record frameworks are rendered on the frontend.
Previously the necessary controllers and form wizards were created once upon app start which was more efficient and
meant a lot of the route handling could be passed directly to Express.
This change moves the logic to be more dynamic and to support loading the framework version of the
current Person Escort Record returned from the API.
In order to support multiple versions we need to load in the version based on the version the API returns
for that Person Escort Record.
The structure of the form journeys are based on a particular version of the framework so these need to be known
at the point of building those routes, for example, a step or question may not exist in particular versions so we
can't …
> [P4-2006] Support multiple versions of a Person escort record

- app/move/controllers/update/move-details.js
- app/move/controllers/update/move-details.test.js
To prevent unnecessary submission of move details, we now check that
- the form value for `additional_information` actually exists
- that it is different from the current value
- The API can return null or string for additional_information
- The form value can be string or undefined depending on move type
The strict identity comparison by itself meant that we were patching when there
was no need to, and worse were sending an empty body
n/a
n/a
> fix(move): Prevent undefined additional_info being sent to patch move

- server.js
As of Helmet 4.0.0, inline-scripts are no longer allowed by default.
`govuk-frontend`’s default template uses an inline script to inject
the `js-enabled` class on the `body` element.
NB. for local dev, browsersync would also be clobbered without this policy change
> chore: Pass explicit CSP directives to Helmet

- server.js
This change updates the CSP to include the domains we load some
assets from as trusted sources, like Google Analytics and Fonts.
[Helmet v4 introduced CSP](https://github.com/helmetjs/helmet/wiki/Helmet-4-upgrade-guide) by default
which means we need to explicitly define the sources of our assets. This adds the remaining definitions for
analytics and fonts.
summary of changes and that the commit …
> build: Update Content Security Policy (CSP)

- config/nunjucks/globals.js
- config/nunjucks/globals.test.js
This fix now passes through all arguments to the i18n library.
The nunjucks global that added i18n support was only passing through
the key. This meant that if a context was set it wasn't registered
by the i18n function.
This method is used in components and a component coming soon needs to access
contexts. …
> Pass all arguments to i18n function

- app/move/controllers/update/base.js
- app/move/controllers/update/base.test.js
Display supplier for move rather than location when updating
Missed it in the previous golive work.
We now get the supplier from the move itself. There will either be one or there won't - but there definitely will not be potentially multiple suppliers for the move any more.
n/a
n/a (simply displays the correct string)
> Display supplier for move rather than location when updating

- common/services/move.js
- common/services/move.test.js
- common/services/single-request.js
- common/services/single-request.test.js
This fix gets the single requests download data from the BE endpoint as csv.
Single request downloads were still fetching the download data from the BE as JSON but then attempted to send that data as if it were already in csv format but without processing it, resulting in an inadvertent conversion circularity error.
n/a
n/a
> fix(single-requests): Make single request download work again

- common/lib/permissions.js
- common/lib/user.test.js
Disable prison transfer move creation for SCH and STC user
Feature is not ready yet
n/a
n/a
> Disable prison transfer move creation for SCH and STC user

- app/move/controllers/view.js
- app/move/controllers/view.test.js
- app/move/controllers/view/view.update.urls.js
- app/move/controllers/view/view.update.urls.test.js
- common/lib/permissions.js
- common/lib/user.test.js
This ticket includes the changes in #728 and adds more:
- STC/SCH users should have a dashboard with incoming, outgoing and single requests
- STC/SCH should be able to cancel proposed moves
- STC/SCH should not be able to edit youth transfer moves 
- P4-1997
- P4-2107
- P4-2106
- P4-1932
> [P4-1997 bis] SHC and STC transfer moves

- test/e2e/move.update.forbidden.test.js
- test/e2e/moves.download.test.js
- test/e2e/smoke.test.js
Removes tests relying on the `E2E_SUPPLIER` user
Supplier users now need to login with 2FA
Until we have a proper fix for handling that step, any tests relying on
the E2E_SUPPLIER user need to be disabled.
When fixed, this commit should be reverted.
n/a
n/a
> Disable supplier e2e tests

- test/e2e/move.new.prison.test.js
In order to unblock the e2e pipeline for now, the unknown prison number has been
updated to be in the expected format.
The downstream Prison API recently merged a change that expected the
search format to be in a pariticular format. If it isn't, it will now
throw an error which has been bubbled up from the API.
This means the frontend now receives a 500 from the API and doesn't
display the expected empty results page which causes the e2e tests to fail.
[GitHub release notes](https://github.com/ministryofjustice/hmpps-book-secure-move-frontend/releases) during the release …
> test: Update test prison number to be correct format

- app/moves/middleware/set-results.single-requests.js
- app/moves/middleware/set-results.single-requests.test.js
- common/services/single-request.js
- common/services/single-request.test.js
- common/templates/collection-as-table.njk
This PR adds cancelled moves in the single transfer dashboard.
- P4-1419
> [P4-1419] Cancelled moves

- app/person-escort-record/app/new/controllers.js
- app/person-escort-record/app/new/controllers.test.js
This change will look for that error and then handle it more appropriately
by redirecting back to the move.
An [issue was recorded in sentry](https://sentry.service.dsd.io/mojds/book-a-secure-move-frontend/issues/38714/) which returned an API error when the
frontend was attempting to create a new Person Escort Record when
one had already been created for this move.
This scenario could occur when:
- two users open a move without a record and see the start button
- first user clicks to start a new PER
- second user clicks to start a new PER but will receive an error
because one had already been created
Commit messages with a `fix` or `feat` type are automatically used to generate the [changelog](ministryofjustice/hmpps-book-secure-move-frontend/blob …
> fix(per): Prevent error when record already exists

- common/lib/api-client/request-headers.js
- common/lib/api-client/request-headers.test.js
Request compressed data from API
NB. axios uncompresses the returned data automagickally
Backend now supports it
- [P4-2175 - Add support for compressed requests](https://dsdmoj.atlassian.net/browse/P4-2175)
n/a
> Add Accept-Encoding: gzip header to API requests

- app/moves/middleware/set-results.single-requests.js
- common/parsers/index.test.js
- Fix issues with shifting dates periodically failing tests
- Fix unrelated linting issues
- Use sinon fake timers to set date to middle of year to avoid shifting dates periodically failing date tests
> Fix issue with shifting dates periodically failing date tests

- common/components/add-another/add-another.yaml
- common/components/add-another/template.njk
- common/components/add-another/template.test.js
- common/services/frameworks.js
- common/services/frameworks.test.js
Adds minItems (defaults to 1) and maxItems to field schema for multiple items fields
- Show remove buttons when items exceeds minItems
- Show add another button unless maxItems exceeds items
Prevent removal of last item when there should be at least one item
- [P4-2071](https://dsdmoj.atlassian.net/browse/P4-2071)
> Prevent last property bag from being removed [P4-2071]

- app/allocation/views/view.njk
- common/assets/scss/utilities/_typography.scss
- locales/en/allocation.json
A message is displayed when the allocation is full.
- P4-1600
> P4-1600 Show allocation is already filled 

- app/moves/middleware/set-results.single-requests.js
- common/presenters/single-requests-to-table-component.js
- common/presenters/single-requests-to-table-component.test.js
- locales/en/collections.json
When I select the “approved” filter on the Single Requests table
“Date of travel” (move date) is shown & sorted on. 
This is different from the “Earliest date of travel” on the “pending review” & “rejected” filter
- P4-1955
> Display approved single moves by 'Date of travel'

- .circleci/config.yml
- .circleci/e2e-pre-flight.sh
- app/healthcheck/dependencies.js
Skip redis check if not running and return 'NOT RUNNING' instead
Healthcheck endpoint would fail if redis not running otherwise
n/a
n/a
> Enable dependencies check to work in absence of redis

- app/person-escort-record/router.js
- app/person-escort-record/router.test.js
- common/controllers/form-wizard.js
- common/controllers/form-wizard.test.js
- common/helpers/field/get-field-error-message.js
- common/helpers/field/get-field-error-message.test.js
- common/helpers/field/set-field-error.js
- common/helpers/field/set-field-error.test.js
- locales/en/validation.json
- package-lock.json
- package.json
This adds support for the latest PER framework version, [v1.2.0](https://github.com/ministryofjustice/hmpps-book-secure-move-frameworks/releases/tag/v1.2.0).
This also includes a fix to support the use of emdashes in the framework which were previously being formatted out and then throwing a validation error as that value was no longer found in the list of available options.
In order to support the use of the new version, we need to add it to the list of available packages.
The problem cropped up when one of the framework questions contained an emdash (`—`) in the value and the form wizard
[default formatters](https://github.com/UKHomeOffice/passports-form-wizard/blob/c8131187ddaafd220af89e75b8c2a400f4bdd78e/lib/controller/index.js#L31-L37) would [replace …
> Update Person Escort Record framework version

- common/services/frameworks.js
- common/services/frameworks.test.js
Use correct validations structure when assigning minItems value
Misunderstanding of how validations structure actually worked
n/a
n/a
> Use correct validations structure when assigning default minItems value

- app/person-escort-record/controllers/framework-step.js
- app/person-escort-record/controllers/framework-step.test.js
Call middleware in correct order to support nested conditional fields, add another fields
and previously saved data for the framework step.
The works to support add another fields, that can also be include
nested fields, meant re-working the order of some middleware.
This ended up causing a side-effect where nested fields weren't being
repopulated when editing a step.
This was because of the ordering of the middleware. The synthetic nested
fields didn't yet exist in the fields for this step so weren't ever
populated with a value.
| <kbd><img src="https://user-images.githubusercontent.com/3327997/93453875-22452980-f8d2-11ea-9247-33910b534ca8.png"></kbd> | <kbd><img src="https://user-images.githubusercontent.com/3327997/93453676-e14d1500-f8d1-11ea-81e3-c …
> fix(per): Ensure nested fields are populated with initial values

- app/move/controllers/view.js
- app/move/controllers/view.test.js
- app/person-escort-record/controllers/framework-step.js
- app/person-escort-record/controllers/framework-step.test.js
- app/person-escort-record/router.js
- app/person-escort-record/router.test.js
- common/presenters/framework-section-to-panel-list.js
- common/presenters/framework-section-to-panel-list.test.js
- common/presenters/framework-to-task-list-component.js
- common/presenters/framework-to-task-list-component.test.js
Refactor the URLs of framework sections to be more logical.
Before:
```yaml
/person-escort-record/:section # redirects to first step
/person-escort-record/:section/overview # shows overview for section
/person-escort-record/:section/:step # framework step
```
After:
```yaml
/person-escort-record/:section # shows overview for section
/person-escort-record/:section/start # redirects to first step
/person-escort-record/:section/:step # framework step
```
Currently we use a custom URL as the "overview" for a section and the
root of a section in the URL acts as the starting point, which redirects
to the first step.
This feels like it makes the URL structure less logical. With this change
removing parts of the URL now show higher levels of information.
So a section base URL will show its …
> Restructure framework URLs to be more logical

- common/services/component.js
Add more data to the source of the [error in Sentry](https://sentry.service.dsd.io/mojds/book-a-secure-move-frontend/issues/63155/).
The production instance is currently throwing an error around the
`getComponent` with a circular structure. This error cannot be replicated
locally or any other environment.
This change attempts to provide Sentry with more information of this
error and to fail more silently, hopefully unblocking users who are
seeing this in our production environment.
[GitHub release notes](https://github.com/ministryofjustice/hmpps-book-secure-move-frontend/rel …
> Add extra logging around TypeError

- config/index.js
- server.js
This change updates the reference to the config item.
The app config file was updated to match a more consistent structure.
However, this inadvertantly meant that the Git SHA was no longer being
passed to Sentry to register a new release.
> Re-add release data to Sentry config

- common/presenters/framework-field-summary-list-row.js
This fix removes the chance of mutation by returning a new object.
fixes BOOK-A-SECURE-MOVE-FRONTEND-E
A recent change to the way dependent fields were rendered introduced
some potential mutation of the field object.
When this field was used further down the chain, like rendering
a component it caused a circular structure to appear from the response
question. …
> fix: Remove circular structure when rendering components

- app/move/controllers/view.js
- app/move/controllers/view.test.js
- app/move/middleware.js
- app/move/middleware.test.js
- app/move/views/view.njk
- app/person-escort-record/controllers/framework-section.js
- app/person-escort-record/controllers/framework-section.test.js
- app/person-escort-record/controllers/framework-step.js
- app/person-escort-record/controllers/framework-step.test.js
- app/person-escort-record/views/framework-section.njk
- locales/en/person-escort-record.json
This tidys up the logic around when the banner exists and what users
are allowed to do in those states.
Currently the banners that show the status of the Person Escort Record
and allow it to be started, edited or confirmed don't have any concept
of the status of the move.
This caused issues when some moves were started or completed and the
Person Escort Record banner was no longer visible.
- [P4-2193](https://dsdmoj.atlassian.net/browse/P4-2193)
| <kbd>![image](https://user-images.githubusercontent.com/3327997/93783008-24392080-fc23-11ea-8e6b-0a207672d1d1.png)</kbd> | <kbd>![image](https://user-images.githubusercontent.com/3327997/93782972-197e8b80-fc23-11ea-9b56-7555c3961c17.png)</kbd> |
| <kbd>![image](https://user-images.githubusercontent.com/332799 …
> [P4-2193] Correctly show banners/edit states with different move states

- app/moves/middleware/set-body.single-requests.js
- app/moves/middleware/set-body.single-requests.test.js
- app/moves/middleware/set-results.single-requests.js
- app/moves/middleware/set-results.single-requests.test.js
- common/presenters/allocations-to-table-component.test.js
- common/presenters/single-requests-to-table-component.js
- common/presenters/single-requests-to-table-component.test.js
Ability to sort Single Requests table (follows the same convention as allocations):
- Name - Alphabetical (same as allocations)
- Sent on - Date (same as allocations)
- Move from - Alphabetical (same as allocations)
- Move to - Alphabetical (same as allocations)
- Move type - Alphabetical (same as allocations)
Note: 
- Earliest date of travel (or date of travel) - this is currently a composite of two columns, so is not being sorted as a part of this ticket
-  [P4-2054](https://dsdmoj.atlassian.net/browse/P4-2054)
> [P4-2054] Ability to sort Single Requests table

- app/allocation/controllers/cancel.js
- app/allocation/controllers/cancel.test.js
- common/services/allocation.js
- common/services/allocation.test.js
- common/services/move.js
- common/services/move.test.js
Cancelling moves and cancelling allocations were developed at different times by different people. This PR brings them both up to date with the current approach for making requests.
- Refactor services.move to use api cancel rather than api update
- Explicitly pass reason and comment parameters to service
Code that performs the same task, but is approached differently, makes further work more complicated than it needs to be.
[GitHub release notes](https://github.com/ministryofjustice/hmpps-book-secure-move-frontend/releases) during the release task. Please make sure they …
> refactor: Refactor moves to use api cancel method

- common/lib/permissions.js
- common/lib/user.test.js
Add move permissions to users who have a PER_AUTHOR role.
If users only have the PER_AUTHOR role they currently can't see any
dashboards or move details because this role only adds the Person
Escort Record permissions.
This was an oversight initially and a user with this role should still
be able to view a move so that they can complete Person Escort Records. …
> fix: Allow users with PER editor role to see moves

- common/lib/permissions.js
- common/lib/user.test.js
- test/e2e/_helpers.js
- test/e2e/_move.js
- test/e2e/move.update.sch.test.js
- test/e2e/move.update.stc.test.js
Add `move:cancel` permission for STC & SCH users
- changed permissions config
- added SCH E2E test
- added cancel move tests
- added E2E tests for moves to court, prison, stc, sch, hospitals
- added "drop" to checkUpdateLinks as "court" is not a valid update page for a hospital move
As per the ticket,
> STC & SCH users should NOT be able to edit transfer requests once submitted. They should be able to cancel the request
> STC & SCH should still be able to edit/cancel moves to court moves and hospital moves. This issue is ONLY for transfer moves (moves to Prison, STC & SCH) 
- [P4-2106](https://dsdmoj.atlassian.net/browse/P4-2106) …
> feat: Restore cancel moves and proposed moves for STC & SCH roles

- app/moves/middleware/set-body.single-requests.js
- app/moves/middleware/set-body.single-requests.test.js
- app/moves/middleware/set-filter.single-requests.js
- app/moves/middleware/set-filter.single-requests.test.js
- Sets the correct range type when fetching the single requests depending for the desired status
- Also sets the correct range type for the single request filters depending on the filter status
Displays the approved moves that are happening in the selected date range rather than those that were created in it.
- [P4-2231 - Approved single moves column 'Date of move' contains moves for that week (not moves Booked on that week)](https://dsdmoj.atlassian.net/browse/P4-2231)
| <kbd>![Single_requests_sent_28_Sep_to_4_Oct_2020__This_week_](https://user-images.githubusercontent.com/4856/94677230-78738d00-0314-11eb-9377-daa4ac2b36e5.png)</kbd> | <kbd>![Single_requests_sent_28_Sep_to_4_Oct_2020__This_week_](https://user-images.githubusercontent.com/4856/94677356 …
> [P4-2231] Use move rather than created date for approved single requests

- app/move/fields/filter.prison-number.js
- app/move/validators.js
- app/move/validators.test.js
- locales/en/fields.json
- locales/en/validation.json
- test/e2e/_helpers.js
Add form-wizard validation to the prison number field
A validator was added to the prison number field
There is an existing issue with "Prison number containing colon character - e.g. 08:00 returns nasty exception" [P4-2124](https://dsdmoj.atlassian.net/browse/P4-2124).
Recently a downstream service made some changes, and these errors were being surfaced in the `frontend` application as 5xx errors. These errors were also being thrown while running the E2E tests.
#763 works around the issue for the E2E tests, but the underlying bug is still present.
This fix applies validation to the field to ensure that only correctly formatted prison numbers are sent downstream.
- [P4-2126](https://dsdmoj.atlassian.net/browse/P4-2126)
----
----
----
| <kbd><img …
> [P4-2126] fix: Add validation to prison number field

- app/move/validators.js
- app/move/validators.test.js
- locales/en/fields.json
This relaxes the validation to allow lowercase letters to be used.
It also updates the hint text to use quotes instead of primes:
https://carsonparkdesign.com/quotation-marks-apostrophes-versus-primes/
The API supports case insensitive search on prison number so we
shouldn't force uppercase validation on the frontend.
summary of changes and that the commit body gives a more detailed description …
> fix: Allow prison number to be case insensitive

- .eslintrc.js
- app/person-escort-record/controllers/framework-step.js
- app/person-escort-record/controllers/framework-step.test.js
- common/assets/javascripts/application.js
- common/assets/scss/components/_all.scss
- common/components/add-another/_add-another.scss
- common/components/add-another/add-another.js
- common/components/add-another/template.njk
- common/controllers/form-wizard.js
- common/controllers/form-wizard.test.js
- common/helpers/field/reduce-add-another-fields.js
- common/helpers/field/reduce-add-another-fields.test.js
- common/helpers/field/reduce-dependent-fields.js
- common/helpers/field/reduce-dependent-fields.test.js
- common/templates/layouts/base.njk
- server.js
Adding and removing items not happens on the client-side (if supported) using the ’Add Another’ pattern from the MoJ Design System/Frontend package
It... "can be more jarring for a user if they are adding many items as they need to wait for the page to reload after each addition."
- [P4 2076 - Enhance "Add another" with JavaScript component from MOJ Design System](https://dsdmoj.atlassian.net/browse/P4-2076)
n/a
> Progressively enhance add another

- common/services/single-request.js
- common/services/single-request.test.js
Adds move dates to single-request getCancelled method
Absence of move date handling resulted in cancelled moves not having any date filter applied
n/a
n/a
> fix: Add actual move dates to single-request getCancelled method

- app/allocation/controllers/view.js
- app/allocation/controllers/view.test.js
- app/allocations/middleware/set-body.allocations.js
- app/allocations/middleware/set-body.allocations.test.js
- app/allocations/middleware/set-results.allocations.js
- app/allocations/middleware/set-results.allocations.test.js
- app/home/middleware.js
- app/home/middleware.test.js
- app/move/controllers/view.js
- app/move/controllers/view.test.js
- app/move/controllers/view/view.update.urls.js
- app/move/controllers/view/view.update.urls.test.js
- app/moves/middleware/redirect-base-url.js
- app/moves/middleware/redirect-base-url.test.js
- app/moves/middleware/set-results.moves.js
- app/moves/middleware/set-results.moves.test.js
- common/controllers/collection/render-as-cards.js
- common/controllers/collection/render-as-cards.test.js
- common/lib/prohibitions.js
- common/lib/prohibitions.test.js
- common/middleware/locals.js
- common/middleware/locals.test.js
- common/middleware/permissions.js
- common/middleware/permissions.test.js
- common/middleware/set-primary-navigation.js
- common/middleware/set-primary-navigation.test.js
- server.js
Adds the ability for permissions to be prohibited by location type.
Prohibits `move:create` when the location_type is `court`.
Refactors calls to check permissions to use a method attached to the request object.
We have users that can access court locations and also have the `move:create` permission. This led to the unwanted outcome of being able to create a move through the frontend from a court.
- [P4-2105 - Prevent moves being created from courts](https://dsdmoj.atlassian.net/browse/P4-2105)
n/a
> P4 2105 prevent moves being created from courts

- app/person-escort-record/controllers/framework-step.js
- app/person-escort-record/controllers/framework-step.test.js
- common/helpers/frameworks/index.js
- common/helpers/frameworks/set-validation-rules.js
- common/helpers/frameworks/set-validation-rules.test.js
- common/services/frameworks.js
- common/services/frameworks.test.js
Conditionally apply validation to follow up comments from the Person Escort Record framework.
In order to support the new addition of NOMIS information the validation rules need to be made more
dynamic so that if information exists within NOMIS, we do not require the user to provide further details.
- [P4-2210](https://dsdmoj.atlassian.net/browse/P4-2210)
| With NOMIS mappings | |
| <kbd>![image](https://user-images.githubusercontent.com/3327997/95979106-0a01f500-0e13-11eb-9cff-de6d2c37f862.png)</kbd> | <kbd>![image](https://user-images.githubusercontent.com/3327997/95978805-9829ab80-0e12-11eb-91d0-98309f3d6181.png)</kbd> |
| Validation with NOMIS mappings | |
| <kbd>![image](https://user-images.githubusercontent.com/3327997/95979145-17b77a80-0e13-11eb …
> [P4-2210] Conditionally validate follow up comments based on NOMIS mappings

- common/helpers/frameworks/set-validation-rules.js
- common/helpers/frameworks/set-validation-rules.test.js
This catches a scenario where a followup comment from the Person Escort
Record framework doesn't have any validations.
Fixes BOOK-A-SECURE-MOVE-FRONTEND-W
Previously the helper assumed validations existed.
> fix(per): Handle when followup comments does not have any validations

- app/person-escort-record/controllers/framework-step.js
- app/person-escort-record/controllers/framework-step.test.js
- app/person-escort-record/views/framework-step.njk
- common/lib/api-client/models.js
- locales/en/person-escort-record.json
- test/fixtures/api-client/person_escort_record.create.json
- test/fixtures/api-client/person_escort_record.find.json
This adds a new banner to the framework steps when any information
coming from NOMIS fails.
It contains a list of information that could not be included so that the
user knows to check NOMIS for that information.
- [P4-2077](https://dsdmoj.atlassian.net/browse/P4-2077)
<kbd><img width="784" alt="Screenshot 2020-10-14 at 12 25 24" src="https://user-images.githubusercontent.com/3327997/95992817-48ed7600-0e26-11eb-973e-c8167bb95173.png"></kbd>
[GitHub release notes](https://github.com/ministryofjustice/hmpps-book-secure-move-frontend/releases) during the release task. Please …
> [P4-2077] Display banner when NOMIS sync fails

- package-lock.json
- package.json
Add a new version of the framework.
This allows the app to use the latest Person Escort Record framework.
> build: Increase book-a-secure-move-frameworks version

- app/move/controllers/unassign.js
- app/move/controllers/unassign.test.js
- app/move/views/unassign-ineligible.njk
- locales/en/validation.json
This change adds a check to the form wizard that handles the removal
of a person and displays a message to the user if this action cannot be
done.
This change still persists the button on the allocation page to remove a person instead of removing it
as simply removing might confused the user as to the circumstances in which it is not available.
Another option would be to disable the button and add a message as to why this action isn't possible
but this part of the interface already felt quite complicated and introducing this message might add extra
things to digest on one screen.
This is also based on a per move basis so can't be done as a single action on the allocation. Therefore, the
message has been moved to the step when a user attempts to complete the action. This was also much more …
> [P4-2317] fix(allocation): Stop person removal from an active or completed move

- common/lib/metrics.js
- common/lib/metrics.test.js
1. Fixed metrics 404 handling when called externally
A `404` error was being thrown rather than passed to `next` middleware.
This led to a `500` actually being served
2. Minor improvement of metrics recording
- Obfuscated code returned by auth callback
- Normalised asset paths when recording metrics
eg. 
```
/connect/hmpps/callback?code=foo => /connect/hmpps/callback?code=:code
/assets/app.a1b2c3d4.js => /assets/app.:sha.js
```
1. returns an actual 404 now
2. treats such paths as the same and provides more unified metrics and doesn't inadvertently expose the auth code (not a security issue per se, but better not to)
n/a
n/a
> Fix metrics 404

- app/person-escort-record/app/new/controllers.js
- app/person-escort-record/app/new/controllers.test.js
- common/presenters/framework-nomis-mappings-to-panel.js
- common/presenters/framework-nomis-mappings-to-panel.test.js
- common/services/person-escort-record.js
- common/services/person-escort-record.test.js
This updates the creation of a Person Escort Record to use the move ID
instead of the profile ID which is associated to that move.
The API now needs to accept the move ID to be able to correctly calculate
the logic around adding NOMIS information. This change supports the
new method dictated by the API.
- [P4-1888](https://dsdmoj.atlassian.net/browse/P4-1888) …
> refactor(per): Use move ID instead of profile ID when creating

- app/move/controllers/create/base.test.js
- app/move/controllers/create/move-date.test.js
- app/move/controllers/create/save.test.js
- app/moves/middleware/set-body-request-filters/age.test.js
- common/presenters/move-to-additional-info-list-component.test.js
- common/presenters/move-to-meta-list-component.test.js
- common/presenters/move-to-summary-list-component.test.js
When using date mocking libraries, it is important to restore the original behaviour at the end of the tests, otherwise weird failures will occur with unrelated tests.
Restore original behaviour after using sinon / timezoneMock
> test: Correctly restore core dates after mocking

- common/lib/user.test.js
The current permission tests require the permissions to be in the same order as defined in the config. However, that is not what we're actually wanting to test.
As per [this medium post](https://medium.com/building-ibotta/testing-arrays-and-objects-with-chai-js-4b372310fe6d) the usage of `deep.equal` has been replaced with `have.members` …
> test: Use member test for array contents

- common/controllers/form-wizard.js
- common/controllers/form-wizard.test.js
This change means that we will start to log them in Sentry so that we
can understand how often they are occurring and if there is a way to
reduce these occurrences.
There have been reports from users that they are seeing CSRF (This form
has been tampered with) errors frequently in production.
> Capture CSRF errors in Sentry

- app/person-escort-record/controllers/framework-step.js
- app/person-escort-record/controllers/framework-step.test.js
- app/person-escort-record/views/framework-step.njk
- common/assets/scss/utilities/_all.scss
- common/assets/scss/utilities/_form.scss
- common/components/framework-response/framework-response.yaml
- common/components/framework-response/template.njk
- common/components/framework-response/template.test.js
- common/helpers/frameworks/index.js
- common/helpers/frameworks/render-previous-answer-to-field.js
- common/helpers/frameworks/render-previous-answer-to-field.test.js
- common/lib/api-client/models.js
- common/presenters/framework-field-summary-list-row.js
- common/presenters/framework-field-summary-list-row.test.js
- locales/en/actions.json
- locales/en/person-escort-record.json
- package-lock.json
- package.json
- test/fixtures/api-client/person_escort_record.create.json
- test/fixtures/api-client/person_escort_record.find.json
This adds the ability to show a previous answer to a question on the Person Escort Record journey.
This is done as part of the rendering step within the framework step controller.
In some cases users are moving the same person multiple times within a short period, for example a move to court each day of the week. In many cases the answers to the assessment remain the same. This feature allows users to see the previous answer to a question and review it rather than having to fill the information in again.
- [P4-2294](https://dsdmoj.atlassian.net/browse/P4-2294)
- [P4-2066](https://dsdmoj.atlassian.net/browse/P4-2066)
<kbd>![booksecuremove-pr-916 herokuapp com_move_347296fb-ef85-4cf7-a5e5-d19b642ae2ad_person-escort-record_risk-information_security](https://user-images.githubusercontent.com/3 …
> [P4-2294][P4-2066] Show previous answer for a Person Escort Record question

- common/assets/scss/utilities/_form.scss
- common/helpers/frameworks/render-previous-answer-to-field.js
- common/helpers/frameworks/render-previous-answer-to-field.test.js
- common/presenters/framework-responses-to-meta-list-component.js
- common/presenters/framework-responses-to-meta-list-component.test.js
This change updates the styling to ensure the correct hierarchy and
that the correct classnames are used.
The classnames were refactored but this meant some of the desired
styling was lost.
| <kbd>![image](https://user-images.githubusercontent.com/3327997/97440876-f5981f00-191f-11eb-836c-e3cc6cc473b3.png)</kbd> | <kbd>![image](https://user-images.githubusercontent.com/3327997/97440817-e1542200-191f-11eb-9d52-bcbe904ca803.png)</kbd> |
| <kbd>![image](https://user-images.githubusercontent.com/3327997/97444654-4c075c80-1924-11eb-8e7f-fcf0bc9aca26.png)</kbd> | <kbd>![image](https://user-images.githubusercontent.com/3327997/97444529-2b3f0700-1924-11eb-8563-54f9cf91fc62.png)</kbd> |
> fix(per): Correct styling used to indicate when a question is prefilled

- app/allocation/controllers/view.js
- app/allocation/views/view.njk
- common/presenters/allocations-to-table-component.js
- common/presenters/allocations-to-table-component.test.js
- common/services/allocation.js
- common/services/allocation.test.js
- locales/en/collections.json
This PR depends on this BE PR
https://github.com/ministryofjustice/hmpps-book-secure-move-api/pull/1070 (which has now been merged)
Switch to using allocation's `metadata` to determine slots rather than having to ask for `moves` and `moves.profile`.
Additonally displays 'CANCELLED' rather than '0' for a cancelled allocation's progress when listing it.
Also displays the number of moves on the individual allocation view rather than '0'.
Reduce the number of includes required to render the list of allocations
- [P4-2341 - FE - Support Metadata in FE client for Allocation Dashboard](https://dsdmoj.atlassian.net/browse/P4-2341)
|<kbd>![Allocations_for_26_Oct_to_1_Nov_2020__This_week_](https://user-images.githubusercontent.com/4856/97456183-870f8d00-1930-11e …
> feat(allocation): Improve allocations listing performance

- .github/dependabot.yml
Prevent major node updates.
We want to stick to even releases of Node so this prevents dependabot
over-eagerly asking us to bump the version.
> build: Prevent dependabot suggesting major updates to node

- common/lib/metrics.js
- common/lib/metrics.test.js
Obfuscate `filter[police_national_computer]` and `filter[prison_number]`query args in path used for recording metrics
As these args were not obfuscated, so each lookup was treated as a separate and unique path
n/a
n/a
n/a
> Improve metrics url deduping

- app/person-escort-record/router.js
- app/person-escort-record/router.test.js
- locales/en/errors.json
This change uses the ID of the Person Escort Record to create the form wizard and journey keys so that they are unique for each record.
This also introduces a link to the error page to make it easier to refresh a form that has been tampered with.
We have seen lots of CSRF errors reported in Sentry. This occurs when a new CSRF token is generating for that form wizard and its journey.
Currently the key is not unique per Person Escort Record form wizard which means that if a user opens an existing record in another tab, for example to compare the previous information or re-use some information, and then try and submit the form step, it will have regenerated the CSRF token and the initial form step will now error.
- [P4-2419](https://dsdmoj.atlassian.net/browse/P4-2419)
| …
> [P4-2419] Ensure form wizards are unique for each Person Escort Record

- common/presenters/framework-field-summary-list-row.js
- common/presenters/framework-field-summary-list-row.test.js
This passes a responded property to the framework response component
for add another fields.
The framework response component was updated to know about both
responded and prefilled and now requires that the value be passed
as true in order to render the value.
| <kbd>![image](https://user-images.githubusercontent.com/3327997/97720085-bef90a80-1abf-11eb-9315-d8bb084ddec1.png)</kbd> | <kbd>![image](https://user-images.githubusercontent.com/3327997/97720005-a4bf2c80-1abf-11eb-85b8-b43afc23b4b0.png)</kbd> | …
> fix(per): Ensure add another responses are rendered correctly

- app/move/controllers/create/person-search.js
- app/move/controllers/create/person-search.test.js
This change uses the saved form values for redirect to the results
step rather than the original `req.body` value. The saved values are
sanitized and have had the whitespace trimmed so are the safer values
to use.
Before this change if a user entered a space before or after a search
term it would be passed to the next view and to the API and would produce
no results for the user.
- [P4-XXXX]()
| <kbd>![image](https://user-images.githubusercontent.com/3327997/98274381-43013580-1f8b-11eb-9860-6825822b9628.png)</kbd> | <kbd>![image](https://user-images.githubusercontent.com/3327997/98274381-43013580-1f8b-11eb-9860-6825822b9628.png)</kbd> |
| <kbd>![image](https://user-images.githubusercontent.com/3327997/98274328-311f9280-1f8b-11eb-83d2-2a362a7cc0c0.png)< …
> fix: Trim whitespace from person search inputs

- app/move/controllers/create/person-search-results.js
- app/move/controllers/create/person-search-results.test.js
This change addresses something seen from error validation analytics,
where if there is only one result when searching for a person, that
result will now be automatically selected.
Closes #809
The analytics showed a lot of validation errors for this particular
field, which suggests that the user behaviour is for this item to
already be selected.
summary of changes and that the commit body gives a …
> feat: Select radio item when only one result

- common/services/allocation.js
- common/services/allocation.test.js
Ensures allocation resource object always has a `moves` property
Endpoint that returns multiple allocations no longer includes move relationships in the response
- [IM-79 - Allocations unavailable in Staging](https://dsdmoj.atlassian.net/browse/IM-79)
> fix(allocation): Ensure allocation service resource always has moves

- app/move/controllers/create/document.js
- common/components/multi-file-upload/multi-file-upload.js
- common/controllers/form-wizard/index.js
- common/controllers/form-wizard/index.test.js
- common/controllers/form-wizard/mixins/csrf.js
- common/controllers/form-wizard/mixins/csrf.test.js
- common/templates/form-wizard.njk
- locales/en/errors.json
- package-lock.json
- package.json
This change overriddes the methods used to generate and verify the
CSRF token for all form wizard instances to use a globally set secret
that is stored separately on the user's session.
This will help prevent the CSRF errors that sometimes occur when a user
is interacting with different form wizards in multiple tabs.
Currently each form wizard sets a CSRF token for each instance. This is
stored in the session using the SessionModel. When changes are made to
this session, for example creating a new CSRF token, the SessionModel
uses the values it had for the session at the request to [save back
to the session](https://github.com/HMPO/hmpo-form-wizard/blob/c8131187ddaafd220af89e75b8c2a400f4bdd78e/lib/model.js#L42-L45).
This can lead to the CSRF secret being reset to a previous value in
some …
> [P4-2419] Form has been tampered with errors

- config/i18n/index.js
- config/i18n/interpolation.js
- config/i18n/interpolation.test.js
- config/nunjucks/filters.js
- config/nunjucks/filters.test.js
- test/unit/component-helpers.js
Enables i18next interpolation to use same filters as nunjucks
Also adds a formatter `exists` which returns a boolean if the value passed is undefined or an empty string
Filters sharing because there's no need to reinvent the wheel
`exists` formatter allows for construction of dynamic if/else style contexts when calling nested strings
Preparatory work ahead of https://github.com/ministryofjustice/hmpps-book-secure-move-frontend/pull/888
- [P4-2337 - Create view for timeline component](https://dsdmoj.atlassian.net/browse/P4-2337)
n/a
> Make app filters available to as i18n formatters [P4-2337]

- common/helpers/events/add-triggered-events.js
- common/helpers/events/add-triggered-events.test.js
- common/helpers/events/event-details-helpers.js
- common/helpers/events/event-details-helpers.test.js
- common/helpers/events/set-event-details.js
- common/helpers/events/set-event-details.test.js
- common/presenters/events-to-timeline-component.js
- common/presenters/events-to-timeline-component.test.js
- common/presenters/index.js
- locales/en/events.json
Adds presenter for data transformation
Adds events locales to provide content
Adds presenter for transformation of events to timeline format
Takes details from each event and mixes in
- move and person
- who performed the event (agency)
- context if any
- value determined by a `contextKey` for the corresponding event type as defined in `events.json`
- event's relationships
- event's `eventable` relationship as a singularised property
- eg. an eventable with type `journeys' is mixed in as `journey`
- common event properties
- eg. `notes` and `occurred_at` timestamp
Also adds status change pseudo-events which are displayed as a GDS badge rather than as the standard heading
<kbd>![Move_details_for_MELLIE__ROGER_–_Book_a_secure_move](https://user-images.githubusercontent.com/4856/99073114-3265 …
> Transform move events into data consumable by timeline component

- common/lib/api-client/index.js
- common/lib/api-client/index.test.js
- common/lib/api-client/middleware/index.js
- common/lib/api-client/middleware/process-response.js
- common/lib/api-client/middleware/process-response.test.js
- common/lib/api-client/middleware/request.js
- common/lib/api-client/middleware/request.test.js
- common/lib/find-unpopulated-resources.checks.js
- common/lib/find-unpopulated-resources.checks.test.js
- common/lib/find-unpopulated-resources.js
- common/lib/find-unpopulated-resources.test.js
- common/lib/populate-resources.js
- common/lib/populate-resources.test.js
- common/services/move.js
- common/services/move.test.js
- Find and inflate unpopulated resources returned to api-client
Modifications to `common/lib/api-client/middleware/request.js` and `common/lib/api-client/middleware/process-response.js` allow for minimal resource stubs  to be added to the included section.
`common/lib/find-unpopulated-resources.js` allows for the detection of unpopulated resources  in any data structure passed to it
`common/lib/populate-resources.js` allows for the inflation of any unpopulated resources in any data structure passed to it
- Enable move#getById to ask for population of resources
Some backend endpoints do not allow for the retrieval of resources using includes.
Devour sets any resource referenced as a relationship but not present in the included section to null.
- [P4-2337 - Create view for timeline …
> Find and inflate unpopulated resources returned to api-client [P4-2337]

- common/lib/api-client/middleware/request.js
- common/lib/api-client/middleware/request.test.js
- locales/en/events.json
`populateResources` in the api-client request middleware got missed when renamed to `preserveResourceRefs`
because of this omission, the resources never got preserved and, as a consequence, never got populated. This reinstates the desired behaviour.
- [P4-2337 - Create view for timeline component](https://dsdmoj.atlassian.net/browse/P4-2337)
n/a
> Correct populateResources to preserveResourceRefs renaming

- app/move/views/view.njk
This temporarily removes the tabs from the move detail view.
The URL will still be accessible to those who know it but it won't
be able to be accessed by navigating to it.
The API doesn't currently return the minimum events we desire so for
now the tabs won't be displayed on the detail view.
> chore: Remove tabs from move detail

- app/move/controllers/view/view.locals.js
- app/move/controllers/view/view.locals.test.js
- Get move url from view.tabs.urls
- Prefix tags with move url
- Use move url to create base PER url
Links are broken on move timeline view and would be on any other move views introduced needing to share the main move view content 
n/a
n/a
> Ensure links to PER and tags on move:* views are absolute

- app/allocation/config/cancel.config.js
- app/allocation/config/create.config.js
- app/allocation/config/index.js
- app/allocation/config/remove.config.js
- app/allocation/index.js
- app/move/config/assign.config.js
- app/move/config/cancel.config.js
- app/move/config/create.config.js
- app/move/config/index.js
- app/move/config/review.config.js
- app/move/config/unassign.config.js
- app/move/config/update.config.js
- app/move/index.js
- app/person-escort-record/app/confirm/config.js
- app/person-escort-record/app/confirm/index.js
- app/person-escort-record/app/new/index.js
- common/lib/framework-form-wizard.js
- common/lib/framework-form-wizard.test.js
- common/middleware/index.js
- common/middleware/unique-form-wizard.js
- common/middleware/unique-form-wizard.test.js
This change creates a wizard using the UUID of the resource in cases
where it is intended to be individual.
Currently form wizards used as part of a particular resource share
the same journey and wizard names.
This can lead to unintended side-effects when these wizards are accessed
through different URLs or opened in new windows or tabs.
For example, if a wizard is submitted with errors in one tab and opened
up in another those errors will be persisted, and in some cases the
redirect will occur on the original resource instead of the intended one. …
> Use unique form wizard for individual resources

- app/move/controllers/create/move-details.js
- app/move/controllers/create/move-details.test.js
- common/middleware/set-location-items.js
- common/middleware/set-location-items.test.js
`setLocationItems` can now be passed an array of location types which will be combined and sorted alphabetically.
Hospital location items are now made up of locations matching both `high_security_hospital` and `hospital`
Users could not select a non high security hospital
- [P4-2408 - Show both NOMIS "High Security Hospitals" & "Hospital" location types for type ahead on Hospital moves](https://dsdmoj.atlassian.net/browse/P4-2408)
As before. Just adds extra items to hospital dropdown
> Show both NOMIS "High Security Hospitals" & "Hospital" location types for type ahead on Hospital moves [P4-2408]

- app/move/controllers/create/base.js
- app/move/controllers/create/base.test.js
- app/move/controllers/create/person.test.js
- app/move/views/assign/assign-conflict.njk
- app/move/views/assign/no-special-vehicle.njk
- app/move/views/create/move-not-supported.njk
- app/move/views/create/save-conflict.njk
- app/move/views/unassign-ineligible.njk
- common/lib/api-client/models/category.js
- common/lib/api-client/models/index.js
- common/lib/api-client/models/index.test.js
- common/lib/api-client/models/person.js
- common/services/person.js
- common/services/person.test.js
- common/templates/layouts/action-prevented.njk
- locales/en/validation.json
- test/fixtures/api-client/category.find.json
- test/fixtures/api-client/person.find.json
After a user selects a prisoner to be moved, checks whether they should be moved or not.
If not, displays a page explaining that the person cannot be moved and why not.
Prevents prisoners being inadvertently moved. 
- [P4-2310 - Check category at "Who is being moved step"](https://dsdmoj.atlassian.net/browse/P4-2310)
<kbd>![Error__ARCAMONE__AMERY_cannot_be_moved_using_this_service](https://user-images.githubusercontent.com/4856/99797837-e1fb6500-2b27-11eb-853f-2cecabea5b2e.png)</kbd>
> Check prisoner category before creating a move

- common/lib/api-client/transformers/transform-resource.js
- common/lib/api-client/transformers/transform-resource.test.js
This change clears the cache when an item is transformed and sets the
new values so that any future occurrences return the correct structure.
This is slightly less efficient that being able to udpate a cached
resource but [devour doesn't currently support](https://github.com/twg/devour/blob/71e158307d462018be0c43164d285e9a959d0983/src/middleware/json-api/_deserialize.js#L15-L34) a method to do this.
In some instances, if the same resource is return multiple times within
a collection, for example a person in a list of moves, the transformer
was only being called once because devour would cache that resource within
its deserializer.
This meant that if the same person was being moved on the same day they
wouldn't have the fullname property that parts of the app expect.
- [P4-XXXX]()
| Before …
> fix: Apply transformer to duplicate resources correctly

- common/middleware/development.js
- common/middleware/development.test.js
Only set development permissions if they don't exist.
This prevents the permissions being overridden on every request.
It also means that they can be updated via another method like session
injection and won't be overridden.
> chore: Don't set development permissions if they already exist

- common/lib/api-client/transformers/transform-resource.js
If the custom deserializer isn't removed this method will result in
an infinite loop as it will keep calling itself.
We need to ensure this is removed, regardless of whether a transform
method is present or not.
> fix: Ensure custom deserializer is removed before calling parent

- common/lib/api-client/transformers/transform-resource.js
- common/lib/api-client/transformers/transform-resource.test.js
Clearing devour's cache doesn't work so we remove existing item explicitly instead
Nested copy of object in the included section would cause the transformer to go into an infinite loop
n/a
n/a
> fix: Prevent model transformer infinite looping

- common/presenters/events-to-timeline-component.js
- common/presenters/events-to-timeline-component.test.js
- test/e2e/_routes.js
- test/e2e/move.timeline.test.js
- test/e2e/pages/index.js
- test/e2e/pages/move-timeline.js
- Reverses order in which timeline items are output
- Adds basic e2e tests for move timeline
- ensures that timeline view can be rendered
- ensures that minimal events exist on page
Reverse order is as per design.
Tests are good, but more to the point, ensuring that the timeline view can be rendered would have caught the infinite loop bug in the model `transformResource` method.
n/a
| After | Before |
| <kbd>![Move_details_for_SCHMITT__ERICH_–_Book_a_secure_move](https://user-images.githubusercontent.com/4856/100391127-6e2af200-302a-11eb-88d5-334218883f06.png)</kbd> | <kbd>![Move_details_for_SCHMITT__ERICH_–_Book_a_secure_move](https://user-images.githubusercontent.com/4856/100391209-a29eae00-302a-11eb-8e57-3d55c6d0b739.png)</kbd> |
Has been tested in the following …
> Reverse order of items in move timeline

- common/middleware/ensure-authenticated.js
- common/middleware/ensure-authenticated.test.js
- common/middleware/ensure-selected-location.js
- common/middleware/ensure-selected-location.test.js
- config/index.js
This change adds the path to the whitelist so that they authentication
is bypassed.
Currently the components app is being the global authentication and
location middleware. There is no need for this on environments where
it is enabled.
> chore: Whitelist the components URL

- app/router.js
- common/lib/mount.js
- common/lib/mount.test.js
- test/fixtures/mount/default/app1/index.js
- test/fixtures/mount/empty/.gitkeep
- test/fixtures/mount/missing/app1/.gitkeep
- test/fixtures/mount/missing/app2/index.js
- test/fixtures/mount/mountpath/app1/index.js
- test/fixtures/mount/multiple/app1/index.js
- test/fixtures/mount/multiple/app2/index.js
- test/fixtures/mount/skip/app1/index.js
- test/fixtures/mount/skip/app2/index.js
Extract router subapp loading to its own module for reuse
- adds tests
- enables empty folders to not cause the app to crash
- streamlines the returning of noop middleware
n/a
n/a
> Extract router subapp loading to its own module for reuse

- Dockerfile
The tasks need to be called in some environments to do actions like
clearing cache.
To have access to this we need this copied across in the container.
> build: Add tasks folder to Dockerfile

- common/helpers/frameworks/index.js
- common/helpers/frameworks/map-item-to-section.js
- common/helpers/frameworks/map-item-to-section.test.js
- common/helpers/frameworks/map-question-to-response.js
- common/helpers/frameworks/map-question-to-response.test.js
- common/lib/api-client/transformers/assessment.transformer.js
- common/lib/api-client/transformers/assessment.transformer.test.js
This extends the transformer for the assessment resource.
It includes some additions to each section of the framework to make it
easier to work with this resource within the application.
It adds:
- section progress
- responses for a particular section
- questions for a particular section
- framework question to each response
This allows some transformation that takes place within the app to
visualise responses or questions to happen a little easier.
It tries to bring together the content from the framework and the values
returned by the API into the one object.
- [P4-2444](https://dsdmoj.atlassian.net/browse/P4-2444) …
> Extend assessment transformer

- app/population/controllers/edit.js
- app/population/controllers/edit.test.js
- app/population/steps/edit.js
- locales/en/actions.json
- locales/en/population.json
If adding new population details, use "Add numbers" as a page title, if editing existing population details use "Change numbers" as a page title.
Change the button text to "Calculate and save" in both instances
- [P4-2548](https://dsdmoj.atlassian.net/browse/P4-2548)
| ![Screenshot_2020-12-03 Population Details - create_population](https://user-images.githubusercontent.com/196695/101016069-2f33f980-3560-11eb-9b27-a61b2bf69e0f.png) | ![Screenshot_2020-12-03 Change numbers - create_population](https://user-images.githubusercontent.com/196695/101016097-365b0780-3560-11eb-907b-7907e49b6a62.png) |
| ![Screenshot_2020-12-03 Population Details - create_population(1)](https://user-images.githubusercontent.com/196695/101016131-407d0600-3560-11eb-9ca4-a4406ac5e3 …
> [P4-2548] fix: Update edit population heading and button

- app/population/controllers/edit.js
- app/population/controllers/edit.test.js
Use the fullname of the user when updating, not the string "user.fullname"
- [P4-XXXX]()
> fix: Use session.user.fullname for updated_by

- app/move/controllers/create/save.js
- app/move/controllers/create/save.test.js
Fixes an issue when prison recall conflicts occur.
The current error handler for rendering conflicts expects there to
be a to location and a title for that location.
However, for a prison recall move this doesn't exist so this fixes
that issue and uses the label for the prison recall option when
the location doesn't exist.
Fixes BOOK-A-SECURE-MOVE-FRONTEND-1F
https://sentry.io/organizations/ministryofjustice/issues/2072489820
| <kbd>![image](https://user-images.githubusercontent.com/3327997/101360910-31ff5900-3896-11eb-85c1-0e65635cc016.png)</kbd> | <kbd>![image](https://user-images.githubusercontent.com/3327997/101360867-214ee300-3896-11eb-8b60-202e506db24c.png)</kbd> |
> fix: Use correct content for prison recall conflicts

- common/controllers/framework/framework-overview.js
- common/controllers/framework/framework-overview.test.js
- common/controllers/framework/framework-section.js
- common/controllers/framework/framework-section.test.js
- common/controllers/framework/framework-step.js
- common/controllers/framework/framework-step.test.js
- common/helpers/frameworks/render-previous-answer-to-field.js
- common/helpers/frameworks/render-previous-answer-to-field.test.js
- common/presenters/framework-to-task-list-component.js
- common/presenters/framework-to-task-list-component.test.js
- common/templates/framework-overview.njk
- common/templates/framework-section.njk
- common/templates/framework-step.njk
- locales/en/assessment.json
- locales/en/person-escort-record.json
- locales/en/youth-risk-assessment.json
This set of changes moves some of the Person Escort Record specific content keys to the generic namespace so that they can be shared between the two.
Some of the Youth Risk Assessment pages are currently using the Person Escort Record content when they need to be using
youth risk assessment specific content.
> Use correct content for framework assessment

- app/allocation/controllers/assign-to-allocation.js
- app/allocation/controllers/assign-to-allocation.test.js
- app/allocation/controllers/index.js
- app/allocation/controllers/view.js
- app/allocation/controllers/view.test.js
- app/allocation/index.js
- app/allocation/views/view.njk
- app/move/controllers/assign/base.js
- app/move/controllers/assign/base.test.js
- app/move/controllers/create/base.js
- app/move/controllers/create/base.test.js
This change includes two fixes to prevent a circular structure error. It:
- prevents the assign journey being completed when a move already has a profile
- handles the deciding of the next move to assign using a redirect route instead of on page load of the allocation
See Jira ticket for more information.
- [IM-28](https://dsdmoj.atlassian.net/browse/IM-28)
Fixes BOOK-A-SECURE-MOVE-FRONTEND-T
https://sentry.io/organizations/ministryofjustice/issues/1920836995
> [IM-28] Protect assign journey with extra checks

- common/controllers/form-wizard/index.js
- common/controllers/form-wizard/index.test.js
- common/templates/form-wizard-error.njk
- locales/en/errors.json
This creates some extra logging to sentry around expired journeys.
We have had some reports of this screen being shown to users. At the moment we catch this as an expected error rather than throw it as an unhandled exception.
<kbd>![image](https://user-images.githubusercontent.com/3327997/101501699-f92fb480-3967-11eb-90ba-8b4e472fd854.png)</kbd>
<kbd>![image](https://user-images.githubusercontent.com/3327997/101501734-02b91c80-3968-11eb-8cbf-39c4eb7cf7a4.png)</kbd>
> Log expired journeys

- common/templates/framework-section.njk
- locales/en/assessment.json
This text was currently specific to the Person Escort Record but is
used by both assessment.
It needs to be set using a context so that it is dynamic based on which
is being viewed.
> Use context for locked assessment text

- app/move/controllers/view/view.locals.js
- app/move/controllers/view/view.locals.test.js
Ensure Person Escort Record information is correctly displayed when no feature flag.
The youth risk assessment is currently hidden behind a feature flag.
When this is not enabled the move detail should fall back to the
Person Escort Record.
> Ensure Person Escort Record is displayed without feature flag

- common/lib/api-client/models/approve.js
- common/lib/api-client/models/index.js
- common/services/single-request.js
- common/services/single-request.test.js
This changes the current approval action to use the "events" endpoints
on a move rather than relying on a `PATCH`.
When a `PATCH` is called it doesn't trigger the necessary events
and actions in the background so this change ensures all frontend
status changes are using the correct endpoints.
> Use approval endpoint for approving single requests

- test/e2e/_helpers.js
- test/e2e/move.update.sch.test.js
Catch API errors that occur when running end-to-end tests and log them to Sentry.
Currently in some scenarios the API may return a `422` when we
create a dynamic fixture.
It's hard to debug to see what extactly went wrong so this change
adds the ability to catch those errors and log them to Sentry so that
they can be investigated.
<kbd>![image](https://user-images.githubusercontent.com/3327997/101631997-24c0a680-3a1d-11eb-8ab8-bcd9b4481ff4.png)</kbd>
<kbd>![image](https://user-images.githubusercontent.com/3327997/101632042-34d88600-3a1d-11eb-9744-d5434d6b29ba.png)</kbd>
<kbd>![image](https://user-images.githubusercontent.com/3327997/101632073-43bf3880-3a1d-11eb-9ffd-80bb9bb6599b.png)</kbd>
> Catch API errors that are generated in the end-to-end tests

- app/youth-risk-assessment/app/confirm/controllers.js
- app/youth-risk-assessment/app/confirm/controllers.test.js
- app/youth-risk-assessment/app/new/controllers.js
- app/youth-risk-assessment/app/new/controllers.test.js
Make use of the new setServices middleware for the youth risk assessment service. Part of the work to enable request context in services. …
> refactor: Update controllers to use youth risk assessment service from req

- webpack.config.production.js
SVG files were being double processed by webpack, once as images, and once as fonts.
This resulted in the svg files looking like:
export default __webpack_public_path__ + "icon-tag-remove-cross.aa3a837b.svg";
There are no SVG font assets, so this simply removes svg from the font config
Updated webpack production config to not process svg as fonts.
SVG files were being created as an unexecuted line of javascript and so not rendering when requested.
- [P4-2567 - 'X' icon no longer showing in filter tag](https://dsdmoj.atlassian.net/browse/P4-2567)
| After | Before |
| <kbd>![Single_requests_sent_7_to_13_Dec_2020__This_week_](https://user-images.githubusercontent.com/4856/101673289-e348ef00-3a4e-11eb-91f6-8af18f005a0d.png)</kbd> | …
> Make filter remove icons show up properly [P4-2567]

- app/population/controllers/edit.js
- app/population/controllers/edit.test.js
- app/population/middleware/set-population.js
- app/population/middleware/set-population.test.js
Make use of the new setServices middleware for the population service. Part of the work to enable request context in services. …
> refactor: Update controllers to use population service from req

- app/move/controllers/view/view.locals.js
- app/move/views/view.njk
- common/lib/permissions.js
- common/lib/user.test.js
- common/presenters/message-banner/move-to-message-banner-component.js
- common/presenters/message-banner/move-to-message-banner-component.test.js
- locales/en/actions.json
- locales/en/messages.json
This set of changes includes:
- content tweak to youth banner
- permission updates for all roles and suppliers
- logic update to handle existing PERs when youth feature is enabled
These changes came as a result of feedback from users and the business.
- [P4-2562](https://dsdmoj.atlassian.net/browse/P4-2562)
- [P4-2570](https://dsdmoj.atlassian.net/browse/P4-2570) …
> [P4-2562] [P4-2570] Youth risk assessment updates

- common/services/document.js
- common/services/document.test.js
Converts document service to class which takes the req object on isntantiation.
> refactor: Update document service to class with req object

- common/helpers/field/reduce-add-another-fields.js
- common/helpers/field/reduce-add-another-fields.test.js
This is a fix to ensure that when items are added using JavaScript
and that item contains radios or checkboxes, that the data name does
not receive an index.
This causes each item to use a different field name and means in some
cases the form submits these values as an array instead of a string.
> fix: Ensure radio/checkboxes within add another keep same name

- common/components/add-another/add-another.js
Ensure that conditionally revealed blocks triggered by radio button have correct `aria-controls` value associated with them
Clicking on radio in an added item would trigger the corresponding block in the first item to be revealed
n/a
| After | Before |
| <kbd>![after](https://user-images.githubusercontent.com/4856/102341470-cc932280-3f8f-11eb-95ca-23e5a3496612.gif)</kbd> | <kbd>![before](https://user-images.githubusercontent.com/4856/102341492-d3ba3080-3f8f-11eb-8094-680f0c95f6c9.gif)</kbd> |
> Handle conditional fields triggered by radio within add another

- common/presenters/date-table/locations-to-population-table-component.js
- common/presenters/date-table/locations-to-populations-table-component.test.js
- common/presenters/date-table/population-helpers.js
- common/presenters/date-table/population-helpers.test.js
This PR separates out the row and cell related functions from the ones that construct a population table. This will make it easier to iterate in future PRs.
The `dayConfig`, `establishmentConfig` and `freeSpaceCellContent` functions have been moved into a separate file, along with their tests. …
> refactor: Extract row & cell functions into helper

- app/population/controllers/dashboard.js
- app/population/controllers/dashboard.test.js
- app/population/index.js
- app/population/middleware/index.js
- app/population/middleware/set-population.js
- app/population/middleware/set-population.test.js
- app/population/middleware/set-results.population-tables.js
- app/population/middleware/set-results.population-tables.test.js
- app/population/views/dashboard.njk
- common/assets/scss/components/_all.scss
- common/assets/scss/components/_population-table.scss
- common/lib/api-client/models/index.js
- common/lib/api-client/models/location.js
- common/lib/api-client/models/locations-free-spaces.js
- common/presenters/date-table/locations-to-population-table-component.js
- common/presenters/date-table/locations-to-populations-table-component.test.js
- common/services/locations-free-spaces.js
- common/services/locations-free-spaces.test.js
- locales/en/population.json
- test/fixtures/api-client/location.find.json
- test/fixtures/api-client/location.findAll.json
PMU users manage the population of establishments via category groups. This PR groups the establishments via these categories.
- Categories have been added to the location model
- getPrisonFreeSpaces uses an include of `category`, and the response is grouped by category, with an added caption
- Population dashboard loops over many population tables 
- [P4-2288](https://dsdmoj.atlassian.net/browse/P4-2288)
| ![Screenshot_2020-12-15 Population for 14 to 20 Dec 2020 (This week)](https://user-images.githubusercontent.com/196695/102280463-1a267580-3f25-11eb-8510-c70ff54a987b.png) |![Screenshot_2020-12-16 Population for 14 to 20 Dec 2020 (This week)](https://user-images.githubusercontent.com/196695/102371880-9321dd80-3fb6-11eb-8e0c-91674788618a.png)|
| …
> [P4-2288] Display categories on population pages

- app/population/controllers/daily.js
- app/population/controllers/daily.test.js
- app/population/views/daily.njk
Recent refactoring broke the link to quick edit from the population grid. This PR fixes an existing bug with "add numbers" on the daily page. Another PR will restore the quit edit functionality.
A lack of E2E tests meant this wasn't caught on previous PRs.
- [] Added unit tests to cover changes …
> fix: Quick fix for broken population adding

- common/presenters/date-table/population-helpers.js
- common/presenters/date-table/population-helpers.test.js
A regression was introduced in a recent refactor which broke the deep linking into the edit screen.
The API returns `null`, and the previous test was comparing against `undefined`. This code now used `lodash`'s `isNil` to handle all cases.
> fix: Use correct link to population edit page

- app/population/middleware/set-population.js
- app/population/middleware/set-population.test.js
Now that transfers are returned on the locations_free_spaces service, there is no longer an need for extra requests to retrieve this information.
This PR removes the calls to load transfers and replaces them with the information from the locations_free_spaces request
> Refactor: Use transfers from locations_free_spaces service

- common/lib/api-client/request-headers.js
- common/lib/api-client/request-headers.test.js
Added an extra check before setting the `X-Current-User` header.
In development we can set options to bypass SSO, which means a user object exists without a username.
- [P4-1776]()
> fix: Set current user header only when the username is present

- common/helpers/move/get-locals.js
- common/helpers/move/get-locals.test.js
- common/lib/api-client/models/profile.js
- common/presenters/person-to-summary-list-component.js
- common/presenters/person-to-summary-list-component.test.js
- common/services/move.js
- common/services/move.test.js
- locales/en/fields.json
- test/fixtures/api-client/profile.create.json
Adds person’s category to personal summary details if the person has a prison number
- [P4-2461 - Display the person's category on their record page](https://dsdmoj.atlassian.net/browse/P4-2461)
<kbd>![Move_details_for_CASEDY__DOMSANIGH_–_Book_a_secure_move](https://user-images.githubusercontent.com/4856/102611446-d438ff80-4126-11eb-8ec4-932006ab758f.png)</kbd>
> Display person category on move record page [P4 2461]

- app/move/app/new/controllers/assessment.js
- app/move/app/new/controllers/assessment.test.js
- app/move/app/new/controllers/base.js
- app/move/app/new/controllers/base.test.js
- app/move/app/new/controllers/document.test.js
- app/move/app/new/controllers/save.js
- app/move/app/new/controllers/save.test.js
- common/services/profile.js
- common/services/profile.test.js
Moves profile creation to the base controller.
Fixes issue where changing the person wouldn't create a new profile.
Currently we check if a profile exists within the assessment controller.
This is done as part of setting the previous assessment.
However, we are introducing different flows to the journey which will
mean these steps are never seen, and therefore the profile is never
created.
This leads to an error when saving the move as the profile doesn't
exist.
This also addresses a bug where if a user tries to change the person,
a new profile is not created as we don't validate that the profile is
for the currently selected person.
- [P4-2557](https://dsdmoj.atlassian.net/browse/P4-2557)
> [P4-2557] fix: Check for profile in base create controller

- common/lib/api-client/models/location.js
- common/lib/api-client/models/profile.js
- test/fixtures/api-client/location.find.json
- test/fixtures/api-client/location.findAll.json
- test/fixtures/api-client/profile.create.json
This adds a new attribute to the locations model (`young_offender_institution`) and a new attribute to the profile model (`requires_youth_risk_assessment `).
These new attributes are required to add the logic for sending prisoners from a prison that are serving their sentence on the youth estate.
- [P4-2557](https://dsdmoj.atlassian.net/browse/P4-2557)
> [P4-2557] Add new attributes required for youth moves

- common/helpers/move/get-locals.js
- common/helpers/move/get-locals.test.js
Put a guard to ensure `move.profile` is not null
`person` is retrieved from the `profile` object
https://sentry.io/organizations/ministryofjustice/issues/2100728538/?project=2014813&query=is%3Aunresolved#exception
Fixes BOOK-A-SECURE-MOVE-FRONTEND-23
n/a
> Ensure profile not null in move get-locals helper

- .circleci/config.yml
The latest tag is having some issues with the latest release of the
code climate test coverage reporter.
The quickest way out of it is to pin the version instead of using
`latest`.
See this thread for more information:
https://github.com/codeclimate/test-reporter/issues/449
> test: Pin codeclimate test coverage reporter

- app/move/app/new/controllers/base.js
- app/move/app/new/controllers/base.test.js
- app/move/app/new/controllers/save.js
- app/move/app/new/controllers/save.test.js
- app/move/app/new/steps.js
- app/move/fields/index.js
- app/move/fields/serving-youth-sentence.js
- locales/en/fields.json
- locales/en/moves.json
This set of changes introduces logic within the move creation journey to ask if a prisoner is serving their sentence in the youth estate.
This check only occurs when the location is marked as a `prison` and also a `young_offender_institution` and the person is between 18 and 19. 
This moves the logic for determining if a youth risk assessment should be shown to the profile, where the attribute `requires_youth_risk_assessment` is set when creating the move.
In some scenarios this can be determined automatically, in others the extra question needs to be asked.
- if coming from `secure_childrens_home` - **true**
- if coming from `secure_training_centre` - **true**
- if coming from `prison`
- if `young_offender_institution`
- if under 18 - **true**
- if over 18 - **false**
- if serving on …
> [P4-2557] Create logic to determine if the person is serving a youth sentence

- app/allocation/controllers/view.js
- app/move/views/view.njk
- app/moves/middleware/set-results.moves.js
- app/moves/middleware/set-results.moves.test.js
- common/helpers/move/get-locals.js
- common/helpers/move/get-locals.test.js
- common/helpers/move/get-per-details.js
- common/helpers/move/get-per-details.test.js
- common/lib/permissions.js
- common/lib/user.test.js
- common/presenters/move-to-card-component.js
- common/presenters/move-to-card-component.test.js
- common/presenters/moves-by-location.js
- common/presenters/moves-by-location.test.js
- common/presenters/profile-to-card-component.js
- common/presenters/profile-to-card-component.test.js
- test/e2e/pages/move-detail.js
This set of changes removes and tidies up logic that was written to allow the Person Escort Record to be rolled out on a permission basis.
This feature is now available to all users so we don't need to hide it behind a permission any longer.
> Remove Person Escort Record feature flag

- app/person-escort-record/index.js
- app/youth-risk-assessment/index.js
- common/controllers/framework/framework-step.js
- common/controllers/framework/framework-step.test.js
- common/middleware/framework/index.js
- common/middleware/framework/set-breadcrumbs.js
- common/middleware/framework/set-breadcrumbs.test.js
- common/middleware/framework/set-section-breadcrumb.js
- common/middleware/framework/set-section-breadcrumb.test.js
- common/templates/framework-overview.njk
- common/templates/framework-section.njk
- locales/en/moves.json
This change adds a breadcrumb for the assessment sections and steps.
This makes navigating around the assessments easier and gives users
an anchor when going through steps/sections.
- [P4-XXXX]()
| <kbd>![image](https://user-images.githubusercontent.com/3327997/102901122-82b5ab00-446d-11eb-8a47-50359608550a.png)</kbd> | <kbd>![image](https://user-images.githubusercontent.com/3327997/102900704-f905dd80-446c-11eb-8011-f661d5d5f881.png)</kbd> |
> Add breadcrumbs to Person Escort Record and Youth Risk Assessment

- common/lib/api-client/request-headers.js
- common/lib/api-client/request-headers.test.js
- common/middleware/sentry-request-id.js
- common/middleware/sentry-request-id.test.js
- common/middleware/set-transaction-id.js
- common/middleware/set-transaction-id.test.js
- server.js
This uses the request ID header to store against sentry issues and also
passes that same value to API calls.
This allows a particular frontend request can be traced through to particular API calls that might have
errorred.
> Store transaction ID in Sentry and pass to API calls

- common/lib/metrics.js
- common/lib/metrics.test.js
This change adjusts the controller handling the response to expect a promise from now on.
The recent dependency bump for promster included a breaking change,
even though the version didn't show a major version change:
https://github.com/ministryofjustice/hmpps-book-secure-move-frontend/pull/1188
The call to get the summary became a promise. 
Fixes BOOK-A-SECURE-MOVE-FRONTEND-2A
https://sentry.io/organizations/ministryofjustice/issues/2109959785
> fix: Prevent metrics error from recent dep upgrade

- common/middleware/sentry-request-id.js
- common/middleware/sentry-request-id.test.js
This change separates the two variables and allows them to be set
independently.
Before we were always using the transaction ID for Sentry tags.
But in the case where the request ID doesn't exist, we don't want
to set it in Sentry, we'd rather leave it unset which shows there
was no request ID available.
> refactor: Separate request ID and transaction ID in Sentry tags

- common/lib/api-client/middleware/request.js
This uses optional chaining to ensure the parent property exists
before trying to use the nested property.
The debugger was updated to use the response code and text from the
error. But it seems in some cases the response doesn't exist.
https://sentry.io/organizations/ministryofjustice/issues/2118879002/?project=2014813
Fixes BOOK-A-SECURE-MOVE-FRONTEND-2F
> fix: Make sure error response exists first before using in debugging

- common/components/pagination/_pagination.scss
- common/components/pagination/pagination.yaml
- common/components/pagination/template.test.js
Add a modifier to the pagination component to allow it to be split across the container element.
Also includes a tidy up to the examples. Examples should only show visual changes. Custom options are document in the yaml files and should be tested within creating visual examples that will be rendered in the component explorer.
This allows pagination to be displayed on either side of the container
element and will be used to pagination results in a collection.
<kbd>![image](https://user-images.githubusercontent.com/3327997/103294355-06354600-49f2-11eb-8b50-e9baaa9aa893.png)</kbd>
[**DEMO**](https://booksecuremove-pr-1202.herokuapp.com/components/pagination)
> chore: Add support for split pagination modifier

- app/README.md
- app/allocations/index.js
- app/moves/constants.js
- app/population/index.js
- common/controllers/collection/render-as-cards.js
- common/controllers/collection/render-as-cards.test.js
- common/controllers/collection/render-as-table.js
- common/middleware/collection/index.js
- common/middleware/collection/set-date-pagination.js
- common/middleware/collection/set-date-pagination.test.js
- common/templates/layouts/collection.njk
This change makes the date pagination used for rendering resources
within a collection specific to the type of pagination it is - date.
There is some future work to introduce pagination to cycle through
pages so this separation will allow that work to be introduced more
easily.
> refactor: Rename pagination to be date specific

- common/parsers/index.test.js
This change moves the variables so that they are set within mochas test
blocks and will therefore use the mocked dates correctly.
The expected dates for these tests were set outside the test blocks
which means they don't use the mock dates used by the tests.
This worked up until we changed year to 2021.
> Set expected dates within test blocks so they use mock dates

- common/controllers/form-wizard/index.js
- common/controllers/form-wizard/index.test.js
- test/e2e/_helpers.js
This change improves the way 422 errors are passed to Sentry.
This change improves the way that the error is sent with the exception
so that more detail, like the source of meta of an error can be seen.
Previously errors were sent as additional data, however, this meant that
only the first two levels of properties could be seen.
| <kbd>![image](https://user-images.githubusercontent.com/3327997/104430066-89c06c80-5586-11eb-8f21-32a7945af945.png)</kbd> | <kbd>![image](https://user-images.githubusercontent.com/3327997/104429917-6990ad80-5586-11eb-986f-c98dc1b8040c.png)</kbd> |
|  | <kbd>![image](https://user-images.githubusercontent.com/3327997/104429831-54b41a00-5586-11eb-93d0-4fcbcd8812e4.png)</kbd> |
> chore: Expand error logging detail in Sentry

- app/moves/constants.js
- app/moves/middleware/set-results.moves.js
- app/moves/middleware/set-results.moves.test.js
- common/presenters/index.js
- common/presenters/moves-by-vehicle.js
- common/presenters/moves-by-vehicle.test.js
- common/services/move.js
- common/services/move.test.js
- common/templates/collection-as-cards.njk
- locales/en/collections.json
- locales/en/default.json
This adds the ability to view the incoming and outgoing dashboards to group moves by the van that the people will be getting on.
Previously groupings were done by destination or pickup location.
This change has been adapted so it still supports the existing view by default. This grouping can currently be seen by changing the query string parameter `group_by`. 
Once we are confident there is sufficient data within production we can either enable this by default or allow users to choose their preferred view.
This change is possible by the supplier's sending the van for each move.
Grouping moves by van allows users within prison reception or police custody suites to better manage their workload. It allows them to know which vans are arriving in which order and who needs to get on them. They …
> [P4-2595] Group moves by vehicle on incoming and outgoing dashboards

- app/allocation/config/cancel.config.js
- app/allocation/config/create.config.js
- app/allocation/config/remove-move.config.js
- app/move/app/cancel/config.js
- app/move/app/review/config.js
- app/move/app/unassign/config.js
- app/population/index.js
- common/middleware/unique-form-wizard.js
- common/middleware/unique-form-wizard.test.js
This change uses the custom form wizard controller as the default
controller for all unique form wizards.
There are some cases where we might not be defining it which can
cause rogue CSRF errors because the CSRF depends on the method
used internally.
> fix: Ensure the form wizard uses the default controller

- app/moves/middleware/redirect-base-url.js
- app/moves/middleware/redirect-base-url.test.js
- common/lib/api-client/auth.js
This uses optional chaining so if the parent object doesn't exist the value will return `undefined` rather
than throw a "Cannot find property" error.
The test for this catch was using the wrong permission name which meant
that it didn't catch the scenario where the current location didn't
exist and the app would through a "Cannot read property" error.
https://sentry.io/organizations/ministryofjustice/issues/2149703392/?project=2014813&query=is%3Aunresolved
> Catch error when redirecting moves without a current location

- common/lib/permissions.js
- common/lib/user.test.js
This adds the ability to create/edit/confirm youth risk assessments
for users with the prison or YOI role.
> chore: Add youth risk assessment permissions to prison role

- common/services/single-request.js
- common/services/single-request.test.js
Use string value for the single requests allocation filter.
The single requests filter should remove moves that are part of
an allocation.
When moving to the `POST` endpoint in the API the frontend needs to
ensure this value is sent as a string instead of a boolean, otherwise
the API won't filter by that value correctly.
| <kbd>![image (1)](https://user-images.githubusercontent.com/3327997/105704111-2cbda280-5f06-11eb-9ecd-f064a8db909b.png)</kbd> | <kbd>![image](https://user-images.githubusercontent.com/3327997/105704117-2e876600-5f06-11eb-92e3-fe17952450c1.png)</kbd> |
> fix: Single requests filter should not return allocations

- app/population/controllers/edit/details.js
- app/population/controllers/edit/details.test.js
Using the [form-wizard lifecycle](https://github.com/UKHomeOffice/passports-form-wizard/wiki/HMPO%20Forms%20Flow.pdf), on the `getValues` method, if the form input is a numeric one, convert it to a string. This reduces the chances of introducing bugs due to type conversions.
In JavaScript the number 0 is falsey, but the string "0" is truthy.
The govuk input uses the value directly when deciding if to display it or not - https://github.com/alphagov/govuk-frontend/blob/master/src/govuk/components/input/template.njk#L51
Unfortunately this means that 0 number values are not displayed. The solution is to turn it into a string before the template is rendered.
- [P4-2629](https://dsdmoj.atlassian.net/browse/P4-2629)
| ![Screenshot_2021-01-27 Change numbers - …
> [P4-2629] Show 0 values in numeric fields

- app/population/controllers/edit/details.js
- app/population/controllers/edit/details.test.js
For some reason in pre-prod there are some population free spaces missing values, which causes the display population details screen to error. I'm not sure what's caused that - perhaps its faulty previous data, (as an error with pre-population would be caught) - but it shouldn't show as an uncaught error on the details page.
This fix will set any missing values to an empty string, which would then require the user to supply a value to pass the validation logic and save the free spaces data.
Commit messages with a `fix` or `feat` type are automatically used to generate the [changelog](ministryofjustice/hmpps-book-secure-move-frontend/blob/master/CHANGELOG.md …
> fix(pmu): Render missing values as empty string

- common/templates/form-wizard.njk
- common/templates/includes/move-summary.njk
Uses a fixed height for the right hand column image.
In some instances the right hand panel will overlap the footer.
This is because the image element doesn't have a fixed height and
before the image has been fully loaded the JavaScript used to pin the
column when scrolling will set the height of the container.
When the image loads in the container is now too small so when scrolling
down or resizing the browser window, causing the column to stack,
will make the content overlap the following elements like the footer.
- [P4-XXXX]()
| <kbd>![image](https://user-images.githubusercontent.com/3327997/106732858-1c45b000-6609-11eb-80b7-71832b84d888.png)</kbd> | <kbd>![image](https://user-images.githubusercontent.com/3327997/106732015-14394080-6608-11eb-874a-26 …
> fix: Prevent right hand panel overlapping footer content

- app/move/middleware.js
- common/lib/populate-resources.js
- common/lib/populate-resources.test.js
**This is a temporary fix to remove the lookup for missing resources
from the frontend.**
It replaces the population loop with Sentry logging for missing resources within the events structure.
Currently the API doesn't return the full "eventable" resource within
the `included` property of the response payload. This means that the
frontend API client can't deserialize this resource.
Code was implemented to do this extra loading from the frontend and
to loop over each eventable to try and get that resource and deserialize
it.
This has caused some unexpected infinite looping in production so for
now this population is being removed and replaced with a Sentry warning
so that we can get an idea of scale of missing resources.
It might be better to implement this retrieval directly on the API …
> fix: Prevent loop when accessing the timeline

- .github/dependabot.yml
Add condition to ignore v15 of Node.js.
We're only interesting in even numbers of Node.js that will become LTS variants.
> Ignore v15 of node

- app/person-escort-record/app/confirm/controllers.js
- app/person-escort-record/app/confirm/controllers.test.js
- app/person-escort-record/app/confirm/fields.js
- app/person-escort-record/app/confirm/handover-details.njk
- app/person-escort-record/app/confirm/steps.js
- app/person-escort-record/views/print-record.njk
- common/controllers/framework/confirm-assessment.js
- common/controllers/framework/confirm-assessment.test.js
- common/presenters/message-banner/assessment-to-handed-over-banner.js
- common/presenters/message-banner/assessment-to-handed-over-banner.test.js
- common/presenters/message-banner/assessment-to-unconfirmed-banner.js
- common/presenters/message-banner/assessment-to-unconfirmed-banner.test.js
- common/services/person-escort-record.js
- common/services/person-escort-record.test.js
- common/templates/framework-section.njk
- locales/en/actions.json
- locales/en/assessment.json
- locales/en/default.json
- locales/en/fields.json
- locales/en/messages.json
- locales/en/moves.json
- locales/en/person-escort-record.json
- locales/en/validation.json
- test/e2e/pages/confirm-person-escort-record.js
- test/e2e/pages/index.js
- test/e2e/pages/move-detail.js
- test/e2e/person-escort-record.new.test.js
This change amends the confirmation banner and confirmation step to capture handover details.
The handover details are required for us to know who has handed a person over from an establishment. This process can happen after the actual handover has taken place so we have added support for a historic time to be recorded.
- [P4-1892](https://dsdmoj.atlassian.net/browse/P4-1892)
| <kbd>![image](https://user-images.githubusercontent.com/3327997/107514501-a9f14480-6ba1-11eb-86a5-eaca7a025f3f.png)</kbd> | <kbd>![image](https://user-images.githubusercontent.com/3327997/107514318-6ac2f380-6ba1-11eb-85e1-5431ae01d02a.png)</kbd> |
| <kbd>![image](https://user-images.githubusercontent.com/3327997/107514468-9e058280-6ba1-11eb-9e49-454880ceb184.png)</kbd> | …
> [P4-1892] Capture handover details

- common/presenters/message-banner/assessment-to-unconfirmed-banner.js
- common/presenters/message-banner/assessment-to-unconfirmed-banner.test.js
- locales/en/actions.json
- test/e2e/pages/move-detail.js
The completed banner still contained the old wording for confirming a
PER.
This fix updates the copy to be more accurate to the action taking
place.
| <kbd>![image](https://user-images.githubusercontent.com/3327997/107955892-42b70400-6f96-11eb-8949-4d1f9ae6222b.png)</kbd> | <kbd>![image](https://user-images.githubusercontent.com/3327997/107955818-26b36280-6f96-11eb-8ef8-95cc3978732d.png)</kbd> |
> fix: Use correct action content for digital handover in banner

- common/middleware/set-locations.js
- common/middleware/set-locations.test.js
Remove unused app param middleware.
This function is not actually doing anything.
https://expressjs.com/en/4x/api.html#app.param
> Param callback functions are local to the router on which they are
> defined. They are not inherited by mounted apps or routers. Hence, param
> callbacks defined on app will be triggered only by route parameters
> defined on app routes.
We do not define our routes on the main app, therefore this means that this
middleware is never used, as params are never configured at this level.
A similar function will need to be applied at each level of router that
requires it
This was tested by adding a `throw new Error('App Param Check')` and running the E2E tests. There were no failures, and no entries in the log files, so this function is not being used.
- [P4-XXXX]() …
> refactor: Remove unused app param middleware

- app/allocations/index.js
- app/allocations/middleware/set-body.allocations.js
- app/moves/index.js
- app/moves/middleware/set-body.moves.js
- app/moves/middleware/set-body.moves.test.js
- app/moves/middleware/set-from-location.js
- app/moves/middleware/set-from-location.test.js
- app/moves/middleware/set-results.moves.js
- app/moves/middleware/set-results.moves.test.js
- app/population/index.js
- app/population/middleware/set-breadcrumb.js
- app/population/middleware/set-breadcrumb.test.js
- app/population/middleware/set-location-free-spaces.js
- app/population/middleware/set-location-free-spaces.test.js
- app/population/middleware/set-population.js
- app/population/middleware/set-population.test.js
- common/controllers/collection/render-as-cards.js
- common/controllers/collection/render-as-cards.test.js
- common/middleware/errors.js
- common/middleware/errors.test.js
- common/middleware/sentry-enrich-scope.js
- common/middleware/set-location.js
- common/middleware/set-location.test.js
- common/templates/layouts/collection.njk
- server.js
- test/e2e/moves.outgoing.multiple.test.js
- test/e2e/pages/page.js
Param middleware can only be applied to routes that specify the param.
This sets `req.location` based off the session, and overrides it if specified by the location from `params`. This `req.location` is then used for the majority of the app, baring a few specific instances where the session location is used.
This then allows moves, allocations and singles requests to be viewed that are not the currently selected location. In order to protect the user from mistakenly creating a move from the wrong location, if the currently selected location and the currently viewed location are different, the `create a move` button is hidden.
- [P4-XXXX]()
|  ![Screenshot_2021-02-10 Outgoing moves for Wednesday 10 Feb 2021 …
> fix: Use location from params on all specified routes

- common/presenters/message-banner/assessment-to-unconfirmed-banner.js
- common/presenters/message-banner/assessment-to-unconfirmed-banner.test.js
- locales/en/messages.json
This updates the content key to ensure that the correct content is
displayed for cancelled moves with an incomplete PER.
The key was previously dynamic which mean if the PER was not complete
when cancelled it wouldn't find the content.
This fixes it by hard coding that key and updating the content to
explain this further scenario.
- [P4-2679](https://dsdmoj.atlassian.net/browse/P4-2679)
| <kbd>![image](https://user-images.githubusercontent.com/3327997/108707264-ab0e6400-7507-11eb-87e9-3719c71b7d91.png)</kbd> | <kbd>![image](https://user-images.githubusercontent.com/3327997/108707208-9b8f1b00-7507-11eb-9e4f-041524535669.png)</kbd> |
> [P4-2679] Ensure uneditable PER message is correct for cancelled moves

- app/move/app/new/controllers/personal-details.js
- app/move/app/new/controllers/personal-details.test.js
- app/move/app/new/controllers/save.js
- app/move/app/new/controllers/save.test.js
- app/move/controllers/update/personal-details.test.js
- common/services/person.js
- common/services/person.test.js
This change adds some extra logic around to cater for this scenario.
It also caters for a scenario where a person is selected using the
person lookup, but then the user decides to create a new person instead.
In the instance this does still occur we will now be capturing the move ID for the move
that was created and also the expected profile ID.
We have seen a number of errors in Sentry where a profile can't
be updated because it is "missing a Person ID".
Some investigation allowed this error to be re-created when going back
to the personal details page and making a change during the move creation
journey.
- https://sentry.io/organizations/ministryofjustice/issues/2179979853
> fix: Improve missing person ID error when creating a move

- common/lib/populate-resources.js
This changes wraps this warning with a check to ensure there are
missing resources before throwing the warning to Sentry.
Currently we are throwing a sentry warning each time we try and
populate the resources for the events timeline.
In actual fact we only care about the instances when there are missing
resources.
- https://sentry.io/organizations/ministryofjustice/issues/2196140978
> fix: Reduce Sentry warnings for missing resources to correct instances

- app/allocation/config/create.config.js
- app/allocation/index.js
- app/move/app/new/config.js
- app/move/app/new/controllers/save.js
- app/move/app/new/controllers/save.test.js
- app/move/app/new/index.js
- server.js
- test/e2e/move.new.police.test.js
- test/e2e/move.new.prison.test.js
- test/e2e/move.new.stc.test.js
- test/e2e/pages/allocation-criteria.js
- test/e2e/pages/allocation-details.js
- test/e2e/pages/create-move.js
This set of changes adds support to create moves and allocations within the same session using multiple tabs.
It uses the existing unique form wizard to create a new wizard for each journey. This prevents journeys being reset when a new one is opened in a new tab.
The Form Wizard that is used to power a lot of the form journeys was original designed to only support one journey and session at a time.
However, as our system is a repeat use system we have started to see errors where the journey is missing pre-requisite steps.
The assumption based on the data from Sentry is that users are using multiple tabs to try and complete multiple moves at the same time. This behaviour makes sense when you think of how people want to use this system.
- …
> Allow multiple moves and allocation to be created at the same time

- app/locations/controllers.js
- app/locations/controllers.test.js
Using the lodash uniqBy method to create a unique list of objects.
The previous method did not quite uniqe list.
- [P4-2639]()
> fix: Remove duplicates from CDM locations list

- app/move/app/new/controllers/save.js
- app/move/app/new/controllers/save.test.js
This logging was introduced to try and debug when a move was trying to
be created without a person ID.
However, it seems the whole profile is missing so this change
adjusts the logging to not output the value if it doesn't exist.
Fixes BOOK-A-SECURE-MOVE-FRONTEND-3J
- https://sentry.io/organizations/ministryofjustice/issues/2251754356/
> fix: Don't assume property exists when logging profile error

- common/lib/api-client/middleware/request.js
- common/lib/api-client/middleware/request.test.js
- common/middleware/errors.js
- common/middleware/errors.test.js
This creates some extra Sentry logging when the API returns with timeouts. It adds the URL that timed out to the Sentry breadcrumb so that we can determine what URL the frontend thinks failed.
It also includes a clean up to errors to remove certain properties before they are logged to stdout.
We see a large number of timeouts and it is sometimes hard to tie the frontend and API together in these instances. With this change it should help us see more specifically which URLs the errors are occurring on, and along with the transaction ID verify if the API did take longer than the timeout or not.
- [P4-XXXX]()
> Create extra logging around timeouts

- app/move/app/new/controllers/document.test.js
- common/controllers/form-wizard/index.js
- common/controllers/form-wizard/index.test.js
This changes adds the journey details to the Sentry error when it
is triggered from within the Form Wizard.
In some instances its hard to debug what steps as user has taken
to get to that error.
This change will allow us to see the exact steps a user has accessed
during that journey. This should aid in debugging some of these errors.
<kbd>![image](https://user-images.githubusercontent.com/3327997/111470889-37cfca80-8720-11eb-8680-1720a3db57d1.png)</kbd>
> Increase logging around Form Wizard errors

- .circleci/config.yml
Channel name was wrong and slack hook on fail didn't work.
> refactor: Fix slack channel name

- common/lib/permissions.js
- common/lib/user.test.js
- common/presenters/assessment-print-button.js
- common/presenters/assessment-print-button.test.js
- common/presenters/message-banner/assessment-to-confirmed-banner.js
- common/presenters/message-banner/assessment-to-confirmed-banner.test.js
- common/presenters/message-banner/assessment-to-handed-over-banner.js
- common/presenters/message-banner/assessment-to-handed-over-banner.test.js
- common/presenters/message-banner/assessment-to-unconfirmed-banner.js
- common/presenters/message-banner/assessment-to-unconfirmed-banner.test.js
- common/presenters/message-banner/move-to-message-banner-component.js
- common/presenters/message-banner/move-to-message-banner-component.test.js
Two new permissions have been added `person_escort_record:print` and `youth_risk_assessment:print`, this allows us to pick which roles can print the respective forms.
It was requested that we remove the `print` button on PERs for court users due to security concerns.
- [P4-2719]()
summary of changes and that …
> [P4-2719] Hide print PER button for court role

- test/e2e/pages/page.js
Location selection in e2e now clicks the inactive locations detail component prior to clicking a location.
When I added the code for inactive locations, this e2e test didn't fail because it selects a random location, we were unlucky enough that no inactive locations were selected, so the e2e tests didn't fail and this went by undetected.
Clicking the inactive locations detail component first will make the inactive locations visible, which means the tests won't fail anymore.
- [P4-2637](https://dsdmoj.atlassian.net/browse/P4-2637) …
> [P4-2637] Fix inactive locations breaking e2e test

- common/lib/api-client/auth.js
- common/lib/api-client/auth.test.js
When the auth fails, the (internal) promise is rejected without being
cleared. This means the next time the code is executed, the Promise will
automatically reject.
By clearing the Promise (and other auth token values), the next request
will have a fresh Promise to resolve or reject as per the server
response
Unauthenticated requests are held while waiting for an auth token, if the auth fails, then all requests currently in flight will fail. To fix this issue would require per user auth tokens, see notes below.
When dealing with auth in `book-a-secure-move`, it is important to remember that user authentication happens via the auth service, and that the server is separately authenticated client for the backend api. This means that one api auth token is shared between all requests on the …
> fix: Don't cache failed authentication

- common/presenters/message-banner/assessment-to-unconfirmed-banner.js
- common/presenters/message-banner/assessment-to-unconfirmed-banner.test.js
- locales/en/assessment.json
The current behaviour for handing a person over is prevented once
that move has left custody. This follows previous logic tied to marking
an assessment as "confirmed".
However, handover was built to support historic recording of that
information.
This change removes the logic to prevent handover occurring once a move
has left.
This allows users to retrospectively record handover and for them to benefit from pre-filling of assessments.
- [P4-2777](https://dsdmoj.atlassian.net/browse/P4-2777)
| <kbd>![image](https://user-images.githubusercontent.com/3327997/115538166-829ab000-a293-11eb-9a1c-7a7ec0563fb3.png)</kbd> | <kbd>![image](https://user-images.githubusercontent.com/3327997/115537740-086a2b80-a293-11eb-9a1c-bb5058824f07.png)</kbd> |
| …
> [P4-2777] Allow handover to occur after a person has left custody

- .github/dependabot.yml
As of version 4 the module is pure ESM which conflicts with the way
we are importing it.
To prevent needing to rewrite large pieces of the codebase at this stage
it is easier to pin the current version.
> chore: Pin convert-hrtime to version 3

- app/filters/views/filters.njk
- common/controllers/filters.js
- common/controllers/filters.test.js
- common/helpers/url.test.js
- common/lib/request.js
- common/lib/request.test.js
- common/middleware/set-request-filters.test.js
- common/presenters/filters-to-categories-list-component.js
- common/presenters/filters-to-categories-list-component.test.js
- common/presenters/table/object-to-table-head.js
- package-lock.json
- package.json
We currently use two libraries for working with querystrings:
- [qs](https://www.npmjs.com/package/qs)
- [query-string](https://www.npmjs.com/package/query-string)
This change removes the use of `query-string` which was used on fewer
occasions and doesn't currently support parsing of objects which we
use on some occasions.
Having two dependencies doing very similar things seemed unnecessary. The benefit of moving to one will be easier maintenance moving forward too.
[GitHub release notes](https://github.com/ministryofjustice/hmpps-book-secure-move-frontend/releases) during the …
> chore: Remove second query string library

- app/locations/controllers.js
- app/locations/controllers.test.js
- common/presenters/moves-by-location.js
- common/presenters/moves-by-location.test.js
- common/services/reference-data.js
- common/services/reference-data.test.js
- test/fixtures/moves.json
Previously locations were be sorted unix-style which is alphabetically
but case-sensitive. 
This change fixes that sorting in the service closer to the source
of the data rather than at controller level.
Closes #744
This had been addressed at controller level in #1421 
We have a mix of casing for location titles and
ideally need to ensure the alphabetical sorting is not case-sensitive.
- #744
> Ensure locations are sorted correctly

- common/services/person.js
- common/services/person.test.js
The Got request library requires search params to be called using
string format instead of an object.
This fix changes the format to one that is already used elsewhere.
- [BOOK-A-SECURE-MOVE-FRONTEND-4E](https://sentry.io/organizations/ministryofjustice/issues/2393276985/?project=2014813&query=is%3Aunresolved)
> fix: Call timetable filter using string format instead of object

- common/lib/api-client/middleware/got-request.js
- common/lib/api-client/middleware/got-request.test.js
- package-lock.json
- package.json
This changes the [default HTTPS agent](https://www.npmjs.com/package/got#agent) for the Got request library by adding the [keepaliveagent](https://www.npmjs.com/package/agentkeepalive) package.
Quoting [imperva](https://www.imperva.com/learn/performance/http-keep-alive/):
>The HTTP keep-alive header maintains a connection between a client and your server, reducing the time needed to serve files. A persistent connection also reduces the number of TCP and SSL/TLS connection requests, leading to a drop in round trip time (RTT).
- [P4-2709](https://dsdmoj.atlassian.net/browse/P4-2709)
> Add keep alive agent to Got

- app/move/app/edit/controllers/base.js
- app/move/app/edit/controllers/base.test.js
- common/helpers/move/get-update-urls.js
- common/helpers/move/get-update-urls.test.js
- common/lib/api-client/models/accept.js
- common/lib/api-client/models/complete.js
- common/lib/api-client/models/index.js
- common/lib/api-client/models/start.js
- common/presenters/move-to-meta-list-component.js
- common/presenters/move-to-meta-list-component.test.js
- common/services/move.js
- common/services/move.test.js
- test/e2e/_helpers.js
- test/e2e/_move.js
- test/e2e/move.update.police.test.js
- test/e2e/move.update.sch.test.js
- test/e2e/move.update.stc.test.js
This change prevents the edit links from being displayed and the pages being accessible once a move
has left custody.
This also adds methods to support changing the status of a move to the move service. This allows them
to be used by end-to-end tests so that we can fully test this behaviour.
Currently all update links and pages are available and accessible
after a move has left custody. This includes moves in transit and
completed moves.
This information should not be updatable by our users because the
move has already begun in the accepted state. This could lead to a
mismatch in data in our system and what has actually taken place.
- [P4-2818](https://dsdmoj.atlassian.net/browse/P4-2818)
| <kbd>![image](https://user-images.githubusercontent.com/332799 …
> [P4-2818] Prevent editing of completed moves

- locales/en/validation.json
This change removes the double label output.
The `datetime` validation was inserted the label twice, both in the
contents and the contents of the key it references.
- [P4-2820](https://dsdmoj.atlassian.net/browse/P4-2820)
| <kbd>![image](https://user-images.githubusercontent.com/3327997/118263468-3ddaf100-b4ae-11eb-88e4-f130aaa1ad8a.png)</kbd> | <kbd>![image](https://user-images.githubusercontent.com/3327997/118263427-2bf94e00-b4ae-11eb-9cb7-1de23ed006ca.png)</kbd> |
> [P4-2820] Remove double label in datetime validation messages

- locales/en/fields.json
- locales/en/moves.json
This updates the wording used to determine if a person is serving
their sentence within the Secure Youth Estate or not.
We use this question to decide whether they require a youth risk
assessment and we have seen some instances where this isn't being
answered "yes" if the person is on remand.
In some cases this leads to the incorrect level of assessment being
completed.
- [P4-2843](https://dsdmoj.atlassian.net/browse/P4-2843)
> [P4-2843] Update wording of secure youth estate triage question

- common/middleware/set-primary-navigation.js
- common/middleware/set-primary-navigation.test.js
- config/index.js
This reverts commit 1397d9992d5fb4c7bf2acec3f7aaadfd7e769cd1.
Which removes the feature flag created for releasing the population dashboard.
This feature has been live in all environments so we can now remove the feature flag.
> chore: Remove population dashboard feature flag

- common/assets/scss/overrides/_moj-frontend.scss
- locales/en/actions.json
This change tweaks the styling of the organisation switcher component
to bring it more inline with the wider HMPPS services.
It moves the action from the right to inline, next to the current
location.
We want users to have a seamless experience when navigating between services 
within the HMPPS estate. So making generic components like this visually appear the
same will help this experience.
- [P4-2783](https://dsdmoj.atlassian.net/browse/P4-2783)
| <kbd>![image](https://user-images.githubusercontent.com/3327997/118635666-c10c8780-b7cb-11eb-8c10-3dd37c3197f6.png)</kbd> | <kbd>![image](https://user-images.githubusercontent.com/3327997/118635593-a803d680-b7cb-11eb-9037-41d99ba3cd11.png)</kbd> |
> [P4-2783] Bring organisation switcher inline with wider HMPPS estate

- locales/en/events.json
This change updates the property used to display the location in
some of the journey events.
Previously it was always using the to location but in some instances
the event will be recording the arrival at the from location.
- [P4-2890](https://dsdmoj.atlassian.net/browse/P4-2890)
| <kbd>![image](https://user-images.githubusercontent.com/3327997/118981105-e804be00-b971-11eb-934e-8110afc4174a.png)</kbd> | <kbd>![image](https://user-images.githubusercontent.com/3327997/118981010-cc99b300-b971-11eb-85f3-66896ea71509.png)</kbd> |
> [P4-2890] Use correct location property for journey events

- webpack.config.js
This change corrects the way assets are loaded and moves the optimiser
inline to ensure assets are optimised correctly.
During a recent change the assets started to become inlined which
prevented them from displaying correctly.
| <kbd>![image](https://user-images.githubusercontent.com/3327997/119114211-daa50d80-ba1d-11eb-9ac2-032fa4c93275.png)</kbd> | <kbd>![image](https://user-images.githubusercontent.com/3327997/119113455-070c5a00-ba1d-11eb-9e7e-e31a527c599e.png)</kbd> |
> Load image assets correctly

- common/lib/api-client/middleware/got-errors.js
- common/lib/api-client/middleware/got-errors.test.js
This change updates the error message when the error is a 422 returned
by the API client.
This change updates the error message to include the title from the
first error.
Although an error response can contain multiple errors, in most cases
it is returning a single error.
The main benefit is that it will allow errors within Sentry to be
separated and potentially handled differently in terms of assigning,
ignoring or actioning.
- [P4-2900](https://dsdmoj.atlassian.net/browse/P4-2900)
| <kbd>![image](https://user-images.githubusercontent.com/3327997/119377481-1574a300-bcb5-11eb-89ab-f18e29fd4401.png)</kbd> | <kbd>![image](https://user-images.githubusercontent.com/3327997/119377540-28877300-bcb5-11eb-80cf-5d4ac2705299.png)</kbd> |
Has been tested in the …
> [P4-2900] Update 422 error messages to include error title

- locales/en/events.json
This tweaks the content from the estimated time of arrival events
to remove the location from the heading.
This prevents the label wrapping for locations that have a long name
and also follows the existing pattern of keeping the detail within
the description.
- [P4-2899](https://dsdmoj.atlassian.net/browse/P4-2899)
| <kbd>![image](https://user-images.githubusercontent.com/3327997/120667085-0fd14700-c485-11eb-936f-47739c4d2eea.png)</kbd> | <kbd>![image](https://user-images.githubusercontent.com/3327997/120666830-d13b8c80-c484-11eb-836e-51037927604e.png)</kbd> |
> [P4-2899] Update content for ETA events

- server.js
Make sure sentry doesn't pick up 'ping' endpoint for performance sampling
> chore: Update Sentry perf tracing to ignore ping

- audit-ci.json
- package-lock.json
Fixes 1755 where it affects runtime dependencies (got) and ignores for the dev dependencies for which there is not fix currently present.
> chore: Fix advisory 1755

- app/move/views/view.njk
- locales/en/actions.json
This adds a link to the move detail page to allow a user to see the
journeys if they have access to that feature.
> Enable journeys to be viewed from a move

- app/move/app/view/index.js
- app/move/app/view/middleware/index.js
- app/move/app/view/middleware/locals.warnings.js
- app/move/app/view/middleware/locals.warnings.test.js
- app/move/app/view/views/warnings.njk
- locales/en/assessment.json
This creates a new middleware layer to set the locals required to
display warnings on the warnings tab.
This new set of information is more streamlined than before as it
doesn't try to do any combining of previous warnings.
- [P4-2912](https://dsdmoj.atlassian.net/browse/P4-2912)
| Adult booking request |  |
| <kbd>![image](https://user-images.githubusercontent.com/3327997/123621814-856dd000-d803-11eb-9907-bcc51f398e28.png)</kbd> | <kbd>![image](https://user-images.githubusercontent.com/3327997/123621664-5eaf9980-d803-11eb-9023-bd1c4abb7073.png)</kbd> |
| With started PER |  |
| <kbd>![image](https://user-images.githubusercontent.com/3327997/123621767-78e97780-d803-11eb-84c2-69ab620b3ffd.png)</kbd> | …
> Add warnings tab to new move page design

- common/presenters/move-to-meta-list-component.js
- common/presenters/move-to-meta-list-component.test.js
- test/e2e/_routes.js
- test/e2e/allocation.assign.test.js
- test/e2e/pages/allocation-view.js
- test/e2e/pages/create-move.js
This fixes the check for a person on a profile so that it doesn't error with `null` profiles.
Add end-to-end tests to test the assign/removal journeys for allocations.
When there is no profile, the deserialized object contains a `null` value which prevents the fallback from being assigned. This caused the panel to error.
This bug wasn't picked up by any tests so some more tests for these journeys have been added.
> Ensure move details handles null profiles correctly

- common/lib/api-client/middleware/got-request.js
- common/lib/api-client/middleware/got-request.test.js
A manual breadcrumb was previously added for errors occuring in the
API client to help debugging. This was required for Axios but GOT
will add the last call.
This is causing duplicates so we can now remove this extra change.
| <kbd>![image](https://user-images.githubusercontent.com/3327997/124456184-52d35280-dd82-11eb-8875-41529505ac6a.png)</kbd> | <kbd>![image](https://user-images.githubusercontent.com/3327997/124456431-95952a80-dd82-11eb-84d8-8d6717707408.png)</kbd> |
> Remove additional breadcrumb from API client error handling

- common/lib/api-client/middleware/got-request.js
- common/lib/api-client/middleware/got-request.test.js
The API sometimes returns Bad Gateway or Gateway timeout errors.
In those instances, to prevent the request ending on the first attempt,
enabling a retry may avoid these errors for users.
- [BOOK-A-SECURE-MOVE-FRONTEND-4T](https://sentry.io/organizations/ministryofjustice/issues/2422455305/?project=2014813&query=is%3Aunresolved&statsPeriod=14d)
> Retry 502 and 504 errors on the API

- common/middleware/set-location-items.js
- common/middleware/set-location-items.test.js
- common/services/reference-data.js
- common/services/reference-data.test.js
- test/e2e/_helpers.js
Rather than making an API call for each location type and combining the results, we can now make a single API with all of the location types.
This avoids making multiple unnecessary calls to the API.
Closes #1028 
> Avoid multiple API calls for location types

- common/services/user.js
- common/services/user.test.js
This follows on from https://github.com/ministryofjustice/hmpps-book-secure-move-frontend/pull/1790 to add more information around missing location errors. We hypothesis that perhaps the reason the user has no locations is because the auth source was unable to be determined.
By warning in this situation we're hoping to be able to figure out in more detail what's going on.
- [P4-2975](https://dsdmoj.atlassian.net/browse/P4-2975)
> Warn when the auth source cannot be determined

- app/auth/middleware.js
- app/auth/middleware.test.js
- app/locations/controllers.js
- app/locations/controllers.test.js
- app/locations/index.js
- app/locations/middleware.js
- app/locations/middleware.test.js
- common/services/user.js
- common/services/user.test.js
We now populate the locations for supply users when the session is generated, rather than when they visit the locations page.
We think that supplier users are losing their locations when their authentication session needs regenerating because they don't visit the locations page.
- [P4-2975](https://dsdmoj.atlassian.net/browse/P4-2975)
> Ensure supplier user locations aren't cleared out

- app/auth/middleware.js
- app/auth/middleware.test.js
- app/tools/controllers.js
- app/tools/controllers.test.js
- common/lib/permissions.js
- common/lib/permissions.test.js
- common/lib/user.js
- common/lib/user.test.js
- common/services/user.js
- common/services/user.test.js
This refactors how locations are fetched for users (following #1799) and various other parts of the authentication and user middleware. The refactor is relatively large, but the underlying behaviour should be pretty much unchanged, and we're able to remove around 150 lines of code :smile:. Worth reviewing commit by commit!
This is to avoid unnecessarily fetching locations for supplier users which are then not used. It should also make the code related to user authentication and fetching easier to follow and understand.
Closes #1805
> Avoid fetching unnecessary locations for supplier locations

- common/assets/scss/components/_all.scss
- common/components/identity-bar/_identity-bar.scss
- common/components/identity-bar/identity-bar.yaml
- common/components/identity-bar/macro.njk
- common/components/identity-bar/template.njk
- common/components/identity-bar/template.test.js
- common/templates/layouts/base.njk
This creates a new component to display the summary information for
a move or person page.
[**COMPONENT EXAMPLE**](https://booksecuremove-pr-1832.herokuapp.com/components/identity-bar)
This component will be used by the new layouts for the move and person pages.
- [P4-2908](https://dsdmoj.atlassian.net/browse/P4-2908)
<kbd>![image](https://user-images.githubusercontent.com/3327997/126401736-5b8cd1ff-b6ca-44ca-ac71-49f79c3aae23.png)</kbd>
<kbd>![image](https://user-images.githubusercontent.com/3327997/126401756-25ef227f-11a5-4bef-9b57-d98db76bc32a.png)</kbd>
> [P4-2908] Create new identity bar component

- app/move/app/view/index.js
- app/move/app/view/middleware/index.js
- app/move/app/view/middleware/locals.identity-bar.js
- app/move/app/view/middleware/locals.identity-bar.test.js
- app/move/app/view/views/_layout.njk
- common/assets/javascripts/application.js
- common/assets/scss/overrides/_positioning.scss
- common/components/card/_card.scss
- locales/en/default.json
- locales/en/moves.json
- package-lock.json
- package.json
This adds the new identity bar component to the move page redesign.
[**DEMO**](https://booksecuremove-pr-1833.herokuapp.com/move/cc721283-e508-4635-ad9b-7f8fc80187b0/beta/warnings)
This component will be re-used by both the new move page and the person page.
- [P4-2908](https://dsdmoj.atlassian.net/browse/P4-2908)
| <kbd>![image](https://user-images.githubusercontent.com/3327997/126404036-198e8bc4-375b-4983-8b16-6643fabcca4f.png)</kbd> | <kbd>![image](https://user-images.githubusercontent.com/3327997/126403824-3346fe08-7e81-40f7-a32c-42c9bd3fc40b.png)</kbd> |
| <kbd>![image](https://user-images.githubusercontent.com/3327997/126403798-5a9bc163-3e34-48d1-bf01-2116a8599f90.png)</kbd> | <kbd>![image](https://user-images.githubusercontent.com/3327997/126403 …
> [P4-2908] Add identity bar to new move page design

- common/middleware/set-location.js
- common/middleware/set-location.test.js
- server.js
This reverts commit a9f1f53.
We've solved the bug which caused us to introduce these warnings and now we're getting them appearing for legitimate cases, so we can stop sending them to Sentry.
> Revert Sentry warnings for a missing location

- .env.example
This adds a few more useful environment variables that need to be set to run the app, re-orders and groups them into sections, and documents where to get a suitable value for a few of them.
Specifically I've removed "v1" from API_PATH as this is determined from API_VERSION now, and I've set it to a meaningful value.
> docs: Improve .env.example defaults

- common/lib/api-client/transformers/transform-resource.js
- common/lib/api-client/transformers/transform-resource.test.js
Currently devour, the JSON:API client will build a cached of
deserialized resources. We have added a transformation layer to help
with certain things the frontend requires for these resources.
However, if an error occurs, the cache remains in tact which will
mean that in some cases, on a refresh of the page the app will use
the cached version.
This can lead to some unexpected renders so this fix calls the `clear()`
method on the cache to ensure on the next request it will begin again
from the start.
| <kbd>![before](https://user-images.githubusercontent.com/3327997/127046342-a88ffdb1-94a1-48a5-9238-527061e6f2ee.gif)</kbd> | <kbd>![after](https://user-images.githubusercontent.com/3327997/127046184-e7a07ea4-0913-4c6d-aa45-8a8f6b2b557e.gif)</kbd> |
Has …
> fix: Ensure cache is cleared on errors during deserialization

- app/move/app/edit/controllers/move-details.js
- app/move/app/edit/controllers/move-details.test.js
- common/presenters/move-to-meta-list-component.js
- common/presenters/move-to-meta-list-component.test.js
- common/presenters/move-to-summary-list-component.js
- common/presenters/move-to-summary-list-component.test.js
- locales/en/fields.json
This updates the presenters where a destination is shown as well
as the move details edit step.
Previously prison recall moves were created without a destination (or
`to_location`).
So most of the logic on the frontend was driven just by `move_type`.
However, now suppliers are updating the API with the actual end
destination we need to adapt the logic on the frontend for both
rendering and editing to cater for scenarios where `prison_recall`
moves have a `to_location`.
- [P4-3026](https://dsdmoj.atlassian.net/browse/P4-3026)
- [BOOK-A-SECURE-MOVE-FRONTEND-55](https://sentry.io/organizations/ministryofjustice/issues/2494793865/?project=2014813&query=is%3Aignored&statsPeriod=14d)
| <kbd>![image](https://user-images.githubusercontent.com/3327997/127349575 …
> [P4-3026] Support prison recall moves that also have a destination

- app/move/app/view/views/_layout.njk
- app/move/views/timeline.njk
- app/move/views/view.njk
- common/templates/includes/tabs.njk
This refactors how tabs are rendered so there's a common template we can use in as many views as we like. We can't, unfortunately, use the component provided by `govuk-frontend` as it expects all the panels to be rendered at the same time, and then JS is used to switch between the tabs.
I've made this change ahead of needing to use the tabs template for the new profile page, so I decided to split it out into its own PR.
> Refactor tab templates

- server.js
This reduces the number of traces we record in Sentry, to avoid hitting rate limits. It also sends all traces to Sentry, rather than not just production.
See individual commits for more details on the changes.
Related to https://github.com/ministryofjustice/hmpps-book-secure-move-api/pull/1529
> Improve Sentry performance tracing

- server.js
This creates 2 new routes to intentionally trigger an error when
accessing a property of `null`.
This change should be reverted once this problem has been resolved.
We have seen an [error in production](https://github.com/ministryofjustice/hmpps-book-secure-move-frontend/pull/1875) but it was not captured in
Sentry. In order to rule out anything to do with limits or new errors
not being captured this change adds a way to throw a similar error.
- [P4-XXXX]()
> chore: Create temporary error routes to debug Sentry

- config/index.js
- server.js
This adds an optional environment variable (`SENTRY_DEBUG`) which can be set to `true` and will turn on Sentry debugging. This allows us to investigate why issues might not be appearing in Sentry.
It's not good practice to set this in production for long periods of time, but it doesn't pose any risk of leaking information.
See https://docs.sentry.io/platforms/javascript/configuration/options/#debug for more information on the option.
> Make it possible to debug Sentry

- server.js
This partially reverts a9f1f53 to stop sending location information to Sentry. We've discovered that Sentry errors triggered from members of our team have so many locations that the payload is too big to be accepted by Sentry, so we get 413 errors and no issue appearing in Sentry.
We only added this extra information to debug a separate issue which has since been fixed, so I think we can remove it. If we ever need it back again we should think about only exporting the IDs of the locations rather than the whole object.
I've also reverted https://github.com/ministryofjustice/hmpps-book-secure-move-frontend/commit/522bd18c413da60ee2c5bd7d752f8a7b5d7397cc because I'm very confident this is the problem, but if we want to keep them, I'm okay with that too.
> Don't collect locations in Sentry issues

- common/presenters/journeys-to-meta-list-component.js
- common/presenters/journeys-to-meta-list-component.test.js
- locales/en/moves.json
This change ensures the presenter doesn't error when missing a vehicle
or when the vehicle value is set to `null`.
It also adds fallback text for when there is no vehicle.
We don't need to do the same for `from_location` and `to_location`
as the API will not accept a journey without these values.
fixes BOOK-A-SECURE-MOVE-FRONTEND-51
When this code was first implemented it was using destructuring for
vehicle fallback.
But in the cases where a vehicle doesn't exist in the API it can
return a value of `null` which prevents the fallback object from being
set as the value.
This meant that the rest of the presenter would error trying to access
properties of a `null` value.
- [BOOK-A-SECURE-MOVE-FRONTEND-51](https://sentry.io/organizations/ministryofjustice/issues/2443987548/?project=2014813&quer …
> fix: Prevent journeys without a vehicle throwing an error

- locales/en/events.json
At the moment, when a vehicle changes in a journey we show the registration number of the journey, rather than of the event. This means that if a vehicle changes twice in one journey the previous events start showing the incorrect information.
https://github.com/ministryofjustice/hmpps-book-secure-move-api/blob/d61bd961b1df994526bb3d6204916df51a309af7/app/models/generic_event/journey_change_vehicle.rb#L3 is where the fields on the event are defined.
[Jira Ticket](https://dsdmoj.atlassian.net/browse/P4-2989)
> fix: Display correct vehicle registration in events

- package-lock.json
This runs the `npm audit fix` command to update some of the
app dependencies that contain vulnerabilities.
> Update deps using npm audit

- app/move/app/view/controllers/index.js
- app/move/app/view/controllers/render-assessments.js
- app/move/app/view/controllers/render-details.js
- app/move/app/view/controllers/render-details.test.js
- app/move/app/view/index.js
- app/move/app/view/middleware/index.js
- app/move/app/view/middleware/locals.move-details.js
- app/move/app/view/middleware/locals.move-details.test.js
- app/move/app/view/middleware/locals.tabs.js
- app/move/app/view/middleware/locals.tabs.test.js
- app/move/app/view/middleware/locals.urls.js
- app/move/app/view/middleware/locals.urls.test.js
- app/move/app/view/views/_layout.njk
- app/move/app/view/views/details.njk
- app/move/app/view/views/timeline.njk
- app/move/app/view/views/warnings.njk
- common/templates/includes/tabs.njk
- locales/en/actions.json
- locales/en/moves.json
This contains changes to rename the "Assessments" tab to "Details" as well as reducing the links in the move summary side panel.
During research the "Assessments" tab didn't test so well with a task list. Users also struggled finding any of the move information or changing any of it.
These changes bring the move information up a level to one of the tabs and provide a single call to action from the move summary panel to both view or change any of that information.
(Details tab is yet to be built out)
| <kbd>![image](https://user-images.githubusercontent.com/3327997/129946447-28d98ef0-a485-4175-82f5-46ffcd24996d.png)</kbd> | <kbd>![image](https://user-images.githubusercontent.com/3327997/129946272-3c01a0fb-d39c-4f93-85d8-82edce48114e.png)</kbd> |
| …
> Swap individual links in move summary for single link

- common/services/move.js
- common/services/move.test.js
This includes the journey location information (to and from location) in the timeline events for the moves. We need this because the timeline events sometimes contain references to journeys which are cancelled, and therefore we have no way of including the `to_location` and `from_location` fields of those journeys. This means the timeline view on the frontend is sometimes missing information (this is the case where a journey has a different `to_location` or `from_location` of the move and therefore isn't included).
This might have a performance impact on the page, but we can monitor closely if this becomes a problem. I don't expect many moves to have multiple journeys.
Depends on https://github.com/ministryofjustice/hmpps-book-secure-move-api/pull/1554.
[Jira …
> fix: Include journey information in move events

- app/move/app/view/middleware/locals.warnings.js
- app/move/app/view/middleware/locals.warnings.test.js
- app/move/app/view/views/warnings.njk
- app/move/index.js
- app/move/middleware.js
- app/move/middleware.test.js
- common/components/message/message.yaml
- common/components/message/template.njk
- common/components/message/template.test.js
- locales/en/assessment.json
This changes the logic around the warnings tab for the new profile page design. When there is no Person Escort Record (PER) it won't show any warnings, instead a message will be shown saying what needs to happen.
Once the PER has been started and sections become complete, it will show the warnings for this information.
When people use this section to determine how a person should be moved they should use the latest information from the PER. Therefore, we have reduced the logic around this section to only show once the PER has been started and sections become complete.
<kbd><img width="914" alt="Screenshot 2021-08-20 at 16 22 57" src="https://user-images.githubusercontent.com/3327997/130248574-ab62fdff-1ce3-452c-83ec-b576fdcdf520.png"></kbd>
<kbd><img width="617" alt="Screenshot 2021-08-20 …
> Only show warnings once the Person Escort Record has been started

- common/components/panel/_panel.scss
- common/components/panel/panel.yaml
- common/components/panel/template.njk
- common/components/panel/template.test.js
- common/presenters/assessment-category-to-panel-component.js
- common/presenters/assessment-category-to-panel-component.test.js
- common/presenters/framework-section-to-panel-list.js
- common/presenters/framework-section-to-panel-list.test.js
This adds a change to allow panels to be focusable, specifically in the scenario where they are used to display warnings
such as risk and health information.
It also includes a change to offset the scroll position when these elements are clicked so that content isn't hidden by placing
them at the top of the window.
The alert badges can be clicked either from the listing pages (incoming/outgoing) or the header of a move. Currently there is not focus which means it visually hard to see which has been selected, and also will prevent content being read by assistive technology.
In some cases, like the framework steps a form field will also be highlighted, but the question and hint text can sometimes
be visually out of view.
| …
> Focus on warnings when clicked using anchors

- common/services/allocation.js
This uses the safe navigation operator to ensure that `result.moves.length` doesn't raise a `TypeError` when `result.moves` is undefined. This appears to be happening occasionally as we've received a Sentry issue for it: https://sentry.io/organizations/ministryofjustice/issues/2582039703/
It looks like the code is only temporary anyway since there's a TODO block around it, but since we're getting Sentry issues for it today I figure there's no harm in fixing it now.
> fix: Cope with result.moves being undefined

- locales/en/statuses.json
The `sending_establishment_failed_to_fill_allocation` cancellation reason was actually listed as `unfilled` in the locale file, which meant this wasn't being rendered on the frontend when it was the case.
I've also re-order the cancellation reasons to match the ordering in the API so it's slightly easier to match up.
[Jira Ticket](https://dsdmoj.atlassian.net/browse/P4-3120)
> fix: Fix missing allocation cancelled description

- common/lib/permissions.js
- common/lib/permissions.test.js
This isn't an action that can be performed on youth risk assessments, so there's no reason to have a permission for it.
By removing this permission it should avoid the "Print Youth Risk Assessment" links from appearing on the frontend as they only render if the user has the permission. This fixes a bug where pressing that link would take the user to a 404 page.
[Jira Ticket](https://dsdmoj.atlassian.net/browse/P4-3137)
> Remove youth_risk_assessment:print permission

- app/person/middleware/locals.tabs.js
- app/person/middleware/locals.tabs.test.js
- common/presenters/moves-to-table-component.js
- common/presenters/moves-to-table-component.test.js
This hides the moves tab on the profile page for non-CDM users, since they can't access the page anyway. I've also change the tag style to the standard MoJ badge until we're confident on the colours we want.
[Jira Ticket](https://dsdmoj.atlassian.net/browse/P4-3131)
> Hide moves tab for non-CDM users

- app/move/app/new/controllers/person-search-results.js
- app/move/app/new/controllers/person-search-results.test.js
- app/move/app/view/views/warnings.njk
- common/presenters/move-to-card-component.js
- common/presenters/move-to-card-component.test.js
- common/presenters/profile-to-card-component.js
- common/presenters/profile-to-card-component.test.js
- locales/en/assessment.json
- locales/en/messages.json
This makes a few changes to the new move pages following further design refinements. See individual commits for more details.
[Jira Ticket](https://dsdmoj.atlassian.net/browse/P4-3133)
> Move design style tweaks

- common/controllers/framework/framework-section.js
- common/controllers/framework/framework-section.test.js
- common/controllers/framework/framework-step.js
- common/controllers/framework/framework-step.test.js
- common/middleware/framework/set-previous-next-framework-section.js
- common/middleware/framework/set-previous-next-framework-section.test.js
- common/templates/framework-step.njk
This improves the framework button navigation to make it easier for users to complete an entire PER/YRA in one go. Specifically this:
- Removes section summary screens from the end of each section and instead takes users straight to the first question of the next section.
- Removes the ‘Save and continue’ button from the final question screen as this is the end of the framework. Instead this is replaced by the existing ‘Save and return to overview button’.
See individual commits for more details as I had to do some refactoring before making the implementation changes.
[Jira Ticket](https://dsdmoj.atlassian.net/browse/P4-3142)
This is mostly not a visual change, except for the button on the last question.
> Improve framework button navigation

- app/move/app/view/controllers/render-details.js
- app/move/app/view/controllers/render-details.test.js
- app/move/app/view/views/details.njk
- common/components/identity-bar/_identity-bar.scss
- common/components/identity-bar/template.njk
- common/controllers/framework/framework-overview.js
- common/controllers/framework/framework-overview.test.js
- common/presenters/move-to-identity-bar-actions/assessment-actions.js
- common/presenters/move-to-identity-bar-actions/assessment-actions.test.js
- common/presenters/move-to-summary-list-component.js
- common/presenters/move-to-summary-list-component.test.js
- common/templates/framework-overview.njk
- locales/en/fields.json
This improves the journey for how to access parts of an assessment (youth risk assessment and person escort record). Specifically this moves the print button to the overview page, adds a link to the PER in the identity bar and moves the assessment links to a documents section in the details tab.
[Jira Ticket](https://dsdmoj.atlassian.net/browse/P4-3136)
> Improve assessment call to actions

- app/move/app/view/index.js
- app/move/app/view/middleware/locals.warnings.js
- app/move/app/view/middleware/locals.warnings.test.js
- app/move/app/view/views/warnings.njk
- common/presenters/event-to-tag-component.js
- common/presenters/event-to-timeline-panel.js
- common/presenters/event-to-timeline-panel.test.js
- common/presenters/framework-section-to-panel-list.js
- common/presenters/index.js
- common/presenters/move-to-important-events-tag-list-component.js
- common/presenters/move-to-important-events-tag-list-component.test.js
- common/presenters/move-to-in-transit-events-panel-list.js
- common/presenters/move-to-in-transit-events-panel-list.test.js
- locales/en/assessment.json
This adds suppliers incidents to the new move design warnings tab in a similar way to https://github.com/ministryofjustice/hmpps-book-secure-move-frontend/pull/1096 for the old design.
See individual commits for more details.
> Add supplier incidents to warnings tab

- common/middleware/framework/set-breadcrumbs.js
- common/middleware/framework/set-breadcrumbs.test.js
This hides the framework assessment item from the breadcrumbs of a page if the user is performing a handover.
> Hide framework from handover breadcrumbs

- server.js
We're still experiencing a problem where the MoJ Sentry account gets rate limited after a couple of weeks because too many transactions are being reported.
This reduces the sample rate from 25% to 10%.
> chore: Reduce Sentry transaction sample rate

- package-lock.json
- package.json
This includes a fix for missing NOMIS assessment codes for cell share risk assessments.
[Jira Ticket](https://dsdmoj.atlassian.net/browse/P4-3326)
> build: Add latest frameworks package

- common/presenters/move-to-additional-info-list-component.js
- common/presenters/move-to-additional-info-list-component.test.js
This prevents users from inputting HTML and it being output on the page directly. Currently the behaviour of rendering the input as HTML opens up a potential HTML injection vulnerability.
[Jira Ticket](https://dsdmoj.atlassian.net/browse/P4-3204)
> Don't allow HTML in move additional information

- app/move/app/view/middleware/locals.message-banner.js
- app/move/app/view/middleware/locals.message-banner.test.js
This fixes an issue in the message banner where text was wrapping without any right spacing/padding to the surrounding DIV.
[JIRA P4-3135 ](https://dsdmoj.atlassian.net/browse/P4-3135) 
**Old:**
**New:**
> fix: Adding right hand padding to the message banner as there was no  spacing when text was wrapped

- Dockerfile
This should fix an issue where Alpine Linux no longer has a `python` package available and instead requires an explicit version.
See https://github.com/docker-library/docker/issues/240 for more information.
> Explicitly install Python 3 in Docker container

- app/person-escort-record/views/print-record.njk
This feature was added in e7e4f8574da5d7f4af5af423da94cd3791a7a153 but it was accidentally tied to whether a person has a self harm warning, rather than if they require medication during transport. I've fixed it now so the warning shows up during the correct conditions.
We don't have any tests currently which check what is showing in the print PER view in different situations. It requires a further refactor as we should most likely extract sections of this out in to individual components and test those individually. Since this bug is currently live and means the PER print out could be incorrect, I've opted to fix the issue quickly now, and I'll refactor the view later and write comprehensive tests as part of that.
[Jira Ticket](https://dsdmoj.atlassian.net/browse/P4-2731)
> Fix when medication while moving warning is displayed

- Dockerfile
In 841ad36b359aefe10e063d5ec2ef784bff5cb12d I changed the Python package name from `python` to `python3` to fix the package being missing, but actually it looks like the correct solution would have been to change this to `python2` instead.
> Build Docker container with Python 2

- Dockerfile
There appears to be an issue in Alpine 3.14 related to the version of Docker we're using. There's more information about this issue here: https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.14.0#faccessat2
For now, the suggested fix might be to downgrade to the previous version of Alpine Linux. Once the build is working again, we might think about switching to a more familiar Debian base.
> Downgrade to Alpine 3.13

- app/move/app/view/middleware/locals.identity-bar.js
- app/move/app/view/middleware/locals.identity-bar.test.js
- locales/en/moves.json
If a move was in proposed state it would not have a move date.  The original summary header message being displayed expected a date to be present ergo it did not read correctly.
**Before any changes:**
**After (move pending review):**
**After (move reviewed):**
> fix: Fixing wording in identity bar for proposed moves

- common/templates/includes/move-summary.njk
Small change to prevent a (random) blue line from appearing on the allocations pages.  This was being included as part of a person summary being present and in this case there isn't one. [JIRA](https://dsdmoj.atlassian.net/browse/P4-3118)
**Before:**
**After:**
> fix: Removing blue line appearing to the right on allocation pages

- common/templates/framework-section.njk
Removes superfluous 'Back to move' link from the PER.  You can get back to the move via the breadcrumb trail.
**Before:**
**After:**
> fix: Removes superfluous back link from the PER

- common/templates/includes/move-summary.njk
When the personal details have not yet been provided we do not want to show side panel (to avoid clutter). 
**Before:**
**After:**
> fix: Removes the person details side panel when nothing to show

- app/allocation/views/view.njk
- test/e2e/pages/page.js
> fix: Remove style override on cancel allocation banner so uses default style

- package.json
Small chore to the package.json to bring inline with the readme.md.  I was unable to install the application with node 16.13.1 for example.
> fix: Small tweak to package.json to allow greater then or equal to versions of node and npm

- common/controllers/framework/framework-section.js
- common/controllers/framework/framework-section.test.js
- common/templates/framework-section.njk
- package-lock.json
Changes shows the PER section status tag on the individual PER section pages. [JIRA](https://dsdmoj.atlassian.net/browse/P4-3157).
**Before:**
**After:**
> fix: Adds the PER section status tag to the top of section pages

- common/presenters/move-to-meta-list-component.js
- common/presenters/move-to-meta-list-component.test.js
This no longer displays additional information for prison remand moves as this is repeating what is already on screen.
**Before:**
**After:**
> fix: Removes additional info from side panel when prison remand

- app/move/app/view/middleware/locals.message-banner.js
- app/move/app/view/middleware/locals.message-banner.test.js
- common/presenters/message-banner/assessment-to-handed-over-banner.js
- common/presenters/message-banner/assessment-to-handed-over-banner.test.js
- common/presenters/message-banner/move-to-message-banner-component.js
- common/presenters/message-banner/move-to-message-banner-component.test.js
- locales/en/messages.json
- test/e2e/pages/move-detail.js
- test/e2e/person-escort-record.new.test.js
Reverts ministryofjustice/hmpps-book-secure-move-frontend#2182
This has a knock on effect with the old design hence the revert.
> Revert "fix: Changes to remove of handover notification banner, information availble in history of events"

- app/allocation/views/view.njk
- test/e2e/pages/page.js
Reverts ministryofjustice/hmpps-book-secure-move-frontend#2196
Reverting as this impacts the old design and we do not want this.  Will address this in another PR.
> Revert "fix: Remove style override on cancel allocation banner so uses default style"

- app/allocation/controllers/view.js
- app/allocation/controllers/view.test.js
- app/allocation/views/view.njk
You will only see this change on the new design.
**Before: (old design)**
**After: (new design)**
> fix: Remove style override on cancel allocation banner so uses default style on new design

- app/move/app/edit/controllers/move-details.js
- app/move/app/edit/controllers/move-details.test.js
Prior to this change no flash banner was presented to the end user when the to location was changed.  Now the following is displayed to the user upon changing the to location:
> fix: Show the flash banner when the to location is changed on a move

- app/move/app/view/views/_layout.njk
- common/templates/layouts/base.njk
This slightly changes the navigation in the new design on how to get back to the dashboard. This is temporary as it was identified as a blocker for launching the new design, and will be improved in the future.
[Jira Ticket](https://dsdmoj.atlassian.net/browse/P4-3354)
> Patch new design move page navigation

- .circleci/config.yml
- Dockerfile
- README.md
Dockerfile node version has been updated to 16.13.1
So that the frontend portal runs on the latest LTS node version.
- P4-3286
> chore: Bump dockerfile to node 16.13.1

- locales/en/fields.json
- locales/en/statuses.json
This is a new cancellation reason that we're adding to the API to support manual corrections of the data. We're not going to allow users of the frontend to pick this option, but we will need to display it when it's set in the backend.
Depends on https://github.com/ministryofjustice/hmpps-book-secure-move-api/pull/1678.
> Add database correction cancellation reason

- common/presenters/move-to-identity-bar-actions/assessment-actions.js
- common/presenters/move-to-identity-bar-actions/assessment-actions.test.js
It doesn't make sense that the handover can be recorded once a move has been cancelled, so the button shouldn't be visible.
> Hide record handover button if move is cancelled

- app/move/app/cancel/controllers.js
- app/move/app/cancel/controllers.test.js
There is a bug where the move information is not passed to the view on the form to cancel a move, so sentences which rely on this information aren't formatted correctly.
Notably, this affected the title of the page, and the warning message.
> Fix the person name missing on cancel form

- app/move/app/view/middleware/locals.person-summary.js
- app/move/app/view/middleware/locals.person-summary.test.js
- common/templates/includes/person-summary.njk
- locales/en/actions.json
We've spotted an issue with the new move page design where it's no longer possible to change the person details of a person from the move page. This behaviour has been lost from the old design, so we're putting in a quick fix now to allow us to continue with the launch.
> Make it possible to edit personal details in new design

- common/lib/api-client/models/journey.js
- common/presenters/journeys-to-meta-list-component.js
- common/presenters/journeys-to-meta-list-component.test.js
- locales/en/moves.json
This adds the ability to see the journey dates when viewing journeys on a move. This hasn't been designed in particular, but since the view is limited only to CDMs at the moment I think that's okay.
[Jira Ticket](https://dsdmoj.atlassian.net/browse/P4-3337)
> Add journey dates to journeys view

- common/presenters/move-to-identity-bar-actions/assessment-actions.js
- common/presenters/move-to-identity-bar-actions/assessment-actions.test.js
We want to show the button if no handover has occurred, so we need to check the occurred at time of the handover rather than relying just on the state of the assessment.
[Jira Ticket](https://dsdmoj.atlassian.net/browse/P4-3474)
> Correct logic for record handover button

- common/middleware/framework/set-breadcrumbs.js
- common/middleware/framework/set-breadcrumbs.test.js
The breadcrumbs middleware for frameworks (person escort record and youth risk assessment) include an entry for the move itself. We don't need to do this, as the middleware for the move will do this.
[Jira Ticket](https://dsdmoj.atlassian.net/browse/P4-3449)
> Remove duplicate breadcrumb from frameworks

- locales/en/events.json
We'd like to change the heading labels of these events to reflect the fact that they're going to be used by both suppliers and police (for example when a person is held in police custody during a lockout or overnight lodging).
[Jira Ticket](https://dsdmoj.atlassian.net/browse/P4-3335)
> refactor: Change headings of certain events

- .circleci/config.yml
- package-lock.json
We don't need this job as it's covered by GitHub in two places:
- a73e70a7e5bbae3e77577ca5c100e72b52d7defe is used to check the code itself for any security vulnerability.
- Dependabot will check for vulnerable dependencies and automatically open PRs for us.
Removing this job removes the need to read the output of this task in CircleCI and instead we can rely on the graphical features provided by GitHub.
> chore: Remove CircleCI security job

- common/presenters/profile-to-card-component.js
- common/presenters/profile-to-card-component.test.js
It's not useful to include the alt text on this image as it's not a visual description of the image, and instead has the person's name which is already accessible in the heading.
[Jira Ticket](https://dsdmoj.atlassian.net/browse/P4-3492)
> Remove alt text on person image

- common/helpers/field/add-errorlist-to-errors.js
This is sometimes the case, particularly with a radio buttons where there isn't a single element with a single ID. Instead of having a link which doesn't go anywhere, we don't need to have a link.
[Jira Ticket](https://dsdmoj.atlassian.net/browse/P4-3493)
> Handle case when field doesn't have an id

- app/moves/constants.js
- common/templates/framework-overview.njk
We're using strings which expect data to to be passed with them but without actually passing any data. This leads to the placeholder text remaining visible for users.
[Jira Ticket](https://dsdmoj.atlassian.net/browse/P4-3546)
> Fix incorrect use of strings which expect data

- common/presenters/message-banner/assessment-to-handed-over-banner.js
- common/presenters/message-banner/assessment-to-handed-over-banner.test.js
- locales/en/events.json
This improves the design of the handover box and events, when the handover details haven't been provided.
[Jira Ticket](https://dsdmoj.atlassian.net/browse/P4-3546)
> Hide handover placeholder strings

- common/assets/javascripts/application.js
- common/components/footer/footer.js
- common/components/whats-new-banner/template.njk
- common/components/whats-new-banner/whats-new-banner.js
- common/components/whats-new-banner/whats-new-banner.test.js
We have added GA to the banner and footer links to allow us to track user interaction
To track user interaction
- [P4-3459](https://dsdmoj.atlassian.net/browse/P4-3459)
> Add analytics to in-service communication banners and footer links

- .circleci/config.yml
Remove the `Publish release to GitHub` step from circle CI build
> Remove publish release to GitHub step from Circle CI config

- common/lib/api-client/models/journey.js
- locales/en/events.json
This is to make it clearer which journey events are associated with which journeys.
Depends on https://github.com/ministryofjustice/hmpps-book-secure-move-api/pull/1787.
[Jira Ticket](https://dsdmoj.atlassian.net/browse/P4-3345)
> Include journey numbers in events

- common/helpers/events/get-event-classification.js
- common/helpers/events/get-event-classification.test.js
- common/helpers/events/get-header-classes.js
- common/helpers/events/get-header-classes.test.js
- common/lib/api-client/transformers/move.transformer.js
- common/presenters/move-to-in-transit-events-panel-list.js
- locales/en/events.json
We'd like to include these events as important events that happen during a move. Since these events are not classified as incidents, the code had to be changed slightly to support these.
The code is a little messy, as it doesn't actually rely on the important events field as its returned from the API, but I think refactoring this is for a different time.
[Jira Ticket](https://dsdmoj.atlassian.net/browse/P4-3519)
> Include property change events in move overview

- common/components/message/template.njk
The `Message` component has been changed to only use a h2 title if there's content to be displayed under it.
This came up in the accessibility audit, the auditors stated: "This text has been marked up as a level 2 heading, and does not provide the purpose of a heading, and does not introduce any content or information. For users of screen reading assistive technologies, this can be misleading when not encountering any information after the heading."
- P4-3548
No visible changes.
> feat: Fix headings used for styling

- common/helpers/events/get-event-classification.js
- common/helpers/events/get-event-classification.test.js
- locales/en/events.json
When an `event_type` is `PersonMoveDeathInCustody` we use the `app-tag--inactive` class instead of the `app-tag--destructive` class
The purpose of this to change the colour of the flag ‘DEATH IN CUSTODY’ from red to grey. This is because it is **NOT** a risk, but rather ‘general information’.
- [P4-3520](https://dsdmoj.atlassian.net/browse/P4-3520)
> Change flag colour of 'DEATH IN CUSTODY' from red to grey

- common/components/add-another/add-another.js
This copies the fix from MoJ Frontend (https://github.com/ministryofjustice/moj-frontend/pull/186) in to our own copy of the library, see details on that original PR for what the issue is and why this fixes it.
Ideally, we wouldn't have customised this component so much that upstream fixes are applied downstream, but for now at least this fixes the bug.
[Jira Ticket](https://dsdmoj.atlassian.net/browse/P4-3549)
> Ensure label is found when adding another

- test/e2e/_helpers.js
When ensuring that e2e move locations don't match, I overlooked the fact that from/to location can be overridden.
> chore: Fix logic around e2e move location matching

- app/move/app/view/index.js
- app/move/app/view/middleware/index.js
- app/move/app/view/middleware/locals.identity-bar-journeys.js
- app/move/app/view/middleware/locals.identity-bar-journeys.test.js
- app/move/app/view/middleware/locals.identity-bar.test.js
- app/move/app/view/middleware/locals.move-details.js
- app/move/app/view/middleware/locals.move-details.test.js
- app/move/app/view/views/_layout.njk
- common/assets/scss/components/_all.scss
- common/assets/scss/components/_lockout-banner.scss
- common/assets/scss/overrides/_all.scss
- common/components/identity-bar/_identity-bar.scss
- common/components/identity-bar/template.njk
- locales/en/moves.json
When a move is locked out we show a prison lockout banner warning message, and we show all the journeys which are not cancelled or rejected to the user.
As a user I want to know where and when a move is stopping overnight for a lockout so that I know the whereabouts of the detainee.
- [P4-3342](https://dsdmoj.atlassian.net/browse/P4-3342)
> Update identity bar at relevant points in the move

- common/presenters/move-to-journeys-summary.js
- common/presenters/move-to-journeys-summary.test.js
This removes any journeys which are cancelled or rejected and doesn't include them when displaying journeys in the identity bar and move details tab.
This was missed in #2375.
> Ensure only active journeys are considered

- app/move/app/view/middleware/locals.move-details.js
- app/move/app/view/middleware/locals.move-details.test.js
- common/components/add-another/add-another.js
- common/helpers/move/get-move-summary.js
- common/helpers/move/get-move-summary.test.js
- common/presenters/move-to-meta-list-component.js
- common/presenters/move-to-meta-list-component.test.js
We now add information to the side panel to inform users where and when a move is stopping overnight for a lockout 
So that as user knows the whereabouts of the detainee throughout the move
- [P4-3343](https://dsdmoj.atlassian.net/browse/P4-3343)
> Update side panel at relevant points in the move

- common/components/framework-response/framework-response.yaml
- common/components/framework-response/template.njk
- common/components/framework-response/template.test.js
- common/helpers/frameworks/responses-to-save-reducer.js
- common/helpers/frameworks/responses-to-save-reducer.test.js
- common/presenters/framework-field-summary-list-row.js
- common/presenters/framework-field-summary-list-row.test.js
Currently we always show a link to amend a framework response if the value is not set, regardless of the assessment status. This causes a problem with optional top-level questions which may not have been responded to by the time the PER is complete. At that point we can't let the user modify the PER though, as the PER cannot be changed once complete.
Related to https://github.com/ministryofjustice/hmpps-book-secure-move-api/pull/1814
[Jira Ticket](https://dsdmoj.atlassian.net/browse/P4-2987)
> Consider assessment status when showing framework responses

- common/services/frameworks.js
- common/services/frameworks.test.js
For single line top level text fields the length ends up being the full length of the page. This looks a little odd, and it's inconsistent with the text area fields. We'd like to change the default so it looks better.
> Reduce default field length

- config/index.js
This changes how the Contentful configuration variables are determined to ensure in a development environment they're not required. Currently, the `.env.example` has them as empty values, but if a user were to follow this, the app wouldn't start.
> Make Contentful optional for development

- common/services/whats-new-content.js
- common/services/whats-new-content.test.js
- common/templates/layouts/base.njk
This ensures the banner is hidden after 2 weeks even if the user doesn't dismiss it. I've also refactored the service a little.
> Hide what's new banner after 2 weeks 

- .circleci/config.yml
Added a step to convert testcafe reports to relative paths.
This needs to happen so that circleci can balance our tests for us (shorter run times)
- P4-3545
> chore: Convert testcafe reports to relative path

- app/move/app/view/middleware/locals.move-details.js
The `some` method only exists for arrays.
[Sentry issue](https://sentry.io/organizations/ministryofjustice/issues/3235426684/)
> Ensure important events is an array

- .circleci/config.yml
- .codeclimate.yml
- README.md
We removed codeclimate a while back, this PR is to remove the last references of it within our circle ci config file and readme.
> Remove references to codeclimate

- common/services/whats-new-content.js
- common/services/whats-new-content.test.js
- server.js
We now have the ability to integrate images into Contenful content via the use of assets
This allows us to show changes via the use of images as well as text
- [P4-3522](https://dsdmoj.atlassian.net/browse/P4-3522)
> Integrate images into Contentful content

- app/police-custody-form/controllers.js
- app/police-custody-form/controllers.test.js
Currently users are taken to the timeline, but we'd like users to end up on the main move page (which ends up on the warnings tab).
> Redirect users to move page after filling in police form

- locales/en/messages.json
As requested by the content designer, we've removed the word "recorded" from the text.
[Jira Ticket](https://dsdmoj.atlassian.net/browse/P4-3509)
> Update wording on handover banner

- locales/en/events.json
This improves the textual content for the handover event as per content designer request. The main difference is that the location of where the handover occurred is now included, as this supports lockouts where there can be more than one handover event.
[Jira Ticket](https://dsdmoj.atlassian.net/browse/P4-3662)
> Improve content for the handover event

- app/move/app/view/middleware/locals.move-details.js
- app/move/app/view/views/_layout.njk
- app/person-escort-record/app/confirm/controllers.js
- app/person-escort-record/app/confirm/controllers.test.js
- app/person-escort-record/app/confirm/handover-details.njk
- common/assets/scss/components/_lockout-banner.scss
- common/controllers/framework/confirm-assessment.js
- common/controllers/framework/confirm-assessment.test.js
- common/lib/api-client/transformers/move.transformer.js
- common/presenters/index.js
- common/services/person-escort-record.js
- locales/en/assessment.json
This updates the record handover form to be used for lockouts. See commits for individual details, but this changes some content on the form when during a lockout, includes the location when recording the handover and shows the record handover button.
[Jira Ticket](https://dsdmoj.atlassian.net/browse/P4-3396)
> Allow handover form to be used for lockouts

- .github/workflows/branch-deploy.yml
This ensures that the pods are restarted with the latest Docker image, as currently the pods aren't updated with a new image if a branch gets changed after the first deployment.
> Restart deployment after branch based apply

- common/presenters/move-to-important-events-tag-list-component.js
These were added accidentally when we started including these events in db2990edad77481b2e34e4274be7ebac6d40c42b and 5532e88971848e0d77ed60174c4624068d851d7a.
> Exclude certain events from tags list

- .github/workflows/branch-deploy.yml
This should hopefully fix the issue where the dependabot PRs branch-based deployment action was failing.
> chore: Fix dependabot PRs not being able to BDD

- locales/en/default.json
Change wording that appears in Overview table when no answer is given.
The empty field text displayed has has changed from 'Reviewed and nothing provided' to 'No answer provided'.
It assumes the user has definitely seen the question and chosen not to answer.
- [P4-3605](https://dsdmoj.atlassian.net/browse/P4-3605)
> fix: Change the wording for optional fields when not answer given

- common/templates/layouts/base.njk
Follow this format for supplying a user_id for universal GA: https://developers.google.com/analytics/devguides/collection/gtagjs/cookies-user-id#set_user_id
> Use Universal Google Analytics Format

- .circleci/config.yml
Staging builds are failing because NPM isn't installed
> chore: Install NPM on build docker step

- .circleci/config.yml
gifsicle's post-install was throwing an error because of missing packages
> chore: Add missing packages

- .github/workflows/dependabot-auto-merge.yml
We have now added a new GitHub action to auto merge any dependabot PR's which are upgrading to either a new `minor` or `patch` version
**Note: This marketplace action does a check to see if the author is dependabot. So this will always pass on non dependabot PRs**
[Link to marketplace action](https://github.com/marketplace/actions/dependabot-auto-merge) 
This will reduce the overhead needed to constantly attend to dependabot PRs each day
- [P4-3721](https://dsdmoj.atlassian.net/browse/P4-3721)
> Add dependabot auto merge action

- common/components/add-another/_add-another.scss
- common/components/add-another/template.njk
Updated the scss styles used on the Remove property button
Note: **This issue is around the `add-another` component, which actually affected all pages where you would add another element to a form**
The old scss stylings caused the button to act in a way which wasn't what we wanted, not allowing the user to remove a property item due to it ghosting.
- [P4-3723](https://dsdmoj.atlassian.net/browse/P4-3723)
> Fix remove property button from ghosting when adding new property element

- .github/branch-deploy/deployment.yml
It's a bit excessive to have 2 pods for branch based deploys
> chore: Reduce branch based deploy pod count to 1

- .github/workflows/branch-deploy-cleanup.yml
- .github/workflows/branch-deploy.yml
Branch based deploys have been changed to use Personal Access Token to create the deployments.
This changed because dependabot opened/closed PRs weren't able perform any deploy actions.
> chore: Swap branch based deploys to use PAT

- common/lib/permissions.js
- common/lib/permissions.test.js
Give PMU users the permission to update a move
So we can allow PMU users to update a moves date
- [P4-3777](https://dsdmoj.atlassian.net/browse/P4-3777)
> Allow Population Managers to change move dates

- app/auth/middleware.js
- app/moves/middleware/set-download-results.moves.js
- app/moves/middleware/set-download-results.moves.test.js
- app/moves/middleware/set-download-results.single-requests.js
- app/moves/middleware/set-download-results.single-requests.test.js
- app/police-custody-form/controllers.js
- common/lib/api-client/rest-client.js
- common/lib/api-client/rest-client.test.js
- common/lib/user.js
- common/lib/user.test.js
- common/services/event.js
- common/services/event.test.js
- common/services/move.js
- common/services/move.test.js
- common/services/reference-data.js
- common/services/reference-data.test.js
- common/services/single-request.js
- common/services/single-request.test.js
- common/services/user.js
- common/services/user.test.js
Multiple functions have been changed to pass `req` through to RestClient.
When a function in RestClient was refactored previously, the instances of it weren't refactored to match, this means that headers weren't correctly being sent to the API, meaning that the created_by of the events aren't being populated.
- P4-3828
> chore: Populate created_by for events created through the police custody form

- app/move/app/view/middleware/locals.move-details.js
- common/presenters/move-to-handovers-summary.js
- common/presenters/move-to-handovers-summary.test.js
- common/presenters/move-to-summary-list-component.js
Changed it so that 1 PerHandover can only mark 1 Journey as handed over.
Excluded proposed journeys from the handover status section.
We've noticed that a move has been created with 2 journeys from the same location, 1 proposed, 1 complete, and it is showing 2 rows as `handed over` for the same location in the details tab.
- P4-3883
> [P4-3883] Exclude proposed journeys from the "Handover status" section of the move details tab

- locales/en/moves.json
The "Review single request" button no longer spans multiple lines.
Because it didn't fit the style of the rest of the buttons on the website.
- P4-3840
| <kbd><img src="https://user-images.githubusercontent.com/4104309/194837740-11d271bf-7a44-4784-a39f-6afc1824ef98.png"></kbd> | <kbd><img src="https://user-images.githubusercontent.com/4104309/194838432-9d36a295-d168-419c-840e-dabc4bc93168.png"></kbd> |
> fix: "Review single request" button no longer spans multiple lines

- common/middleware/development.js
- config/index.js
- server.js
Added USER_USERNAME env variable.
This has changed because when using BYPASS_SSO, no username is set, which causes issues with the `add events` form.
> chore: Add .env variable USER_USERNAME for use with BYPASS_SSO

- locales/en/assessment.json
- test/e2e/person-escort-record/new.test.js
The wording on the warnings page of unlocked incomplete PERs has changed.
This wording has changed to be more consistent with the locked wording.
- P4-3946
| <kbd><img src="https://user-images.githubusercontent.com/4104309/201099825-915d1134-9f3e-4e2b-8ed8-cd71e9b020bd.png"></kbd> | <kbd><img src="https://user-images.githubusercontent.com/4104309/201099867-f1113871-56dc-40bd-ae15-ebcd9c0ee662.png"></kbd> |
> feat: Add locked PER dialog to the moves overview page

- app/move/app/view/views/warnings.njk
- common/components/framework-response/framework-response.yaml
- common/components/framework-response/template.njk
- common/components/framework-response/template.test.js
- common/controllers/framework/framework-section.js
- common/controllers/framework/framework-section.test.js
- common/presenters/framework-field-summary-list-row.js
- common/presenters/framework-field-summary-list-row.test.js
- common/presenters/framework-step-to-summary.js
- common/presenters/framework-step-to-summary.test.js
- locales/en/default.json
Users with read-only roles are no longer show a link to edit incomplete sections of a PER 
The links were not useful as clicking them redirected back to the current page, given the user is unable to complete PERs
- [P4-4041](https://dsdmoj.atlassian.net/browse/P4-4041)
| <kbd><img width="816" alt="image" src="https://user-images.githubusercontent.com/113102670/207918572-5a451094-6a5f-48c6-9d09-a4221a2bf85c.png"></kbd> | <kbd>
</kbd> |
[GitHub release notes](https://github.com/ministryofjustice/hmpps-book-secure-move-frontend/releases) …
> [P4-4041] hide Answer question links when user is read only

- common/services/contentful/contentful.test.ts
- common/services/contentful/contentful.ts
- common/services/contentful/dedicated-content.ts
Fixed an error that was thrown when contentful content didn't have a date set.
This has changed because it was causing an error when trying to view dedicated content in production.
- P4-4082
> fix: Fix error thrown by content which doesn't have a date

- package.json
It was missing and we're not sure why but a move was created with this version and it now can't be displayed.
(hotfix)
> fix: Add framework v2.4.1

- package-lock.json
- package.json
- server.js
Version 5.0.0 of helmet introduced some defaults which caused the e2e tests to fail. For now the config has been updated to match the existing behaviour. We can revisit this later if we want to benefit from the improved security of the new default settings.
[P4-4109]
Upgraded the `helmet` npm package
Because it was suggested by dependabot
- [P4-4109](https://dsdmoj.atlassian.net/browse/P4-4109)
N/A …
> [P4-4109] Upgrade helmet package

- app/move/app/view/views/details.njk
It was always showing "1 person" when viewing the details of a move that is part of an allocation. Now it shows the correct number.
It was a bug.
- [P4-4138](https://dsdmoj.atlassian.net/browse/P4-4138)
| <kbd><img width="789" alt="Screenshot 2023-04-17 at 11 58 13" src="https://user-images.githubusercontent.com/40831617/232465429-1f170260-5375-46a0-979f-d746406a62ae.png"></kbd> | <kbd><img width="796" alt="Screenshot 2023-04-17 at 11 58 22" src="https://user-images.githubusercontent.com/40831617/232465471-2b076387-e09c-4dfb-a298-87f4d75dac2b.png"></kbd> |
Commit messages with a `fix` or `feat` type are automatically used to generate the [changelog](ministryofjustice/hmpps-book-secure-move-frontend/blob/main/C …
> [P4-4138] fix: Show correct allocation moves count on move details page

- app/allocation/controllers/view.js
- app/allocation/controllers/view.test.js
- app/allocation/views/view.njk
- app/move/app/view/middleware/locals.move-details.test.ts
- common/helpers/allocation/can-edit-allocation.test.ts
- common/helpers/allocation/can-edit-allocation.ts
- common/types/allocation.ts
- common/types/move.ts
- factories/allocation.ts
- factories/location.ts
- factories/move.ts
- package-lock.json
- package.json
- test/e2e/allocation/update.test.js
- test/e2e/pages/allocation-details-edit.js
- test/e2e/pages/allocation-journey.js
- test/e2e/pages/allocation-view.js
Added a link to the view allocation page which takes you to the edit allocation details page. This allows the allocation date to be changed by a user with the correct permissions (namely PMU).
Feature request by PMU. Late last year we allowed moves that were part of an allocation to have their date changed individually as a temporary solution. Now, instead of that, PMU will be able to change the date of an allocation and all of its moves via a single action. Once this feature has been released we will be able to block direct editing of allocation move dates again.
- [P4-4134](https://dsdmoj.atlassian.net/browse/P4-4134)
| <kbd>![Screenshot 2023-04-19 at 13 13 56](https://user-images.githubusercontent.com/40831617/233071549-25f8014b-7fa6-4d68-bda5-79894 …
> [P4-4134] feat: Add link on view allocation page to edit details

- common/helpers/allocation/can-edit-allocation.test.ts
We still want to be able to edit the date of an allocation if it has cancelled moves associated with it. This already works, but the logic depends on the fact that cancelled moves are considered editable, so I'm adding a test in case that changes in future.
We decided to double-check this functionality, so that it doesn't end up blocking PMU from changing the date of some allocations
- [P4-4137](https://dsdmoj.atlassian.net/browse/P4-4137)
[GitHub release notes](https://github.com/ministryofjustice/hmpps-book-secure-move-frontend/releases) during the release task. Please make …
> test: Add regression test for allocations with cancelled moves

- app/allocation/controllers/edit/allocation-details.test.ts
- app/allocation/controllers/edit/allocation-details.ts
- common/types/basm_request.ts
- common/types/move.ts
- common/types/session_model.ts
- common/types/supplier.ts
- locales/en/allocations.json
- Format the date nicely on the edit allocation details page
- Clear errors after displaying them so they don't show up again if you navigate away and come back
- Show success banner (just shows "the supplier" instead of the name of the supplier as we don't download the necessary details from the API)
- Feedback after demo on Friday
- [P4-4133](https://dsdmoj.atlassian.net/browse/P4-4133)
--- …
> Fix allocation edit page  p4 4133

- server.js
Reduce Sentry Transaction Sampling from 10% to 1% and ignore /healthcheck
- Reduced Sentry Transaction Sampling rate from 10% to 1%
- Ignore `/healthcheck` endpoint when sampling Sentry transactions
- The project currently consumes ~1.8 million transactions, this change will reduce the consumption by ~90%
> Reduce Sentry Transaction Sampling from 10% to 1% and ignore /healthcheck

- app/allocation/controllers/edit/allocation-details.test.ts
- app/allocation/controllers/edit/allocation-details.ts
- common/helpers/allocation/can-edit-allocation.test.ts
- common/helpers/allocation/can-edit-allocation.ts
[P4-4172]
* Don't show the link to update an allocation if it's empty (which means that all moves have been cancelled)
* If someone accesses the page and changes the date anyway, do so without error
* Sentry alerted us to this bug when someone tried to change the date of an allocation with zero move count
- [P4-4172](https://dsdmoj.atlassian.net/browse/P4-4172) …
> fix: Fix empty allocation date change bug

- app/move/app/view/controllers/render-details.test.js
- common/helpers/allocation/can-edit-allocation.ts
- common/helpers/move/can-edit-move-date.test.ts
- common/helpers/move/can-edit-move-date.ts
- common/types/move.ts
- factories/allocation.ts
- Hide date change link for allocation moves
- This has been disabled in the API as we now have a proper way of updating allocation dates. We need to hide the link because if someone tries to use it, it will error out.
- [P4-4140](https://dsdmoj.atlassian.net/browse/P4-4140)
| ----- | ----- |
| ![Screenshot 2023-05-26 at 12 00 09](https://github.com/ministryofjustice/hmpps-book-secure-move-frontend/assets/40831617/30d4f166-a8e4-42c2-a1d1-919cd31d5978) | ![Screenshot 2023-05-26 at 12 01 08](https://github.com/ministryofjustice/hmpps-book-secure-move-frontend/assets/40831617/94ddf7d0-daa2-4082-a666-a24a11f07a09) | …
> [P4-4140] Do not allow date change for allocation moves

- .testcaferc.json
- Increase timeouts on e2e tests
- They keep failing and the only seem to pass with very large timeouts. We need to get the main branch building again so we will leave them this high for now, and try and work out what's slowing them down so much later.
> Increase timeouts on e2e tests

- app/move/app/new/controllers/move-details.js
- app/move/app/new/controllers/move-details.test.js
- config/index.ts
- docs/environment-variables.md
- helm_deploy/values-preprod.yaml
- helm_deploy/values-production.yaml
Added feature flag to disable AP moves for certain suppliers
Added feature flag to disable AP moves for certain suppliers. The FEATURE_FLAG_AP_DISABLED_SUPPLIERS environment variable, if set, should be a comma-separated list of supplier keys, as they exist in the BaSM API DB. For example:
serco
geoamey
serco,geoamey
- MAP-212 …
> [MAP-212] Add feature flag for AP moves

- app/person-escort-record/app/confirm/handover-details.njk
- locales/en/assessment.json
Changed the wording on the handover form.
This changed so that users see the right content for lodging moves during handover.
- MAP-87
> feat: Change wording on handover form for lodgings

- common/lib/permissions.js
- common/lib/permissions.test.js
Allows PECS team to download hourly CSV
> fix: MAP-345 add download moves permission to CDM

- common/services/single-request.js
- common/services/single-request.test.js
- locales/en/fields.json
- locales/en/statuses.json
- Support `incomplete_per` cancellation reason
- This cancellation reason has been added to the API to enable suppliers to cancel moves when the PER is incomplete without being accused of unnecessary cancellations. We need to make sure that the frontend doesn't break and that it displays the reason correctly.
- MAP-293
summary of changes and that the commit body gives a more detailed description of …
> [MAP-293] Support incomplete_per cancellation reason

- .github/workflows/branch-deploy.yml
- common/controllers/framework/framework-section.js
- common/controllers/framework/framework-section.test.js
- common/controllers/framework/framework-step.js
- common/controllers/framework/framework-step.test.js
Use standardised approach for checking if PER can be edited.
Sometimes we allow people to edit the PER but then when they click on the individual sections it prevents them from editing them, as it was using different logic whcih was relying on the `.editable` field of the PER. We are looking into what causes the situation where this field does not have the expected value, but for now this should prevent any more issues for users.
- MAP-499
> [MAP-499] Use standardised approach for checking if PER can be edited

- .circleci/config.yml
- .github/workflows/branch-deploy.yml
- package-lock.json
- package.json
Upgrade NPM to v10 to allow Node v18.19+ in build scripts
So we don't have to pin Node to < v18.19
> [MAP-536] Get branch-based deploy working

- common/components/filter/template.njk
- common/components/filter/template.test.js
- Mark overview as links not tabs for screen readers
- Flagged by accessibility report
[MAP-884]
[MAP-884]: https://dsdmoj.atlassian.net/browse/MAP-884?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MAP-884] Mark overview as links not tabs for screen readers

- app/locations/controllers.js
- app/locations/controllers.test.js
- app/locations/views/locations.njk
- test/e2e/pages/page.ts
Remove inactive locations list
Because it violated accessibility standards and was an unused feature, so we decided to just delete it
- [MAP-886]
| ------ | ------ |
| <img width="622" alt="Screenshot 2024-06-06 at 16 14 14" src="https://github.com/ministryofjustice/hmpps-book-secure-move-frontend/assets/40831617/f4a2bd0e-7b24-4cf1-9b3a-5f930539f53e"> | <img width="650" alt="Screenshot 2024-06-06 at 16 14 28" src="https://github.com/ministryofjustice/hmpps-book-secure-move-frontend/assets/40831617/584db190-3ab1-4a73-a485-95e83e2ffe70"> | …
> [MAP-886] Remove inactive locations list

- locales/en/events.json
> feat: MAP-1501 Display the date a move is updated to

- helm_deploy/values-preprod.yaml
- helm_deploy/values-production.yaml
- helm_deploy/values-uat.yaml
- package-lock.json
- package.json
[MAP-1565](https://dsdmoj.atlassian.net/browse/MAP-1565)
Here we add support for Framework v2.5.1, adding a new question to the Personal Escort Record:
**Do not deploy until the API version has been deployed/migrated and suppliers have given us the go ahead**
[MAP-1565]: https://dsdmoj.atlassian.net/browse/MAP-1565?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MAP-1565 Add Framework version 2.5.1

- package-lock.json
- package.json
[MAP-1565](https://dsdmoj.atlassian.net/browse/MAP-1565)
[Adding Framework v2.5.2](https://github.com/ministryofjustice/hmpps-book-secure-move-frameworks/releases/tag/v2.5.2)
Fixes incorrect text in Civil Disorder questions 
**Overview:** 
**Warnings:**
[MAP-1565]: https://dsdmoj.atlassian.net/browse/MAP-1565?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MAP-1565] Add Framework version 2.5.2

- app/allocation/views/view.njk
- common/components/framework-response/template.njk
- common/components/framework-response/template.test.js
- common/helpers/field/add-errorlist-to-errors.js
- common/helpers/field/add-errorlist-to-errors.test.js
- common/presenters/framework-field-summary-list-row.js
- common/presenters/framework-field-summary-list-row.test.js
- locales/en/actions.json
- test/e2e/pages/allocation-view.js
- Add question name to review/amend links on PER/YRA
- Add visually hidden text to remove person links on allocation
- Add "for bag 1" etc to property bag validation errors
To comply with accessibility recommendations
- MAP-879
The only visible change is the validation errors
> MAP-879: Duplicate link texts

- helm_deploy/values-production.yaml
We never have a legitimate reason to use the `hmpps-book-secure-move-frontend-production.apps.cloud-platform.service.justice.gov.uk` URL so let's remove it as it is causing SSL cert validation errors.
MAP-1976
> MAP-1976: Remove default URL

- helm_deploy/values-production.yaml
Currently, the frontend talks to the API via the hostname:
`hmpps-book-secure-move-frontend-production/hmpps-book-secure-move-frontend-production-cert`
and - at 80 characters -  that [hostname is too long to be added to the cloud platform config](https://github.com/ministryofjustice/cloud-platform-environments/blob/main/namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-book-secure-move-api-production/certificate.yaml)
Instead, we change the API_BASE_URL to `https://api.bookasecuremove.service.justice.gov.uk`
https://dsdmoj.atlassian.net/browse/MAP-1976
> Change production API_BASE_URL to support SSL certificate

- .circleci/config.yml
Here we pin CI's node version to `20.18.2-browsers`
The previous `lts-browsers` appears to no longer use v20:
```
npm error code EBADENGINE
npm error engine Unsupported engine
npm error engine Not compatible with your version of node/npm: hmpps-book-secure-move-frontend@3.0.0
npm error notsup Not compatible with your version of node/npm: hmpps-book-secure-move-frontend@3.0.0
npm error notsup Required: {"node":"20","npm":"10"}
npm error notsup Actual:   {"npm":"10.9.2","node":"v22.13.1"}
```
> chore: Pin CI's node version to '20.18.2-browsers'

- common/services/contentful/contentful.test.ts
- common/services/contentful/contentful.ts
- common/services/contentful/dedicated-content.test.ts
- common/services/contentful/dedicated-content.ts
- common/services/contentful/downtime.test.ts
- common/services/contentful/whats-new.test.ts
- Added Redis caching to fetchEntries() to store the data returned from Contentful. This reduces the number of calls made to Contentful. A TTL of 300 seconds / 5 minutes has been added. After which time the application will make a new call to Contentful to retrieve new data.
- Resolved failing unit tests
- Resolved linting errors  
To reduce the number of calls being made to Contentful. 
- MAP-1857
> feat(MAP-1857): Add Redis cache to contentful api call

- package.json
- dependency updates to fix the security issues listed [here ](https://github.com/ministryofjustice/hmpps-book-secure-move-frontend/security/code-scanning)
- Updated Axios from version 1.7.2 to 1.8.2
- MAP-2270
> chore(MAP-2270): Update Axios dependency to 1.8.2

- .circleci/config.yml
- Upgrade to `browser-tools@1.5.3`
- Use `latest` version of Chrome
CI e2e tests were failing because `Google Chrome v123.0.6312.86 (stable) failed to install.`
> chore: Upgrade CI Browser Tools and use latest Chrome version

- README.md
- common/assets/javascripts/application.js
- common/assets/scss/application.scss
- common/templates/layouts/base.njk
- config/nunjucks/index.js
- config/nunjucks/index.test.js
- config/paths.js
- package-lock.json
- package.json
- server.js
- test/unit/component-helpers.ts
Added the HMRC Timeout dialog component to enable users to be notified when their session is about to expire and to inform them that they will be automatically signed out in 2 minutes. 
- MAP-2299
> MAP-2299 - Add HMRC - Service timeout component to BaSM frontend

- common/services/contentful/contentful.ts
Updated common / services / contentful / contentful.ts - fetchBanner() to fix the error when entries is not an array.
Error being thrown when entires is not an array.
- MAP-2357
> chore(MAP-2357): Update fetchBanner function to fix error

- locales/en/events.json
Changed the wording of the PersonMoveBookedIntoReceivingEstablishment event to "[Person] booked for arrival at [location]" 
To clarify that the person hasn't actually made it to the establishment and been booked in
- MAP-2224
| <kbd>
</kbd> | <kbd><img width="650" alt="image" src="https://github.com/user-attachments/assets/b950fb33-3496-4d2e-a0cd-90819ae41b66" /></kbd> |
[GitHub release notes](https://github.com/ministryofjustice/hmpps-book-secure-move-frontend/releases) during the release task. Please make sure they will read well on …
> feat: MAP-2224 Change 'booked into' to 'booked for arrival at'
