package-lock.json, package.json, server.js
This change includes some things needed to make the app ready for a production environment.
See commits for more detailed breakdown and comments.
=> [P4-468]/[P4-468] Production ready changes

README.md, config/index.js, package-lock.json, package.json, server.js
This change adds support for sentry if the relevant environment
variables exist.
=> [P4-470] Add sentry

.circleci/config.yml, Dockerfile, server.js
This PR contains some changes needed to get the app running in production environments.
=> Production changes

app/moves/controllers/form.js, app/moves/controllers/form.test.js, config/index.js, server.js
This set of changes ensure exceptions are logged in Sentry.
It also includes a change to the form processing to ensure we are capturing any validation errors that we aren't aware of.
=> [P4-470] Capture errors in sentry

.circleci/config.yml, .codeclimate.yml, README.md, app/move/fields.js, package-lock.json, package.json
This adds some extra integrations to the repo:
- Coveralls - code coverage reporting
- Code climate - code quality analysis
=> Add extra integrations

app/move/fields.js, app/move/steps.js, common/assets/javascripts/application.js, common/assets/scss/components/_all.scss, common/assets/scss/components/_autocomplete.scss, package-lock.json, package.json
This adds the autocomplete component to the create move journey.
=> [P4-362] Autocomplete

app/move/fields.js, locales/en/fields.json
This adds the hint text to the date of birth field.
=> [P4-524] Add hint text to date of birth field

.eslintrc.js, common/services/person.js, start.js
This change also includes adding a eslint rule to prevent this
happening in the future.
=> Remove stray console.log

app/locations/controllers.js, app/locations/controllers.test.js, app/locations/index.js, app/locations/views/locations.njk, common/middleware/locals.js, common/templates/layouts/base.njk, locales/en/actions.json
This allows the user to switch location as per the prototype. It builds upon #192 so please review only the last commit.
=> [P4-506] Choose location

README.md, app/locations/views/locations.njk, config/i18n.js, config/index.js, config/nunjucks/globals.js, locales/en/actions.json, locales/en/locations.json
This display a message to the user when there are no available
locations.
Rather than throw an app level error we want to communicate to the
user what has happened and how to solve the scenario.
=> [P4-611] Add message when no locations are available

locales/en/locations.json
This change updates the copy of the message that is displayed when
a user doesn't have access to any locations.
=> Amend no locations message

common/lib/request.js, common/lib/request.test.js
A little bit of a tidyup/refactor around the query string method
=> Tidy up query string method

nodemon.json
This work adds `/locales` to the `nodemon` files to watch for changes
=> add locales to nodemon filelist

common/services/move.js, common/services/move.test.js, common/services/person.js, common/services/person.test.js, common/services/reference-data.js, common/services/reference-data.test.js
This works continues to address #82 as well as making the service tests
less dependant on other libraries and also testing them in greater detail.
=> Refactor services unit tests

config/logger.js, config/logger.test.js, config/nunjucks/index.js, config/nunjucks/index.test.js
This adds some more unit test coverage for some config areas that were missing
and form of unit tests.
=> Improve unit test coverage

app/move/controllers/create/base.js, app/move/controllers/create/base.test.js, app/move/controllers/create/move-details.js, app/move/controllers/create/move-details.test.js, app/move/views/view.njk, common/presenters/move-to-meta-list-component.js, common/templates/form-wizard.njk, common/templates/layouts/two-column.njk
Add right-hand summary panel to the create journey
=> [P4-497] Create Move right hand summary panel

common/lib/user.js, common/lib/user.test.js
This extends the User class to assign the correct set of app
level permissions for users that have a Prison specific role
applied to them.
=> [P4-648] Set correct app permissions for Prison users

package-lock.json, package.json, webpack.config.js
Update sass loader dependency. Also includes an update to `webpack` config
- `npm t` passes
- Application works as in you can login and view the dashboard
=> Update sass loader dependency

README.md, package.json
This adds an NPM tasks so that tests can be watched whilst developing.
=> Add task to watch tests

server.js
We don't have a static public folder for the moment so removing this reference to it
=> Remove public static folder

common/lib/api-client/middleware/request.js, common/lib/api-client/middleware/request.test.js, common/services/reference-data.js, common/services/reference-data.test.js
This PR includes some updates needed to make the locations by supplier work with the latest API changes being made.
=> Locations by supplier updates

.circleci/config.yml, package-lock.json, package.json
Save time initialising and running each job and free up CircleCI queue.
https://dsdmoj.atlassian.net/browse/P4-754
=> Merge CircleCI jobs

.circleci/config.yml, Dockerfile, README.md, config/nunjucks/globals.test.js, package.json
https://dsdmoj.atlassian.net/browse/P4-756
=> Upgrade to Node 12

docker-compose.yml
Use the existing .env file and connect to API on host.
=> Update docker-compose.yml to run locally

.circleci/config.yml, .gitignore, .testcaferc.json, README.md, package-lock.json, package.json, test/e2e/helpers.js, test/e2e/moves.test.js, test/e2e/page-model.js, test/e2e/smoke.test.js
https://dsdmoj.atlassian.net/browse/P4-698
=> Add test for checking move tag creation and nav

package.json
This will provide a better per-test reporting during the test run in addition to xunit summary.
=> E2E: Add spec inline reporting for CI

.gitignore, app/move/controllers/create/index.js, app/move/controllers/create/personal-details.js, app/move/controllers/create/personal-details.test.js, app/move/controllers/create/pnc-search-results.js, app/move/controllers/create/pnc-search-results.test.js, app/move/fields/create.js, app/move/steps/create.js, app/move/views/create/pnc-search-results.njk, app/move/views/create/pnc-search.njk, common/assets/scss/components/_all.scss, common/components/results/_results.scss, common/components/results/macro.njk, common/components/results/results.yaml, common/components/results/template.njk, common/components/results/template.test.js, common/helpers/field.js, common/helpers/field.test.js, common/services/person.js, common/services/person.test.js, common/templates/form-wizard.njk, common/templates/layouts/base.njk, locales/en/actions.json, locales/en/fields.json, locales/en/moves.json, test/e2e/helpers.js, test/e2e/moves.test.js, test/e2e/page-model.js
Work involved around the PNC search functionality
=> [P4-744] PNC search functionality

test/e2e/helpers.js, test/e2e/moves.test.js, test/e2e/page-model.js
This work adds the journey when a user gets search results from the PNC search and uses them
=> [P4-772] - Pnc search with results e2e

app/move/controllers/create/pnc-search-results.js
A tiny refactor to this method
=> A little bit of a tidy up to the configure method

common/components/multi-file-upload/_multi-file-upload.scss, common/components/multi-file-upload/multi-file-upload.js
A few tweaks to how the loading bar looks on the multi-upload-component
=> Tweak loading bar design

common/services/document.test.js
A tidy up of the variables used in these tests to make more sense
=> Small tidy up of code

package.json
Tyom worked with us for a few weeks and made some great contributions.
The most notable being the setup for end 2 end tests with testcafe.
Thanks Tyom \o/
=> Add tyom to contributors

locales/en/statuses.json
This includes the accepted status in the locales and also updates
the text for requested to be more verbose.
=> Add accepted status to locales

README.md, app/move/controllers/create/document.js, app/move/controllers/create/document.test.js, app/move/steps/create.js, app/move/views/view.njk, config/index.js, config/nunjucks/globals.js
This change adds the ability to enable or disbale the document upload
feature using environment variables.
=> Feture flag document upload feature

app/moves/controllers/list.js, app/moves/controllers/list.test.js, common/lib/user.js, common/lib/user.test.js
=> P4-910 Provide supplier role with dashboard & profile view

README.md, app/move/controllers/create/document.js, app/move/controllers/create/document.test.js, app/move/controllers/create/move-details.js, app/move/controllers/create/move-details.test.js, app/move/steps/create.js, app/move/views/view.njk, config/index.js, config/nunjucks/globals.js
This change adds logic using the form wizard next step functionality
to determine whether a user should see the documents step.
It uses an attribute of from location to decide whether the documents step should
be shown.
This removes the need to base this on a feature flag and environment variable
so this has also been removed.
=> [P4-742] Determine whether to show the documents steps

common/lib/api-client/models.js, test/fixtures/api-client/location.find.json, test/fixtures/api-client/location.findAll.json
This adds a new attribute that was added to the location model
to help determine whether documents can be uploaded for that
location.
=> [P4-1024] Add attribute to location model

README.md, common/lib/api-client/middleware/request.js, package-lock.json, package.json, server.js
This change adds debugging support for axios and adds debug logs to
the API client.
This allows debugging to be enabled during development to help
see what requests are being made, when.
=> Add debugging support

app/move/controllers/create/assessment.test.js, app/move/controllers/create/base.js, app/move/controllers/create/base.test.js, app/move/controllers/create/document.test.js, app/move/controllers/create/move-details.js, app/move/controllers/create/move-details.test.js, app/move/controllers/create/person-search.test.js, app/move/fields/create.js, app/move/steps/create.js, app/move/views/create/person-search.njk, locales/en/fields.json, locales/en/moves.json, test/e2e/moves.test.js, test/e2e/page-model.js
Create logic to determine which person search step a user should see based on the location they are sending someone from.
=> [P4-960] Person search logic

app.json, config/index.js
This add the configuration file required for Heroku review apps
to auto create apps for each pull request on GitHub.
=> Add support for Heroku Review Apps

test/e2e/moves.test.js, test/e2e/page-model.js
Unfortunately the e2e tests were broken with a recent change as we
aren't currently able to run them on PR branches.
This change fixes the current failing tests.
=> Update the e2e tests for prison moves

app/move/fields/create.js, app/move/steps/create.js, locales/en/fields.json
This updates the release status question to match the [new key](https://github.com/ministryofjustice/hmpps-book-secure-move-api/pull/305) in the API.
=> fix: Update release status assessment question

app/move/controllers/create/person-search-results.js, app/move/controllers/create/person-search-results.test.js, app/move/views/create/person-search-results.njk
This includes a couple of small changes to the person search.
- Fix one of the translation keys used
- Make sure the search term is displayed correctly
=> Update person search

app/move/controllers/create/index.js, app/move/controllers/create/prison-transfer-reason.js, app/move/controllers/create/prison-transfer-reason.test.js, app/move/fields/create.js, app/move/steps/create.js, common/lib/api-client/models.js, common/services/reference-data.js, common/services/reference-data.test.js, locales/en/fields.json, locales/en/moves.json
This PR creates the `/prison-transfer-reason` for the OCA flow.
=> [P4-1061] Step for the move request reason

common/lib/permissions.js, common/lib/user.test.js
This adds the ability to create and cancel moves for prison and YOI
users.
=> chore: Update permissions for Prison users

app/move/views/create/assessment.njk, locales/en/moves.json
This change includes a re-work of the text when NOMIS information is incorrect to be more accurate to what a user needs to do.
=> Update incorrect text for NOMIS alerts

common/middleware/ensure-authenticated.js, common/middleware/ensure-authenticated.test.js
Fixes https://sentry.service.dsd.io/mojds/frontend/issues/47341
=> fix: Ensure content-type is defined before checking it

app/move/controllers/create/move-details.js, app/move/controllers/create/move-details.test.js, app/move/controllers/create/save.js, app/move/controllers/create/save.test.js, app/move/fields/create.js, app/move/steps/create.js, app/moves/middleware.js, app/moves/middleware.test.js, common/lib/permissions.js, common/lib/user.test.js, config/index.js, test/e2e/move.new.prison.test.js, test/e2e/pages/create-move.js, test/e2e/pages/moves-dashboard.js, test/e2e/roles.js, test/e2e/smoke.test.js
This PR provides the journey for the OCA user -- based on the logged in user having the correct role and the current location being a `prison`.
It also includes the tests described in P4-1151.
~For the moment being the tests fail because the api incorrectly validates the date on save.~
The above is now fixed.
=> [P4 1150] Journey for the OCA user

app/moves/views/list-by-status.njk, common/presenters/move-to-meta-list-component.js, common/presenters/move-to-meta-list-component.test.js, locales/en/default.json
The date of travel in the sidebar.
=> [NOJIRA]  Date of travel in sidebar

app/moves/controllers/list.js, app/moves/index.js, app/moves/views/_layout.njk, app/moves/views/download.njk, app/moves/views/list.njk, common/lib/permissions.js, common/lib/user.test.js, common/middleware/set-primary-navigation.js, common/middleware/set-primary-navigation.test.js, common/templates/layouts/base.njk, locales/en/default.json, locales/en/moves.json, server.js
This introduces a primary navigation to the site. Some of the items are conditional based on permissions so there is a piece of middleware to handle this which passes the final items to the view layer.
<kbd><img src="https://user-images.githubusercontent.com/3327997/79458413-ade82080-7fe9-11ea-909a-cf2ecdaf9f60.png"></kdb>
<kbd><img src="https://user-images.githubusercontent.com/3327997/79458514-d07a3980-7fe9-11ea-8109-31994e71d363.png"></kdb>
<kbd><img src="https://user-images.githubusercontent.com/3327997/79458539-db34ce80-7fe9-11ea-8376-fc0f75a7efda.png"></kdb>
<kbd><img src="https://user-images.githubusercontent.com/3327997/79458690-10d9b780-7fea-11ea-9aa8-235621d88009.png"></kdb>
<kbd><img src="https://user-images.githubusercontent.com/3327997/79458708-1afbb600-7fea-11ea-8c5c-1a121633 …
=> Add primary navigation menu

common/services/person.js, common/services/person.test.js, common/services/person/person.unformat.js, common/services/person/person.unformat.test.js
- Move all tests to submodule
- Decouple tests from specific fields
- Allow value type keys to be passed through
=> Refactor person service unformat method

common/components/filter/_filter.scss, common/components/filter/filter.yaml, common/components/filter/template.njk, common/components/filter/template.test.js
This change makes a few updates the filter component:
- remove underline on selected state
- adds ARIA roles of `tablist` and `tab` to improve accessibility
- tweaks layout on smaller devices
- adjusts focus state to include outline
- increase contrast of hover state of non-active items
- adds ability to focus on selected state and apply visual focus
*Click screenshots to enlarge*
| <kbd><img src="https://user-images.githubusercontent.com/3327997/80621379-1e0d9200-8a3f-11ea-8ce0-709ac2f0b34d.png"></kbd> | <kbd><img src="https://user-images.githubusercontent.com/3327997/80619383-8dce4d80-8a3c-11ea-8f56-fa0d13f78adc.png"></kbd> |
| <kbd><img src="https://user-images.githubusercontent.com/3327997/80621431-2ebe0800-8a3f-11ea-93af-14ff9328b26b.png"></kbd> …
=> Update filter component

app/allocation/controllers/assign/assessment.js, app/allocation/controllers/assign/base.js, app/allocation/controllers/assign/confirmation.js, app/allocation/controllers/assign/index.js, app/allocation/controllers/assign/person-search-results.js, app/allocation/controllers/assign/person-search.js, app/allocation/controllers/assign/save.js, app/allocation/fields/index.js, app/allocation/index.js, app/allocation/steps/assign.js, app/allocation/steps/index.js, app/allocation/views/assign/assign-conflict.njk, app/allocation/views/assign/confirmation.njk, app/allocation/views/assign/no-special-vehicle.njk, app/allocation/views/view.njk, common/lib/permissions.js, common/lib/user.test.js, common/services/move.js, common/services/move.test.js, common/services/person.js, common/services/person.test.js, config/i18n.js, locales/en/allocation.json, locales/en/allocations.json, locales/en/fields.json, locales/en/messages.json, locales/en/validation.json
=> P4 1330 oca assign person to allocation

app/allocation/controllers/assign/agreement-status.js, app/allocation/controllers/assign/agreement-status.test.js, app/allocation/controllers/assign/assessment.js, app/allocation/controllers/assign/assessment.test.js, app/allocation/controllers/assign/base.js, app/allocation/controllers/assign/base.test.js, app/allocation/controllers/assign/confirmation.js, app/allocation/controllers/assign/index.js, app/allocation/controllers/assign/person-search-results.test.js, app/allocation/controllers/assign/person-search.test.js, app/allocation/controllers/assign/save.test.js, app/allocation/fields/index.js, app/allocation/fields/special-vehicle-check.js, app/allocation/steps/assign.js
Adds tests for code added in #539
=> P4 1330 oca assign person to allocation tests

app/move/views/view.njk, common/components/card/_card.scss, common/presenters/person-to-card-component.js, common/presenters/person-to-card-component.test.js, locales/en/default.json
This change updates the content used in the heading to be more
consistent with the allocation screen.
It also includes a tweak to the padding to make the top/bottom align
with the left padding and changes the case to lowercase to match
the latest design.
| <kbd><img src="https://user-images.githubusercontent.com/3327997/83013385-d6b1fb80-a014-11ea-8e57-787e3a1a366d.png"></kbd> | <kbd><img src="https://user-images.githubusercontent.com/3327997/83013309-b3874c00-a014-11ea-9c8d-539751c9a943.png"></kbd> |
| <kbd><img src="https://user-images.githubusercontent.com/3327997/83013368-ce59c080-a014-11ea-864d-c49d893e2af5.png"></kbd> | <kbd><img src="https://user-images.githubusercontent.com/3327997/83013325-be41e100-a014-11ea-9303-8b0a09eb8ec0.png"></kbd> |
=> chore: Update content for a move without a person

.github/pull_request_template.md
Updates the template for GitHub Pull Requests.
A common template for Pull Requests will help reviewers during the review stage by having a consistent approach to explaining changes.
It will help to ensure that particular considerations are taken into account with each set of changes, for example when changes include new environment variables.
After discussions in retrospectives other members of the team will be starting to look at Pull Requests to review ongoing changes. Having a template that encourages a more detailed description around PRs will also benefit non-technical users.
Commit messages with a `fix` or `feat` type are automatically used to generate the [changelog](ministryofjustice/hmpps-book-secure-move-frontend/blob/master/CHANGELOG.md …
=> Update GitHub Pull Request template

Dockerfile
Reduce the image of the build docker image 
* Using node:12.10-alpine as the base image
* Using multi-stage docker builds
Using node:12.10-alpine provide a lighter OS base to d 
- [P4-1563]
Before:
After:
There was no change to the application code. 
But this change changes some of the dependencies  that are compiled natively to the new  OS libraries there is a unlikely but possible impact.
The image was build and ran locally inside the provided docker-compose stack to verify it serves the home page, as a smoke test.
=> [P4-1563] Improve docker image size

app/move/controllers/assign/base.js, app/move/controllers/assign/base.test.js, app/move/controllers/assign/person-search-results.js, app/move/controllers/assign/person-search-results.test.js, app/move/controllers/assign/person-search.js, app/move/steps/assign.js, app/move/steps/create.js, app/move/views/person-search-results.njk, app/move/views/person-search.njk, common/presenters/allocation-to-meta-list-component.js, common/presenters/allocation-to-meta-list-component.test.js, common/presenters/allocation-to-summary-list-component.js, common/presenters/allocation-to-summary-list-component.test.js, common/templates/form-wizard.njk, locales/en/allocations.json, locales/en/moves.json
Changes made:
* allocations dashboards: Column title from 'Date' ‘Date of travel’ 
* allocations dashboards: filter name from 'Total' to ‘Total allocations’
* Individual allocations summary record page ‘Estate type’ prison hidden from view
* OCA adds; Page title for the first page becomes ‘Who do you want to add to this allocation?’
* OCA adds: added right hand column to the search person and search results page
Also: renamed / moved a few things for better readability.
=> fix(allocations): Copy changes on the allocation(s) app

app/allocations/middleware/set-body.allocations.js, app/allocations/middleware/set-body.allocations.test.js, app/home/constants.js, app/home/controllers.js, app/home/controllers.test.js, app/home/dashboard.njk, app/home/index.js, app/home/middleware.js, app/home/middleware.test.js, app/moves/middleware/index.js, app/moves/middleware/set-body.moves.js, app/moves/middleware/set-body.single-requests.js, app/moves/middleware/set-body.single-requests.test.js, app/moves/middleware/set-filter.moves.js, app/moves/middleware/set-filter.moves.test.js, app/moves/middleware/set-results.moves.test.js, common/helpers/date-utils.js, common/helpers/date-utils.test.js, common/middleware/set-primary-navigation.js, common/middleware/set-primary-navigation.test.js, common/services/move.js, common/services/move.test.js, locales/en/dashboard.json
This set of changes adds the outgoing and incoming panels to the dashboard. It re-uses the existing patterns for filters to display the results for the default time period.
The incoming section was recently added to the app and we need a way to show a summary of those sections on the dashboard so this change adds both outgoing and incoming to the dashboard in the same style as the other sections.
- [P4-1456](https://dsdmoj.atlassian.net/browse/P4-1456)
| <kbd><img src="https://user-images.githubusercontent.com/3327997/83749435-9decd480-a65b-11ea-9f5f-9210e95a67ae.png"></kbd> | <kbd><img src="https://user-images.githubusercontent.com/3327997/83749204-3e8ec480-a65b-11ea-8318-fe8347225004.png"></kbd> |
| <kbd><img …
=> [P4-1456] Show incoming/outgoing moves on dashboard

.eslintrc.js, common/lib/api-client/middleware/request.js, start.js
Added line breaks before statement.
Switched from switch statement to if block.
eslint changes failed to get applied to #559
n/a
=> style: Fix eslint issues after merging #559

test/e2e/_helpers.js, test/e2e/allocation.new.test.js, test/e2e/pages/allocation-criteria.js, test/e2e/pages/allocation-details.js, test/e2e/pages/allocation-journey.js, test/e2e/pages/allocation-view.js, test/e2e/pages/move-detail.js, test/e2e/pages/page.js
Updates to the end-to-end tests for allocations to fix the selectors as well as testing some further values.
Previous changes resulted in the current selectors not matching the elements. This required updating. The previous tests also didn't test the output of the allocation so these changes increase that coverage be ensuring the inputted values are present in the allocation view page.
summary of …
=> Allocations end-to-end test fixes

app/locations/views/locations.njk
Remove the case transformation of the list of locations.
Previously we were trying to change the case of the list of locations
on the locations page.
The problem with this is that it then doesn't replicate how we replay
the location everywhere else on the service, for example, the banner in
the header or the list of locations in dropdowns.
This change removes that fix so we at least replay them consistently.
If we want to amend the case, this should ideally be done at source
(the API or NOMIS), or in some form of translations for specific
locations.
| <kbd><img src="https://user-images.githubusercontent.com/3327997/84063350-d91f3880-a9b8-11ea-8e38-a5148022158a.png"></kbd> | <kbd><img src="https://user-images.githubusercontent.com/3327997/84063287-be4cc …
=> Fix locations casing

.circleci/config.yml, Dockerfile, README.md, package.json
Node is released in short-term odd-numbered releases (9, 11 etc) which
become unsupported after 6 months, and even-numbered releases which
become get LTS status (long-time support).
It's preferential to always use LTS versions for software used in
production as odd-numbered releases are essentially beta versions
of LTS versions.
Docs for v14: https://nodejs.org/dist/latest-v14.x/docs/api/
summary …
=> chore: Upgrade Node to 14

test/e2e/pages/allocation-details.js
Fixed the e2e test for cancel allocation that needs a date to be this week.
A well-meaning developer had changed the date to be generically in the future.
To cancel the allocation you need to see it in the weekly view, in the current test. We may refactor it to just use the id.
No jira.
=> fix(allocations): Fix the cancel allocation e2e tests

app/allocation/controllers/create/save.js, app/allocation/controllers/create/save.test.js, common/lib/api-client/models.js, common/presenters/allocation-to-meta-list-component.js, common/presenters/allocation-to-meta-list-component.test.js, locales/en/allocation.json, test/e2e/pages/allocation-view.js, test/e2e/pages/page.js, test/fixtures/api-client/allocation.findAll.json
This PR saves and display the name of the user who created an allocation. It's a temporary solution whilst awaiting a more solid implementation.
This PR adds `requested_by` to the allocation model, saves it alongside said allocation, and displays it as per prototype on the allocation summary.
Many thanks to @solidgoldpig for the escaping of the dynamic regex 🏆 
To let the users know who created an allocation.
- [P4-1473]()
| <kbd><img width="565" alt="Screenshot 2020-06-17 at 14 22 56" src="https://user-images.githubusercontent.com/853989/84903789-70b21480-b0a6-11ea-8b3e-8e7eee2deb64.png"></kbd> | <kbd><img width="568" alt="Screenshot 2020-06-17 at 14 23 10" src="https://user-images.githubusercontent.com/853989/84903858-8293b780-b0a6-11ea-8463-0d67da70 …
=> [P4-1473] - feat(allocations): Record & display the user who requests the allocation

app/person-escort-record/index.js, app/person-escort-record/middleware.js, app/person-escort-record/middleware.test.js, app/person-escort-record/router.js, app/person-escort-record/router.test.js, common/services/frameworks.js, common/services/frameworks.test.js
This creates a form wizard for each section of the person escort
framework passing in the transformed steps and questions.
The form wizard then handles next steps and form validation.
This adds support to render the form steps generated from the [person escort record framework](https://github.com/ministryofjustice/hmpps-book-secure-move-frameworks)
- [P4-1734](https://dsdmoj.atlassian.net/browse/P4-1734)
[GitHub release notes](https://github.com/ministryofjustice/hmpps-book-secure-move-frontend/releases) during the release task. Please make sure they will read well on their …
=> [P4-1734] Add route handler to show framework steps

README.md, app/move/index.js, common/lib/permissions.js, common/lib/user.test.js, config/index.js, test/e2e/move.update.forbidden.test.js, test/e2e/move.update.police.test.js, test/e2e/move.update.stc.test.js
Remove `FEATURE_FLAG_EDITABILITY` flag
Has been enabled with the flag for nearly 2 months and can now be removded
=> Remove EDITABILITY feature flag

common/controllers/form-wizard.js, common/controllers/form-wizard.test.js, common/helpers/field/flatten-conditional-fields.js, common/helpers/field/flatten-conditional-fields.test.js, common/helpers/field/index.js, common/helpers/field/reduce-dependent-fields.js, common/helpers/field/reduce-dependent-fields.test.js, common/services/frameworks.js, common/services/frameworks.test.js, package-lock.json
This adds support to create conditional comments fields from the manifest where an option has defined
followup comments. 
This change included updating the form wizard support to handle objects as part of a field options conditionals
and to ensure validation works correctly and is rendering correctly.
For particular question types within the form wizard we want to support the ability to provide additional
comments. Rather than requiring a new question and therefore response for each item we wanted to support
these type of comments fields being dynamically created.
This required some of that heavy lifting to be done on the frontend within the form wizard.
**Note:** This PR doesn't address the error messages not currently bringing in the correct content.
- …
=> [P4-1735] Support followup comments from framework

app/person-escort-record/index.js, app/person-escort-record/middleware.js, app/person-escort-record/middleware.test.js, app/person-escort-record/router.js, app/person-escort-record/router.test.js, common/lib/api-client/models.js, common/lib/api-client/models.test.js, common/services/index.js, common/services/person-escort-record.js, common/services/person-escort-record.test.js, test/fixtures/api-client/person_escort_record.find.json
This creates the models that will be used to build a person escort record along with an initial service to get one.
We'll need to query the API for the person escort record associated with a move so this builds
the expected structure of the API endpoints.
- [P4-1737](https://dsdmoj.atlassian.net/browse/P4-1737)
=> [P4-1737] Create models and service for Person Escort Record

README.md, app/move/controllers/create/save.js, app/move/controllers/create/save.test.js, common/lib/api-client/index.js, common/lib/api-client/middleware/index.js, common/lib/api-client/middleware/request-headers.js, common/lib/api-client/middleware/request-headers.test.js, common/lib/api-client/middleware/request.js, common/lib/api-client/middleware/request.test.js, common/lib/api-client/models.js, config/index.js
Adds version requested to Accept header
Enabled migration to v2
- [P4-1854](https://dsdmoj.atlassian.net/browse/P4-1854)
=> P4 1854 move frontend to version 2

app/person-escort-record/controllers/frameworks.js, app/person-escort-record/controllers/frameworks.test.js
This change takes the values from the API and pre-fills the form step with those values.
This allows a user to update an existing value for a question within the framework.
- [P4-1767](https://dsdmoj.atlassian.net/browse/P4-1767)
<kbd><img src="https://user-images.githubusercontent.com/3327997/86823830-3de7b480-c085-11ea-95ef-27966974524a.png"></kbd>
summary of changes and that the commit body …
=> [P4-1767] Update a response from the API

app/person-escort-record/controllers/framework-section.js, app/person-escort-record/controllers/framework-section.test.js, common/assets/scss/overrides/_govuk-frontend.scss, common/components/framework-response/framework-response.yaml, common/components/framework-response/macro.njk, common/components/framework-response/template.njk, common/components/framework-response/template.test.js, common/helpers/frameworks/append-response-to-field.js, common/helpers/frameworks/append-response-to-field.test.js, common/helpers/frameworks/index.js, common/helpers/frameworks/map-field-from-name.js, common/helpers/frameworks/map-field-from-name.test.js, common/presenters/framework-field-summary-list-row.js, common/presenters/framework-field-summary-list-row.test.js, common/presenters/framework-step-to-summary.js, common/presenters/framework-step-to-summary.test.js, common/presenters/index.js, common/services/frameworks.js, common/services/frameworks.test.js, config/nunjucks/globals.js, config/nunjucks/globals.test.js
This renders the current responses for the Person Escort Record in a "check your answers" style overview page.
The Person Escort Record is something that can be filled in over time and has a "save and return" style
functionality. This overview page allows a user to see the current status of that record at any point in time.
- [P4-1763](https://dsdmoj.atlassian.net/browse/P4-1763)
<kbd><img src="https://user-images.githubusercontent.com/3327997/86785454-8dfd5180-c05a-11ea-8d75-d67c08193d75.png"></kbd>
<kbd><img src="https://user-images.githubusercontent.com/3327997/86785420-8473e980-c05a-11ea-8c27-90c5c7013597.png"></kbd>
<kbd><img src="https://user-images.githubusercontent.com/3327997/86785271-55f60e80-c05a-11ea-8d59-7318d876bc36.png"></kbd> …
=> [P4-1763] Render responses from the Person Escort Record framework as overview

common/assets/scss/components/_stack-trace.scss, common/lib/api-client/index.js, common/lib/api-client/index.test.js, common/templates/error.njk, test/e2e/_routes.js, test/e2e/allocation.cancel.test.js, test/e2e/allocation.new.test.js, test/e2e/pages/allocation-cancel.js, test/e2e/pages/allocation-criteria.js, test/e2e/pages/allocation-details.js, test/e2e/pages/allocation-journey.js, test/e2e/pages/move-detail.js, test/e2e/pages/page.js
- added output of JSON:API errors to stack trace in development
- added ability to not load auth if no credentials are provided
The main reason is to make debugging easier during development and also gives us the ability
to point version of the frontend against the API Heroku review apps.
| <kbd><img src="https://user-images.githubusercontent.com/3327997/87160081-4c6ae180-c2ba-11ea-9361-4f49afdc40f3.png"></kbd> | <kbd><img src="https://user-images.githubusercontent.com/3327997/87159913-f9912a00-c2b9-11ea-9968-e2e60f9d5810.png"></kbd> |
| <kbd><img src="https://user-images.githubusercontent.com/3327997/87160120-5bea2a80-c2ba-11ea-903f-ed0e28a46135.png"></kbd> | <kbd><img src="https://user-images.githubusercontent.com/3327997/87160004-23e2e780-c2ba-11ea- …
=> Output JSON:API errors during development

app/allocations/middleware/set-body.allocations.js, app/allocations/middleware/set-body.allocations.test.js, app/locations/controllers.js, app/locations/controllers.test.js, app/locations/index.js, app/locations/middleware.js, app/locations/middleware.test.js, app/locations/views/locations.njk, common/lib/api-client/models.js, common/middleware/locals.js, common/services/allocation.js, common/services/allocation.test.js, common/services/reference-data.js, common/services/reference-data.test.js, common/templates/layouts/base.njk
Currently the PMU user sees a list of "example locations" but in reality we want them to be able to browse by region. 
We show the list of regions and we introduce the appropriate filter for allocations.
PMU's work is region-based, not location-based.
- [P4-1389]()
| <kbd><img width="980" alt="Screenshot 2020-06-23 at 10 44 00" src="https://user-images.githubusercontent.com/853989/85389506-6a58e800-b53f-11ea-8478-d39a24535181.png"></kbd> | <kbd><img width="1006" alt="Screenshot 2020-06-23 at 10 41 45" src="https://user-images.githubusercontent.com/853989/85389438-51e8cd80-b53f-11ea-89d8-9824d1837fd3.png"></kbd> |
| <kbd><img width="1045" alt="Screenshot 2020-06-23 at 10 44 11" src="https://user-images.githubusercontent.com/853989/85389552-7ba1f480-b53f …
=> [P4-1389] Add support for regions within allocations

test/e2e/parallel-runner.js
Corrected docs for `max_processes` option
=> build: Fix e2e runner usage docs

app/allocations/index.js
The router call for the allocations route protection check contained
a path argument which prevented the route check middleware from
being applied to all routes.
This will now ensure that users without permission to view allocations
won't be able to access those routes.
=> fix(allocations): Fix permissions check for allocations app

app/person-escort-record/controllers/framework-overview.js, app/person-escort-record/controllers/framework-overview.test.js, app/person-escort-record/controllers/frameworks.js, app/person-escort-record/controllers/frameworks.test.js, common/components/framework-response/framework-response.yaml, common/components/framework-response/template.njk, common/components/framework-response/template.test.js, common/lib/api-client/models.js, common/presenters/framework-field-summary-list-row.js, common/presenters/framework-field-summary-list-row.test.js, common/presenters/framework-step-to-summary.js, common/presenters/framework-step-to-summary.test.js, common/presenters/framework-to-task-list-component.js, common/presenters/framework-to-task-list-component.test.js, common/services/person-escort-record.js, common/services/person-escort-record.test.js, locales/en/default.json, locales/en/person-escort-record.json, test/fixtures/api-client/person_escort_record.create.json, test/fixtures/api-client/person_escort_record.find.json, test/fixtures/api-client/profile.create.json
This PR contains a few tweaks that needed to be made once testing against the actual API endpoints.
In summary:
- update models
- improve framework response handling
- fix references to section progress
The API endpoints are now more stable and some things in the frontend code required tweaking to
make the journeys work properly. …
=> Person Escort Record corrections

common/assets/scss/overrides/_govuk-frontend.scss, common/services/frameworks.js, common/services/frameworks.test.js, config/markdown.js, config/markdown.test.js
This change 
- fixes the importing of the hint text for nested options
- adds support to render markdown from a question's hint text into HTML
We needed to support hint text on question options and in some instances only being able to support text makes it hard to
get across all the information necessary. For example, bullets can help summaries information.
| <kbd><img src="https://user-images.githubusercontent.com/3327997/87703012-1766ff00-c792-11ea-878d-cb9e22cbd032.png"></kbd> | <kbd><img src="https://user-images.githubusercontent.com/3327997/87702768-b8a18580-c791-11ea-89fd-aca6a4273a5a.png"></kbd> | …
=> Import option hint text and support markdown

server.js
This changes the way we remove data by making use of the request handler
option instead of `beforeSend`.
=> refactor: Change the way we don't send data to Sentry

app/move/views/assign/no-special-vehicle.njk, common/assets/scss/application.scss, common/assets/scss/helpers/_all.scss, common/assets/scss/helpers/_reading-width.scss, common/assets/scss/settings/_all.scss, common/assets/scss/settings/_measurements.scss, common/assets/scss/utilities/_reading-width.scss, common/components/message/_message.scss, locales/en/allocation.json, locales/en/messages.json, locales/en/moves.json, locales/en/validation.json
- Update special vehicle error step to be more consistent.
- Update content to remove negative contractions.
This brings this validation error message inline with the errors that are displayed
when a user attempts to create a move/allocation conflict so that we use a consistent pattern.
It also updates the language of the message to avoid using negative contractions inline
with the [GOV.UK Style guide advice](https://www.gov.uk/guidance/style-guide/a-to-z-of-gov-uk-style#contractions).
| <kbd><img src="https://user-images.githubusercontent.com/3327997/87861567-55edec80-c93f-11ea-890d-16b4cc7dd485.png"></kbd> | <kbd><img src="https://user-images.githubusercontent.com/3327997/87861478-71a4c300-c93e-11ea-9d88-16b8853c2c8f.png"></kbd> |
| <kbd><img …
=> Use consistent error message pattern

README.md, app/move/controllers/view.js, app/move/controllers/view.test.js, app/person-escort-record/index.js, common/services/frameworks.js, common/services/frameworks.test.js, common/services/person-escort-record.js, common/services/person-escort-record.test.js, config/index.js, config/paths.js, package-lock.json, package.json
This refactors the way we store, manage and send versions of the framework.
Previously we pulled the latest version from master and didn't use any tags/releases.
This moves the application to start using the git tag of the [frameworks repo](https://github.com/ministryofjustice/hmpps-book-secure-move-frameworks) to manage supported versions.
It also adds support for fixing the currently supported version that is used to create new
records from a framework.
The API requires a client application to send a specific version of the framework to avoid any
unexpected behaviour.
- [P4-1946](https://dsdmoj.atlassian.net/browse/P4-1946) …
=> Send current version of framework when creating a Person Escort Record

app/move/fields/move-not-agreed-instruction.js, locales/en/fields.json
All instances of "Complex cases must be discussed" should be replaced with "Complex cases should be discussed".
=> [P4-1692] Amended wording for complex cases

app/move/controllers/confirmation.js, app/move/controllers/confirmation.test.js, app/move/controllers/create/move-details.js, app/move/controllers/create/move-details.test.js, app/move/controllers/update/move-details.test.js, app/move/fields/index.js, app/move/fields/move-type.js, app/move/steps/create.js, common/lib/permissions.js, common/lib/user.test.js, common/presenters/move-to-meta-list-component.js, common/presenters/move-to-meta-list-component.test.js, common/presenters/moves-by-location.js, common/presenters/moves-by-location.test.js, locales/en/fields.json, test/e2e/_helpers.js, test/e2e/_move.js, test/e2e/pages/create-move.js, test/e2e/pages/move-detail.js
Adds `video_remand` as a `move_type` and a corresponding user permission.
Behaves same as `prison_recall` - selecting the option presents a textarea for additional behaviour rather than a list of locations to select from.
Feature requested by users - currently users were using the `prison_recall` type and adding notes.
- [P4-1815](https://dsdmoj.atlassian.net/browse/P4-1815)
| <kbd>![Where_is_this_person_moving__-_Create_a_move](https://user-images.githubusercontent.com/4856/86335190-15575900-bc46-11ea-9b44-335d113d4e1c.png)</kbd> | <kbd>![Where_is_this_person_moving__-_Create_a_move](https://user-images.githubusercontent.com/4856/86334940-bbef2a00-bc45-11ea-8011-da0214fc1851.png)
</kbd> |
|  | …
=> feat(move): Add video remand as move type option for police user

app/allocation/controllers/create/allocation-criteria.js, app/allocation/controllers/create/allocation-criteria.test.js, app/allocation/fields/estate.js, app/allocation/fields/index.js, app/allocation/fields/prisoner-young-offender-female.js, app/allocation/fields/prisoner-young-offender-male.js, locales/en/fields.json, test/e2e/pages/allocation-criteria.js
Young offenders {female, male} were ignored by the API due to a key mismatch.
This PR aligns the front-end key with the API.
=> [BUG] Fixed allocations for young offenders

app/move/views/create/assessment.njk
This fix updates the way the component is called to display the
information correctly.
A recent changed updated how assessment answers are transformed
in the presenter to load the child component.
This meant updating the way the components were called in the view and
in this instance it was missed.
This was introduced in #698  …
=> fix: Ensure assessment answers are rendered correctly

app/move/controllers/view.js, app/move/controllers/view.test.js, app/move/views/view.njk, app/person-escort-record/controllers/index.js, app/person-escort-record/controllers/print-record.js, app/person-escort-record/controllers/print-record.test.js, app/person-escort-record/index.js, app/person-escort-record/middleware.js, app/person-escort-record/middleware.test.js, app/person-escort-record/views/print-record.njk, common/lib/api-client/models.js, common/presenters/framework-step-to-summary.js, common/presenters/framework-step-to-summary.test.js, common/presenters/index.js, common/presenters/move-to-summary-list-component.js, common/presenters/move-to-summary-list-component.test.js, locales/en/actions.json, locales/en/assessment.json, locales/en/messages.json, package-lock.json, package.json, test/fixtures/api-client/person_escort_record.create.json, test/fixtures/api-client/person_escort_record.find.json
This extends the move detail page to include the print journey once a PER has been confirmed.
It adds a new banner and an action to the view print route for a Person Escort Record.
**Note:** this doesn't include the additional elements needed for the "PER cover sheet" or the move detail summary yet.
The PER needs to be printed out with the first release of this feature so this journey makes that clear
for users to do so.
- [P4-1801](https://dsdmoj.atlassian.net/browse/P4-1801)
<kbd><img src="https://user-images.githubusercontent.com/3327997/88915107-f9a29b00-d263-11ea-93db-ce4662b8940a.png"></kbd>
<kbd><img src="https://user-images.githubusercontent.com/3327997/88932712-bd306880-d27e-11ea-8006-cd710d7494c7.png"></kbd>
Commit messages with a `fix` …
=> [P4-1801] Create initial journey and view for Printing the Person Escort Record

app/person-escort-record/index.js
This moves the middleware to the correct place in the stack so that
it is not called when creating a new PER.
The middleware update caused a `404` when trying to create a new PER as it was trying to find one.
We only want that to occur on routes that require the PER to exist, like editing steps/confirming the PER.
summary of changes and that the commit body gives a more detailed description of …
=> Only use the set PER middleware for routes that require it

app/allocation/controllers/create/index.js, app/allocation/controllers/index.js, app/allocation/controllers/view.js, app/allocation/controllers/view.test.js, app/allocation/index.js, app/allocation/steps/cancel.js, app/allocation/steps/create.js, app/allocation/steps/remove-move.js, app/moves/index.js, app/moves/middleware/set-results.moves.js, app/moves/middleware/set-results.moves.test.js, common/presenters/move-to-card-component.js, common/presenters/move-to-card-component.test.js, common/presenters/moves-by-location.js, common/presenters/moves-by-location.test.js, common/presenters/profile-to-card-component.js, common/presenters/profile-to-card-component.test.js
Updates the card component to only show the tags from the Person Escort Record if the user has
permission to see the PER.
This feature is being incrementally released to users over time. So to cause the smallest disruption to users
who will not be on the new feature we want to keep the existing display of the dashboard and card components.
- [P4-1784](https://dsdmoj.atlassian.net/browse/P4-1784)
| <kbd><img src="https://user-images.githubusercontent.com/3327997/89096527-90439900-d3d7-11ea-8245-8ae75a3d8613.png"></kbd> | <kbd><img src="https://user-images.githubusercontent.com/3327997/89096551-ba955680-d3d7-11ea-9fff-5ed9ba6335d4.png"></kbd> |
| <kbd><img src="https://user-images.githubusercontent.com/3327997/89096442-0e537000-d3d7-11ea-930a-2224290dc8f …
=> [P4-1784] Only display tags from Person Escort Record if a user has permission

app/move/views/view.njk, app/person-escort-record/controllers/framework-step.js, app/person-escort-record/controllers/print-record.js, app/person-escort-record/controllers/print-record.test.js, app/person-escort-record/views/framework-overview.njk, app/person-escort-record/views/framework-section.njk, app/person-escort-record/views/framework-step.njk, app/person-escort-record/views/print-record.njk, common/assets/scss/core/_all.scss, common/assets/scss/core/_lists.scss, common/assets/scss/objects/_all.scss, common/assets/scss/objects/_image-placeholder.scss, common/assets/scss/overrides/_govuk-frontend.scss, common/assets/scss/utilities/_print.scss, common/presenters/framework-field-summary-list-row.js, common/presenters/framework-field-summary-list-row.test.js, locales/en/default.json, locales/en/person-escort-record.json
This introduces the more complex elements and items that need to be rendered on the Person Escort Record print layout like:
- photo placeholder
- checkboxes for attached documents and completed sections
- messages for attached medication or self-harm warnings
We need the print layout to replicate the existing paper document as closely as possible. This adds the elements
needed to make the printout a replacement for the existing paper document.
- [P4-1801](https://dsdmoj.atlassian.net/browse/P4-1801)
| <kbd><img src="https://user-images.githubusercontent.com/3327997/89157815-658b4900-d56d-11ea-8999-d2882301f99a.png"></kbd> | <kbd><img src="https://user-images.githubusercontent.com/3327997/89162753-cd915d80-d574-11ea-83f6-e3f05f9d9950.png"></kbd> |
|  | …
=> [P4-1801] Render more complex elements on PER print layout

app/person-escort-record/controllers/framework-step.js, app/person-escort-record/controllers/framework-step.test.js
This fix changes the `getValues` method to either return the error values
for when the page contains errors, or load the values only from the API.
Previously the framework step controller was extending the form wizard
session values.
However, for the this framework we always load in the values from the
API, unless there are errors.
This prevents a scenario where a conditional step has values, which
are then cleared out in the API. However, when a user navigates back
in the same session, that step contains values from the session which
override the values from the API. …
=> fix(framework): Don't use session values in form steps

locales/en/errors.json
Update the content for the default error handle to include NOMIS downtime.
The NOMIS service, which our service depends on for particular
journeys, will be offline between a set period over the weekend.
To improve the message for our users this change adds the known
offline time period so that users are aware what may be causing the
problem.
| <kbd><img src="https://user-images.githubusercontent.com/3327997/89639041-2b8faf00-d8ad-11ea-91f7-e87b16cf55c2.png"></kbd> | <kbd><img src="https://user-images.githubusercontent.com/3327997/89638946-00a55b00-d8ad-11ea-8bf6-c86438bdcfc7.png"></kbd> | …
=> Update NOMIS error message to contain scheduled downtime

common/assets/scss/overrides/_govuk-frontend.scss, common/components/add-another/add-another.yaml, common/components/add-another/macro.njk, common/components/add-another/template.njk, common/components/add-another/template.test.js, common/templates/layouts/base.njk, locales/en/actions.json, locales/en/default.json
Creates a new component to display fields as part of an "Add another" grouping.
- [P4-2005](https://dsdmoj.atlassian.net/browse/P4-2005)
<kbd><img src="https://user-images.githubusercontent.com/3327997/90235988-70be5e80-de22-11ea-8ad3-20e50eec83b8.png"></kbd>
=> [P-42005] Add "Add another" component for form wizard

app/person-escort-record/controllers/print-record.js, app/person-escort-record/controllers/print-record.test.js, app/person-escort-record/views/print-record.njk, common/assets/scss/utilities/_border.scss, locales/en/person-escort-record.json, package-lock.json, package.json
This adds a handover section to the print layout for the Person Escort Record that includes an area to record
the escort handover procedure as well as handover of property bags.
To replace part A of the Person Escort Record with our digital solution we need to provide
an area for the handover to be recorded. This uses the existing paper PER as a guide and
extends the print view to contain an area where handover can be recorded on a printout.
- [P4-1889](https://dsdmoj.atlassian.net/browse/P4-1889)
<kbd><img src="https://user-images.githubusercontent.com/3327997/90636125-748b2000-e22a-11ea-944e-39db1f7f5e23.png"></kbd>
<kbd><img src="https://user-images.githubusercontent.com/3327997/90636325-b9af5200-e22a-11ea-8b00-b5804d209851.png"></kbd>
Commit …
=> [P4-1889] Include handover section in Person Escort Record print layout

app/person-escort-record/controllers/framework-step.js
This changes the condition that determines whether to redirect to
the overview of a section to not check that the next step contains
the overview step.
This is to prevent the occurrence where the last step is actually
conditional and the user is then never redirected to the overview.
=> fix(framework): Change condition to cater for conditional last steps

app/home/controllers.js, app/home/controllers.test.js, app/home/dashboard.njk, common/controllers/collection/render-as-cards.js, common/controllers/collection/render-as-cards.test.js, common/controllers/collection/render-as-table.js, common/templates/layouts/collection.njk, config/nunjucks/filters.js, config/nunjucks/filters.test.js, locales/en/dashboard.json, test/e2e/pages/dashboard.js, test/e2e/smoke.test.js
Amend the dashboard to include the current week
| ![image](https://user-images.githubusercontent.com/1130499/88258389-a88a2880-ccf2-11ea-9ca4-c4fcb91f8217.png) | ![image](https://user-images.githubusercontent.com/1130499/88896536-89544380-d27c-11ea-8171-d93d0230fe72.png) |
| ![image](https://user-images.githubusercontent.com/1130499/89506704-190a6c80-d7fe-11ea-966e-f34b6c7d6801.png) | ![image](https://user-images.githubusercontent.com/1130499/89506748-2889b580-d7fe-11ea-9287-e247eef4da19.png) |
=> [P4-1323] Displayed the current week in the dashboard

.circleci/config.yml, app/allocation/fields/cancellation_reason_comment.js, app/move/fields/cancellation-reason-comment.js, app/move/views/_includes/person-escort-record-summary.njk, app/move/views/view.njk, app/person-escort-record/app/confirm/fields.js, common/presenters/framework-section-to-panel-list.js, common/presenters/framework-section-to-panel-list.test.js, common/services/frameworks.js, config/index.js, locales/en/assessment.json, locales/en/moves.json, locales/en/person-escort-record.json, test/e2e/_helpers.js, test/e2e/_roles.js, test/e2e/pages/move-detail.js, test/e2e/pages/page.js, test/e2e/person-escort-record.new.test.js
Adds end-to-end test suite to test basic Person Escort Record journeys in a browser.
These tests were initially missed off due to tight deadlines to this is helping to fill that gap and prevent future regressions.
- [P4-1994](https://dsdmoj.atlassian.net/browse/P4-1994)
=> [P4-1994] Person escort record end-to-end tests

app/move/controllers/create/move-details.js, app/move/controllers/create/move-details.test.js, app/move/controllers/create/save.js, app/move/fields/index.js, app/move/fields/move-type.js, app/move/fields/to-location-secure-childrens-home.js, app/move/fields/to-location-secure-training-centre.js, app/move/steps/create.js, app/move/views/confirmation.njk, app/move/views/view.njk, common/lib/permissions.js, common/lib/user.test.js, common/services/move.js, common/services/move.test.js, locales/en/fields.json, locales/en/messages.json, locales/en/moves.json, test/e2e/_move.js, test/e2e/pages/create-move.js
Enable new moves YOI/SCH/STC to YOI/SCH/STC .
Caveats:
- The API doesn't return a type for a YOI. YOI locations are prisons.
- YOI to YOI transfers are prison transfers.
- When a move is created, it's only possible to update the destination in the same category (if you chose STC as the destination, you can only choose another STC).
- All YOI/SCH/STC moves have a mandatory "upload risk assessment" step.
- STC/SCH users should be granted permission to create prison moves.
=> [P4-1997] SHC and STC transfer moves

app/person-escort-record/controllers/print-record.js, common/components/framework-response/template.njk, common/helpers/frameworks/reduce-responses-to-form-values.js, common/helpers/frameworks/responses-to-save-reducer.js, common/presenters/framework-section-to-panel-list.js, test/e2e/_helpers.js
This change extends all calls to particular types to include both
the existing value plus the new value so that it can be released without
causing any breaking changes.
The value types coming from the API have been updated to support a new
pattern that was introduced to cater for multiple types of collections
or objects.
This means that we need to update the references to them in the frontend
so that things still work correctly.
- [P4-2080](https://dsdmoj.atlassian.net/browse/P4-2080)
[GitHub release notes](https://github.com/ministryofjustice/hmpps-book-secure-move-frontend/ …
=> [P4-2080] Update value types to use new API response values

common/lib/permissions.js, common/lib/user.test.js
Further requirements for how SCH/STC moves have come to light
This commit should be reverted when those issues have been addressed
- [P4-2106](https://dsdmoj.atlassian.net/browse/P4-2106)
=> Disable creation of moves to SCH and STC

common/helpers/frameworks/responses-to-save-reducer.js, common/helpers/frameworks/responses-to-save-reducer.test.js
This improvement uses a circular approach to reducing the responses
from a nested response type, like `collection::add_multiple_items`,
in order to re-use as much as possible.
This change also includes unit test coverage to the missing lines.
It also includes a simplification of how we determine what _type_ a response
needs to be formatted into.
In order to meet the tight deadlines this reducer was only built to
cater for the nested response types that were needed for that release.
The code wasn't unit tested fully and didn't cater for the other
known response types at the time.
- [P4-2073](https://dsdmoj.atlassian.net/browse/P4-2073) …
=> [P4-2073] Cater for all nested response types from the PER framework

common/components/framework-response/framework-response.yaml, common/components/framework-response/template.njk, common/components/framework-response/template.test.js, common/helpers/frameworks/reduce-responses-to-form-values.js, common/helpers/frameworks/reduce-responses-to-form-values.test.js, common/helpers/frameworks/responses-to-save-reducer.js, common/presenters/framework-section-to-panel-list.js, common/presenters/framework-section-to-panel-list.test.js, test/e2e/_helpers.js
This change removes references to the legacy names as they have been
removed from the API responses.
The value types for the Person Escort Record framework were updated
to cater for multiple types of object or collection.
- [P4-2080](https://dsdmoj.atlassian.net/browse/P4-2080)
**NOTE:** This change depends on a [breaking API change](https://github.com/ministryofjustice/hmpps-book-secure-move-api/pull/887) and shouldn't be merged until this has been deployed.
[GitHub release notes](https://github.com/ministryofjustice/hmpps-book-secure-move-frontend/releases) during the …
=> [P4-2080] Remove references to legacy value types

package-lock.json, package.json
```
@govuk-frontend                       3.8.0  →   3.8.1
```
n/a
n/a
=> Upgrade govuk-frontend to 3.8.1

nodemon.json
Add a small delay to nodemon restart
On running `npm run develop` the console is spammed with a large number of nodemon restart messages
```
...
[nodemon] restarting due to changes...
[nodemon] restarting due to changes...
[nodemon] restarting due to changes...
[nodemon] restarting due to changes...
...
```
This is because `watch:js:client` is still running wepack after `watch:js:server` is ready. 
Adding a small 200ms delay appears to be enough for `nodemon` to delay restarting, without unduly affecting behaviour during normal development.
n/a
n/a
n/a
n/a …
=> chore: Add small delay to nodemon to improve console logging on startup

app/move/views/assign/no-special-vehicle.njk
This change updates the template inheritance correctly so that the
message will appear. It also fixes a stray `s` which could have come
from an attempted save shortcut.
The template used to display the special vehicle message was inheriting
from a template that didn't contain the block being set in the template.
This led to the message not being displayed correctly.
| <kbd><img src="https://user-images.githubusercontent.com/3327997/92308667-36fef480-ef97-11ea-917b-b10cbf469796.png"></kbd> | <kbd><img src="https://user-images.githubusercontent.com/3327997/92308645-16369f00-ef97-11ea-972c-d321f8117086.png"></kbd> | …
=> fix: Inherit from correct template on special vehicle message step

common/presenters/framework-field-summary-list-row.js, common/presenters/framework-field-summary-list-row.test.js
This change adds a fix to display the "Answer question" text when
a response with a type of `add_multiple_items` has no items.
It will now fallback to the existing part of the presenter instead
of trying to do the custom logic for handling this response type.
This change also includes the addition of some missing unit tests.
Previously it would not show a message when there were not items for this response type.
- [P4-2070](https://dsdmoj.atlassian.net/browse/P4-2070)
- [P4-2072](https://dsdmoj.atlassian.net/browse/P4-2072)
| <kbd><img src="https://user-images.githubusercontent.com/3327997/92596564-eab8fa80-f29d-11ea-9e64-ee0e66fc1e66.png"></kbd> | <kbd><img src="https://user-images.githubusercontent.com/3327997/92596387-a594c880-f29d-11ea-8294-b1df140 …
=> [P4-2072] Handle empty multiple items response types

app/person-escort-record/controllers/print-record.js, app/person-escort-record/controllers/print-record.test.js, app/person-escort-record/views/print-record.njk, common/components/message/_message.scss, common/components/tag/_tag.scss
Adds warning badges/tags to PER print record
Font size is reduced to prevent the likelihood of wrapping the completed sections part on to the next page
- [P4-2003 - PER Print; show warning badges on the overview sheet](https://dsdmoj.atlassian.net/browse/P4-2003)
| <kbd>![print-screen-old](https://user-images.githubusercontent.com/4856/92604905-f8c04880-f2a8-11ea-98f9-ed7ee4ec1d45.png)</kbd> | <kbd>![print-screen-new](https://user-images.githubusercontent.com/4856/92604983-15f51700-f2a9-11ea-8fd3-404f0a57c925.png)</kbd> |
| <kbd>![print-old](https://user-images.githubusercontent.com/4856/92604959-0d044580-f2a9-11ea-99f8-6b28742929f4.png)</kbd> | <kbd>![print-new](https://user-images.githubusercontent.com/4856/92605032-21e0d900-f2a9-11ea-8bdd-7f8c780c03 …
=> Show warning badges on PER print record

locales/en/fields.json
Change the labelling from Prison to Prison or Youth Offender Institution
- [P4-2108](https://dsdmoj.atlassian.net/browse/P4-2108)
=> [P4-2108] Amend Prison labelling

config/index.js
Check `REDIS_HOST` as well as `REDIS_URL` when considering whether to use redis
App broken in a production-like environment without it
n/a
n/a
=> build: Check for REDIS_HOST as well as REDIS_URL

app/healthcheck/controllers.js, app/healthcheck/controllers.test.js, common/lib/api-client/request-headers.js, common/lib/api-client/request-headers.test.js, config/index.js
Add user agent string to api client
This enables us to distinguish our client requests from others using the same library
n/a
n/a
=> Add user agent string to api client

common/services/component.js
This change is trying to show the keys for the second level objects
to try and give a clue as to where the circular structure exists.
This extends the debugging to try and resolve a production bug
where a circular structure is being passed to `JSON.stringify`.
The structure of the top level keys appears correct but somewhere in
the params object there is a circular structure.
summary of changes …
=> chore: Expand params debugging

.circleci/config.yml, common/lib/user.js, common/lib/user.test.js, common/middleware/locals.js, common/middleware/sentry-enrich-scope.js, common/middleware/sentry-enrich-scope.test.js, common/middleware/set-user.js, common/middleware/set-user.test.js, server.js
This adds the username and permissions to the Sentry user data sent
when issues occur.
This will allow us to see who is seeing errors and provide extra
information to try and replicate the error.
=> Add extra data to Sentry with issues

common/services/component.js
This change removes the extra debugging added to try and understand
a production bug.
A error occuring on production needing some extra logging to attempt
to debug it in that environment.
=> chore: Remove extra debugging from production error

package.json
Improve `npm run lint` times by using `eslint` caching - 
```
$ time npm run lint
> hmpps-book-secure-move-frontend@2.44.1 lint hmpps-book-secure-move-frontend
> eslint . --cache
npm run lint  65.57s user 1.86s system 127% cpu 52.901 total
```
```
$ time npm run lint
> hmpps-book-secure-move-frontend@2.44.1 lint hmpps-book-secure-move-frontend
> eslint . --cache
npm run lint  1.49s user 0.22s system 113% cpu 1.502 total
```
- [P4-XXXX]() …
=> chore: Use eslint caching

common/services/move.js, common/services/move.test.js, common/templates/collection-as-cards.njk, config/index.js, mocks/auth-server.js, test/e2e/_move.js, test/e2e/_roles.js, test/e2e/_routes.js, test/e2e/moves.dashboard.test.js, test/e2e/pages/moves-dashboard.js
This fix adds the include for `from_location` to the API call to get
a list of moves.
During a [refactor to improve the speed](https://github.com/ministryofjustice/hmpps-book-secure-move-frontend/commit/2b3d01bc2f00aa9c1935cf639909c7264bb634b0) of the dashboards one of the
includes needed to render the incoming dashboard was removed.
This meant that incoming moves were not grouped by their origin.
- [P4-2279](https://dsdmoj.atlassian.net/browse/P4-2279)
| <kbd>![image](https://user-images.githubusercontent.com/3327997/94036026-c0962b00-fdbb-11ea-9562-69177e811c20.png)</kbd> | <kbd>![image](https://user-images.githubusercontent.com/3327997/94035874-8f1d5f80-fdbb-11ea-8b18-1ddd219adbff.png)</kbd> |
Commit …
=> [P4-2279] Show origin on incoming dashboard

test/e2e/parallel-runner.js
Remove git sha check on master for end-to-end tests.
The tests are no longer run against the staging instance so this check
will prevent the tests from running on master.
=> chore: Remove SHA check from CI test runner

.circleci/config.yml
This uses the same method for running tests against all environments now.
Previously end-to-end tests were being run against staging environments
and their respective auth services.
The staging auth service now requires two-factor authentication for some
users which prevents the tests from running as before.
For staging and PRs we moved to using a mock auth service and running
tests in the same instance on CI.
We forgot to do this for the release pipeline which caused it to fail.
[GitHub release notes](https://github.com/ministryofjustice/hmpps-book-secure-move-frontend/relea …
=> build: Always run end-to-end tests in same instance

package-lock.json, package.json
This adds a depedency to support the latest version of the Book a
secure move frameworks to include updates for supporting NOMIS
information within the Person Escort Record.
The new version is required for the frontend and API to support displaying NOMIS information
as part of the Person Escort Record journeys. …
=> build: Update Person Escort Record framework

common/components/framework-response/framework-response.yaml, common/components/framework-response/template.njk, common/components/framework-response/template.test.js, common/presenters/framework-field-summary-list-row.js, common/presenters/framework-field-summary-list-row.test.js, locales/en/person-escort-record.json
This adds the NOMIS information related to a particular question to the overview page.
We now populate some questions with relevant NOMIS information to reduce the amount of copying between systems that is needed. This also shows the same information on the section overview page.
- [P4-2177](https://dsdmoj.atlassian.net/browse/P4-2177)
<kbd><img src="https://user-images.githubusercontent.com/3327997/95437384-cf004d00-094c-11eb-9d83-2fb2484f0d87.png"></kbd>
<kbd><img src="https://user-images.githubusercontent.com/3327997/95437635-21416e00-094d-11eb-8bce-ddbec05fde73.png"></kbd>
Commit messages with a `fix` or `feat` type are automatically used to generate the [changelog](ministryofjustice/hmpps-book-secure-move-frontend/blob/master/CHANGELOG.md) …
=> [P4-2177] Render NOMIS information on overview page

README.md, app/person-escort-record/views/framework-section.njk, common/assets/scss/components/_all.scss, common/components/feedback-prompt/_feedback-prompt.scss, common/components/feedback-prompt/feedback-prompt.yaml, common/components/feedback-prompt/macro.njk, common/components/feedback-prompt/template.njk, common/components/feedback-prompt/template.test.js, common/templates/layouts/base.njk, config/index.js, config/nunjucks/globals.js, locales/en/person-escort-record.json
This change adds a feedback prompt to the bottom of the section
overview page.
If the variable is not set, the banner will not be shown.
This allows us to link to a URL defined by an environment variable.
- [P4-2179](https://dsdmoj.atlassian.net/browse/P4-2179)
<kbd>![localhost_3000_move_145f9ef5-dc68-4406-89d3-252e5ef27a4f_person-escort-record_offence-information (1)](https://user-images.githubusercontent.com/3327997/96002734-5ceaa500-0e31-11eb-8385-ea445bbe0ddd.png)</kbd>
[GitHub release notes](https://github.com/ministryofjustice/hmpps-book-secure-move-frontend/releases) …
=> [P4-2179] Collect feedback for Person Escort Record

CODE_OF_CONDUCT.md, CONTRIBUTING.md, README.md, docs/coding-standards.md, docs/development.md, docs/environment-variables.md, docs/project-structure.md, docs/releasing.md, docs/testing.md
Improve documentation by adding Contributing guidelines
Also, add a code of conduct, and restructure the development documentation a little bit
- Contributing Guidelines based on https://github.com/alphagov/govuk-frontend/blob/master/CONTRIBUTING.md
- Code of Conduct based on  https://github.com/ministryofjustice/moj-design-system-backlog/blob/master/docs/CODE_OF_CONDUCT.md
summary of changes and …
=> docs: Add contributing guidelines

test/e2e/parallel-runner.js
Allow environment variables set at the project level tp be overridden for current PR
eg. Given a Github PR number of 123
if set, the env var PR123_E2E_VIDEO will be used in place of E2E_VIDEO
Also fixes a bug where env vars set as `false` ended up being true - process.env[foo] values are always stringified (which makes sense)
Enable specific PRs to change the env vars they are using to run the e2e tests without having to change the values for all runs
n/a
n/a
=> chore: Add ability to specify different env vars for each PR

common/assets/scss/components/_all.scss, common/assets/scss/components/_focus-table.scss, common/presenters/index.js, common/presenters/population-table/locations-to-population-table-component.js, common/presenters/population-table/locations-to-population-table-component.test.js, common/presenters/population-table/population-table-config.js, common/presenters/population-table/population-table-config.test.js, config/i18n.js, locales/en/population.json
As a part of the new PMU dashboard, there is a new table for displaying population data. This population table is a slightly different table to the existing ones.
The features that make it different are:
- dynamically generates column headers for Monday-Friday based upon a date
- applyig a focus styling to a day that matches (usually today)
- using an index set of values, as opposed to object properties, to render some of the table data
This PR adds this table as a new component.
- The links to establishments and spaces are currently not useful - these will be improved by the subsequent ticket involving these pieces of functionality.
- Missing population data currently causes an error - this has been left during this development phase to ensure any appropriate changes on the frontend or …
=> feat: Add PMU population table component

package-lock.json, package.json
Increase the frameworks version
A new NOMIS code was added so this supports the latest version.
=> build: Update frameworks version

test/e2e/_helpers.js
This updates the tests so that locations without a supplier are filtered
out from the list of locations to prevent the test intermittently
failing when creating move fixtures.
The API requires a from location to have a supplier otherwise it will
return a validation error.
=> test: Ensure fixture uses from locations with a supplier

package-lock.json, package.json
Increases the frameworks version
Includes changes made to the prefilling rules for the Person Escort Record.
=> build: Increase frameworks version

common/presenters/population-table/population-table-config.js, common/presenters/population-table/population-table-config.test.js
Fix an issue with the population table throwing an error instead of showing "Add" when config function is supplied with partially missing data
- [P4-1420](https://dsdmoj.atlassian.net/browse/P4-1420)
=> [P4-1420] fix: Handle missing data from BE service correctly

common/lib/api-client/models.js, common/lib/api-client/models.test.js, common/services/locations-free-spaces.js, common/services/locations-free-spaces.test.js, test/fixtures/api-client/locations_free_spaces.findAll.json
Add a new service to connect to the `locations_free_spaces` endpoint. This endpoint provides availability data as meta properties based on the existing location reference data.
- `getLocationsFreeSpaces` - general method for all free spaces
- `getPrisonFreeSpaces` - convenience method for the main use case of prison spaces
Also contains model code and tests
- [P4-1420](https://dsdmoj.atlassian.net/browse/P4-1420)
[GitHub release notes](https://github.com/ministryofjustice/hmpps-book-secure-move-frontend/releases) during the release task. Please make sure they will read well …
=> [P4-1420] feat: Add location-free-spaces service

app/allocation/controllers/view.js, app/allocation/controllers/view.test.js, app/allocation/index.js, app/move/controllers/view.js, app/move/controllers/view.test.js, app/moves/index.js, app/moves/middleware/set-results.moves.js, app/moves/middleware/set-results.moves.test.js, config/index.js, docs/environment-variables.md
This change is cleaning up the code used during the release process.
This feature has been fully released so we no longer need the ability
to turn it off per environment.
- [P4-XXXX]()
Closes #896 - this is no longer needed to show where this feature flag was being used.
=> chore: Remove Person Escort Record feature flag

app/README.md
Add some documentation on how the modules are configured and used.
- ~[ ] Added unit tests to cover changes~
- ~[ ] Added end-to-end tests to cover any journey changes~
~Has been tested in the following browsers:~
~- [ ] Chrome~
~- [ ] Firefox~
~- [ ] Edge~
~- [ ] Internet Explorer~
=> docs: Add docs on module usage

common/lib/clear-cache-reference-data.js, common/lib/clear-cache-reference-data.test.js, docs/releasing.md, package-lock.json, package.json, tasks/clear-cache-reference-data.js
Added clear-cache-reference-data.js, a script that can be used to clear reference data out of the Redis cache.
This has been added because currently, all reference data is being cached for 1 week. While this is fine for data that won't change often (gender, ethnicity, etc), it's not great for data that can change more often (locations, etc).
This script can be used manually, or scheduled as a task in CircleCI and can be ran with the following:
`node tasks/clear-cache-reference-data.js DATA_NAME`
OR
`npm run clear-cache-reference-data -- DATA_NAME`
`DATA_NAME` can be replaced with any reference data name, full list:
```
genders
ethnicities
assessment_questions
locations
regions
suppliers
prison_transfer_reasons
allocation_complex_cases
\*
```
- …
=> [P4-2400] Add clear-cache script

common/components/timeline/README.md, common/components/timeline/_timeline.scss, common/components/timeline/template.njk, common/components/timeline/template.test.js, common/components/timeline/timeline.yaml, common/presenters/events-to-timeline-component.js, common/presenters/events-to-timeline-component.test.js, config/i18n/interpolation.js, config/i18n/interpolation.test.js, locales/en/events.json
- Updated timeline component 
- to add a container element inside the item wrapping the item contents
- to allow classes to be added to that container and the item header container
- Added flag value to medical event type and incidents that require them
Also 
- uppercased display of person name in timeline
- added missing JourneyCreate and JourneyUpdate events
- reduced size of event title when displayed as badges
- [P4-2501 - Display Red Flag events in correct panel](https://dsdmoj.atlassian.net/browse/P4-2501)
- [P4-2502 - Display Medical Flag events in correct panel](https://dsdmoj.atlassian.net/browse/P4-2502)
- [P4-2508 - Add strings to support JourneyCreate.heading & JourneyUpdate.heading](https://dsdmoj.atlassian.net/browse/P4-2508)
| …
=> Add flags to timeline events

app/population/controllers/daily.js, app/population/controllers/daily.test.js, app/population/views/daily.njk, common/presenters/population-table/population-table-config.js, common/presenters/population-table/population-table-config.test.js
Link to the edit population page from both the weekly population view and the daily summary view
=> chore: Use correct population edit links

package-lock.json, package.json
Updates the framework to the latest version.
To support a change to NOMIS mappings.
=> chore: Update frameworks to v1.5.3

common/services/population.js
Linting issue was triggered on another PR
- [P4-XXXX]()
=> chore: Fix linting issue

CONTRIBUTING.md
Link to feature flags was broken in github
- [P4-XXXX]()
=> docs: Fix link to feature flags

common/middleware/set-primary-navigation.js, common/middleware/set-primary-navigation.test.js, config/index.js, locales/en/default.json
Add population link to the primary navigation, hidden behind a feature flag
- Added a feature flag for showing the dashboard
- Added a filter to `primary-navigation` to check for feature flags
- [P4-XXXX]()
=> feat: Add population link to dashboard

app/population/controllers/edit.js, app/population/controllers/edit.test.js, app/population/steps/edit.js, locales/en/actions.json
If an existing population is being edited, use "Change numbers", otherwise if this is a new population, use "Add numbers"
- [P4-2548](https://dsdmoj.atlassian.net/browse/P4-2548)
| ![Screenshot_2020-12-02 Population Details - create_population(3)](https://user-images.githubusercontent.com/196695/100874768-fa12a300-349c-11eb-835f-f4821f7a7a7f.png) | ![Screenshot_2020-12-02 Population Details - create_population](https://user-images.githubusercontent.com/196695/100874756-f54def00-349c-11eb-83b4-1f14f303ae9c.png) |
| ![Screenshot_2020-12-02 Population Details - create_population(1)](https://user-images.githubusercontent.com/196695/100874774-faab3980-349c-11eb-99af-b577cc148b1f.png) | ![Screenshot_2020-12-02 Population Details - …
=> P4 2548 population confirm button

app/population/controllers/edit.js, app/population/controllers/edit.test.js
Add cancel link that returns to the population grid if this was creating new population, or the details screen if this was editing a population
- [P4-2549](https://dsdmoj.atlassian.net/browse/P4-2549)
| ![Screenshot_2020-12-02 Population Details - create_population](https://user-images.githubusercontent.com/196695/100875270-b4a2a580-349d-11eb-804f-8539946757c1.png) | ![Screenshot_2020-12-02 Population Details - create_population(5)](https://user-images.githubusercontent.com/196695/100875221-a2c10280-349d-11eb-8fe2-37951016b4c6.png) |
| ![Screenshot_2020-12-02 Population Details - create_population(2)](https://user-images.githubusercontent.com/196695/100875268-b40a0f00-349d-11eb-9593-59c58b2f2b74.png) | ![Screenshot_2020-12-02 Population Details - …
=> P4 2549 population cancel link

app/move/views/_includes/person-escort-record-summary.njk, app/move/views/view.njk, common/lib/api-client/models/move.js, common/lib/api-client/transformers/index.js, common/lib/api-client/transformers/move.transformer.js, common/lib/api-client/transformers/move.transformer.test.js, common/presenters/framework-section-to-panel-list.js, common/presenters/framework-section-to-panel-list.test.js, common/presenters/profile-to-card-component.js, common/presenters/profile-to-card-component.test.js, locales/en/assessment.json, locales/en/person-escort-record.json
This includes some changes to help add support for the youth risk assessment.
It:
- refactors the way the assessment answers and frameworks are rendered on the view template so that they share the same method
- adds an extra property to the move that can be used to determine logic for the youth risk assessment.
The youth risk assessment is another framework that needs to be supported alongside the existing data that comes from the move request as well as data that comes from the person escort record.
These changes allow this logic to be simplified and allows more re-use of existing patterns.
- [P4-2391](https://dsdmoj.atlassian.net/browse/P4-2391) …
=> [P4-2391] Move transformer

app/move/controllers/create/save.js, app/move/controllers/create/save.test.js, common/middleware/set-services.js, common/middleware/set-services.test.js, common/services/index.js, server.js
Adds middleware which instantiates the services on the `req` . Updates how the court hearing service is used as an example.
This is the first step towards the services getting access to the request context. It transitions the court hearing service to the new approach as an example. …
=> chore: Add services to request middleware

app/move/controllers/review.js, app/move/controllers/review.test.js, app/moves/middleware/set-download-results.single-requests.js, app/moves/middleware/set-download-results.single-requests.test.js, app/moves/middleware/set-filter.single-requests.js, app/moves/middleware/set-filter.single-requests.test.js, app/moves/middleware/set-results.single-requests.js, app/moves/middleware/set-results.single-requests.test.js
Make use of the new setServices middleware for the single request service. Part of the work to enable request context in services. …
=> refactor: Use the single request service initiated in the middleware in every relevant controller

app/move/controllers/assign/save.js, app/move/controllers/assign/save.test.js, app/move/controllers/create/assessment.js, app/move/controllers/create/assessment.test.js, app/move/controllers/create/save.js, app/move/controllers/create/save.test.js, app/move/controllers/update/assessment.js, app/move/controllers/update/assessment.test.js, app/move/controllers/update/document.js, app/move/controllers/update/document.test.js, common/services/index.js
Make use of the new setServices middleware for the profile service. Part of the work to enable request context in services. …
=> refactor: Use the profile service initiated in the middleware in every relevant controller

app/move/steps/create.js
This adds support to use a new feature flag to change the journey
for youth moves based on whether or not it is enabled.
Youth moves now need to bypass the risk, health and document upload
sections when creating a move because this information is filled in
during the youth risk assessment.
=> [P4-2377] chore: Feature flag youth move journey changes when creating

common/lib/permissions.js, common/lib/user.test.js
This adds some app level permissions to the PER and youth roles.
Those users who only have the Person Escort Record author role sometimes need access to the incoming dashboard as well so that they can manage incoming people.
The youth risk assessment is only available to those in the youth estate so this adds the relevant permissions to those roles.
- [P4-2390](https://dsdmoj.atlassian.net/browse/P4-2390)
- [P4-2524](https://dsdmoj.atlassian.net/browse/P4-2524)
[GitHub release notes](https://github.com/ministryofjustice/hmpps-book-secure-move-frontend/releases) during the …
=> [P4-2524] [P4-2390] Update permission for PER and Youth Risk Assessment

locales/en/default.json
This amends the text used when an optional question has been reviewed
and no answer given.
In some instances, during user research, it wasn't clear that a question had been submitted without an answer. This copy update attempts to make that more clear.
- [P4-2523](https://dsdmoj.atlassian.net/browse/P4-2523)
=> [P4-2523] Update fallback text for framework responses

app/allocation/controllers/cancel.js, app/allocation/controllers/cancel.test.js, app/allocation/controllers/create/save.js, app/allocation/controllers/create/save.test.js, app/allocation/middleware.js, app/allocations/middleware/set-filter.allocations.js, app/allocations/middleware/set-filter.allocations.test.js, app/allocations/middleware/set-results.allocations.js, app/allocations/middleware/set-results.allocations.test.js, app/move/middleware.js, app/move/middleware.test.js
Make use of the new setServices middleware for the allocation service. Part of the work to enable request context in services. …
=> refactor: Use the allocation service initiated in the middleware in every relevant controller

app/allocation/controllers/remove-move.js, app/move/controllers/assign/save.js, app/move/controllers/assign/save.test.js, app/move/controllers/cancel.js, app/move/controllers/cancel.test.js, app/move/controllers/create/save.js, app/move/controllers/create/save.test.js, app/move/controllers/unassign.js, app/move/controllers/unassign.test.js, app/move/controllers/update/base.js, app/move/controllers/update/base.test.js, app/move/controllers/update/move-details.js, app/move/controllers/update/move-details.test.js, app/move/controllers/view.js, app/move/controllers/view.test.js, app/move/middleware.js, app/move/middleware.test.js, app/moves/middleware/set-download-results.moves.js, app/moves/middleware/set-download-results.moves.test.js, app/moves/middleware/set-filter.moves.js, app/moves/middleware/set-filter.moves.test.js, app/moves/middleware/set-results.moves.js, app/moves/middleware/set-results.moves.test.js, app/population/middleware/set-population.js, app/population/middleware/set-population.test.js, common/lib/populate-resources.js, common/lib/populate-resources.test.js
Make use of the new setServices middleware for the move service. Part of the work to enable request context in services.
=> P4 1776 refactor move service

common/lib/multer.api-document.storage.js, common/lib/multer.api-document.storage.test.js
Make use of the new setServices middleware for the document service. Part of the work to enable request context in services.
summary of …
=> refactor: Use the document service initiated in the middleware in every relevant controller

app/person-escort-record/app/confirm/controllers.js, app/person-escort-record/app/confirm/controllers.test.js, app/person-escort-record/app/new/controllers.js, app/person-escort-record/app/new/controllers.test.js, app/person-escort-record/index.js, app/youth-risk-assessment/index.js, common/lib/populate-resources.js, common/lib/populate-resources.test.js, common/middleware/framework/set-record.js, common/middleware/framework/set-record.test.js
Make use of the new setServices middleware for the PER service. Part of the work to enable request context in services.
=> refactor: Update controllers to use PER service from req

server.js
The setServices middleware was moved further up the chain.
When running in development mode, the development middleware makes use of the services on the req object, so they need to be set before it.
- [P4-1776]()
=> refactor: Move set services middleware so the services are available for development middleware

common/middleware/set-api-client.js, common/middleware/set-api-client.test.js, common/middleware/set-services.js, common/middleware/set-services.test.js, common/services/base.js, common/services/court-hearing.js, common/services/court-hearing.test.js, server.js
The serServices middleware checks if the service is a function, and if so, passes the api client which has been initiated on the req. The end result for the controllers is the same.
Court hearing service updated as an example of what would need to change for each service.
This work is part of sending the request context to the backend.
- [P4-1776]()
summary of changes and that the commit body …
=> refactor: Update setServices to check if service is function and pass req if so

common/services/single-request.js, common/services/single-request.test.js
Converts single request service to class which takes the req object on instantiation.
=> refactor: Update single request service

common/services/base.js, common/services/person.js, common/services/person.test.js, test/e2e/_helpers.js
The person service has been converted to an actual class, rather than an object with functions.
This has changed so that in the future, we can pass the request through to the api client. …
=> refactor: Convert person service to a class

common/services/base.js, common/services/batch-request.js, common/services/batch-request.test.js, common/services/move.js, common/services/move.test.js, common/services/single-request.js, common/services/single-request.test.js, test/e2e/_helpers.js
Converts move service to class which takes the req object on instantiation. Tweaks batch request so that the right api client is used for the requests. Updates the single request service constructor so it can access the move service from req.
[GitHub release notes](https://github.com/ministryofjustice/hmpps-book-secure-move-frontend/releases) during the release task. Please make sure they will read …
=> P4 1776 update move service

common/components/add-another/add-another.yaml, common/components/add-another/template.njk, common/components/add-another/template.test.js, common/services/frameworks.js, common/services/frameworks.test.js, package-lock.json, package.json
This adds support for:
- prefixes and suffixes
- hint text for add another fields
Content changes to the framework have added support for these new features. This means the frontend needs to
also support importing and rendering these features.
- [P4-2438](https://dsdmoj.atlassian.net/browse/P4-2438)
<kbd>![image](https://user-images.githubusercontent.com/3327997/102228035-24735000-3ee2-11eb-97fd-955885f9352a.png)</kbd>
<kbd>![image](https://user-images.githubusercontent.com/3327997/102228183-51276780-3ee2-11eb-80a8-366023ae544f.png)</kbd>
=> [P4-2438] Add support for additional features from framework

app/move/views/view.njk, common/assets/scss/objects/_interruption-card.scss, common/controllers/framework/framework-overview.js, common/controllers/framework/framework-overview.test.js, common/controllers/framework/framework-section.js, common/controllers/framework/framework-section.test.js, common/controllers/framework/framework-step.js, common/controllers/framework/framework-step.test.js, common/helpers/move/get-move-with-summary.js, common/helpers/move/get-move-with-summary.test.js, common/helpers/move/index.js, common/middleware/set-move-with-summary.js, common/middleware/set-move-with-summary.test.js, common/templates/framework-overview.njk, common/templates/framework-section.njk, common/templates/framework-step.njk, common/templates/includes/move-summary.njk
Adds person and move details to sidebar on PER overview, section and step pages.
Missing feature - always part of design
- [P4-1992 - PER: Add person and move details in right hand rail](https://dsdmoj.atlassian.net/browse/P4-1992)
| After | Before |
| <kbd>![Person_Escort_Record_for_MCGLYNN__CLAIRE_–_Book_a_secure_move](https://user-images.githubusercontent.com/4856/101931351-321e9200-3bd1-11eb-960a-cc871ac45a94.png)</kbd> | <kbd>![Person_Escort_Record_for_MCGLYNN__CLAIRE_–_Book_a_secure_move](https://user-images.githubusercontent.com/4856/101931415-495d7f80-3bd1-11eb-8888-958d8ef5fee7.png)</kbd> |
| <kbd>![Risk_information_overview_–_Person_Escort_Record_–_Book_a_secure_move](https://user-images.githubusercontent.com/4856/101931526-76aa2d80-3bd1-11eb-8bbf-79c2496cb83d. …
=> Add person and move details in right hand rail of PER views [P4 1992]

common/controllers/framework/framework-step.js, common/controllers/framework/framework-step.test.js, common/services/single-request.js, common/services/youth-risk-assessment.js, common/services/youth-risk-assessment.test.js
The youth risk assessment service has been converted to a class extending BaseService.
This change was necessary so that we can pass request through to the api client in the future. …
=> refactor: Convert youth risk assessment to a class

common/services/allocation.js, common/services/allocation.test.js
Converts move service to class which takes the req object on instantiation. 
=> refactor: Update allocation service to class

common/services/locations-free-spaces.js, common/services/locations-free-spaces.test.js
Converts locations free spaces service to class which takes the req object on instantiation.
=> refactor: Update locations free spaces service

common/services/person-escort-record.js, common/services/person-escort-record.test.js, test/e2e/_helpers.js
Converts PER service to class which takes the req object on instantiation.
=> refactor: Update PER service

common/services/reference-data.js, common/services/reference-data.test.js, common/services/user.js, common/services/user.test.js, test/e2e/_helpers.js
Converts the reference data service to class which takes the req object on instantiation. 
=> refactor: Convert reference data service to class

common/services/population.js, common/services/population.test.js
Converts population service to class which takes the req object on instantiation.
=> refactor: Update population service

common/services/profile.js, common/services/profile.test.js, test/e2e/_helpers.js
Converts profile service to class which takes the req object on instantiation.
=> refactor: Update profile service

common/helpers/events/event-details-helpers.js, common/helpers/events/event-details-helpers.test.js, common/lib/api-client/models/event.js, common/presenters/event-to-timeline-item-component.js, common/presenters/event-to-timeline-item-component.test.js
Events on timeline now optionally support and display the created by attribute, showing the user who kicked off the event.
Part of work to enable visibility of who did what changes to a move.
- [P4-1716](https://dsdmoj.atlassian.net/browse/P4-1716)
| <kbd><img src="https://user-images.githubusercontent.com/4950775/102781967-714aa100-4390-11eb-9dba-a044a9b41d9c.png"></kbd> | <kbd><img src="https://user-images.githubusercontent.com/4950775/102781793-2cbf0580-4390-11eb-8821-5bd7c2b6d873.png"></kbd> …
=> feat: Show created by for move events

common/lib/api-client/auth.js, common/lib/api-client/auth.test.js, common/lib/api-client/middleware/get-cache.js, common/lib/api-client/middleware/request.js, common/lib/api-client/middleware/request.test.js
This change tweaks the way the debugger is called to make it
more succinct in some places and provide more information about
what is being called/stored.
=> chore: Improve debug logging for API client

common/lib/api-client/auth.js, common/lib/api-client/auth.test.js
This change refactors that piece of code to set a promise with the first
call. If any other subsequent calls comes in before that promise has
resolved it will wait for the first promise to resolve before returning
the token for the following calls.
Currently, if the token expires on a page which requires multiple API
calls that are fired off simultaneously, it will attempt to refresh the
token for each call.
This increases the page load time and in some cases can lead to timeouts
as the API is being hit a large number of times.
=> fix: Prevent multiple simultaneous API token refresh calls

app/population/controllers/dashboard.js, app/population/controllers/dashboard.test.js, test/e2e/_roles.js, test/e2e/_routes.js, test/e2e/pages/index.js, test/e2e/pages/page.js, test/e2e/pages/population-dashboard.js, test/e2e/pages/population-edit.js, test/e2e/population.dashboard.test.js, test/e2e/population.edit.test.js
- Add choose random region for PMU users, as they mostly work on regions, not on single locations
- Add basic navigation test on population dashboard
- Add focus test for population dashboard
- Add test for editing of first cell in a region
Note: At the moment there are the following limitations with these tests:
1. Region is randomly chosen, but only the first location is edited
2. Once a location has been edited, the URL is manually constructed, rather than followed from the details page
3. The numbers entered on the edit screen are not rechecked on the details screen
- [P4-XXXX]()
- [] Added unit tests to cover changes
Commit messages with a `fix` or …
=> test: Add E2E tests for population dashboard

app/move/app/new/steps.js
This change updates the logic in the form journey to bypass when the
condition is true.
When a move to hospital is coming from a location that requires a
youth risk assessment it should bypass the existing risk and health
information steps.
=> Use youth risk assessment for hospital moves

locales/en/errors.json
This reverts commit 84bd233eb8ffc3dd179446895fd82f1b9b6abf0f.
=> Revert "chore: Update NOMIS error message to contain scheduled downtime"

locales/en/events.json
Update to events:
- use correct location for redirects
- add PER confirmation event
These events are currently displaying incorrectly so need fixing.
- [P4-1968](https://dsdmoj.atlassian.net/browse/P4-1968)
| <kbd>![image](https://user-images.githubusercontent.com/3327997/104132387-3f1fd400-537d-11eb-8ad5-ae58921dcc53.png)</kbd> | <kbd>![image](https://user-images.githubusercontent.com/3327997/104132276-82c60e00-537c-11eb-9c87-b6cd41629894.png)</kbd> |
| <kbd>![image](https://user-images.githubusercontent.com/3327997/104132373-20b9d880-537d-11eb-8ea0-cee9cbb98891.png)</kbd> | <kbd>![image](https://user-images.githubusercontent.com/3327997/104132290-aab57180-537c-11eb-982d-d50b9cf50962.png)</kbd> |
=> [P4-1968] Update incorrect events

.eslintrc.js, common/assets/javascripts/application.js, common/components/data/_data.scss, common/components/data/template.njk, common/components/time/template.njk, common/components/time/template.test.js, common/components/time/time.js, common/components/time/time.yaml, package-lock.json, package.json
This extends the time component with:
- ability to show relative time and update on the fly
- show time as a tag component
This time component will be used on the incoming and outgoing dashboards to display the relative time of when a van will be arriving.
- [P4-2595](https://dsdmoj.atlassian.net/browse/P4-2595)
summary of changes and that the commit body gives a more detailed description of …
=> [P4-2595] Extend time component to support relative times

app/allocation/views/confirmation.njk, locales/en/allocations.json
For PMU users, add a link to the weekly population page for the `from_location` in an allocation.
All the data was already present, it was a matter of creating the url, and adjusting the `locales` key.
- [P4-1442](https://dsdmoj.atlassian.net/browse/P4-1442)
| ![Screenshot_2021-01-11 Allocation requested(1)](https://user-images.githubusercontent.com/196695/104217150-ef9bdf80-5432-11eb-9c61-9b25251461a6.png)| ![Screenshot_2021-01-11 Allocation requested](https://user-images.githubusercontent.com/196695/104217139-e9a5fe80-5432-11eb-904f-6942cc3ee37d.png)  |
Commit messages with a `fix` or `feat` type are automatically used to generate the [changelog](ministryofjustice/hmpps-book-secure-move-frontend/blob/master/ …
=> feat(pmu): Add weekly link on allocations confirm

app/population/steps/edit.js, app/population/views/edit/edit.njk, locales/en/fields.json
Apply field grouping to the edit screen to more accurately represent the mockups. This is the pre-refactoring to more easily support P4-2463
This was done dynamically to support the "automatic layout" approach that the rest of the application uses. This is done by using a new property on the steps called `fieldGroups` which separates all the fields into separate groups.
- [P4-2463](https://dsdmoj.atlassian.net/browse/P4-2463)
| ![Screenshot_2021-01-08 Change numbers - create_population](https://user-images.githubusercontent.com/196695/104027324-2669bf80-51bf-11eb-9811-9e9d9b4b1c07.png) |  ![Screenshot_2021-01-08 Change numbers - create_population(1)](https://user-images.githubusercontent.com/196695/104027343-2c5fa080-51bf-11eb-80b6-21551d74af8d.png) | …
=> refactor(pmu): Use grouped fields on edit page

app/population/controllers/edit.js, app/population/controllers/edit.test.js, app/population/views/edit/edit.njk
Show transfers in and out on edit screen
- [P4-2463](https://dsdmoj.atlassian.net/browse/P4-2463)
|  ![Screenshot_2021-01-08 Change numbers - create_population(1)](https://user-images.githubusercontent.com/196695/104027343-2c5fa080-51bf-11eb-80b6-21551d74af8d.png) | ![Screenshot_2021-01-08 Change numbers - create_population(2)](https://user-images.githubusercontent.com/196695/104034891-60d85a00-51c9-11eb-9b7a-673148ec7d83.png) |
[GitHub release notes](https://github.com/ministryofjustice/hmpps-book-secure-move-frontend/releases) during …
=> [P4-2463] Show transfers in/out on edit page

.circleci/config.yml
Ensure helm does not try to get secrets from AWS Secrets Manager (the default SM for DPS) as we don't use it.
=> fix: Fix secrets

helm_deploy/hmpps-book-secure-move-frontend/templates/_envs.tpl
Helm was looking for the secrets in the wrong place, this updates the template to use the namespace. And fixed the redis config.
=> fix: Point to correct secrets space

helm_deploy/hmpps-book-secure-move-frontend/templates/_envs.tpl, helm_deploy/values-preprod.yaml, helm_deploy/values-production.yaml, helm_deploy/values-staging.yaml, helm_deploy/values-uat.yaml
Did not notice the secret name wasn't quite the namespace, but special. Have moved it and the redis secret name to the namespace specific values.
=> fix: Use proper secrets names

helm_deploy/hmpps-book-secure-move-frontend/templates/deployment.yaml
=> fix: Use correct healthcheck path

helm_deploy/hmpps-book-secure-move-frontend/templates/deployment.yaml
=> fix: Readiness probe url type :facepalm:

helm_deploy/hmpps-book-secure-move-frontend/templates/_envs.tpl
Session secret was named wrongly due to copy pasting.
=> fix: Fix session secret name

helm_deploy/hmpps-book-secure-move-frontend/templates/_envs.tpl
=> fix: Update all secret names

.circleci/config.yml
Move back to old day of releasing to unblock the flow of work as the two setups are incompatible.
=> Revert back to old way of deploying staging temporarily

package-lock.json, package.json, server.js
Removes the slashify library.
Ask team for details.
=> fix: Remove slashify

test/e2e/allocation.new.test.js
For now, we are removing the reference to this so that the tests will
pass consistently.
Since introducing pagination we can no longer guarantee the consistency
of this test.
=> test: Remove allocation dashboard test

test/e2e/#smoke.test.js, test/e2e/_helpers.js, test/e2e/move.update.forbidden.test.js
The `smoke.test.js` file has been renamed to start with a character before the alphanumeric section of the ASCII table.
Smoke tests should be run at the beginning of the E2E run, not at the end. They're currently run last because `s` is sorted last in the alphabet in our current test suite. …
=> test: Run smoke tests first not last

app/population/views/edit/details.njk
Fix font size of transfers in/out
- [P4-XXXX]()
| ![Screenshot_2021-01-27 Change numbers - create_population(3)](https://user-images.githubusercontent.com/196695/106034802-46f4ad80-60cb-11eb-9966-0a4c47d1af32.png) | ![Screenshot_2021-01-27 Change numbers - create_population(2)](https://user-images.githubusercontent.com/196695/106034822-4bb96180-60cb-11eb-8a8a-7abdb9c09e0a.png) |
[GitHub release notes](https://github.com/ministryofjustice/hmpps-book-secure-move-frontend/releases) during the release task. Please make sure they will read …
=> [P4-2632] Use correct font sizing for transfers in/out

app/population/middleware/set-location-free-spaces.js, app/population/middleware/set-location-free-spaces.test.js
Restore filtering by locations on population pages
`locations` are stored on `req` not `req.params`
- [P4-2630](https://dsdmoj.atlassian.net/browse/P4-2630)
| ![Screenshot_2021-01-28 Population for 25 to 31 Jan 2021 (This week)(1)](https://user-images.githubusercontent.com/196695/106130266-0c395680-6159-11eb-905a-f4c88907d830.png) | ![Screenshot_2021-01-28 Population for 25 to 31 Jan 2021 (This week)(2)](https://user-images.githubusercontent.com/196695/106130283-1196a100-6159-11eb-848b-656037926c24.png) | …
=> fix(pmu): Correctly filter by regions

app/population/middleware/set-breadcrumb.js, app/population/middleware/set-breadcrumb.test.js
Fix the breadcrumb link for the daily view
When editing daily free spaces, the breadcrumb for the daily view currently links to the edit screen, thus not allowing navigation back to the daily overview.
- [P4-2631](https://github.com/ministryofjustice/hmpps-book-secure-move-frontend/pull/1282)
summary of …
=>  [P4-2631] Use link to daily page for breadcrumb

app/locations/controllers.js
Remove unused and un-tested middleware.
`/app/locations/controllers.js#redirect` is not being used - `/app/auth/controllers.js#redirect` is used and tested.
- [P4-XXXX]()
=> refactor: Remove unused redirect middleware

app/person-escort-record/views/print-record.njk, locales/en/person-escort-record.json
Show contact numbers of dispatching and receiving officers in the printout view
- [P4-2662](https://dsdmoj.atlassian.net/browse/P4-2662)
|  ![Screenshot_2021-02-12 Person Escort Record for AUGICK, #39;NJINS – Book a secure move(1)](https://user-images.githubusercontent.com/196695/107778126-91b52d00-6d3b-11eb-9e1a-98d038455dea.png) | ![image](https://user-images.githubusercontent.com/3327997/107939304-71c17b80-6f7e-11eb-9a9b-5befec53a944.png) |
[GitHub release notes](https://github.com/ministryofjustice/hmpps-book-secure-move-frontend/rele …
=> [P4-2662] - Display dispatching and receiving phone numbers

app/person-escort-record/app/confirm/controllers.js, app/person-escort-record/app/confirm/controllers.test.js, app/person-escort-record/app/confirm/fields.js, locales/en/fields.json
The handover date and time should be in the past. The wording has been adjusted to reflect this, and extra multi-field validation added to ensure these values are in the past.
- [P4-2662](https://dsdmoj.atlassian.net/browse/P4-2664)
=> [P4-2664] Validate handover time

app/locations/controllers.js, app/locations/controllers.test.js, common/lib/permissions.js
Adds check if the user is a contract delivery manager and if so, loads all available locations.
Contract delivery managers need an overview of the everything that's happening.
- [P4-2639](https://dsdmoj.atlassian.net/browse/P4-2639) …
=> Contract delivery manager view

common/presenters/date-table/cell-renderers.js, common/presenters/date-table/cell-renderers.test.js, common/presenters/date-table/population-helpers.test.js
Add links to incoming and outgoing transfers from location weekly population page
- [P4-2464](https://dsdmoj.atlassian.net/browse/P4-2464)
|  ![Screenshot_2021-02-10 Population for 8 to 14 Feb 2021 (This week)(1)](https://user-images.githubusercontent.com/196695/107493727-dd25da80-6b85-11eb-8233-23edb2c2d153.png) |  ![Screenshot_2021-02-10 Population for 8 to 14 Feb 2021 (This week)](https://user-images.githubusercontent.com/196695/107493747-e3b45200-6b85-11eb-953b-1a45e92df20a.png) | …
=> [P4-2464] Add links to population transfers

.github/dependabot.yml, package-lock.json
Update packages using `npm audit fix`
=> chore: Update from npm audit fix

app/help/accessibility-statement.njk, app/help/index.js, common/assets/scss/utilities/_all.scss, config/index.js, config/nunjucks/globals.js, config/nunjucks/globals.test.js, locales/en/allocation.json, locales/en/fields.json
It is a legal requirement to publish an accessibility statement.
This change adds a new route and template for this accessibility
statement.
[View accessibility statement](http://booksecuremove-pr-1357.herokuapp.com/help/accessibility-statement)
- [P4-2647](https://dsdmoj.atlassian.net/browse/P4-2647)
=> [P4-2647] Add an accessibility statement

.circleci/config.yml
The CircleCI Slack Orb is updated to latest version and the common HMPPS vars context is applied to the jobs that post messages to Slack.
In order to enable the transition to the MoJ Slack from the current setup.
=> refactor: Update to laterst Slack orb and add common context for Slack token

app/locations/controllers.js, app/locations/controllers.test.js
The list of locations shown to Contract Delivery Managers now only contains unique locations.
Sme locations have changed suppliers in the past, and for historic reasons appear in the list of locations for both suppliers. When the lists are merged for the Contract Delivery Managers, these locations appeared twice.
- [P4-2639](https://dsdmoj.atlassian.net/browse/P4-2639)
summary of changes and that …
=> fix: De-duplicate list of locations for Contract Delivery Managers

config/index.js
Add an E2E Contract Delivery Manager user
=> chore: Add CDM user for E2E tests

.circleci/config.yml
=> refactor: Fix circle config template

.circleci/config.yml
Emoji is an invalid attribute in the markdown section and every text attribute needs to have a type definition
=> refactor: Add text type and remove invalid emoji attribute

.circleci/config.yml
Fix some missing commas and update where the mentions happen
=> refactor: Fix slack message errors

package.json, server.js
Added tracing to Sentry config.
To enable performance monitoring.
=> refactor: Add config for Sentry performance monitoring

app/locations/controllers.js, app/locations/controllers.test.js
Display locations list in case insensitive order.
| ![Screenshot_2021-03-08 Choose location(1)](https://user-images.githubusercontent.com/196695/110317593-47566180-8004-11eb-8ce9-cd9bde092220.png) | ![Screenshot_2021-03-08 Choose location](https://user-images.githubusercontent.com/196695/110317574-40c7ea00-8004-11eb-92ab-22e88efa6308.png) |
summary of changes …
=> fix: Sort locations list by ignoring case

app/move/app/new/controllers/base.js, app/move/app/new/controllers/base.test.js, common/controllers/collection/render-as-cards.js, common/controllers/collection/render-as-cards.test.js, common/controllers/form-wizard/index.js, common/controllers/form-wizard/index.test.js, locales/en/errors.json
If a location is disabled, hide the create a move button. If the user still manages to navigate to the create move url for a disabled location, show an error page.
Users have no way of knowing which locations in their are disabled, and we no do not allow the creation of moves for disabled locations on the backend.
- [P4-2637](https://dsdmoj.atlassian.net/browse/P4-2637)
summary of changes and that …
=> fix: Hide create move button if disabled location and add error handling

audit-ci.json, package-lock.json
Upgraded y18n, mkdirp to resolve security vulnerabilities. Added dot-prop to the allow list for the audit because there is no available resolution and it is in a dev dependency.
=> Fix security vulnerabilities

.github/dependabot.yml
`convert-hrtime` 5.0.0 requires ESM syntax. This is not currently in use
within our codebase, so the version is being pinned for now
Version 4 was a release that introduced a bug that was rolled back in
Version 5, so there are not currently big changes, apart from the import
syntax
- [P4-XXXX]()
summary of …
=> chore: Ignore convert-hrtime > 5

common/lib/api-client/index-with-requests.test.js
The current api-client tests implement a solitary or mocked approach which means some kinds of bugs can slip through. This PR adds [social](https://www.martinfowler.com/bliki/UnitTest.html) or integrated unit tests to check that the arrangement of classes and middleware are working together correctly. It does this by using [nock[(https://github.com/nock/nock) which mocks out the node http layer (which is many steps away from the usage of api-client)
These tests only expose recently fixed bug behaviour of authorization failing, but they are a good starting point for test in this way.
This is also the other half of the investigation work around #1516  …
=> test: Use nock to improve api-client coverage

common/helpers/field/index.js, common/helpers/field/index.test.js, locales/en/default.json
This change can now be supported since the translation library was
moved to a separate module.
Closes #191
- #191
=> chore: Update initial option to use translation library

app/locations/controllers.js, app/locations/controllers.test.js, app/move/controllers/view.js, app/move/controllers/view.test.js
The locations and move controllers were updated to wrap calls to the API in try catch blocks.
If the API returned an error, we weren't handling it. It would be logged, but it wouldn't exit the req cycle and the users could end up seeing partial data.
=> Fix missing catch

app/move/app/new/controllers/save.js, app/move/app/new/controllers/save.test.js
In some instances we see an error when trying to update a profile
because it is missing a Person ID.
It also adds extra Sentry data to errors picked up from this step
including IDs within the session and the move itself.
The current information in the Sentry errors isn't helping to pinpoint
where that data is being lost from the session.
This adds logging to capture the journey somebody has taken to get
to this point and may help understand the problem better.
- [2272958731](https://sentry.io/organizations/ministryofjustice/issues/2272958731/?project=2014813&query=is%3Aunresolved)
=> Add extra logging to missing Person ID error

test/e2e/_helpers.js, test/e2e/pages/allocation-criteria.js, test/e2e/pages/allocation-details.js, test/e2e/pages/population-edit.js
This change updates the use to use the correct number method.
A recent update to Faker changed the namespace used to create fake
numbers.
<kbd>![image](https://user-images.githubusercontent.com/3327997/116680315-6ab5e100-a9a3-11eb-804b-54244418129b.png)</kbd>
=> chore: Update method to create fake numbers using faker

audit-ci.json
NPM audit vulnerability 1665 was added to the allow list.
While we wait for the maintainer of browser-sync to update the dependency responsible, it'd be nice if our Circle CI builds didn't fail. The related browser-sync issue can be found here: https://github.com/BrowserSync/browser-sync/issues/1863
- [P4-2835](https://dsdmoj.atlassian.net/browse/P4-2835)
=> chore: Allow audit vulnerability 1665

common/lib/api-client/middleware/got-request.js, common/lib/api-client/middleware/got-request.test.js
When Got returns an error it will return a response property only if
the request succeeded.
In instances where the request fails, for example a timeout, it isn't
currently recording debugging and Sentry data correctly.
This change caters for an error including a response or not.
- [BOOK-A-SECURE-MOVE-FRONTEND-4J](https://sentry.io/organizations/ministryofjustice/issues/2394865016/?project=2014813&query=is%3Aunresolved&statsPeriod=14d)
=> fix: Handle Got errors correctly depending on request or response

locales/en/events.json
This updates the copy used to render certain events within the
move timeline.
Some were missing or incorrect. Updated events:
- JourneyHandoverToSupplier
- JourneyPersonBoardsVehicle
- JourneyAdmitToReception
- MoveDateChanged
- [P4-2857](https://dsdmoj.atlassian.net/browse/P4-2857)
=> [P4-2857] Correct events timeline content

common/lib/permissions.js, common/lib/user.test.js
This gives all roles access to the main homepage that contains
an overview of what they have access to. Including incoming/outgoing
areas of the app.
Some user roles were created before we had created the main homepage. This led to them
not being given this permission when it was added. This change follows up to ensure all roles have
access to the homepage.
- [P4-2819](https://dsdmoj.atlassian.net/browse/P4-2819)
=> [P4-2819] Ensure all user roles have access to the homepage

app/allocation/controllers/view.js, app/allocation/controllers/view.test.js, app/move/app/new/controllers/person-search-results.js, app/move/app/new/controllers/person-search-results.test.js, app/moves/middleware/set-results.moves.js, app/moves/middleware/set-results.moves.test.js, app/moves/middleware/set-results.single-requests.test.js, common/components/card/_card.scss, common/components/card/card.yaml, common/components/card/template.njk, common/presenters/court-case-to-card-component.js, common/presenters/court-case-to-card-component.test.js, common/presenters/move-to-card-component.js, common/presenters/move-to-card-component.test.js, common/presenters/moves-by-location.js, common/presenters/moves-by-location.test.js, common/presenters/moves-by-vehicle.js, common/presenters/moves-by-vehicle.test.js, common/presenters/profile-to-card-component.js, common/presenters/profile-to-card-component.test.js, locales/en/default.json, locales/en/fields.json
The incoming/outgoing move screens now display prison/PNC number (dependant on move to location type) on the move cards.
This changed because prison users want to know the prison numbers of individuals coming into and going out of establishments quickly and easily so that they can be prepared for their departure/arrival.
- [P4-2799](https://dsdmoj.atlassian.net/browse/P4-2799)
| <kbd><img width="1186" alt="image" src="https://user-images.githubusercontent.com/4104309/116676986-933bdc00-a99f-11eb-96fa-2452d964879d.png"></kbd> | <kbd><img width="1188" alt="image" src="https://user-images.githubusercontent.com/4104309/117117937-0bcbdf80-ad88-11eb-970d-8b9564a67936.png"></kbd> |
=> feat: Add prison/PNC number on in/out moves

common/lib/permissions.js, common/lib/user.test.js, config/index.js
Added a read-only user role.
Requirement has been confirmed for a PECS Read Only role for the purposes of HMPPS policy audit/assurance team(s). This has been approved by the Head of PECS. 
- P4-2842
=> chore: Add read-only user role

server.js
Adds performance tracing to Sentry init.
Testing out Sentry's performance tracing capabilities as part of a CP trial.
=> chore: Add performance tracing to Sentry init

locales/en/events.json
This creates content for the following missing events:
- MoveNotifyPremisesOfDropOffEta
- MoveNotifyPremisesOfPickupEta
- [P4-2899](https://dsdmoj.atlassian.net/browse/P4-2899)
=> [P4-2899] Update events copy to include new events

app/move/index.js, app/move/middleware.js, app/move/middleware.test.js, app/tools/controllers.js, app/tools/controllers.test.js, app/tools/index.js, common/assets/scss/components/_all.scss, common/assets/scss/components/_development-tools.scss, common/middleware/set-development-tools.js, common/middleware/set-development-tools.test.js, common/templates/layouts/base.njk, config/nunjucks/globals.js, config/nunjucks/globals.test.js, server.js
This creates a new development tools toolbar that sits at the bottom
of the window when development tools are enabled.
We already have some development tools to help change roles and
permissions. This moves those actions to a separate place and extends
them to include move specific actions like progressing a move status.
This will allow developers to more easily see moves in different states during
development.
| <kbd>![image](https://user-images.githubusercontent.com/3327997/119898552-ea4eb580-bf39-11eb-86fc-b5866b764676.png)</kbd> | <kbd>![image](https://user-images.githubusercontent.com/3327997/119898467-cdb27d80-bf39-11eb-9d40-9db5cffda498.png)</kbd> |
| | <kbd>![image](https://user-images.githubusercontent.com/3327997/119898400-b3789f80-bf39-11eb- …
=> Separate development helpers and add move features

server.js
We're currently recording tracing metrics for all environments which
is causing us to get close to current limits within the plan.
Related to #1675 
=> Prevent Sentry tracing in all non-production environments

audit-ci.json, package-lock.json
Minor package updates to address some security vulnerabilities. Unfixable ones for dev dependencies added to allowlist.
=> chore: Fix/allow security advisories

app/move/app/view/controllers/index.js, app/move/app/view/controllers/render-assessments.js, app/move/app/view/controllers/render-assessments.test.js, app/move/app/view/controllers/render-timeline.js, app/move/app/view/controllers/render-timeline.test.js, app/move/app/view/controllers/render-warnings.js, app/move/app/view/controllers/render-warnings.test.js, app/move/app/view/index.js, app/move/app/view/middleware/index.js, app/move/app/view/middleware/locals.actions.js, app/move/app/view/middleware/locals.actions.test.js, app/move/app/view/middleware/locals.move-details.js, app/move/app/view/middleware/locals.move-details.test.js, app/move/app/view/middleware/locals.tabs.js, app/move/app/view/middleware/locals.tabs.test.js, app/move/app/view/views/_layout.njk, app/move/app/view/views/assessments.njk, app/move/app/view/views/timeline.njk, app/move/app/view/views/warnings.njk, app/move/index.js, app/move/middleware.js, app/move/middleware.test.js, locales/en/moves.json
This creates a new sub-app alongside the existing move page for the re-design.
The move page is being redesigned. During development we still want to keep the existing design so these changes are being added and merged alongside the existing design.
- [P4-2910](https://dsdmoj.atlassian.net/browse/P4-2910)
<kbd>![image](https://user-images.githubusercontent.com/3327997/122187467-f79af800-ce86-11eb-9c56-962c0b8f4db6.png)</kbd>
=> [P4-2910] Move page redesign initial structure

app/move/app/view/controllers/render-timeline.js, app/move/app/view/controllers/render-timeline.test.js, app/move/app/view/index.js, app/move/app/view/views/_layout.njk, app/move/app/view/views/assessments.njk, app/move/app/view/views/timeline.njk, app/move/middleware.js, app/move/middleware.test.js
This adds the content for the history of events timeline tab for the
new move page redesign.
It extends the new structure of containing this code within a sub-app.
- [P4-2914](https://dsdmoj.atlassian.net/browse/P4-2914)
<kbd>![image](https://user-images.githubusercontent.com/3327997/123395050-adf19200-d597-11eb-9396-7c310ba9187a.png)</kbd> …
=> [P4-2914] Add history of events to move page redesign

app/move/app/view/controllers/render-assessments.js, app/move/app/view/controllers/render-assessments.test.js, app/move/app/view/controllers/render-timeline.js, app/move/app/view/controllers/render-timeline.test.js, app/move/app/view/controllers/render-warnings.js, app/move/app/view/controllers/render-warnings.test.js, app/move/app/view/index.js, app/move/app/view/middleware/index.js, app/move/app/view/middleware/locals.actions.js, app/move/app/view/middleware/locals.actions.test.js, app/move/app/view/middleware/locals.move-details.js, app/move/app/view/middleware/locals.tabs.js, app/move/app/view/middleware/set-breadcrumb.js, app/move/app/view/middleware/set-breadcrumb.test.js, app/move/app/view/views/_layout.njk, app/move/app/view/views/assessments.njk, app/move/app/view/views/timeline.njk, app/move/app/view/views/warnings.njk, common/middleware/locals.js, common/middleware/locals.test.js, common/presenters/move-to-meta-list-component.js, common/presenters/move-to-meta-list-component.test.js, config/nunjucks/globals.js, locales/en/default.json
This contains a few small changes to the new move page designs:
- correct page titles
- display status separately
- add breadcrumbs
| <kbd>![image](https://user-images.githubusercontent.com/3327997/123997600-7a17d180-d9c8-11eb-990b-d3ebdbe1a1b3.png)</kbd> | <kbd>![image](https://user-images.githubusercontent.com/3327997/123999466-74bb8680-d9ca-11eb-83ea-f3dc0ad0fd5c.png)</kbd> |
| <kbd>![image](https://user-images.githubusercontent.com/3327997/123997672-8b60de00-d9c8-11eb-908b-148c380039c1.png)</kbd> | <kbd>![image](https://user-images.githubusercontent.com/3327997/123997374-3c1aad80-d9c8-11eb-88f8-ff7e6d4b5d34.png)</kbd> |
| <kbd>![image](https://user-images.githubusercontent.com/3327997/123997710-9451af80-d9c8-11eb-9cb0-679845b6023b.png)</kbd> | …
=> Move details panel adjustments

common/lib/populate-resources.js, common/middleware/set-location.js, common/middleware/set-location.test.js, server.js, test/e2e/_helpers.js
This change records these errors as warnings so that we can gather
some information to help debug the scenarios and understand how
frequently it is occurring.
We've had reports that some users are frequently seeing the missing
location 404 page. By default 404s aren't logged to Sentry with any
error information.
- [P4-2975](https://dsdmoj.atlassian.net/browse/P4-2975)
summary of changes and that …
=> [P4-2975] Capture sentry details around missing location errors

common/components/task-list/_task-list.scss, common/components/task-list/task-list.yaml, common/components/task-list/template.njk, common/components/task-list/template.test.js
This change adds the ability to group tasks within sections for the
Task List Component.
This change follows a similar pattern to the MOJ Design System but
maintains the flexibility to apply different tags and labels.
https://moj-design-system.herokuapp.com/components/task-list
[**COMPONENT DEMO**](https://booksecuremove-pr-1810.herokuapp.com/components/task-list)
Previously it only supported showing tasks rather than the ability to
group them.
- [P4-2913](https://dsdmoj.atlassian.net/browse/P4-2913)
<kbd>![image](https://user-images.githubusercontent.com/3327997/125458794-0b4e6172-5865-4f51-bbfa-5cb76cfd2e3a.png)</kbd> …
=> [P4-2913] Extend task list component to support sections

common/lib/api-client/middleware/got-request.js, common/lib/api-client/middleware/got-request.test.js
This fix checks for a valid end timing, whether a `response.end` or
`request.error` value, and won't call the metrics library if this
value doesn't exist.
Alongside that, some extra context has been added to the errors to
help us determine which values are incorrect.
It also fixes an issue with the correct status code not being sent
to the errors middleware meaning the code displayed on the error page
when in development mode wasn't correct.
fixes BOOK-A-SECURE-MOVE-FRONTEND-5E
When some API requests fail we are seeing a
`Value is not a valid number: NaN` error which suggests one of the
values we're sending to this library isn't valid.
- [BOOK-A-SECURE-MOVE-FRONTEND-5E](https://sentry.io/organizations/ministryofjustice/issues/2509607044/?project=2014813&query=is%3Aunresolved)
Has been …
=> fix: Prevent metrics library from erroring without correct type

app/person/controllers.js, app/person/controllers.test.js, app/person/index.js, app/person/middleware.js, app/person/middleware.test.js, app/person/views/render-person.njk, common/presenters/person-to-summary-list-component.js, common/presenters/person-to-summary-list-component.test.js, common/services/person.js, common/services/person.test.js, config/i18n/index.js, locales/en/person.json
This creates a new route and view to show a person's basic information.
For now this includes the personal details associated with this person
regardless of the move.
- [With security category](https://booksecuremove-pr-1844.herokuapp.com/person/ce9436d9-352f-427f-b20f-06c6cc4caf6e)
- [Without security category](https://booksecuremove-pr-1844.herokuapp.com/person/0482f85c-2216-40ca-a73d-67fcd2ae283f)
- [Without prison number](https://booksecuremove-pr-1844.herokuapp.com/person/2d61b0df-d174-4b84-ab54-52f55e91f20e)
We want to start showing links between a person and their moves and creating these pages will allow
users to see these links and see a person's past and upcoming moves.
- [P4-3018](https://dsdmoj.atlassian.net/browse/P4-3018) …
=> [P4-3018] Create new profile page to display a person's information

app/move/app/view/index.js, app/move/app/view/middleware/index.js, app/move/app/view/middleware/locals.person-summary.js, app/move/app/view/middleware/locals.person-summary.test.js, app/move/app/view/middleware/locals.warnings.js, app/move/app/view/middleware/locals.warnings.test.js, app/move/app/view/views/_layout.njk, common/presenters/allocation-to-meta-list-component.js, common/presenters/allocation-to-meta-list-component.test.js, common/presenters/index.js, common/presenters/move-to-meta-list-component.js, common/presenters/move-to-meta-list-component.test.js, common/presenters/person-to-meta-list-component.js, common/presenters/person-to-meta-list-component.test.js, common/templates/includes/move-summary.njk, common/templates/includes/person-summary.njk, locales/en/actions.json, locales/en/person.json
This adds a side panel to render a person's basic information to the new move page design.
This only changes on the new move page for now as this might be tweaked after some upcoming research
sessions so rather than change this frequently in other live sections like move booking its probably better to
wait for now.
The designs have evolved whilst building these parts of the app so that the personal details can sit alongside
the move details in the various deeper sections of the application, for example the Person Escort Record.
This also means this information will sit better alongside the slimmer "identity bar" too.
- [P4-3018](https://dsdmoj.atlassian.net/browse/P4-3018)
<kbd>![image](https://user-images.githubusercontent.com/3327997/127159001-d1a7e1c0-49a7-4269-987e-f489385da749.png)</k …
=> [P4-3018] Personal details side panel 

app/move/app/new/controllers/base.js, app/move/app/new/controllers/base.test.js, app/move/app/new/fields/filter.police-national-computer.js, app/move/app/new/fields/police-national-computer.js, app/move/validators.js, app/move/validators.test.js, locales/en/fields.json, locales/en/validation.json, test/e2e/_helpers.js
This change adds validation to the PNC number search and input fields
when creating a new move.
**Update**
This also now removes fields validated with the new Police National
Computer (PNC) validator from the form wizard so that the user doesn't
see this error.
It then adds each instance to Sentry as a warning.
We've had cases where this number has been incorrectly input which
has lead to records not being returned when searched for.
**Update**
This is because we are not fully certain of the impact of introducing
this validation yet. There are some establishments that are using this
field for non-PNC reference numbers and we want to get an understanding
of scale first before enabling it.
These warnings will allow us to see the location types that are
causing this validation to trigger and …
=> [P4-2984] [P4-2829] Validate Police National Computer number

app/filters/views/filters.njk, locales/en/actions.json
This includes some small things that have been spotted that can be quickly updated to make the
service more consistent and inline with other services in the same space.
Users should feel like they are still accessing things within the same space and that services
are more joined up.
| <kbd>![image](https://user-images.githubusercontent.com/3327997/127490770-2c62139c-ace8-4e61-93ce-8d31b5e37b06.png)</kbd> | <kbd>![image](https://user-images.githubusercontent.com/3327997/127490718-b5112bc9-69f8-4869-89b7-8fbf85abe1e1.png)</kbd> |
| <kbd>![image](https://user-images.githubusercontent.com/3327997/127490466-1fa4cc90-6508-44b4-acb9-625c80c26712.png)</kbd> <kbd>![image](https://user-images.githubusercontent.com/3327997/127490497-c44479a0-48b2-4403-a310-86984f …
=> Minor bug fixes and tweaks

app/move/app/view/constants.js, app/move/app/view/index.js, app/move/app/view/middleware/set-breadcrumb.js, app/move/app/view/middleware/set-breadcrumb.test.js, app/move/index.js, app/move/middleware.js, app/move/middleware.test.js
This includes some refactoring changes to the existing move application and the new design app.
It also includes a switch of the breadcrumb to match the page heading on the new design.
These changes will enable the opt-in work to be done but are small enough that they can be extracted
to make reviewing easier.
- [P4-2915](https://dsdmoj.atlassian.net/browse/P4-2915)
| <kbd>![image](https://user-images.githubusercontent.com/3327997/128484374-03aedec6-bf60-40a8-891e-3b102286203f.png)</kbd> | <kbd>![image](https://user-images.githubusercontent.com/3327997/128484288-fb50a813-8d70-451a-ad5d-7a8cbd35d752.png)</kbd> |
=> [P4-2915] Refactor parts of the move application to support preview opt-in

common/lib/user.js, common/lib/user.test.js
This sorts the locations for a user alphabetically by the title of the location, therefore making it easier for users to navigate and find the location they want to access.
[Jira Ticket](https://dsdmoj.atlassian.net/browse/P4-2925)
=> Sort locations alphabetically

app/person/controllers/index.js, app/person/controllers/moves.js, app/person/controllers/personal-details.js, app/person/controllers/personal-details.test.js, app/person/index.js, app/person/middleware/index.js, app/person/middleware/locals.identity-bar.js, app/person/middleware/locals.identity-bar.test.js, app/person/middleware/locals.tabs.js, app/person/middleware/locals.tabs.test.js, app/person/middleware/set-move-results.js, app/person/middleware/set-move-results.test.js, app/person/views/_layout.njk, app/person/views/moves.njk, app/person/views/personal-details.njk, common/presenters/index.js, common/presenters/moves-to-table-component.js, common/presenters/moves-to-table-component.test.js, locales/en/collections.json, locales/en/person.json
This adds a new tab to the person page for displaying their moves.
=> Add person moves tab

app/move/app/view/controllers/render-assessments.js, app/move/app/view/controllers/render-assessments.test.js, app/move/app/view/controllers/render-timeline.js, app/move/app/view/controllers/render-timeline.test.js, app/move/app/view/controllers/render-warnings.js, app/move/app/view/controllers/render-warnings.test.js, app/person/controllers/moves.js, app/person/controllers/moves.test.js, app/person/controllers/personal-details.js, app/person/controllers/personal-details.test.js, app/person/views/_layout.njk, common/presenters/assessment-answers-to-meta-list-component.js, common/presenters/assessment-answers-to-meta-list-component.test.js
This makes some small design tweaks to the person and moves pages following review from our designer:
- Removes tabs from breadcrumbs
- Increases person layout to full width
- Brings NOMIS framework response date lines closer together
=> Small design tweaks

app/person-escort-record/index.js, app/youth-risk-assessment/index.js, common/controllers/framework/framework-section.js, common/controllers/framework/framework-section.test.js, common/middleware/framework/set-breadcrumbs.js, common/middleware/framework/set-breadcrumbs.test.js, common/middleware/set-move-with-summary.js, common/middleware/set-move-with-summary.test.js, common/templates/framework-section.njk, locales/en/default.json
This adds a pagination element to the section overview pages of the
frameworks, including the Person Escort Record and Youth risk assessment.
It also includes an update to the breadcrumb to bring it inline with the new pattern.
This change allows users to navigate between sections of the assessment
to review the answers.
| <kbd>![image](https://user-images.githubusercontent.com/3327997/129965046-bc13b165-063b-43b3-aec7-2ea58a30b00e.png)</kbd> | <kbd>![image](https://user-images.githubusercontent.com/3327997/129965012-8b81167a-ea4d-411f-b017-be3c1da86b33.png)</kbd> |
| <kbd>![image](https://user-images.githubusercontent.com/3327997/129968794-2df199dc-99a3-4d0f-b309-437b48149b13.png)</kbd> | <kbd>![image](https://user-images.githubusercontent.com/3327997 …
=> Add pagination to section overview page

app/move/app/view/middleware/locals.actions.js, app/move/app/view/middleware/locals.actions.test.js, app/move/app/view/views/_layout.njk, app/move/views/view.njk, locales/en/messages.json
This amends the copy being used for the new move design preview banner.
It uses better language rather than any internal team terminology.
| <kbd><img width="983" alt="Screenshot 2021-08-19 at 15 46 39" src="https://user-images.githubusercontent.com/3327997/130083911-65b4c55e-7569-48ea-8001-81ccc228b44a.png"></kbd> | <kbd><img width="988" alt="Screenshot 2021-08-19 at 15 50 54" src="https://user-images.githubusercontent.com/3327997/130083926-ca6c30bb-a8ad-4110-afae-017b759ed51c.png"></kbd> |
| <kbd>![image](https://user-images.githubusercontent.com/3327997/130084942-e95270b1-ecc9-4af1-bb21-eee6c08a30fe.png)</kbd> | <kbd>![image](https://user-images.githubusercontent.com/3327997/130087146-8668b6ef-aa36-4a27-a599-36f076ba4f47.png)</kbd> |
Has been …
=> Update move preview opt in message

common/controllers/framework/confirm-assessment.js, common/controllers/framework/confirm-assessment.test.js, locales/en/messages.json
This adds success message banners to the confirmation steps of the PER and youth risk assessment.
Users weren't always aware that these steps had been completed, so this shows them in a clearer fashion that something
has changed.
| Confirmed YRA | Handed over PER |
| -- | -- |
| <kbd><img width="1201" alt="Screenshot 2021-08-25 at 09 46 42" src="https://user-images.githubusercontent.com/3327997/130749183-95a039ab-079b-4f85-a0fa-305212edc413.png"></kbd> | <kbd><img width="1208" alt="Screenshot 2021-08-25 at 09 47 52" src="https://user-images.githubusercontent.com/3327997/130749177-03597ba5-b01f-432f-97cf-10477147fbbe.png"></kbd> | …
=> Add success message on confirmation/hand over

common/controllers/framework/framework-step.js, common/controllers/framework/framework-step.test.js, common/templates/framework-section.njk, locales/en/assessment.json
This makes two small changes to make it clearer to the user what the overview it by using the phrasing consistently across the site. See individual commits for more details.
[Jira Ticket](https://dsdmoj.atlassian.net/browse/P4-3143)
=> Improve navigation to framework overviews

config/nunjucks/filters.test.js
Tests broken by DST have been unbroken.
Due to American DST ending, some of the tests failed, these have been fixed in a way that means that they won't need fixing again.
=> chore: Fix unit tests that broke due to DST ending

package-lock.json, package.json
Reverts ministryofjustice/hmpps-book-secure-move-frontend#2184
=> Revert "build(deps): bump redis from 3.1.2 to 4.0.0"

app/move/app/view/views/_layout.njk, common/templates/includes/move-summary.njk
=> fix: Tweaks to border styling on the move details side panel

common/components/message/template.njk, common/templates/layouts/base.njk
This fixes two instances of incorrect aria attributes found in a recent accessibility audit.
[Jira Ticket](https://dsdmoj.atlassian.net/browse/P4-3491)
=> Fix incorrect use of aria attributes

package-lock.json, package.json
I'm hoping this will fix the memory issues, possibly related to: https://github.com/tj/connect-redis/issues/354
=> build: Upgrade connect-redis to 6.1.3

.circleci/config.yml, test/e2e/_helpers.js, test/e2e/move.update.forbidden.test.js
Archived lint+unit test coverage. Changed code to check that moves aren't being made from and to the same location.
Uploading the coverage was taking around 1 minute due to there being so many files, archiving and then uploading takes < 1 second.
The check around move locations should increase our e2e success rate by a lot. There are only 4 STCs in staging, which means there is currently a 25% chance that the tests will fail on the STC > STC move test, if that passes there are only 9 SCHs (11% failure rate).
- P4-3545
=> P4 3545/speed up tests

common/components/add-another/add-another.js, config/index.js, config/nunjucks/globals.js, config/nunjucks/globals.test.js
=> Add support link to footer

package-lock.json, package.json
This includes a new question around the date of arrest.
[Jira Ticket](https://dsdmoj.atlassian.net/browse/P4-2987)
=> Add frameworks 2.4.0

.github/workflows/branch-deploy-cleanup.yml, .github/workflows/branch-deploy.yml
This should fix Branch Based Deploy cleanup throwing an error
=> chore: Fix issue with PR preview PR number on merge

app/move/app/view/middleware/locals.move-details.js
It seems like sometimes the move won't have any important events, so we should make sure to handle this situation.
[Sentry Issue](https://sentry.io/organizations/ministryofjustice/issues/3229345386/?referrer=slack)
=> Handle when move has no important events

.github/workflows/branch-deploy-cleanup.yml, .github/workflows/branch-deploy.yml
Replace deployment comment with Github deployments
=> chore: Replace deployment comment with Github deployments

.github/workflows/branch-deploy-cleanup.yml, .github/workflows/branch-deploy.yml
This adds checks so that only active deploys are set to inactive, previously, inactive deploys were also being set to inactive.
=> chore: Check if github cleans up after deploys

package-lock.json, package.json
Reverts ministryofjustice/hmpps-book-secure-move-frontend#2478
=> Revert "build(deps): bump redis from 3.1.2 to 4.1.0"

app/healthcheck/dependencies.js
Fix redis healthcheck throwing an error regardless of connection status.
=> chore: Fix redis healthcheck

.github/workflows/branch-deploy-cleanup.yml, .github/workflows/branch-deploy.yml
Add permissions to the github actions, hopefully this will fix the dependabot BDDs...
=> chore: Fix dependabot PRs not being able to BDD

common/templates/layouts/base.njk
We have added the ability to track users using a user id
To allow us to better understand our users
- [P4-3653](https://dsdmoj.atlassian.net/browse/P4-3653)
=> Add User Id Tracking

.circleci/config.yml
=> chore: Install NPM on build docker step

.circleci/config.yml
=> chore: Install Node 16 on build docker step

app/auth/middleware.js, app/auth/middleware.test.js, app/move/app/view/controllers/render-timeline.js, app/move/app/view/controllers/render-timeline.test.js, app/move/app/view/middleware/locals.warnings.js, app/move/app/view/middleware/locals.warnings.test.js, common/formatters/index.ts, common/helpers/events/get-description.test.ts, common/helpers/events/get-description.ts, common/lib/user.js, common/lib/user.test.js, common/presenters/event-to-timeline-item-component.js, common/presenters/event-to-timeline-item-component.test.js, common/presenters/event-to-timeline-panel.js, common/presenters/event-to-timeline-panel.test.js, common/presenters/move-to-in-transit-events-panel-list.js, common/presenters/move-to-in-transit-events-panel-list.test.js, common/presenters/move-to-timeline-component.js, common/presenters/move-to-timeline-component.test.js, common/services/user.js, common/services/user.test.js, common/types/event-details.ts, config/index.js
PerCompletion events have been changed to display real names instead of usernames.
This has changed because usernames weren't very user friendly or readable.
- P4-3575
| <kbd><img src="https://user-images.githubusercontent.com/4104309/173071579-96efaef0-5ca3-4a3c-a2f5-53526646852a.png"></kbd> | <kbd><img src="https://user-images.githubusercontent.com/4104309/173071613-66e58455-7e86-4b31-84c5-5660a71876c7.png"></kbd> |
=> chore: Change PerCompletion events to show real names

common/helpers/events/get-description.ts
This fixes an issue which will likely show up after the next deploy
=> chore: Filter potential issue with undefined tokens/names

common/services/user.js, common/services/user.test.js
Add a special case in User.getFullName to return the username if the username is Serco or GEOAmey.
There are scenarios where suppliers will complete PERs, this ensures that they show up in the PerCompletion events.
- P4-3575
=> chore: Add special case in User.getFullName for Serco/GEOAmey

.github/workflows/branch-deploy.yml, common/services/user.test.js
Some branch based deploys are failing, this will hopefully help us understand why.
=> chore: Surround github-script calls with try/catch

package-lock.json, package.json
The sentry packages needed to be aligned at the same version.
=> chore: Bumping sentry trace to be inline with other sentry dependencies

common/helpers/events/get-description.ts, common/services/user.js, common/types/event-details.ts, locales/en/events.json, mocks/auth-server.js
This PR adds support for the new PerUpdated event.
This change is happening so that the PerUpdated event is formatted correctly in the event timeline.
- P4-3577
The 3 events at the bottom are: Without author, Without PER section, Without author or PER section
=> feat: Add formatting for PerUpdated event

app/move/app/new/fields/move-type.js, locales/en/fields.json
Updated the error messaging to be consistent with the gov uk summary component
To allow the users to understand the error on the page
- [P4-3635](https://dsdmoj.atlassian.net/browse/P4-3635)
BEFORE:
AFTER:
=> Fix broken error message (formatting and content issues)

common/services/contentful.ts
A new date field has been added to contentful posts: `bannerExpiry`.
This new field has been added so that we have the option of displaying the banner for less than or more than 2 weeks at a time.
- P4-4012
=> chore: Add new bannerExpiry field to contentful.ts, refactor too

common/services/contentful.ts
What's New? posts are now correctly sorted by date.
This changed so that when looking at the What's New? page, the content gets displayed in the order that they are dated.
- P4-4066
=> fix: Sort "What's New?" posts by date

common/formatters/index.test.ts, common/formatters/index.ts, common/middleware/errors.js, common/middleware/errors.test.js, common/services/contentful.ts, common/templates/error.njk, locales/en/errors.json, locales/en/fields.json
Add a call to contentful on error that isn't already handled, checking for planned downtime that is currently active
- [P4-4040]()
=> [P4 4040] Downtime page

locales/en/events.json
Translations have been added for the new MoveOvernightLodge event.
This has changed so that the new event displays correctly in the frontend.
- P4-3956
=> chore: Add locale for new event: MoveOvernightLodge

app/police-custody-form/police-custody-form.njk
Content on the police custody form has changed so that it works for lodging moves too.
This changed so that lodging moves can use the same "Add events" form.
- P4-3900
=> chore: Adjust police custody form content for lodgings

app/police-custody-form/controllers.js, common/presenters/move-to-in-transit-events-panel-list.js, common/presenters/move-to-in-transit-events-panel-list.test.js, locales/en/messages.json
The wording on the add events banner and also the move overview page has been changed to work with lodgings.
- P4-3902
- P4-3904
=> chore: Change content for add events banner / events section

.circleci/config.yml, .github/workflows/branch-deploy.yml, Dockerfile, package.json
Node bumped to 18 LTS
Alpine bumped to 3.17
Current Node version going out of support
Current Alpine version doesn't contain a required package for update dependencies
- [P4-4110](https://dsdmoj.atlassian.net/browse/P4-4110)
[P4-4110]: …
=> chore: P4-4110 bump node to  18 LTS (alpine 3.17)

.circleci/config.yml
=> chore: P4-4110 remove install npm block from circle config

.circleci/config.yml
=> chore: P4-4110 install node 18.14.10

.circleci/config.yml
=> chore: P4-4110 remove sudo

.circleci/config.yml
=> chore: P4-4110 extract to local

.circleci/config.yml
=> chore: P4-4110 Fix main docker build

.circleci/config.yml, .github/workflows/branch-deploy.yml, Dockerfile, package.json
Emergency rollback of node 18 upgrade
=> Revert "chore: P4-4110 use node 18 cci image"

package-lock.json, package.json
This reverts commit a6b23a9b7b097c85e1ac2723124344a0c12c1c6b.
- [P4-XXXX]()
=> Revert "build(deps-dev): Bump testcafe-browser-provider-browserstack"

app/population/middleware/set-breadcrumb.test.js, config/nunjucks/filters.js, config/nunjucks/filters.test.js, locales/en/actions.json, test/e2e/#smoke.test.js
Fixed the link text on the previous button when in week view to show 'Previous week' as before
Made relative weeks in brackets all lowercase
To ensure consistency with day view
- [P4-4090](https://dsdmoj.atlassian.net/browse/P4-4090)
| <kbd>
</kbd> | <kbd><img width="675" alt="image" src="https://user-images.githubusercontent.com/113102670/228599677-e64808f1-3e9d-4721-8fd7-bb2134b83906.png"></kbd> |
[GitHub release notes](https://github.com/ministryofjustice/hmpps-book-secure-move-frontend/releases) during the release task. Please make …
=> fix: P4-4090 Fix incorrect label on previous week link

common/services/move.js, common/services/move.test.js
Request timeline events when listing all moves
In order to have MoveOvernightLodge events listed to be able to show the warning on the moves pages
- [P4-3894](https://dsdmoj.atlassian.net/browse/P4-3894)
| <kbd><img src=""></kbd> | <kbd>![image](https://github.com/ministryofjustice/hmpps-book-secure-move-frontend/assets/113102670/7266447e-09e4-477d-9e9a-b396e24b6f70)</kbd> |
- [x ] Added unit tests to cover changes
- [x ] Chrome
[GitHub release notes](https://github.com/ministryofjustice/hmpps-book-secure-move-frontend/releases) during the …
=> fix: P4-3894 Request timeline events on listing all moves

.github/workflows/branch-deploy-cleanup.yml, .github/workflows/branch-deploy.yml
Change github actions config to use short-live credentials on branch deploy
Cloud platform will be removing the ability to use long-lived creds in the near future
- [P4-4188](https://dsdmoj.atlassian.net/browse/P4-4188)
[P4-4188]: https://dsdmoj.atlassian.net/browse/P4-4188?atlOrigin=eyJpIjoi …
=> ci: P4-4188 Use short lived creds to auth with ECR on brnach deploy

.github/branch-deploy/config-map.yml, .github/branch-deploy/ingress.yml, .github/workflows/branch-deploy.yml, helm_deploy/values-preprod.yaml, helm_deploy/values-production.yaml, helm_deploy/values-staging.yaml, helm_deploy/values-uat.yaml
Removed live-1 from urls,  added correct secret name for production cert 
Cloud platform moving away from cluster specific urls, cert needed for custom domain name in prod
- [MAP-25](https://dsdmoj.atlassian.net/browse/MAP-25)
summary of changes and that the commit body gives a more detailed description of …
=> ci: MAP-26 remove live-1 from urls, define production cert secretname

helm_deploy/values-uat.yaml
Reconfigure UAT to use GA4
Because UA is being discontinued next month
- [MAP-22]
[MAP-22]: https://dsdmoj.atlassian.net/browse/MAP-22?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJw …
=> [MAP-22] Reconfigure UAT to use GA4

helm_deploy/values-preprod.yaml
- Reconfigure preprod to use correct GA4 measurement ID
- Because I copied the wrong value
[MAP-22]
[MAP-22]: https://dsdmoj.atlassian.net/browse/MAP-22?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2 …
=> [MAP-22] Use correct measurement ID for GA4

helm_deploy/values-production.yaml
Reconfigure production to use GA4
Because Universal Analytics is being discontinued next month
- [MAP-22]
[MAP-22]: https://dsdmoj.atlassian.net/browse/MAP-22?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlh …
=> [MAP-22] Update production to use GA4 property for analytics

app/move/app/new/controllers/prison-transfer-reason.js, app/move/app/new/controllers/prison-transfer-reason.test.js, app/move/app/new/steps.js
AP Moves now ask for a transfer reason
Detailed in AC
- [MAP-21]()
| <kbd><img src=""></kbd> | <img width="603" alt="image" src="https://github.com/ministryofjustice/hmpps-book-secure-move-frontend/assets/113102670/72e4843f-5a86-42eb-adbd-8a3ecbd4a636"></kbd> | …
=> Map 21/approves premises moves

helm_deploy/hmpps-book-secure-move-frontend/values.yaml
Add Date of Arrest feature flag to Helm as it was missed meaning question wasn't being asked
=> ci: Add date of arrest feature flag to Helm

helm_deploy/values-preprod.yaml, helm_deploy/values-production.yaml, helm_deploy/values-staging.yaml, helm_deploy/values-uat.yaml
Add app insights env var
It should have been in the Helm vars but it wasn't
P4-4144
N/A
=> [P4-4144] Add app insights env vars

helm_deploy/values-staging.yaml
Add Service account name (staging only for now) to access redis using IRSA
- [x ] Added to Helm config
=>  MAP-144 Add service account to staging

.circleci/config.yml, .github/branch-deploy/deployment.yml, helm_deploy/values-staging.yaml
=> ci: MAP-144 Add service account to brach deploy deployment

app/person-escort-record/app/confirm/handover-details.njk, locales/en/assessment.json
=> feat: Change wording on handover form for lodgings

common/components/notification-banner/template.njk, common/services/contentful/downtime.test.ts, common/services/contentful/downtime.ts, locales/en/downtime.json
Downtime content now has a message field
Downtime is not always the entire system, so this allows a user publishing content to specify what parts of BaSM are affected by downtime
- MAP-270
=> feat: MAP-270 Display message field for downtime banner

helm_deploy/values-preprod.yaml, helm_deploy/values-production.yaml
- Enabled AP moves for Serco
- Because they are ready now
- MAP-297
=> [MAP-297] Enable AP moves for Serco

.github/branch-deploy/config-map.yml, common/services/user.js, common/services/user.test.js, config/index.ts, helm_deploy/values-preprod.yaml, helm_deploy/values-production.yaml, helm_deploy/values-staging.yaml, helm_deploy/values-uat.yaml, mocks/auth-server.js, test/e2e/parallel-runner.js
The URLs for user details and user groups have been changed from auth URLs to manage-users-api URLs.
This changed as part of the migration from auth to manage-users-api.
- MAP-308
=> chore: Replace user details/groups auth urls with manager-users-api urls

common/presenters/move-to-meta-list-component.js, common/presenters/move-to-meta-list-component.test.js
=> feat: MAP-1503 Highlight when journey dates override move date

app/move/app/new/fields/move-type.js, app/move/app/new/views/move-details.njk, common/templates/collection-as-cards.njk
Adding H2's to headings as requested in: [MAP-885](https://dsdmoj.atlassian.net/jira/software/c/projects/MAP/boards/1354?assignee=6419ad1b67102fc717c0d25e&selectedIssue=MAP-885) 
[MAP-885]: https://dsdmoj.atlassian.net/browse/MAP-885?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: MAP-885 Adding markup for visual headings

app/police-custody-form/index.ts
=> fix(MAP-1707): Revert to module.export

app/allocation/config/edit.config.ts, app/allocation/views/cancel.njk, app/allocation/views/confirmation.njk, app/allocation/views/view.njk, app/locations/views/locations.njk, app/move/app/cancel/cancel.njk, app/move/app/lodging/edit/views/saved.njk, app/move/app/lodging/new/views/saved.njk, app/move/app/review/review.njk, app/move/app/view/views/_layout.njk, app/move/views/confirmation.njk, app/person/views/_layout.njk, app/police-custody-form/police-custody-form.njk, app/whats-new/whats-new.njk, common/templates/form-wizard.njk, common/templates/framework-overview.njk, common/templates/layouts/collection.njk, locales/en/actions.json, locales/en/collections.json, locales/en/moves.json
Page titles have been updated according to the Google Doc:
https://docs.google.com/spreadsheets/d/1HEFJKs1eJ1EWT3B1XakxmjIHtEDIVWkNXMtsc6rhH-c/edit?gid=948187693#gid=948187693
MAP-883
=> MAP-883: Update page titles as per spreadsheet

app/move/app/edit/controllers/court.js, app/move/app/edit/controllers/court.test.js, app/move/app/edit/controllers/health-information.test.ts, app/move/app/edit/controllers/health-information.ts, app/move/app/edit/controllers/risk-information.test.ts, app/move/app/edit/controllers/risk-information.ts, app/move/app/edit/steps.js, app/move/app/new/controllers/assessment.js, app/move/app/new/controllers/court-information.test.ts, app/move/app/new/controllers/court-information.ts, app/move/app/new/controllers/health-information.test.ts, app/move/app/new/controllers/health-information.ts, app/move/app/new/controllers/risk-information.test.ts, app/move/app/new/controllers/risk-information.ts, app/move/app/new/steps.js, common/helpers/field/add-negative-option.test.ts, common/helpers/field/add-negative-option.ts, locales/en/fields.json
- Add " (optional)" to some fields
- Add a negative option to the bottom of some checkbox lists and require a response
- To meet accessibility recommendations
- MAP-881
Example of negative option:
=> MAP-881: Optional fields

app/move/app/new/controllers/person-search-results.js, app/move/app/new/controllers/person-search-results.test.js, app/move/app/new/views/person-search-results.njk, locales/en/moves.json, test/e2e/pages/create-move.ts
Changed header and page title for person search page
Because accessibility
- MAP-1945
=> chore: Update person search page title and header

.github/workflows/security_npm_dependency.yml, .github/workflows/security_trivy.yml, .github/workflows/security_veracode_pipeline_scan.yml, .github/workflows/security_veracode_policy_scan.yml
Might help with some of the errors we are seeing in Github actions
=> chore: MAP-1979 Upgrade versions of hmpps github actions to v2

common/presenters/event-to-timeline-panel.js
- Updated code to add space between each item when displayed in the view. 
**Before change:**
**After change:**
- MAP-1917
=> feat(MAP-1917): Add space after each item

locales/en/fields.json, locales/en/validation.json
- Updated locales text for the fields related to the ticket.
- Existing error message was incorrect.
- MAP-1983
=> feat(MAP-1983): Update validation and fields values

app/help/accessibility-statement.njk
https://dsdmoj.atlassian.net/browse/MAP-1980
Update the accessibility statement
git push --set-upstream origin MAP-1980-accessibility-statement
***
=> chore: Update accessibility statement

.circleci/config.yml, app/move/app/new/controllers/person-search-results.js, app/move/app/new/fields/common.assessment-answer.js, app/move/app/new/fields/common.assessment-answer.test.js, app/move/app/new/fields/common.assessment-checkboxes.js, app/move/app/new/fields/common.assessment-checkboxes.test.js, app/move/app/new/fields/common.explicit-assessment-answer.js, app/move/app/new/fields/common.explicit-assessment-answer.test.js, app/move/app/new/fields/date-type.js, app/move/app/new/fields/gender.js, app/move/app/new/fields/has-court-case.js, app/move/app/new/fields/move-agreed.js, app/move/app/new/fields/people.js, common/helpers/field/index.test.js
- Added missing id values in various field .js files to enabled href links in error message boxes.
The following routes are updated with the changes:
- /move/new/[uniqueID]/person-lookup-[pnc/Prison number]
- /move/new/[uniqueID]/personal-details
- /move/new/[uniqueID]/person-lookup-results?filter[PNCprison_number]=[PNCprisonNumber]
- /move/new/[uniqueID]/move-details
- /move/new/[uniqueID]/move-date
- /move/new/[uniqueID]/court-information
- /move/new/[uniqueID]/court-hearings
- /move/new/[uniqueID]/extradition-details
- /move/new/[uniqueID]hospital
- /move/new/[uniqueID]/risk-information
- /move/new/[uniqueID]/release-status
- /move/new/[uniqueID]/special-vehicle
- /move/new/[uniqueID]/health-information
- /move/new/[uniqueID]/transfer-reason
- /move/new/[uniqueID]/agreement-status
- …
=> feat(MAP-1994): Add id values for anchor href links in error messages

helm_deploy/hmpps-book-secure-move-frontend/Chart.yaml
=> chore: Bump hmpps-helm-charts version

common/middleware/check-staff-network.ts, helm_deploy/values-production.yaml, helm_deploy/values-uat.yaml
Stop reporting off-network access to prisoner images
Stop reporting access to urls that get always get redirected
Consolidate Sentry exceptions - report off-network and bad device together
We're currently sending too many reports to Sentry and can't easily see if bad device access is also off-network
- MAP-2156 …
=> Map 2156 fix username

common/middleware/check-staff-network.test.ts, common/middleware/check-staff-network.ts, helm_deploy/values-preprod.yaml, helm_deploy/values-production.yaml, helm_deploy/values-staging.yaml, helm_deploy/values-uat.yaml, package-lock.json
Adds off-network and bad device options to differ between internal and external users
=> MAP-2156 log external users

common/middleware/check-staff-network.ts, common/middleware/errors.js, common/templates/error.njk, locales/en/errors.json
=> feat: MAP-2156 Add error message for bad device / off network 403s

app/move/app/edit/controllers/date-change-reason.js, app/move/app/edit/controllers/date-changed-reason.js, app/move/app/edit/controllers/date-changed-reason.test.js, app/move/app/edit/controllers/index.js, app/move/app/edit/controllers/move-date.js, app/move/app/edit/controllers/move-date.test.js, app/move/app/edit/fields/date-changed-reason.js, app/move/app/edit/fields/index.js, app/move/app/edit/steps.js, app/move/app/edit/views/move-date.njk, common/lib/api-client/models/move.js, common/services/move.js, locales/en/fields.json, locales/en/moves.json, test/fixtures/api-client/move.find.json, test/fixtures/api-client/move.findAll.json
=> Map 2301 date change reasons

app/move/app/review/fields/rejection-reason.js, locales/en/fields.json, locales/en/statuses.json
=> feat: MAP-2853 Add more information required rejection reason
